fixes && corrections
DraftBot/Documentation pull request #103
Opened 2024-09-01 15:03 UTC by Rababio4579

2024-09-03 14:40 UTC, DraftProducts approved these changes

2024-09-06 15:42 UTC, ErwanGit requested changes

2024-09-06 15:42 UTC, ErwanGit commented on 2.modules/2.niveaux.md
> +    ![exemple d'annonce de niveau](../assets/levels/announcement_level.png)
```suggestion
    ![Exemple d'annonce de niveau](../assets/levels/announcement_level.png)
```

2024-09-06 15:42 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    Vous pourrez ensuite modifier ou supprimer les starboards existants via les boutons "modifier" et "supprimer".
À voir
```suggestion
    Vous pourrez ensuite modifier ou supprimer les starboards existants via les boutons "Modifier" et "Supprimer".
```

2024-09-29 11:28 UTC, DraftProducts approved these changes

2024-09-29 19:05 UTC, ErwanGit requested changes

2024-09-29 19:05 UTC, ErwanGit commented on assets/starboards/dashboard_config.png
Peut-être utiliser un meilleur nom de configuration ?

2024-09-29 19:05 UTC, ErwanGit commented on 2.modules/2.niveaux.md
> +contributors: ['hugo-broc', 'wernouxe', 'rababio4579']
@DraftProducts Il faudrait changer les noms affichés sur le panel (`displayContributorName`)

2024-09-29 19:05 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +  <!-- TODO : ajouter le retour à la ligne -->
Ce n'est pas possible de le faire ?

2024-09-30 16:20 UTC, Rababio4579 commented on 2.modules/25.starboards.md
> +  <!-- TODO : ajouter le retour à la ligne -->
Nico a fix le problème

2024-09-30 17:19 UTC, merged