Auto-moderation
DraftBot/Documentation pull request #106
Opened 2024-10-05 13:59 UTC by Rababio4579

2025-02-13 09:44 UTC, DraftProducts approved these changes

2025-02-13 09:49 UTC, DraftProducts requested changes

2025-02-13 09:49 UTC, DraftProducts commented on docs/2.modules/25.auto-moderation.md
> +    ## Options récurentes :
```suggestion
    ## Options récurrentes :
```

2025-02-13 09:49 UTC, DraftProducts commented on docs/2.modules/25.auto-moderation.md
> +Les sanctions automatiques permettent d'appliquer des actions de modérations aux membres après un certain nombre d'infractions.
```suggestion
Les sanctions automatiques permettent d'appliquer des actions de modération aux membres après une quantité définie d'infractions.
```

2025-02-13 09:49 UTC, DraftProducts commented on docs/2.modules/25.auto-moderation.md
> +- Nombre d'infractions : Nombre d'infractions avant d'appliquer la sanctions.
```suggestion
- Nombre d'infractions : Nombre d'infractions avant d'appliquer la sanction.
```

2025-02-13 12:02 UTC, IIbey requested changes

2025-02-13 12:15 UTC, IIbey requested changes

2025-02-13 18:21 UTC, IIbey approved these changes

2025-02-13 21:19 UTC, ErwanGit requested changes

2025-02-13 21:19 UTC, ErwanGit commented on docs/2.modules/25.auto-moderation.md
> +    Sachez que certaines fonctionnalités apparaissant dans l'image ci-dessus *(`Masquer le nom du modérateur en MP`, `Cacher les réponses des commandes` et `Sanctions prédéfinies`)* disponibles via l
Ajout du point à la fin + saut de ligne
```suggestion
    Sachez que certaines fonctionnalités apparaissant dans l'image ci-dessus *(`Masquer le nom du modérateur en MP`, `Cacher les réponses des commandes` et `Sanctions prédéfinies`)* disponibles via la commande \</config> n'apparaissent pas sur cette page. **Cette dernière traite uniquement de l'auto-modération.**\
    Si vous recherchez des informations concernant la modération, consultez la [page prévue à cet effet](/docs/modules/moderation).
```

2025-02-13 21:19 UTC, ErwanGit commented on docs/2.modules/25.auto-moderation.md
> +    Rendez-vous d'abord dans la catégorie **`🔨 Modération`** de la commande \</config> puis appuyez sur **`Sanctions automatiques`**. Vous pourrez ensuite configurer les sanctions automatiques :
Saut de ligne pour aérer 
```suggestion
    Rendez-vous d'abord dans la catégorie **`🔨 Modération`** de la commande \</config> puis appuyez sur **`Sanctions automatiques`**.\
    Vous pourrez ensuite configurer les sanctions automatiques :
```

2025-02-13 21:19 UTC, ErwanGit commented on docs/2.modules/25.auto-moderation.md
> +    - Majuscules excessives ➜ Nombre de caractères minimum : Nombre de caractères minimum pour compter l'infraction.
Pourquoi ici ne pas faire comme plus bas, c'est-à-dire les sortir du tab vu que ces options sont communes pour le panel et le `/config` ?

2025-02-13 21:42 UTC, ErwanGit approved these changes

2025-02-13 21:42 UTC, ErwanGit commented on docs/2.modules/25.auto-moderation.md
> +    Sachez que certaines fonctionnalités apparaissant dans l'image ci-dessus *(`Masquer le nom du modérateur en MP`, `Cacher les réponses des commandes` et `Sanctions prédéfinies`)* disponibles via l
```suggestion
    Sachez que certaines fonctionnalités apparaissant dans l'image ci-dessus *(`Masquer le nom du modérateur en MP`, `Cacher les réponses des commandes` et `Sanctions prédéfinies`)* disponibles via la commande \</config> n'apparaissent pas sur cette page. **Cette dernière traite uniquement de l'auto-modération.**
```

2025-02-14 03:32 UTC, DraftProducts approved these changes

2025-02-14 09:52 UTC, merged