Add - Stats changelog
DraftBot/Documentation pull request #109
Opened 2024-12-03 21:09 UTC by Tellvex

# Ajout du changelog de statistiques

Cette page contient une description courte et rapide de l'update du membercount.

2024-12-16 15:42 UTC, Rababio4579 requested changes

2024-12-16 15:42 UTC, Rababio4579 commented on changelog/2024-12-03.md
> +Profitez d'une nouvelle variable : regardez dés a présent le nombre de salons dans une catégorie.
```suggestion
Profitez d'une nouvelle variable : regardez dès à présent le nombre de salons dans une catégorie.
```

2024-12-17 17:55 UTC, DraftProducts requested changes

2024-12-17 17:55 UTC, DraftProducts commented on changelog/2024-12-03.md
> +Profitez d'une nouvelle variable : regardez dès à présent le nombre de salons dans une catégorie.
```suggestion
Profitez d'une nouvelle variable : affichez dès à présent le nombre de salons dans une catégorie.

```

2024-12-17 17:56 UTC, DraftProducts approved these changes

2024-12-17 17:56 UTC, merged