Première ébauche - ajout de contenu
DraftBot/Documentation pull request #12
Opened 2022-12-16 13:37 UTC by Hugo-broc

- titres
- description générale
- description de la configuration

2022-12-16 23:26 UTC, IIbey approved these changes

2023-02-01 13:46 UTC, DraftProducts commented
Je viens de retirer le mode "Draft" de la PR pour qu'on ai le rendu de dispo.

2023-02-01 17:28 UTC, Hugo-broc commented
Normalement la page est complète, juste et correcte en fautes d'orthographe. 
A revérifier tout de même 😉

2023-02-01 18:17 UTC, DraftProducts requested changes
Super boulot ! 🔥 Voici quelques améliorations de ponctuation qui me semblent intéressantes ! 🎉

2023-02-01 18:17 UTC, DraftProducts commented on slash/gestion-des-niveaux.md
> +* ***Activer l'xp en vocal*** ⇒ une fois activé, les membres pourront gagnés de l'xp en vocal (conditions : être plus de deux humains dans le salon vocal ; le salon vocal ne doit pas être paramétré c
```suggestion
* ***Activer l'xp en vocal*** ⇒ une fois activé, les membres pourront gagner de l'expérience en vocal (conditions : être plus de deux humains dans le salon vocal ; le salon vocal ne doit pas être paramétré comme "AFK") ***(premium)***
```

2023-02-01 18:17 UTC, DraftProducts commented on slash/gestion-des-niveaux.md
> +* ***Activer le gain d'xp dans les threads*** ⇒ permet de gagner ou non de l'xp dans les threads du serveur.
```suggestion
* ***Niveau maximum*** ⇒ Permet de fixer un niveau maximal ne pouvant pas être dépassé par les membres une fois atteint. ***(premium)***
* ***Couleur*** ⇒ Paramétrer une couleur pour tout le système d'économie. ***(premium)***
* ***Ratio d'xp*** ⇒ Définir le nombre d'expérience gagné par message.
* ***Rôles / Salons sans gain d'xp*** ⇒ Permet de ne pas donner d'expérience à un membre s'il possède un certain rôle ou si il envoie son message dans un certain salon.
* ***Rôles / Salons boosters*** ⇒ Permet de donner plus d'expérience à un membre s'il possède un certain rôle ou si il envoie son message dans un certain salon.
* ***Activer le reset des niveaux lors du départ*** ⇒ Une fois activé, les membres perdront tout leur expérience s'ils quittent le serveur.
* ***Activer les longs messages comptent double xp*** ⇒ Une fois activé, les longs messages gagneront plus d'expérience qu'à la normale.
* ***Activer le gain d'xp dans les threads*** ⇒ Permet de gagner ou non de l'expérience dans les threads du serveur.
```

2023-02-01 18:17 UTC, DraftProducts commented on slash/gestion-des-niveaux.md
> +Afin de ne pas encourager le "farm d'xp", **DraftBot** ne donne de l'xp que pour les messages ayant été envoyés 30 secondes après le message précédent du membre.
```suggestion
Afin de ne pas encourager le "farm d'xp", **DraftBot** ne donne de l'expérience que pour les messages ayant été envoyés 30 secondes après le message précédent du membre.
```

2023-02-01 18:17 UTC, DraftProducts commented on slash/gestion-des-niveaux.md
> +Sur le panel, vous avez les mêmes possibilités de configuration que les slash commandes mais vous avez ici tout sur la même page.
```suggestion
Sur le panel, vous sur une même page, les mêmes possibilités de configuration qu'avec les commandes sur Discord.
```

2023-02-01 18:17 UTC, DraftProducts commented on slash/gestion-des-niveaux.md
> +* *<mark style="color:orange;">/adminxp retirer</mark>* : permet de retirer de l'xp ou des niveaux à un membre
```suggestion
* *<mark style="color:orange;">/adminxp définir</mark>* : Permet de définir le nombre d'xp ou de niveaux d'un membre.
* *<mark style="color:orange;">/adminxp ajouter</mark>* : Permet d'ajouter de l'xp ou des niveaux à un membre.
* *<mark style="color:orange;">/adminxp réinitialiser server</mark>* : Permet de réinitialiser l'xp et les niveaux de tous les membres du serveur.
* *<mark style="color:orange;">/adminxp retirer</mark>* : Permet de retirer de l'xp ou des niveaux à un membre.
```

2023-02-01 18:17 UTC, DraftProducts commented on slash/gestion-des-niveaux.md
> +* ***Réinitialiser*** ⇒ supprimer toutes les récompenses du serveur.
```suggestion
* ***Créer*** ⇒ Créer une nouvelle récompense.
* ***Modifier*** ⇒ Modifier une récompense existante.
* ***Supprimer*** ⇒ Supprimer une récompense existante.
* ***Réinitialiser*** ⇒ Supprimer toutes les récompenses du serveur.
```

2023-02-01 18:17 UTC, DraftProducts commented on slash/gestion-des-niveaux.md
> +* ***Message personnalisé*** ⇒ changer le message par défaut envoyé lors d'une récompense gagnée
```suggestion
* ***Activer les annonces*** ⇒ Activer le système d'annonce de récompenses gagnées.
* ***Salon*** ⇒ Choisir le salon dans lequel les annonces de récompenses gagnées seront envoyées.
* ***Message personnalisé*** ⇒ Changer le message par défaut envoyé lors d'une récompense gagnée.
```

2023-02-01 23:26 UTC, IIbey requested changes

2023-02-01 23:26 UTC, IIbey commented on slash/gestion-des-niveaux.md
> +Pour créer une récompense, appuyez sur le bouton "Créer une récompense" sur la droite de la page. Une pop-up s'ouvrira et vous proposera des champs à compléter en fonction de la récompense voulue : t
```suggestion
Pour créer une récompense, appuyez sur le bouton "Créer une récompense" sur la droite de la page. Un pop-up s'ouvrira et vous proposera des champs à compléter en fonction de la récompense voulue : type de récompense à donner, niveau requis...

2023-02-01 23:26 UTC, IIbey commented on slash/gestion-des-niveaux.md
> +* ***Message personnalisé*** ⇒ changer le message par défaut envoyé lors d'un passage de niveau
```suggestion
* ***Activer les annonces*** ⇒ Activer le système d'annonce des nouveaux niveaux.
* ***Salon*** ⇒ Choisir le salon dans lequel les annonces de nouveau niveau seront envoyées.
* ***Message personnalisé*** ⇒ Changer le message par défaut envoyé lors d'un passage de niveau.

2023-02-01 23:26 UTC, IIbey commented on slash/gestion-des-niveaux.md
> +Grâce à la commande <mark style="color:orange;">/topniveau</mark> vous avez accès au classement des niveaux du serveur. Vous y verrez les cinq premiers membres ainsi que votre position. Pour voir l'e
```suggestion
Grâce à la commande <mark style="color:orange;">/topniveau</mark>, vous avez accès au classement des niveaux du serveur. Vous y verrez les cinq premiers membres ainsi que votre position. Pour voir l'ensemble du classement, cliquez sur le bouton situé sous le message de **DraftBot** ("Voir l'ensemble du classement").

2023-02-03 12:41 UTC, ErwanGit commented on slash/gestion-des-niveaux.md
> +Sur le panel, vous avez les mêmes possibilités de configuration que les slash commandes mais vous avez ici tout sur la même page.
Peut être préciser commandes Slash ?

2023-02-03 12:43 UTC, ErwanGit requested changes

2023-02-03 12:43 UTC, ErwanGit commented on slash/gestion-des-niveaux.md
> +La commande *<mark style="color:orange;">/adminxp réinitialiser server</mark>* est irréversible : impossible d'annuler l'action et de redonner l'xp à tous les membres du serveur.
```suggestion
La commande *<mark style="color:orange;">/adminxp réinitialiser serveur</mark>* est irréversible : impossible d'annuler l'action et de redonner l'xp à tous les membres du serveur.
```

2023-02-03 12:43 UTC, ErwanGit commented on slash/gestion-des-niveaux.md
> +La commande *<mark style="color:orange;">/adminxp réinitialiser server</mark>* est irréversible : impossible d'annuler l'action et de redonner l'xp à tous les membres du serveur.
Après il est a noté que cela risque d'être déplacer dans le /config directement en ce qui concerne le reset

2023-02-03 13:12 UTC, Hugo-broc commented on slash/gestion-des-niveaux.md
> +La commande *<mark style="color:orange;">/adminxp réinitialiser server</mark>* est irréversible : impossible d'annuler l'action et de redonner l'xp à tous les membres du serveur.
Oui, tout à fait mais cela n'est pas encore fait pour le moment donc on peut attendre un peu avant de le mettre je pense.

2023-02-03 13:20 UTC, ErwanGit requested changes
J'ai oublié, mais cela bien que les noms de fichiers soit normalisés, que soit les noms des assets soit en français ou soit en anglais

2023-02-03 14:40 UTC, DraftProducts commented on slash/gestion-des-niveaux.md
> +Sur le panel, vous avez les mêmes possibilités de configuration que les slash commandes mais vous avez ici tout sur la même page.
Je viens d'edit

2023-02-07 08:52 UTC, DraftProducts commented
Il manque tous les points que j'avais ajoutés dans ma review (à la fin de chaque tiré de liste)

2023-02-09 14:02 UTC, IIbey requested changes

2023-02-09 14:02 UTC, IIbey commented on slash/gestion-des-niveaux.md
> +Pour créer une récompense, appuyez sur le bouton "Créer une récompense" sur la droite de la page. Un pop-up s'ouvrira et vous proposera des champs à compléter en fonction de la récompense voulue : ty
```suggestion
Pour créer une récompense, appuyez sur le bouton **"Créer une récompense"** sur la droite de la page. Un pop-up s'ouvrira et vous proposera des champs à compléter en fonction de la récompense voulue : type de récompense à donner, niveau requis...

2023-02-09 14:04 UTC, DraftProducts requested changes
Super boulot ! Il y a juste quelques soucis de formulations et de markdown au niveau des titres, les rendant indisponibles dans le sommaire de la page : 
![image](https://user-images.githubusercontent.com/29425008/217834326-e2f37bfb-c5ad-4d44-a22b-600f1b5aa5e2.png)

2023-02-09 14:04 UTC, DraftProducts commented on slash/gestion-des-niveaux.md
> +La commande *<mark style="color:orange;">/adminxp réinitialiser serveur</mark>* est irréversible : impossible d'annuler l'action et de redonner l'expérience à tous les membres du serveur.
```suggestion
La commande *<mark style="color:orange;">/adminxp réinitialiser serveur</mark>* est irréversible : Il sera impossible d'annuler la réinitialisation et de redonner l'expérience à vos les membres.
```

2023-02-09 14:04 UTC, DraftProducts commented on slash/gestion-des-niveaux.md
> +### Le classement du serveur
```suggestion
### Classement du serveur
```

2023-02-12 09:04 UTC, bariboo commented
Hello ! J'ai remarqué quelque chose qui, je pense, ne devrait pas se situer ici, Hugo à fait toute la partie Gestion des Niveaux mais également la configuration de ceux ci, et donc, je pense que la partie "configuration" devrait se trouver sur cette page : https://docs.draftbot.fr/slash/configuration/niveaux au lieu de celle-ci !

2023-02-14 02:36 UTC, DraftProducts requested changes
Review effectuée en collaboration avec Ls62 par rapport aux demandes récurrentes du support :v:

2023-02-14 02:36 UTC, DraftProducts commented on slash/gestion-des-niveaux.md
> +* ***Couleur*** ⇒ Paramétrer une couleur pour tout le système d'économie ***(premium)***.
```suggestion
* ***Activer l'xp en vocal*** ⇒ Une fois activé, les membres pourront gagner de l'expérience en vocal (conditions : être plus de deux humains dans le salon vocal ; le salon vocal ne doit pas être paramétré comme "AFK") ***(✨ premium)***.
* ***Niveau maximum*** ⇒ Permet de fixer un niveau maximal ne pouvant pas être dépassé par les membres une fois atteint ***(✨ premium)***.
* ***Couleur*** ⇒ Paramétrer une couleur pour tout le système d'économie ***(✨ premium)***.
```

2023-02-14 02:36 UTC, DraftProducts commented on slash/gestion-des-niveaux.md
> +* ***Activer l'xp en vocal*** ⇒ Une fois activé, les membres pourront gagner de l'expérience en vocal (conditions : être plus de deux humains dans le salon vocal ; le salon vocal ne doit pas être par
```suggestion
* ***Activer l'xp en vocal*** ⇒ Une fois activé, les membres pourront gagner de l'expérience en vocal (conditions : être plus de deux humains sans micro coupé dans un salon vocal non configuré comme "AFK") ***(premium)***.
```

2023-02-14 02:36 UTC, DraftProducts commented on slash/gestion-des-niveaux.md
> +![Panel de configuration des annonces de nouveau niveau](../.gitbook/assets/levels/dashboard_announcement_config_new_level_.png)
```suggestion
![Panel de configuration des annonces de nouveau niveau](../.gitbook/assets/levels/dashboard_announcement_config_new_level.png)
```

2023-02-14 02:36 UTC, DraftProducts commented on slash/gestion-des-niveaux.md
> +
```suggestion

{% hint style="info" %}
Notez qu'il est possible de voir la liste des variables disponible en entrant le caractère `{` dans la zone de texte.
{% endhint %}

```

2023-02-14 02:36 UTC, DraftProducts commented on slash/gestion-des-niveaux.md
> +
```suggestion
{% hint style="info" %}
Notez qu'il est possible de voir la liste des variables disponible en entrant le caractère `{` dans la zone de texte.
{% endhint %}
```

2023-02-14 02:41 UTC, DraftProducts commented
> Hello ! J'ai remarqué quelque chose qui, je pense, ne devrait pas se situer ici, Hugo à fait toute la partie Gestion des Niveaux mais également la configuration de ceux ci, et donc, je pense que la partie "configuration" devrait se trouver sur cette page : [docs.draftbot.fr/slash/configuration/niveaux](https://docs.draftbot.fr/slash/configuration/niveaux) au lieu de celle-ci !

Je suis d'accord avec @bariboo, peut-être serait-il mieux de garder le schéma ?
- Faire une seule page par système qui inclue utilisation et configuration comme l'a fait @Hugo-broc dans cette PR.
- Avoir deux pages une pour les utilisateurs et une pour les admins pour la configuration.

Quoi qu'il en soit j'aime beaucoup la présentation actuelle.

2023-02-15 21:07 UTC, Hugo-broc commented on slash/gestion-des-niveaux.md
> +#### Récompense gagnée
Plutôt "reçu**e**s", mais c'est corrigé 👍

2023-02-16 14:11 UTC, ErwanGit requested changes

2023-02-16 14:11 UTC, ErwanGit commented on slash/gestion-des-niveaux.md
> +![Panel de configuration des annonces de nouveau niveau](../.gitbook/assets/levels/dashboard_announcement_config_new_level.png
```suggestion
![Panel de configuration des annonces de nouveau niveau](../.gitbook/assets/levels/dashboard_announcement_config_new_level.png)
```

2023-02-16 23:40 UTC, DraftProducts approved these changes

2023-02-16 23:59 UTC, ToutouilleDev approved these changes

2023-02-17 00:54 UTC, IIbey approved these changes

2023-02-17 07:37 UTC, bariboo commented
Hello, je vois encore quelques améliorations à faire sur la page niveau qui sera la référence :

- Je pense que on pourrait remplacer le caractère "⇒" par  "➜" (Plus esthétique)

- Quand vous avez parler des options premium, vous avez mis <Nom du bouton> (✨ premium). Pourquoi ne pas juste mettre <✨ Nom du bouton> et mettre cette phrase :
"Les boutons étant précédés d'un "✨" indiquent que le premium est nécéssaire" ?

- Sur certaines explications vous avez mis "Rôles/Salons booster" je pense que ça peu perdre l'utilisateur.

- Dans l'option argent en vocal, mettte un*info hints* concernant les conditions. 

- Rajouter un *warning hints* pour les fois où il faut enregistrer son message sur le panel

- Mettre les mots avec lien hypertexte en bleu.

2023-02-17 10:54 UTC, ErwanGit requested changes

2023-02-17 10:54 UTC, ErwanGit commented on slash/niveaux.md
> +![Classement des niveaux des membres du serveur](../.gitbook/assets/levels/view_topniveau.png)
Modifier le nom du fichier aussi
```suggestion
![Classement des niveaux des membres du serveur](../.gitbook/assets/levels/view_toplevel.png)
```

2023-02-17 14:50 UTC, Hugo-broc commented
> * Je pense que on pourrait remplacer le caractère "⇒" par  "➜" (Plus esthétique)
Pourquoi pas mais il faudra y penser partout car c'était la flèche que nous utilisions pour la documentation avant.

> * Quand vous avez parler des options premium, vous avez mis  (✨ premium). Pourquoi ne pas juste mettre <✨ Nom du bouton> et mettre cette phrase :
>   "Les boutons étant précédés d'un "✨" indiquent que le premium est nécessaire" ?
Personnellement, je trouve cela plus explicite de mettre en fin de ligne si c'est premium ou non que de regarder les émojis. 
Si je cherche encore plus les détails : si des personnes mal voyantes mettent "Lecture à voix haute", ils entendront le "premium" à la fin de la phrase, ce qui est clair alors que l'émoji ne voudra rien dire pour eux.

> * Sur certaines explications vous avez mis "Rôles/Salons booster" je pense que ça peut perdre l'utilisateur.
C'est la fonctionnalité "Rôles boosters" et "Salons boosters" réunies. Je trouve que cela ne sert à rien de noter 2 fois la même chose. Cela permet aussi d'avoir une documentation plus courte pour s'y retrouver.

> * Dans l'option argent en vocal, mettre un _info hints_ concernant les conditions.
Je trouve cela non nécessaire car cela couperait la liste et agrandirait la page pour un détail (ce n'est pas un point sur lequel nous nous penchons précisément). Des parenthèses suffisent ici.

> * Rajouter un _warning hints_ pour les fois où il faut enregistrer son message sur le panel
Pas d'accord avec cela : il faudrait le mettre sur chaque endroit où il y a de la configuration sur DraftBot sur le panel, ce qui fait beaucoup ! Donc soit laisser le texte avec une citation (>) pour ne pas surcharger ou soit ne rien mettre du tout.

2023-02-18 15:12 UTC, DraftProducts approved these changes

2023-02-18 15:56 UTC, ErwanGit approved these changes

2023-02-18 16:31 UTC, merged