Rôles automatiques (Configuration guidée)
DraftBot/Documentation pull request #17
Opened 2023-01-31 15:19 UTC by bariboo

Reste de modifications à faire.

2023-01-31 15:55 UTC, ErwanGit requested changes
Également, je ne peux pas le mettre car tu ne l'as pas modifié mais également revoir la description de la page, surtout pour le "live vidéo" qui est très implicite et peu faire penser au partage d'écran

2023-01-31 15:55 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +**Info hints** Si vous n'êtes pas pas premium, vous pouvez ajouter un maximum de 3 rôles.
Pas du tout convaincu du franglais ici

2023-01-31 15:55 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +Après avoir cliqué sur le bouton "En vocal".
Un peu étrange ces phrases dans la documentation, peut-être voir pour une autre présentation

2023-01-31 15:55 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +Après avoir cliqué sur le bouton "En live".
Même chose

2023-01-31 15:55 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +![Menu d'accueil de la configuration des Rôles automatiques en live](../../.gitbook/assets/R%C3%B4le_en_Live.png)
Renommer le fichier sans accent pour éviter ce genre de chose

2023-01-31 15:56 UTC, ErwanGit commented
J’ai mis la PR en Draft puisque tu dis qu’il te reste des modifications

2023-01-31 18:29 UTC, bariboo commented on slash/configuration/roles-automatiques.md
> +Après avoir cliqué sur le bouton "En vocal".
Hello, est ce que vous pourriez me donner des conseils sur celle là et celle du dessous ? 
Cimerrr !

2023-02-01 12:22 UTC, ErwanGit requested changes

2023-02-01 12:22 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +[Menu d'accueil de la configuration des Rôles automatiques en live](../../.gitbook/assets/autorole/live.png)
Image pas ok sur la preview

2023-02-01 14:56 UTC, DraftProducts commented on slash/configuration/roles-automatiques.md
> +[Menu d'accueil de la configuration des Rôles automatiques en live](../../.gitbook/assets/autorole/live.png)
```suggestion
![Menu d'accueil de la configuration des Rôles automatiques en live](../../.gitbook/assets/autorole/live.png)
```

2023-02-05 20:19 UTC, ErwanGit requested changes

2023-02-05 20:19 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +{% tab title="Via la commande `/config`" %}
Le markdown n'est pas ok ici
<img width="403" alt="image" src="https://user-images.githubusercontent.com/24718500/216842366-5eaac449-fa91-4fef-bc0d-c99c8851260b.png">
```suggestion
{% tab title="Via la commande /config" %}
```

2023-02-05 20:19 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +Veuillez d'abord vous rendre dans `/config` ➜ 🏷️Rôles Automatiques ➜ "À l'arrivée".
```suggestion
Veuillez d'abord vous rendre dans `/config` ➜ 🏷️ Rôles Automatiques ➜ "À l'arrivée".
```

2023-02-05 20:19 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +{% endhint %}
Peut-être ajouté les limites premiums (10) ?

2023-02-05 20:19 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +![Menu d'accueil de la configuration des Rôles automatiques à l'arrivée](../../.gitbook/assets/autorole/join.png)
Plus partant pour ça
```suggestion
![Menu d'accueil de la configuration des rôles automatiques à l'arrivée](../../.gitbook/assets/autorole/join.png)
```

2023-02-05 20:19 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +Si les rôles apparaissent en rouge, cela veut dire que soit DraftBot n'a pas les permissions de donner ce rôle soit qu'il n'est pas suffisament haut dans la hiérarchie des rôles.
```suggestion
Si les rôles apparaissent en rouge, cela veut dire que soit DraftBot n'a pas les permissions de donner ce rôle, soit qu'il n'est pas suffisamment haut dans la hiérarchie des rôles.
```

2023-02-05 20:19 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +Séléctionner ensuite le rôle que vous souhaitez rendre automatique à l'arrivée d'un nouveau membre.
```suggestion
Sélectionner ensuite le rôle que vous souhaitez rendre automatique à l'arrivée d'un nouveau membre.
```

2023-02-05 20:19 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +*Vous avez la possibilité de supprimer le rôle du serveur une fois le système désactivé.*
Je le renote ici mais je trouve qu'il a quand même beaucoup de redondance dans ce passage là 
Aucune idée de reformulation, @IIbey @Hugo-broc ?

2023-02-05 20:19 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +Les rôles automatiques en **Live** sont utiles lorsque vos membres font des streams sur Youtube ou encore Twitch.
Proposition
```suggestion
Les rôles automatiques en **Live** sont utiles lorsque vos membres sont en direct sur YouTube ou encore Twitch.
```

2023-02-05 20:19 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +Si vous souhaitez cependant les retirer, cliquez de nouveau sur "Restreindre le rôle" puis "retirer".
```suggestion
Si vous souhaitez cependant les retirer, cliquez de nouveau sur "Restreindre le rôle" puis "Retirer".
```

2023-02-05 20:19 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +![Menu d'accueil de la configuration des Rôles automatiques en live](../../.gitbook/assets/autorole/live.png)
```suggestion
![Menu d'accueil de la configuration des rôles automatiques en live](../../.gitbook/assets/autorole/live.png)
```

2023-02-05 20:19 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +Si vous souhaitez par contre retirer **tous** les rôles automatiques à l'arrivée, cliquez sur "Réinitialiser".
Je suis pas spécialement fan de la répétition ici, il faudrait trouver une autre tournure. 
Aussi, sur la doc, il y a aucun saut de ligne ici
<img width="788" alt="image" src="https://user-images.githubusercontent.com/24718500/216842450-b4957129-aa27-464c-b3a9-7e4e8c647f0d.png">

2023-02-07 19:35 UTC, Hugo-broc requested changes

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +Veuillez d'abord vous rendre dans `/config` ➜ 🏷️ Rôles Automatiques ➜ <mark style="color:blue;">"À l'arrivée"</mark>.
```suggestion
Veuillez d'abord vous rendre dans <mark style="color:orange;">/config</mark> ➜ 🏷️ Rôles Automatiques ➜ <mark style="color:blue;">"À l'arrivée"</mark>.
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +Si vous n'êtes pas premium, vous pouvez ajouter un maximum de 3 rôles. Si c'est le cas, le maximum est de 10.
```suggestion
Si vous êtes un membre premium, vous pouvez ajouter un maximum de 10 rôles. Si vous ne l'êtes pas, le seuil maximum sera de 3 rôles.
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +Sélectionner ensuite le rôle que vous souhaitez rendre automatique à l'arrivée d'un nouveau membre.
```suggestion
Sélectionnez ensuite le rôle que vous souhaitez rendre automatique à l'arrivée d'un nouveau membre.
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +#### Ajouter ou retirer un rôle attribuer lorsqu'un membre est en vocal
```suggestion
#### Ajouter ou retirer un rôle attribué lorsqu'un membre est en vocal
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +Veuillez d'abord vous rendre dans `/config` ➜ 🏷️ Rôles Automatiques ➜ <mark style="color:blue;">"En vocal"</mark>.
```suggestion
Veuillez d'abord vous rendre dans <mark style="color:orange;">/config</mark> ➜ 🏷️ Rôles Automatiques ➜ <mark style="color:blue;">"En vocal"</mark>.
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +Pour ajouter un rôle automatique en vocal d'un membre, vous pouvez cliquer sur "Configurer".
```suggestion
Pour ajouter un rôle automatique à un membre en vocal, vous pouvez cliquer sur "Configurer".
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +![Menu d'accueil de la configuration des Rôles automatiques en vocal](../../.gitbook/assets/autorole/voice.png)
```suggestion
![Menu d'accueil de la configuration des rôles automatiques en vocal](../../.gitbook/assets/autorole/voice.png)
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +Sélectionner ensuite le rôle que vous souhaitez rendre automatique à l'arrivée d'un nouveau membre.
```suggestion
Sélectionnez ensuite le rôle que vous souhaitez rendre automatique à l'arrivée d'un nouveau membre.
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +![Dashboard Rôles Automatiques en vocal](../../.gitbook/assets/autorole/dashboard_voice.png)
```suggestion
![Panel des rôles automatiques en vocal](../../.gitbook/assets/autorole/dashboard_voice.png)
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +![Dashboard Rôles Automatiques à l'arrivée](../../.gitbook/assets/autorole/dashboard_join.png)
```suggestion
![Panel des rôles automatiques à l'arrivée](../../.gitbook/assets/autorole/dashboard_join.png)
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +Les rôles automatiques en **Live** sont utiles lorsque vos membres sont en direct sur YouTube ou encore Twitch.
```suggestion
Les rôles automatiques de live vous permettent de donner un rôle à un membre lorsqu'il est en direct sur YouTube ou encore sur Twitch.
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +Veuillez d'abord vous rendre dans `/config` ➜ 🏷️ Rôles Automatiques ➜ <mark style="color:blue;">"En live"</mark>.
```suggestion
Veuillez d'abord vous rendre dans <mark style="color:orange;">/config</mark> ➜ 🏷️ Rôles Automatiques ➜ <mark style="color:blue;">"En live"</mark>.
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +Pour ajouter un rôle automatique en vocal d'un membre, vous pouvez cliquer sur "Configurer".
```suggestion
Pour ajouter un rôle automatique à un membre en live, vous pouvez cliquer sur "Configurer".
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +*Vous avez la possibilité de sélectionner un rôle déjà existant ou d'en créer un directement.*
```suggestion
*Vous avez la possibilité de sélectionner un rôle déjà existant ou d'en créer un nouveau.*
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +#### Restreindre ce rôle à uniquement certains utilisateurs
```suggestion
#### Restreindre un rôle de live à certains utilisateurs
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +Vous pouvez également limiter ce rôle à certaines personnes en possédant un spécifique. Pour faire cela, cliquez sur le bouton "Restreindre le rôle".
```suggestion
Vous pouvez autoriser **DraftBot** à donner le rôle de live au membre uniquement s'il en possède un autre. Pour faire cela, cliquez sur le bouton "Restreindre le rôle".
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +Si vous souhaitez cependant les retirer, cliquez de nouveau sur "Restreindre le rôle" puis "Retirer".
```suggestion
Si vous souhaitez retirer cette restriction, cliquez de nouveau sur "Restreindre le rôle" puis "Retirer".
```

2023-02-07 19:35 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +*Vous pouvez aussi les réinitialiser.*
```suggestion
*Vous avez également la possibilité de les réinitialiser.*
```

2023-02-07 19:36 UTC, ErwanGit requested changes
Par contre rappel (il me semble), mais il faudrait changer la description de la page, surtout pour le terme "live vidéo"

2023-02-07 19:36 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +Si vous n'êtes pas premium, vous pouvez ajouter un maximum de 3 rôles. Si c'est le cas, le maximum est de 10.
Peut-être un truc comme ça 
Voir à cause de la répétition du mot premium mais j'ai du relire 2 fois ta phrase pour comprendre 
```suggestion
La limite des rôles automatiques est de 3 pour les serveurs non-premium et 10 pour les serveurs premiums.
```

2023-02-07 19:36 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +![Dashboard Rôles Automatiques à l'arrivée](../../.gitbook/assets/autorole/dashboard_join.png)
Je pense qu'il faut éviter les anglicismes comme ça sur des pages françaises
```suggestion
![Configuration des rôles Automatiques à l'arrivée sur le panel](../../.gitbook/assets/autorole/dashboard_join.png)
```

2023-02-08 19:30 UTC, Hugo-broc requested changes

2023-02-08 19:30 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
>    Choisissez des rôles qui seront automatiquement ajouté lorsqu'un nouveau
```suggestion
  Choisissez des rôles qui seront automatiquement ajoutés lorsqu'un nouveau
```

2023-02-08 19:30 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +Si souhaitez retirer un rôlede cette liste, cliquez sur "Retirer".
```suggestion
Si souhaitez retirer un rôle de cette liste, cliquez sur "Retirer".
```

2023-02-08 19:30 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +Certains rôles peuvent apparaitre en rouge pour l'une des raisons suivantes :
Mettre des \ au bout des lignes pour juste un retour à la ligne, sans en sauter. Car ici, toutes les flèches sont alors collées dans un paragraphe.
```
{% hint style="warning" %}
Certains rôles peuvent apparaitre en rouge pour l'une des raisons suivantes :\
➜ DraftBot n'a pas les permissions de gérer les rôles.\
➜ Le rôle de DraftBot est en dessous des rôles que vous souhaitez attribuer.\
➜ Le rôle de l'utilisateur est en dessous des rôles qu'il souhaite attribuer.\
➜ Le rôle est géré par un bot ou par Discord.
{% endhint %}
```

2023-02-08 19:30 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +![Configuration des rôles Automatiques à l'arrivée sur le panel](../../.gitbook/assets/autorole/dashboard_join.png)
```suggestion
![Configuration des rôles automatiques à l'arrivée sur le panel](../../.gitbook/assets/autorole/dashboard_join.png)
```

2023-02-08 19:30 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +Certains rôles peuvent apparaitre en rouge pour l'une des raisons suivantes :
Mettre des \ au bout des lignes pour juste un retour à la ligne, sans en sauter. Car ici, toutes les flèches sont alors collées dans un paragraphe.
```
{% hint style="warning" %}
Certains rôles peuvent apparaitre en rouge pour l'une des raisons suivantes :
➜ DraftBot n'a pas les permissions de gérer les rôles.
➜ Le rôle de DraftBot est en dessous des rôles que vous souhaitez attribuer.
➜ Le rôle de l'utilisateur est en dessous des rôles qu'il souhaite attribuer.
➜ Le rôle est géré par un bot ou par Discord.
{% endhint %}
```

2023-02-08 19:30 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +Les rôles automatiques de live vous permettent de donner un rôle à un membre lorsqu'il est en direct sur YouTube ou Twitch. Le mode streamer du compte Discord de l'utilisateur souhaitant obtenir ce r
```suggestion
Les rôles automatiques de live vous permettent de donner un rôle à un membre lorsqu'il est en direct sur YouTube ou Twitch. Le mode streamer du compte Discord de l'utilisateur souhaitant obtenir ce rôle lors d'une diffusion d'un stream doit être activé pour que cela fonctionne (activable depuis les paramètres du compte Discord dans la catégorie "Mode streamer").
```

2023-02-08 20:06 UTC, ErwanGit requested changes

2023-02-08 20:06 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
> +  membre rejoint le serveur, un salon vocal, ou lance un stream.
```suggestion
  membre rejoint le serveur, un salon vocal, ou lance un stream sur YouTube ou Twitch.
```

2023-02-08 20:06 UTC, ErwanGit commented on slash/configuration/roles-automatiques.md
>  ![Menu d'accueil de la configuration des Rôles automatiques](<../../.gitbook/assets/autorole/view.png>)
Peut-être mettre une image ou il y a plus de contrastes pour le rôle Vocal ?

2023-02-09 14:17 UTC, IIbey requested changes

2023-02-09 14:17 UTC, IIbey commented on slash/configuration/roles-automatiques.md
>  ![Menu d'accueil de la configuration des Rôles automatiques](<../../.gitbook/assets/autorole/view.png>)
```suggestion
![Menu d'accueil de la configuration des rôles automatiques](<../../.gitbook/assets/autorole/view.png>)

2023-02-09 14:17 UTC, IIbey commented on slash/configuration/roles-automatiques.md
> +Veuillez d'abord vous rendre dans <mark style="color:orange;">/config</mark> ➜ 🏷️ Rôles Automatiques ➜ <mark style="color:blue;">"À l'arrivée"</mark>.
```suggestion
Veuillez d'abord vous rendre dans <mark style="color:orange;">/config</mark> ➜ 🏷️ Rôles automatiques ➜ <mark style="color:blue;">"À l'arrivée"</mark>.

2023-02-09 14:17 UTC, IIbey commented on slash/configuration/roles-automatiques.md
> +Veuillez d'abord vous rendre dans <mark style="color:orange;">/config</mark> ➜ 🏷️ Rôles Automatiques ➜ <mark style="color:blue;">"En live"</mark>.
```suggestion
Veuillez d'abord vous rendre dans <mark style="color:orange;">/config</mark> ➜ 🏷️ Rôles automatiques ➜ <mark style="color:blue;">"En live"</mark>.

2023-02-09 14:17 UTC, IIbey commented on slash/configuration/roles-automatiques.md
> +*Vous avez également la possibilité de les réinitialiser.*
```suggestion
Pour ajouter un rôle automatique à un membre en live, cliquez sur **"Configurer"**.
*Vous avez la possibilité de sélectionner un rôle déjà existant sur votre serveur ou de demander la création automatique d'un nouveau.*

#### Restreindre un rôle en live à certains utilisateurs

Vous pouvez demander à **DraftBot** de donner le rôle de live aux membres possédant un rôle spécifique défini. Pour cela, cliquez sur le bouton **"Restreindre le rôle"**.

Si vous souhaitez retirer cette restriction, cliquez de nouveau sur **"Restreindre le rôle"** puis **"Retirer"**.
*Vous avez également la possibilité de les réinitialiser.*

2023-02-09 14:17 UTC, IIbey commented on slash/configuration/roles-automatiques.md
> +Pour restreindre des salons aux membres en vocal, cliquez sur "Restreindre des salons aux membres en vocal" puis sélectionnez le salon en question. Seuls les membres possédant ce rôle pourront le voi
```suggestion
Pour restreindre des salons aux membres en vocal, cliquez sur **"Restreindre des salons aux membres en vocal"** puis sélectionnez le salon en question. Seuls les membres possédant ce rôle pourront le voir.

2023-02-09 14:17 UTC, IIbey commented on slash/configuration/roles-automatiques.md
> +Pour retirer un rôle automatique à l'arrivée d'un membre, vous pouvez cliquer sur "Modifier".
```suggestion
Pour ajouter un rôle automatique à un membre en vocal, vous pouvez cliquer sur **"Configurer"**.
*Vous avez la possibilité de sélectionner un rôle déjà existant ou d'en créer un directement.*

Pour retirer un rôle automatique à l'arrivée d'un membre, vous pouvez cliquer sur **"Modifier"**.

2023-02-09 17:33 UTC, ErwanGit approved these changes

2023-02-12 09:10 UTC, bariboo commented
Hello ! @DraftProducts est ce que tu pourrais s'il te plaît modifier la première image (view) pour en enlever le fond ? Je pense que on pourra merge après 👀

2023-02-14 02:45 UTC, DraftProducts commented
Salut @bariboo c'est fait !

2023-02-14 12:06 UTC, IIbey approved these changes

2023-02-15 22:56 UTC, Hugo-broc requested changes

2023-02-15 22:56 UTC, Hugo-broc commented on slash/configuration/roles-automatiques.md
> +La limite des rôles automatiques est de 3 pour les serveurs non-premium et de 10 pour les serveurs premiums.
```suggestion
La limite des rôles automatiques est de 3 pour les serveurs non-premiums et de 10 pour les serveurs premiums.
```

2023-02-17 09:01 UTC, bariboo commented
Hello @DraftProducts je pense que cette page pourra être Merge ! 👍

2023-02-17 15:53 UTC, Hugo-broc approved these changes

2023-02-18 18:00 UTC, Hugo-broc approved these changes

2023-02-19 00:19 UTC, DraftProducts approved these changes

2023-02-19 00:36 UTC, merged