Amélioration de la page modération
DraftBot/Documentation pull request #18
Opened 2023-02-01 18:03 UTC by Hugo-broc

Prévu :
- MAJ page
- Ajout images
- MEP

2023-02-01 18:07 UTC, DraftProducts approved these changes

2023-02-01 23:17 UTC, IIbey requested changes

2023-02-01 23:17 UTC, IIbey commented on slash/moderation.md
> +Vous pouvez bannir un membre avec la commande <mark style="color:orange;">/ban \[utilisateur] \[raison]</mark>. Deux options s'offrent alors à vous en plus :
```suggestion
En plus de pouvoir bannir un membre avec la commande <mark style="color:orange;">/ban \[utilisateur] \[raison]</mark>. Deux autres options s'offrent à vous :

2023-02-01 23:17 UTC, IIbey commented on slash/moderation.md
> +Le fait d'exclure un membre fera quitter le membre du serveur mais il pourra toujours revenir avec une autre invitation. Si vous souhaitez qu'il ne puisse pas revenir, consultez le [bannissement](mod
```suggestion
Le fait d'exclure un membre fera quitter le membre du serveur, mais il pourra toujours revenir avec une autre invitation. Si vous souhaitez qu'il ne puisse pas revenir, consultez le [bannissement](moderation.md#bannissement).\

2023-02-01 23:17 UTC, IIbey commented on slash/moderation.md
> +Vous pouvez retrouver la configuration de l'**autosanction** de **DraftBot** sur cette page :
```suggestion
Vous pouvez retrouver la configuration de l'**auto-sanction** de **DraftBot** sur cette page :

2023-02-02 17:39 UTC, Hugo-broc commented on slash/moderation.md
> +Vous pouvez bannir un membre avec la commande <mark style="color:orange;">/ban \[utilisateur] \[raison]</mark>. Deux options s'offrent alors à vous en plus :
Plutôt "[...] [raison], deux options s'offrent à vous :", non ? Car la phrase ne veut rien dire sinon avec "En plus".

2023-02-02 22:18 UTC, IIbey commented on slash/moderation.md
> +Vous pouvez bannir un membre avec la commande <mark style="color:orange;">/ban \[utilisateur] \[raison]</mark>. Deux options s'offrent alors à vous en plus :
Pour faire comme ça ? Je ne suis pas contre. 

" Vous pouvez bannir un membre avec la commande <mark style="color:orange;">/ban \[utilisateur] \[raison]</mark>. Deux options s'offrent à vous : "

2023-02-03 12:34 UTC, ErwanGit approved these changes

2023-02-03 14:49 UTC, DraftProducts requested changes
Il faudrait uniformiser les noms des fichiers en anglais. (warn, kick, history)

2023-02-07 19:31 UTC, ErwanGit requested changes

2023-02-07 19:31 UTC, ErwanGit commented on slash/moderation.md
>  {% endhint %}
Par contre, il faudrait modifier ça partout car c'est faux
DraftBot n'a pas besoin de cette permission pour cette commande. Néanmoins, **par défaut**, l'utilisateur doit avoir cette permission pour pouvoir accéder à cette commande

2023-02-07 19:31 UTC, ErwanGit commented on slash/moderation.md
> +Le fait d'exclure un membre fera quitter le membre du serveur, mais il pourra toujours revenir avec une autre invitation. Si vous souhaitez qu'il ne puisse pas revenir, consultez le [bannissement](mo
Peut-être voir pour ajouter une couleur sur l'hyperlink ?

2023-02-07 19:31 UTC, ErwanGit commented on slash/moderation.md
> +Le fait de bannir un membre fera quitter le membre du serveur et il ne pourra jamais y revenir. Vous pouvez également bannir temporairement le membre en question. Si vous souhaitez qu'il puisse reven
Même chose pour l'hyperlink

2023-02-09 14:31 UTC, IIbey requested changes

2023-02-09 14:31 UTC, IIbey commented on slash/moderation.md
> +Vous pourrez, si vous le souhaitez, retirer le mute du membre avec la commande <mark style="color:orange;">/demute \[membre]</mark>.
```suggestion
Vous pourrez, si vous le souhaitez, acquitter un membre de sa réduction au silence avec la commande <mark style="color:orange;">/demute \[membre]</mark>.

2023-02-14 10:22 UTC, DraftProducts requested changes

2023-02-14 10:22 UTC, DraftProducts commented on slash/moderation.md
> +### Vous pouvez retrouver la configuration de l'**auto-sanction** de **DraftBot** sur cette page :
Si tu tiens à garder cette MeP, faudrait retirer le formatage titre car ça l'affiche comme partie de la documentation dans le sommaire automatique.
```suggestion
**Vous pouvez retrouver la configuration de l'**auto-sanction** de **DraftBot** sur cette page :**
```

2023-02-15 22:36 UTC, Hugo-broc commented on slash/moderation.md
>  [moderation.md](configuration/moderation.md)
Une autre mise en page vient d'être mise et a été proposée plus bas par DraftMan 👇

2023-02-16 14:06 UTC, ErwanGit requested changes

2023-02-16 14:06 UTC, ErwanGit commented on slash/moderation.md
> +**DraftBot** peut donner une note à un membre uniquement si vous disposez de la permission "_Gérer les messages_" sur votre serveur.
Faux, c'est la permission par défaut mais cela peut-être modifié par l'administrateur pour donner l'accès à un certain rôle

2023-02-16 14:06 UTC, ErwanGit commented on slash/moderation.md
> +Le membre recevra un message privé avec le motif de son avertissement.
Peut-être avertir si ses messages privés sont ouverts ?

2023-02-16 14:06 UTC, ErwanGit commented on slash/moderation.md
> +**DraftBot** peut donner une note à un membre uniquement si vous disposez de la permission "_Gérer les messages_" sur votre serveur.
Faux, c'est la permission par défaut mais cela peut-être modifié par l'administrateur pour donner l'accès à un certain rôle

2023-02-16 14:06 UTC, ErwanGit commented on slash/moderation.md
> +Vous pouvez réduire au silence un membre avec la commande <mark style="color:orange;">/mute \[membre] \[temps] \[raison]</mark>. La durée d'un mute ne peut pas dépasser **28 jours**.
Peut-être un retour à la ligne pour la date ?
```suggestion
Vous pouvez réduire au silence un membre avec la commande <mark style="color:orange;">/mute \[membre] \[temps] \[raison]</mark>.\
La durée d'un mute ne peut pas dépasser **28 jours**.
```

2023-02-16 14:06 UTC, ErwanGit commented on slash/moderation.md
> +Vous pouvez bannir un membre avec la commande <mark style="color:orange;">/ban \[utilisateur] \[raison]</mark>. Deux options s'offrent à vous :
Proposition
```suggestion
Vous pouvez bannir un membre avec la commande <mark style="color:orange;">/ban \[utilisateur] \[raison]</mark>. Deux options facultatives supplémentaires s'offrent à vous :
```

2023-02-17 14:27 UTC, Hugo-broc commented on slash/moderation.md
> +**DraftBot** peut donner une note à un membre uniquement si vous disposez de la permission "_Gérer les messages_" sur votre serveur.
```suggestion
DraftBot peut donner un **avertissement** à un membre uniquement si vous disposez de la permission "_Gérer les messages_" sur votre serveur.
```

2023-02-17 14:40 UTC, ErwanGit requested changes

2023-02-17 14:40 UTC, ErwanGit commented on slash/moderation.md
> +**DraftBot** peut donner une note à un membre uniquement si vous disposez de la permission "_Gérer les messages_" sur votre serveur.
Aucun changement effectué ici

2023-02-17 14:40 UTC, ErwanGit commented on slash/moderation.md
> +**DraftBot** peut donner un avertissement à un membre uniquement si vous disposez de la permission "_Gérer les messages_" sur votre serveur.
Aucun changement apporté

2023-02-17 14:55 UTC, Hugo-broc commented on slash/moderation.md
> +**DraftBot** peut donner une note à un membre uniquement si vous disposez de la permission "_Gérer les messages_" sur votre serveur.
Cela a été résolu pourtant
![image](https://user-images.githubusercontent.com/120671943/219688264-e4829a5e-03f6-43d2-a7c7-6deeb188b5b1.png)

2023-02-17 14:55 UTC, Hugo-broc commented on slash/moderation.md
> +**DraftBot** peut donner un avertissement à un membre uniquement si vous disposez de la permission "_Gérer les messages_" sur votre serveur.
Cela a été résolu pourtant
![image](https://user-images.githubusercontent.com/120671943/219688444-12e84a03-3044-4752-a31c-83bcace82cc1.png)

2023-02-17 16:42 UTC, ErwanGit commented on slash/moderation.md
> +**DraftBot** peut donner une note à un membre uniquement si vous disposez de la permission "_Gérer les messages_" sur votre serveur.
C'est faux car il n'est pas nécessaire d'avoir cette permission si l'administrateur a donné accès à la commande à travers un rôle indépendamment des permissions

2023-02-17 16:42 UTC, ErwanGit commented on slash/moderation.md
> +**DraftBot** peut donner un avertissement à un membre uniquement si vous disposez de la permission "_Gérer les messages_" sur votre serveur.
Même chose que plus haut

2023-02-17 23:39 UTC, Hugo-broc commented on slash/moderation.md
> +**DraftBot** peut donner une note à un membre uniquement si vous disposez de la permission "_Gérer les messages_" sur votre serveur.
Mais du coup, on n'a pas besoin de le mettre tout court en fait, c'est cela ?

2023-02-18 08:59 UTC, ErwanGit commented on slash/moderation.md
> +**DraftBot** peut donner une note à un membre uniquement si vous disposez de la permission "_Gérer les messages_" sur votre serveur.
Soit tu peux ne pas le mettre, soit tu indiques que c'est la permission par défaut et que cela peut être modifier dans les intégrations (peut-être faire une page exprès sur la documentation pour ça ?)

2023-02-18 14:19 UTC, Hugo-broc commented on slash/moderation.md
> +**DraftBot** peut donner une note à un membre uniquement si vous disposez de la permission "_Gérer les messages_" sur votre serveur.
@ErwanGit, cela te semble mieux comme cela ?
```suggestion
{% hint style="warning" %}
**DraftBot** peut donner une note à un membre uniquement si vous disposez de la permission "_Gérer les messages_" ou qu'un de vos rôles peut utiliser la commande <mark style="color:orange;">/note</mark> sur votre serveur.
{% endhint %}
```

2023-02-18 19:33 UTC, ErwanGit commented on slash/moderation.md
> +**DraftBot** peut donner une note à un membre uniquement si vous disposez de la permission "_Gérer les messages_" sur votre serveur.
C'est mieux oui

2023-02-18 22:44 UTC, ErwanGit approved these changes

2023-02-19 00:39 UTC, IIbey commented on slash/moderation.md
> +Vous pouvez expulser un membre de votre serveur avec la commande <mark style="color:orange;">/expulser \[membre] \[raison]</mark>.
```suggestion
Le fait d'expulser un membre fera quitter le membre du serveur, mais il pourra toujours revenir avec une autre invitation. Si vous souhaitez qu'il ne puisse pas revenir, consultez le <mark style="color:orange;">[bannissement](moderation.md#bannissement)</mark>.\

Vous pouvez expulser un membre de votre serveur avec la commande <mark style="color:orange;">/expulser \[membre] \[raison]</mark>.
````

2023-02-19 00:43 UTC, IIbey requested changes

2023-02-19 00:43 UTC, IIbey commented on slash/moderation.md
> +Vous pouvez bannir un membre avec la commande <mark style="color:orange;">/ban \[utilisateur] \[raison]</mark>. Deux options facultatives supplémentaires s'offrent à vous :
Pareil ici.

```suggestion
Le fait de bannir un membre fera quitter le membre du serveur et il ne pourra jamais y revenir. Vous pouvez également bannir temporairement le membre en question. Si vous souhaitez qu'il puisse revenir sur votre serveur, consultez l'<mark style="color:orange;">[expulsion](moderation.md#expulsion)</mark>.\

Vous pouvez bannir un membre avec la commande <mark style="color:orange;">/ban \[utilisateur] \[raison]</mark>. Deux options facultatives supplémentaires s'offrent à vous :
```

2023-02-19 00:43 UTC, IIbey commented on slash/moderation.md
> +Vous pouvez expulser un membre de votre serveur avec la commande <mark style="color:orange;">/expulser \[membre] \[raison]</mark>.
Je pense que c'est mieux de mettre un espace pour aérer les textes.

```suggestion
Le fait d'expulser un membre fera quitter le membre du serveur, mais il pourra toujours revenir avec une autre invitation. Si vous souhaitez qu'il ne puisse pas revenir, consultez le <mark style="color:orange;">[bannissement](moderation.md#bannissement)</mark>.\

Vous pouvez expulser un membre de votre serveur avec la commande <mark style="color:orange;">/expulser \[membre] \[raison]</mark>.
````

2023-02-19 14:57 UTC, IIbey commented on slash/moderation.md
> +Vous pouvez ajouter une note à un membre dans son historique de sanctions avec <mark style="color:orange;">/note \[utilisateur] \[note]</mark>\
```suggestion
Vous pouvez ajouter une note à un membre dans son historique de sanctions avec <mark style="color:orange;">/note \[utilisateur] \[note].</mark>\

2023-02-19 14:57 UTC, IIbey requested changes

2023-02-19 14:57 UTC, IIbey commented on slash/moderation.md
> +Vous pouvez ajouter une note à un membre dans son historique de sanctions avec <mark style="color:orange;">/note \[utilisateur] \[note]</mark>\
Après cela, je pense que c'est bon
```suggestion
Vous pouvez ajouter une note à un membre dans son historique de sanctions avec <mark style="color:orange;">/note \[utilisateur] \[note].</mark>\

2023-02-20 23:47 UTC, IIbey approved these changes

2023-02-21 01:03 UTC, DraftProducts approved these changes

2023-02-21 01:04 UTC, merged