feat-welcome-messages
DraftBot/Documentation pull request #20
Opened 2023-02-12 11:09 UTC by bariboo

- Ajout de tabs pour configurer depuis le panel.

2023-02-22 23:01 UTC, IIbey requested changes

2023-02-22 23:01 UTC, IIbey commented on slash/configuration/arrivees-and-departs.md
>  Pour changer le message qui sera envoyé à l'arrivé d'un membre, il vous suffit de cliquer sur "Message personnalisé", il vous sera possible ensuite d'indiquer le texte.
```suggestion
Pour changer le message qui sera envoyé à l'arrivée d'un membre, il vous suffit de cliquer sur "Message personnalisé", il vous sera possible ensuite d'indiquer le texte.

2023-02-22 23:01 UTC, IIbey commented on slash/configuration/arrivees-and-departs.md
>  Pour mentionner un membre à son arrivé, il vous suffit de cliquer sur "Mentionner le membre". Si vous souhaitez désactiver la mention du membre à son arrivé, vous pouvez cliquer sur <mark style="colo
```suggestion
Pour mentionner un membre à son arrivée, il vous suffit de cliquer sur "Mentionner le membre". Si vous souhaitez désactiver la mention du membre à son arrivé, vous pouvez cliquer sur <mark style="color:green;">"Mention activée"</mark>.

2023-02-24 21:04 UTC, ErwanGit requested changes

2023-02-24 21:04 UTC, ErwanGit commented on slash/configuration/arrivees-and-departs.md
> +Si vous souhaitez mettre une couleur de votre choix ou avoir la possibilitée d'upload une image de votre choix, il vous faut être <mark style="color:orange;">[premium](https://draftbot.fr/premium)</m
Il faut éviter ce genre de franglais 
```suggestion
Si vous souhaitez mettre une couleur de votre choix ou définir une image de fond de votre choix, il vous faut être <mark style="color:orange;">[premium](https://draftbot.fr/premium)</mark>.
```

2023-02-24 21:04 UTC, ErwanGit commented on slash/configuration/arrivees-and-departs.md
> +![Modifier la couleur de fond du message de bienvenue](../../.gitbook/assets/welcome/dashboard-imagefond.gif)
Les noms de fichiers doivent-être en anglais et pas en franglais

2023-02-24 21:04 UTC, ErwanGit commented on slash/configuration/arrivees-and-departs.md
> +{% endhint %}
```suggestion
{% hint style="info" %}
Les dimensions optimales de l'image sont de 1000 x 300 pixels.
{% endhint %}
```

2023-02-24 21:04 UTC, ErwanGit commented on slash/configuration/arrivees-and-departs.md
> +Si vous voulez modifier la couleur de fond de votre message de bienvenue, rendez vous sur la <mark style="color:orange;">prévisalisation</mark> puis lorsque vous êtes sur l'image, cliquez sur le bout
```suggestion
Si vous voulez modifier la couleur de fond de votre message de bienvenue, rendez vous sur la <mark style="color:orange;">prévisualisation</mark> puis lorsque vous êtes sur l'image, cliquez sur le bouton "Modifier". 
```

2023-02-25 17:17 UTC, bariboo commented
Pour rester dans le même principe que sur les autres pages, je refais la partie `via la commande /config`.  En attente de review ! 
Mais j'ai une question : j'ai fais la configuration étape par étape aussi pour le panel, je le laisse ou je fais comme pour les pages économie et Niveau ?

2023-02-25 17:32 UTC, bariboo commented
(Je ne fais que la partie Message de bienvenue pour le moment puis je ferai les messages d'au revoir une fois que vous aurez valider)

2023-02-26 20:43 UTC, ErwanGit requested changes
L179: Retirer les parehentèses

2023-02-26 20:43 UTC, ErwanGit commented on slash/configuration/arrivees-and-departs.md
> +- "<mark style="color:blue;"># Salon d'envoi"</mark> ➜ Définir le salon où le message de bienvenue sera envoyé.
J'aurai plutôt mis comme ça
```suggestion
- "<mark style="color:blue;">Salon d'envoi"</mark> ➜ Définir le salon où le message de bienvenue sera envoyé.
```

2023-02-26 20:43 UTC, ErwanGit commented on slash/configuration/arrivees-and-departs.md
> +Les variables sont des bouts de texte qui évoluent suivant la personne, le serveur, le salon ou encore le temps. Voici celles utilisables dans les messages de bienvenue de **Draftbot**.
```suggestion
Les variables sont des bouts de texte qui évoluent suivant la personne, le serveur, le salon ou encore le temps. Voici celles utilisables dans les messages de bienvenue de **DraftBot**.
```

2023-02-26 20:43 UTC, ErwanGit commented on slash/configuration/arrivees-and-departs.md
> +Votre message doit faire au maxiumum 1200 caractères.
```suggestion
Votre message doit faire au maximum 1 200 caractères.
```

2023-02-26 20:43 UTC, ErwanGit commented on slash/configuration/arrivees-and-departs.md
> +- "@ Mentionner le membre" ➜ Une fois cette option activée, le membre sera mentionné dans le message de bienvenue.
Même chose qu'au dessus
```suggestion
- "Mentionner le membre" ➜ Une fois cette option activée, le membre sera mentionné dans le message de bienvenue.
```

2023-02-26 20:43 UTC, ErwanGit commented on slash/configuration/arrivees-and-departs.md
> +Les variables sont des bouts de texte qui évoluent suivant la personne, le serveur, le salon ou encore le temps. Voici celles utilisables dans les messages de bienvenue de **Draftbot**.
+ le markdown fonctionne pas, je pense à cause du fait qu'il y a pas de saut de ligne
```suggestion
Les variables sont des bouts de texte qui évoluent suivant la personne, le serveur, le salon ou encore le temps. Voici celles utilisables dans les messages de bienvenue de **DraftBot**.
```

2023-02-26 20:43 UTC, ErwanGit commented on slash/configuration/arrivees-and-departs.md
> +Les variables sont des bouts de texte qui évoluent suivant la personne, le serveur, le salon ou encore le temps. Voici celles utilisables dans les messages de bienvenue de **Draftbot**.
Il y a pas de sauts de lignes sur la documentation

2023-02-26 20:43 UTC, ErwanGit commented on slash/configuration/arrivees-and-departs.md
> +Si vous voulez modifier la couleur de fond de votre message de bienvenue, rendez vous sur la <mark style="color:orange;">prévisalisuation</mark> puis lorsque vous êtes sur l'image, cliquez sur le bou
```suggestion
Si vous voulez modifier la couleur de fond de votre message de bienvenue, rendez vous sur la <mark style="color:orange;">prévisualisation</mark> puis lorsque vous êtes sur l'image, cliquez sur le bouton "Modifier".
```

2023-03-02 14:18 UTC, Hugo-broc requested changes

2023-03-02 14:18 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +- `{user.tag}` ➜ Tag du membre _Pseudo#0000_
```suggestion
- `{user.tag}` ➜ Tag du membre _(Pseudo#0000)_
```

2023-03-02 14:18 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +Vous avez le choix entre trois couleurs ainsi que celui par défaut avec le bouton <mark style="color:red;">"Aucune"</mark>, si vous souhaitez en avoir une personnalisée, vous devez avoir un abonnemen
```suggestion
Vous avez le choix entre trois couleurs ainsi que celle par défaut (avec le bouton "<mark style="color:red;">Aucune</mark>").\
Si vous souhaitez avoir une couleur personnalisée, vous devez avoir un abonnement <mark style="color:blue;">[premium](https://draftbot.fr/premium)</mark>.
```

2023-03-02 14:18 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +- "Image" ➜ Permet d'ajouter une image une image de fond à votre message de bienvenue. **_([✨ premium](https://draftbot.fr/premium))_**
```suggestion
- "Image" ➜ Permet d'ajouter une image de fond à votre message de bienvenue. **_([✨ premium](https://draftbot.fr/premium))_**
```

2023-03-02 14:18 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +Veuillez d'abord vous rendre sur le <mark style="color:orange;">[Panel](https://draftbot.fr/dashboard/)</mark> ➜ Arrivées & départs.
```suggestion
Veuillez d'abord vous rendre sur le <mark style="color:orange;">[panel de **DraftBot**](https://draftbot.fr/dashboard/)</mark> ➜ Arrivées & départs.
```

2023-03-02 14:18 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +### Activer et désactiver le système de Message de bienvenue
```suggestion
### Activer ou désactiver le système de messages de bienvenue
```

2023-03-02 14:18 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +Pour faire cela, cliquez sur le sélecteur intitulé <mark style="color:orange;">Salon des messages de bienvenue</mark>, puis choisissez le salon voulu.
```suggestion
Pour faire cela, cliquez sur le sélecteur intitulé "Salon des messages de bienvenue", puis choisissez le salon voulu.
```

2023-03-02 14:18 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +Pour modifier le message de bienvenue, rendez-vous dans <mark style="color:orange;">Message personnalisé</mark>. Vous pouvez ensuite modifier le texte à votre guise.
```suggestion
Pour modifier le message de bienvenue, rendez-vous dans "Message personnalisé". Vous pouvez ensuite modifier le texte à votre guise.
```

2023-03-02 14:18 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +</details>
Sinon le menu déroulant ne fonctionne pas.
```suggestion
<details>
```

2023-03-02 14:18 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +Les variables sont des bouts de texte qui évoluent suivant la personne, le serveur, le salon ou encore le temps. Voici celles utilisables dans les messages de bienvenue de **Draftbot**.
Tout à fait, il faut donc enlever le markdown **en plus** de rectifier le nom de DraftBot.

2023-03-02 14:18 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +- `{user.tag}` ➜ Tag du membre _Pseudo#0000_
*(Par contre le markdown fonctionne bien dans la liste ici.)*
```suggestion
- `{user.tag}` ➜ Tag du membre _(Pseudo#0000)_
```

2023-03-02 14:18 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> + Votre message doit faire au maxiumum 1200 caractères.
```suggestion
 Votre message peut faire au maximum 1 200 caractères.
```

2023-03-02 14:18 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +Pour mentionner automatiquement un membre à son arrivée, vous devez activer le module <mark style="color:orange;">Mentionner le membre dans son message de bienvenue</mark>.
```suggestion
Pour mentionner automatiquement un membre à son arrivée, vous devez activer le module "Mentionner le membre dans son message de bienvenue".
```

2023-03-02 14:18 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +### Changer la couleur du message de bienvenue.
```suggestion
### Changer la couleur du message de bienvenue
```

2023-03-02 14:18 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +Pour activer le système d'au revoir, il vous suffit de cliquer sur "Activer le système". Si vous souhaitez désactiver le système, il vous suffit de cliquer sur <mark style="color:green;">"Système act
```suggestion
Pour activer le système de messages d'au revoir, il vous suffit de cliquer sur "Activer le système". Si vous souhaitez désactiver le système, il vous suffit de cliquer sur <mark style="color:green;">"Système activé"</mark>.
```

2023-03-10 14:23 UTC, Hugo-broc requested changes

2023-03-10 14:23 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +"<mark style="color:blue;">Salon d'envoi"</mark> ➜ Définir le salon où le message de bienvenue sera envoyé.
```suggestion
"<mark style="color:blue;">Salon d'envoi</mark>" ➜ Définir le salon où le message de bienvenue sera envoyé.
```

2023-03-10 14:23 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +Votre message doit faire au maxiumum 1 200 caractères.
Attention, cette faute avait déjà été remontée plus haut !
```suggestion
Votre message doit faire au maximum 1 200 caractères.
```

2023-03-10 14:23 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +"<mark style="color:blue;">Salon d'envoi"</mark> ➜ Définir le salon où le message de bienvenue sera envoyé.
```suggestion
"<mark style="color:blue;">Salon d'envoi</mark>" ➜ Définir le salon où le message de bienvenue sera envoyé.
```

2023-03-10 14:23 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +Votre message doit faire au maxiumum 1 200 caractères.
Attention, cette faute avait déjà été remontée plus haut !
```suggestion
Votre message doit faire au maximum 1 200 caractères.
```

2023-03-10 14:23 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +Veuillez d'abord vous rendre sur le <mark style="color:orange;">[panel de **DraftBot**](https://draftbot.fr/dashboard/)</mark> ➜ Arrivées & départs.
Revoir comment a été mis le lien car cela s'affiche mal
![image](https://user-images.githubusercontent.com/120671943/224340132-36c67e38-ea36-4ab3-9dac-b619922ee4ba.png)

2023-03-10 14:30 UTC, Hugo-broc requested changes
Revoir toutes les images (sauf la première de la partie "Panel") car aucune ne s'affiche sur le rendu final :
![Problème d'images](https://user-images.githubusercontent.com/120671943/224341846-2a4af7f6-17ad-4693-bec2-70ff32dac55a.png)

2023-03-16 18:30 UTC, bariboo commented
Hello @DraftProducts , possible de check les images ? Après on pourra normalement merge !

2023-03-21 05:44 UTC, DraftProducts commented
Excuse-moi pour l'attente @bariboo, c'est fait !

Je pense qu'on peut aussi retirer le gif ou le remplacer par une image mettant en valeur le changement d'image.

2023-03-21 19:44 UTC, ErwanGit approved these changes

2023-03-24 13:36 UTC, IIbey requested changes

2023-03-24 13:36 UTC, IIbey commented on slash/configuration/arrivees-and-departs.md
> +Les dimensions optimales de l'image sont de 1000 x 300 pixels.
```suggestion
Les dimensions optimales de l'image sont de 1 000 x 300 pixels.

2023-03-24 13:36 UTC, IIbey commented on slash/configuration/arrivees-and-departs.md
> +Les dimensions optimales de l'image sont de 1000 x 300 pixels.
```suggestion
Les dimensions optimales de l'image sont de 1 000 x 300 pixels.

2023-03-27 18:47 UTC, Hugo-broc requested changes
Le sommaire n'est pas fait.

2023-03-27 18:59 UTC, Hugo-broc requested changes
Attention au copier-coller !
La moitié de mes changements viennent de là car la configuration des messages d'au revoir est la même que celle des messages de bienvenue.
Quand on fait du copier-coller, on oublie pas de changer ce qu'il y a à changer !

2023-03-27 18:59 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +"<mark style="color:blue;">Salon d'envoi</mark>" ➜ Définir le salon où le message de bienvenue sera envoyé.
La liste n'est pas mise avec `-` et donc le texte est collé à la ligne d'avant.
Supprimer également l'espace avec la ligne d'après.
```suggestion
- "<mark style="color:blue;">Salon d'envoi</mark>" ➜ Définir le salon où le message de bienvenue sera envoyé.
```

2023-03-27 18:59 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +Si vous souhaitez en avoir une personnalisée, vous devez être souscrit à  un abonnement <mark style="color:blue;">[premium](https://draftbot.fr/premium)</mark>.
```suggestion
Si vous souhaitez avoir une couleur personnalisée, vous devez souscrire à un abonnement <mark style="color:blue;">[premium](https://draftbot.fr/premium)</mark>.
```

2023-03-27 18:59 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +Vous devez d'abord activer le système en cliquant sur le bouton d'activation du module. Si vous voulez le désactiver, recliquez sur ce même bouton.
"ensuite" à la place de "d'abord" car il est déjà dans la phrase au dessus, c'est trop répétitif au sinon.
```suggestion
Vous devez ensuite activer le système en cliquant sur le bouton d'activation du module. Si vous voulez le désactiver, recliquez sur ce même bouton.
```

2023-03-27 18:59 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +"<mark style="color:blue;">Salon d'envoi</mark>" ➜ Définir le salon où le message de bienvenue sera envoyé.
La liste n'est pas mise avec `-` et donc le texte est collé à la ligne d'avant.
Supprimer également l'espace avec la ligne d'après.
```suggestion
- "<mark style="color:blue;">Salon d'envoi</mark>" ➜ Définir le salon où le message de bienvenue sera envoyé.
```

2023-03-27 18:59 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +Les variables sont des bouts de texte qui évoluent suivant la personne, le serveur, le salon ou encore le temps. Voici celles utilisables dans les messages de bienvenue de DraftBot.
L'inconvénient du copier-coller :joy:
```suggestion
Les variables sont des bouts de texte qui évoluent suivant la personne, le serveur, le salon ou encore le temps. Voici celles utilisables dans les messages d'au revoir de DraftBot.
```

2023-03-27 18:59 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +"<mark style="color:blue;">Salon d'envoi</mark>" ➜ Définir le salon où le message de bienvenue sera envoyé.
```suggestion
"<mark style="color:blue;">Salon d'envoi</mark>" ➜ Définir le salon où le message d'au revoir sera envoyé.
```

2023-03-27 18:59 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +- "Couleur de fond" ➜ Permet de modifier la couleur de fond du message de bienvenue.
Again !
```suggestion
- "Couleur de fond" ➜ Permet de modifier la couleur de fond du message d'au revoir.
```

2023-03-27 18:59 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +Si vous souhaitez en avoir une personnalisée, vous devez être souscrit à un abonnement <mark style="color:blue;">[premium](https://draftbot.fr/premium)</mark>.
```suggestion
Si vous souhaitez avoir une couleur personnalisée, vous devez souscrire à un abonnement <mark style="color:blue;">[premium](https://draftbot.fr/premium)</mark>.
```

2023-03-27 18:59 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +- "Couleur" ➜ Définir la couleur de la barre latérale de votre message de bienvenue. **_([✨ premium](https://draftbot.fr/premium))_**
Attention, il y a beaucoup de fois cette faute...
```suggestion
- "Couleur" ➜ Définir la couleur de la barre latérale de votre message d'au revoir. **_([✨ premium](https://draftbot.fr/premium))_**
```

2023-03-27 18:59 UTC, Hugo-broc commented on slash/configuration/arrivees-and-departs.md
> +- "Image" ➜ Permet d'ajouter une image de fond à votre message de bienvenue. **_([✨ premium](https://draftbot.fr/premium))_**
Bah alors ?!
```suggestion
- "Image" ➜ Permet d'ajouter une image de fond à votre message d'au revoir. **_([✨ premium](https://draftbot.fr/premium))_**
```

2023-04-24 18:14 UTC, ErwanGit requested changes

2023-04-24 18:14 UTC, ErwanGit commented on slash/configuration/arrivees-and-departs.md
> +Vous avez le choix entre trois couleurs ainsi que celle par défaut (avec le bouton "<mark style="color:red;">Aucune</mark>").
Aucune = transparent 
A préciser

2023-04-29 08:23 UTC, ErwanGit requested changes

2023-04-29 08:23 UTC, ErwanGit commented on modules/arrivees-and-departs.md
> +ㅤ
Je trouve qu'il y a trop de sauts de ligne ici

2023-04-29 08:23 UTC, ErwanGit commented on modules/arrivees-and-departs.md
> +ㅤ
Je trouve qu'il y a trop de sauts de ligne ici

2023-04-29 08:23 UTC, ErwanGit commented on modules/arrivees-and-departs.md
> +
Je trouve qu'il y a trop de sauts de ligne ici

2023-04-29 08:23 UTC, ErwanGit commented on modules/arrivees-and-departs.md
> +- "Couleur de fond" ➜ Permet de modifier la couleur de fond du message d'au revoir.
Je trouve qu'il y a trop de sauts de ligne ici

2023-04-29 08:23 UTC, ErwanGit commented on modules/arrivees-and-departs.md
> +
Je trouve qu'il y a trop de sauts de ligne ici

2023-04-29 08:23 UTC, ErwanGit commented on .gitbook/assets/welcome/configuration-bye.png
modifier le nom de fichier avec `bye` => `goodbye` pour rester cohérent

2023-04-29 08:23 UTC, ErwanGit commented on .gitbook/assets/welcome/configuration-bye-color.png
modifier le nom de fichier avec `bye` => `goodbye` pour rester cohérent

2023-04-29 08:23 UTC, ErwanGit commented on .gitbook/assets/welcome/dashboard-bye-enable.png
modifier le nom de fichier avec `bye` => `goodbye` pour rester cohérent

2023-04-29 08:23 UTC, ErwanGit commented on .gitbook/assets/welcome/dashboard-bye-configuration.png
modifier le nom de fichier avec `bye` => `goodbye` pour rester cohérent

2023-04-29 08:23 UTC, ErwanGit commented on modules/arrivees-and-departs.md
A voir mais le nom des fichiers pour les pages sont en français

2023-04-30 14:53 UTC, ErwanGit requested changes

2023-04-30 14:53 UTC, ErwanGit commented on SUMMARY.md
> +- [👋 Arrivées & départs](modules/arrivees-and-departs.md)
```suggestion
- [👋 Arrivées & départs](modules/arrivees-et-departs.md)
```

2023-04-30 15:13 UTC, ErwanGit approved these changes

2023-05-04 09:21 UTC, IIbey approved these changes

2023-05-21 16:33 UTC, DraftProducts approved these changes
C'est tout bon pour moi !

2023-05-21 16:34 UTC, DraftProducts commented
Merci pour tout ce travail abattu !

2023-05-21 16:34 UTC, merged