Ajout des socialnotifs
DraftBot/Documentation pull request #21
Opened 2023-02-15 17:40 UTC by Tellvex

2023-02-18 22:03 UTC, ErwanGit requested changes
Je trouve que cette première version sur cette page des notifications sociales n'est pas très cohérente avec les autres pages redirigés par les autres membres 
Cela serait bien que la mise en page soit cohérente tout au long de la documentation, peu importe le ou les rédacteurs.

Egalement, je pense qu'il faudra revoir les captures d'écrans actuellement affichés
Les captures d'écrans ne sont pas assez bien rogner et on peut y voit des rôles et des images de fin
Tu peux éventuellement prendre les captures d'écrans qu'on avait fait avec Nicolas pour le `/config`, on avait essayer de faire des trucs propres
- YouTube : https://www.draftbot.fr/images/exemples/youtube.png
- Twitch : https://www.draftbot.fr/images/exemples/twitch.png
- Live Presence : https://www.draftbot.fr/images/exemples/presence.png
- Reddit : https://www.draftbot.fr/images/exemples/reddit.png

2023-02-19 12:22 UTC, Tellvex reviewed
Merci pour les arrière-plans 😀

2023-02-19 12:56 UTC, Tellvex commented
Ehm, j'crois j'ai fait de la merde pour les personnes en charge de review 😅
C'est possible de remettre les reviewers comme avant ?

2023-02-19 14:32 UTC, ErwanGit requested changes

2023-02-19 14:32 UTC, ErwanGit commented on slash/notifications-sociales.md
> +Le message sera entièrement **customisable** par les administrateurs, permettant (en général) d'avoir accès a un rôle de notifications pour **la sortie des vidéos**.
Pas convaincu de la tournure de la phrase

2023-02-19 14:32 UTC, ErwanGit commented on slash/notifications-sociales.md
> +Il peut y avoir **une seule notification sociale <mark style="color:orange;">[YouTube](https://www.youtube.com/)</mark> maximum** pour les serveurs **non-premiums** contrairement aux serveurs premium
Peut-être remplacer notification sociale par chaîne ? Dans les phrases de DraftBot, on ne parle jamais de notification sociale dans ce contexte là

2023-02-19 14:32 UTC, ErwanGit commented on slash/notifications-sociales.md
> +Les Notifications Sociales <mark style="color:orange;">[Twitch](https://www.twitch.tv/)</mark> sont limitées aux serveurs <mark style="color:orange;">[✨ Premiums](https://www.draftbot.fr/premium)</ma
Proposition
```suggestion
Les annonces <mark style="color:orange;">[Twitch](https://www.twitch.tv/)</mark> sont limitées aux serveurs <mark style="color:orange;">[✨ Premiums](https://www.draftbot.fr/premium)</mark>.
```

2023-02-19 14:32 UTC, ErwanGit commented on slash/notifications-sociales.md
> +Voici une illustration du module :
Pas convaincu d'avoir cette phrase

2023-02-19 14:32 UTC, ErwanGit commented on slash/notifications-sociales.md
> +Ce module permet d'afficher une notification lors d'une publication dans un subreddit.Comme pour les autres modules de notifications sociales, le message envoyé est entièrement customisable : il pour
Il y a un genre d'alinéa non voulu sur la documentation
![image](https://user-images.githubusercontent.com/24718500/219954363-0d78eed1-9a0d-4604-a9fc-ab9dec953bbe.png)

2023-02-19 14:32 UTC, ErwanGit commented on slash/notifications-sociales.md
> +Ce module permet d'afficher une notification lors d'une publication dans un subreddit.Comme pour les autres modules de notifications sociales, le message envoyé est entièrement customisable : il pour
```suggestion
Ce module permet d'afficher une notification lors d'une publication dans un subreddit. Comme pour les autres modules de notifications sociales, le message envoyé est entièrement customisable : il pourra donc être envoyé sous forme de **message classique ou sous forme d'embed.**
```

2023-02-19 14:32 UTC, ErwanGit commented on slash/notifications-sociales.md
> +Il peut y avoir **une seule notification <mark style="color:orange;">[Reddit](https://www.reddit.com/)</mark> maximum** pour les serveurs **non-premiums**, contrairement aux serveurs premiums qui pou
Peut-être parler de subreddit par rapport au commentaire plus haut ?

2023-02-19 14:32 UTC, ErwanGit commented on slash/notifications-sociales.md
> +L'envoi d'une notification live presence nécessite d'avoir **son compte Twitch ou Youtube lié à Discord**. Plus d'information ci-dessous.
+ le mode streamer doit être activé par le streamer, sinon il ne sera pas annoncé

2023-02-19 14:32 UTC, ErwanGit commented on slash/notifications-sociales.md
> +Le module **Live Presence** consiste a envoyer une notification lorsqu'un membre a un statut "**Streame** ..." (Symbolisé par la bulle violette et le triangle).
Peut-être mettre une illustration d'un profil Discord en live

2023-02-19 14:32 UTC, ErwanGit commented on slash/notifications-sociales.md
> +![Notification sociale de live presence](../.gitbook/assets/socialnotifs/view_presence.png)
```suggestion
![Notification sociale de Live Presence](../.gitbook/assets/socialnotifs/view_presence.png)
```

2023-02-19 14:32 UTC, ErwanGit commented on slash/notifications-sociales.md
> +Je vous invite à suivre <mark style="color:orange;">[ce tuto réalisé par Discord](https://support.discord.com/hc/fr/articles/8063233404823-Connexions-et-r%C3%B4les-li%C3%A9s-pour-les-membres-de-la-co
Il faut revoir cette phrase, pas du tout fan du "Je vous invite"
De plus, peut-être faire cela directement sur la documentation plutôt que rediriger ?

2023-02-19 15:36 UTC, Tellvex commented on slash/notifications-sociales.md
> +Le message sera entièrement **customisable** par les administrateurs, permettant (en général) d'avoir accès a un rôle de notifications pour **la sortie des vidéos**.
D'acc, je corrigerai ça

2023-02-19 15:39 UTC, Tellvex commented on slash/notifications-sociales.md
> +Je vous invite à suivre <mark style="color:orange;">[ce tuto réalisé par Discord](https://support.discord.com/hc/fr/articles/8063233404823-Connexions-et-r%C3%B4les-li%C3%A9s-pour-les-membres-de-la-co
J'y ai réfléchi et je pensais que ça s'éloignait trop du sujet initial, après j'ai déjà les screens de prêt donc je pourrait edit ça

2023-02-19 16:00 UTC, Tellvex commented on slash/notifications-sociales.md
> +L'envoi d'une notification live presence nécessite d'avoir **son compte Twitch ou Youtube lié à Discord**. Plus d'information ci-dessous.
Pas forcément : 
- Par défaut quand tu lances un live sur _youtube ou twitch_ (du moment où tu es sur OBS ou StreamLabs), ton mode streamer s'active par défaut. Quand tu démarres un live, le statut s'actualise

2023-02-19 16:04 UTC, Tellvex commented on slash/notifications-sociales.md
> +L'envoi d'une notification live presence nécessite d'avoir **son compte Twitch ou Youtube lié à Discord**. Plus d'information ci-dessous.
![image](https://user-images.githubusercontent.com/78918215/219959652-abafaf1a-db3c-4cfa-824c-2eead9fe02bf.png)

Par exemple, là je suis en mode streamer mais je ne suis pas en live et aucune notif s'affiche, cela dit si tu es en live mais sans le mode streamer actif, une notif s'enverra quand même car tu auras le statut "stream sur ..."

2023-02-19 16:05 UTC, Tellvex commented on slash/notifications-sociales.md
> +Le module **Live Presence** consiste a envoyer une notification lorsqu'un membre a un statut "**Streame** ..." (Symbolisé par la bulle violette et le triangle).
J'attendrais que Sparta soit en live

2023-02-19 16:07 UTC, ToutouilleDev commented on slash/notifications-sociales.md
> +Voici une illustration du module :
> Pas convaincu d'avoir cette phrase

Personnalisable à la place de customisable ?
Quelle partie de la phrase te plait moyen ?

2023-02-19 16:58 UTC, ToutouilleDev commented on slash/notifications-sociales.md
> +Le module **Live Presence** consiste a envoyer une notification lorsqu'un membre a un statut "**Streame** ..." (Symbolisé par la bulle violette et le triangle).
> J'attendrais que Sparta soit en live

J'ai lancé un live pour qu'il puisse ajouter l'image donc c'est bon pour ce point ( @ErwanGit )

2023-02-19 22:10 UTC, IIbey requested changes

2023-02-19 22:10 UTC, IIbey commented on slash/notifications-sociales.md
> +### Comment lier son compte Twitch ou Youtube à Discord
```suggestion
### Comment lier son compte Twitch ou YouTube à Discord

2023-02-19 22:10 UTC, IIbey commented on slash/notifications-sociales.md
> +Le module **Live Presence** consiste a envoyer une notification lorsqu'un membre a un statut "**Streame** ..." (Symbolisé par la bulle violette et le triangle).
```suggestion
Le module **Live Presence** consiste à envoyer une notification lorsqu'un membre a un statut "**Streame** ..." (symbolisé par la bulle violette et le triangle).

2023-02-19 22:10 UTC, IIbey commented on slash/notifications-sociales.md
> +Si vous n'avez pas le premium, il existe une alternative appellée le <mark style="color:orange;">[Live Presence](https://docs.draftbot.fr/modules/notifications-sociales#live-presence)</mark>.
```suggestion
Si vous n'avez pas le premium, il existe une alternative appelée le <mark style="color:orange;">[Live Presence](https://docs.draftbot.fr/modules/notifications-sociales#live-presence)</mark>.

2023-02-19 22:10 UTC, IIbey commented on slash/notifications-sociales.md
> +## Youtube
```suggestion
## YouTube

2023-02-19 22:40 UTC, Tellvex commented
Toutes les fautes que tu as mentionnées ( @IIbey ) sont corrigées.

2023-02-21 12:14 UTC, Tellvex commented on slash/notifications-sociales.md
> +Il peut y avoir **une seule notification <mark style="color:orange;">[Reddit](https://www.reddit.com/)</mark> maximum** pour les serveurs **non-premiums**, contrairement aux serveurs premiums qui pou
J'ai pas très bien compris, qu'est-ce que tu entends par "parler de subreddit". Globalement les gens qui activent cette feature connaissent un minimum reddit, donc savent globalement ce qu'est un subreddit

2023-02-21 12:16 UTC, Tellvex commented on slash/notifications-sociales.md
> +Je vous invite à suivre <mark style="color:orange;">[ce tuto réalisé par Discord](https://support.discord.com/hc/fr/articles/8063233404823-Connexions-et-r%C3%B4les-li%C3%A9s-pour-les-membres-de-la-co
Suite à une discussion sur le #documentation, on va rester sur une redirection, à voir si en fonction des retours on change ça plus tard, même si la priorité pour le moment est de terminer la page.

2023-02-21 14:39 UTC, IIbey requested changes

2023-02-21 14:39 UTC, IIbey commented on modules/notifications-sociales.md
> +L'envoi d'une notification live presence nécessite d'avoir **son compte Twitch ou Youtube lié à Discord**. Plus d'information ci-dessous.
```suggestion
L'envoi d'une notification live presence nécessite d'avoir **son compte Twitch ou YouTube lié à Discord**. Plus d'information ci-dessous.

2023-02-21 14:39 UTC, IIbey commented on modules/notifications-sociales.md
> +Suite a cette manipulation, vous devrez normalement avoir cet aperçu sur votre profil lorsque vous serez en live :
```suggestion
Suite à cette manipulation, vous devrez normalement avoir cet aperçu sur votre profil lorsque vous serez en live :

2023-02-21 14:39 UTC, IIbey commented on modules/notifications-sociales.md
> +Ce module permet d'afficher des bandes-dessinées en lien avec le métier de développeur.
```suggestion
Ce module permet d'afficher des bandes dessinées en lien avec le métier de développeur.

2023-02-21 16:37 UTC, Tellvex commented
@IIbey toutes les fautes ont été corrigées !

2023-02-21 20:44 UTC, ErwanGit requested changes
J'arrive pas à accéder à la prévisualisation sur GitHub, je suppose qu'il y a un soucis au niveau du sommaire, il faudra regarder cela

2023-02-21 20:44 UTC, ErwanGit commented on modules/notifications-sociales.md
> +![Image de live](../.gitbook/assets/socialnotifs/view_live.jpg)
Alors, je suis pas en faveur de cette capture d'écran précise pour plusieurs raisons : 
- Le titre du stream pourrait être un vrai titre de simulation et non un titre par défaut
- Cette capture d'écran affiche les rôles du support : en sachant que les couleurs des rôles du support changent régulièrement et que cette documentation a pour but de rester à jour dans le temps, je serai pour retirer les rôles de la capture d'écran pour éviter de donner l'impression que cette capture d'écran est trop ancienne alors que l'interface de Discord n'a pas changé
- La capture d'écran fait la promotion d'un serveur externe au support de DraftBot, je ne suis pas en faveur de faire de la publicité sur des plateformes officielles sur des projets non affiliées à DraftBot directement

2023-02-21 20:44 UTC, ErwanGit commented on modules/notifications-sociales.md
> +![Notification sociale EpicGames](../.gitbook/assets/socialnotifs/view_epicgames.jpg)
La couleur de l'embed a été omis, es-ce voulu ?

2023-02-21 20:44 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Ce module permet d'envoyer une annonce lorsqu'un jeu gratuit est disponible sur le EpicGames Store.
```suggestion
Ce module permet d'envoyer une annonce lorsqu'un jeu gratuit est disponible sur le Epic Games Store.
```

2023-02-21 20:44 UTC, ErwanGit commented on modules/notifications-sociales.md
> +![Notification sociale EpicGames](../.gitbook/assets/socialnotifs/view_epicgames.jpg)
```suggestion
![Notification sociale Epic Games](../.gitbook/assets/socialnotifs/view_epicgames.jpg)
```

2023-02-21 20:44 UTC, ErwanGit commented on modules/notifications-sociales.md
> +*Illustration a placer ici*
Si besoin, on peut forcer une annonce pour prendre une capture d'écran
Vous pouvez demander à moi ou Nicolas, cela devrait pas poser de problème

2023-02-21 20:44 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Voici <mark style="color:orange;">[ce tuto réalisé par Discord](https://support.discord.com/hc/fr/articles/8063233404823-Connexions-et-r%C3%B4les-li%C3%A9s-pour-les-membres-de-la-communaut%C3%A9)</ma
```suggestion
Voici <mark style="color:orange;">[ce tutoriel réalisé par Discord](https://support.discord.com/hc/fr/articles/8063233404823-Connexions-et-r%C3%B4les-li%C3%A9s-pour-les-membres-de-la-communaut%C3%A9)</mark> qui explique globalement comment ajouter des connexions ainsi que l'obtention des rôles liés sur un serveur.
```

2023-02-21 20:44 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Voici <mark style="color:orange;">[ce tuto réalisé par Discord](https://support.discord.com/hc/fr/articles/8063233404823-Connexions-et-r%C3%B4les-li%C3%A9s-pour-les-membres-de-la-communaut%C3%A9)</ma
Je ne pense pas qu'il soit utile de parler des rôles liées ici
Egalement, on peut directement mettre le lien qui va sur la partie des connexions je pense si tu souhaites vraiment rediriger sur cette page de Discord
```suggestion
Voici <mark style="color:orange;">[ce tuto réalisé par Discord](https://support.discord.com/hc/fr/articles/8063233404823-Connexions-et-rôles-liés-pour-les-membres-de-la-communauté#h_01GRWEP9GQ1SSBN1Q0TX30E4EP)</mark> qui explique globalement comment ajouter des connexions ainsi que l'obtention des rôles liés sur un serveur.
```

2023-02-21 20:44 UTC, ErwanGit commented on modules/notifications-sociales.md
> +## Live Presence
On pourrait profiter de la documentation pour parler d'éléments techniques, comme le fait par exemple qu'il existe un cooldown de 30min au niveau des nouvelles annonces de ce module pour éviter les potentiels spams

2023-02-25 11:21 UTC, Tellvex commented on modules/notifications-sociales.md
> +![Notification sociale EpicGames](../.gitbook/assets/socialnotifs/view_epicgames.jpg)
J'ai pris une capture venant du serveur de Lucas (ls69), je pense tout simplement qu'il a désactivé la couleur. Je peux éventuellement prendre une autre capture si tu veux.

2023-02-25 14:16 UTC, ErwanGit commented on modules/notifications-sociales.md
> +![Notification sociale EpicGames](../.gitbook/assets/socialnotifs/view_epicgames.jpg)
Pour rester cohérent avec les autres captures oui

2023-02-27 16:20 UTC, Tellvex commented
@ErwanGit et @Hugo-broc, le problème d'aperçu a été corrigé, vous pouvez donc voir a quoi ressemblent les dernières updates

2023-02-28 18:02 UTC, ErwanGit requested changes

2023-02-28 18:02 UTC, ErwanGit commented on modules/notifications-sociales.md
> +
Je pense qu'il faudrait développer la configuration

2023-02-28 18:02 UTC, ErwanGit commented on modules/notifications-sociales.md
> +
Je pense qu'il faudrait développer la configuration

2023-02-28 18:02 UTC, ErwanGit commented on modules/notifications-sociales.md
> +*Illustration a placer ici*
Je pense qu'il faudrait développer la configuration

2023-02-28 18:02 UTC, ErwanGit commented on modules/notifications-sociales.md
> +*Illustration a placer ici*
Je pense qu'il faudrait développer la configuration

2023-02-28 19:19 UTC, Hugo-broc requested changes
- Je trouve qu'il y a beaucoup de texte en gras par rapport aux autres pages. Peut-être en enlever un peu...
- Je suis d'accord avec Erwan sur le fait qu'il faut détailler plus la configuration des différents systèmes. Comme la configuration est possible via /config **et** sur le panel, il faudrait détailler la configuration sur chacun d'entre eux sur une table.
Il y a encore pas mal de boulot.

2023-02-28 19:19 UTC, Hugo-broc commented on modules/notifications-sociales.md
> +Il peut y avoir **une seule chaîne <mark style="color:orange;">[YouTube](https://www.youtube.com/)</mark> différente** pour les serveurs **non-premiums** contrairement aux serveurs premiums qui peuve
La formulation peut sûrement être encore améliorée mais je la trouve mieux qu'auparavant.
```suggestion
{% hint style="info" %}
Avec le <mark style="color:orange;">[premium](https://draftbot.fr/premium)</mark>, débloquez la limite de 1 chaîne suivie (limite en n'ayant pas le premium) en passant à 5 chaînes YouTube différentes.
{% endhint %}
```

2023-02-28 19:19 UTC, Hugo-broc commented on modules/notifications-sociales.md
> +Les annonces <mark style="color:orange;">[Twitch](https://www.twitch.tv/)</mark> sont limitées aux serveurs <mark style="color:orange;">[✨ Premiums](https://www.draftbot.fr/premium)</mark>.
```suggestion
Les annonces <mark style="color:orange;">[Twitch](https://www.twitch.tv/)</mark> sont limitées aux serveurs <mark style="color:orange;">[✨ premiums](https://www.draftbot.fr/premium)</mark>.
```

2023-02-28 19:19 UTC, Hugo-broc commented on modules/notifications-sociales.md
> +Si vous n'avez pas le premium, il existe une alternative appelée le <mark style="color:orange;">[Live Presence](https://docs.draftbot.fr/modules/notifications-sociales#live-presence)</mark>.
```suggestion
Si vous n'avez pas le premium, il existe une alternative appelée le <mark style="color:orange;">[live presence](https://docs.draftbot.fr/modules/notifications-sociales#live-presence)</mark>.
```

2023-02-28 19:19 UTC, Hugo-broc commented on modules/notifications-sociales.md
> +Il faut aussi noter que l'administrateur peut configurer le module dealabs uniquement pour certaines catégories (exemples : High-Tech).
Soit mettre exemple au singulier si tu ne mets qu'un exemple ou bien alors remettre au pluriel si tu ajoutes ou ou des exemples en plus.
```suggestion
Il faut aussi noter que l'administrateur peut configurer le module dealabs uniquement pour certaines catégories (exemple : High-Tech).
```

2023-02-28 19:51 UTC, Tellvex commented on modules/notifications-sociales.md
> +
C'est prévu, juste que j'avais pas la motivation pour continuer et que je me renseignais sur les tabs. J'ai aussi un avis à vous demander sur le #documentation (discord) par rapport à ça.

2023-02-28 19:53 UTC, Tellvex commented on modules/notifications-sociales.md
> +Le module **Live Presence** consiste à envoyer une notification lorsqu'un membre a un statut "**Streame** ..." (symbolisé par la bulle violette et le triangle).
D'acc, on pourrait aussi pousser ça plus loin et faire comme sur la page socialnotifs (en prefix) et ajouter l'icône de la plateforme dans le titre.

2023-02-28 19:57 UTC, Tellvex commented
Comme je l'ai précisé dans la review de @ErwanGit, j'ai un sondage à faire par rapport à la configuration. De plus, je ne sais pas qui a passé cette pr  en "Ready for review" car j'étais loin d'avoir terminé. De plus, j'en avais parlé avec @DraftProducts, mais on va sûrement ajouter la page Twitter dans le tas et on publiera la page après l'update.

( @Hugo-broc et @ErwanGit )

2023-02-28 19:59 UTC, Tellvex commented on modules/notifications-sociales.md
> +Il peut y avoir **une seule chaîne <mark style="color:orange;">[YouTube](https://www.youtube.com/)</mark> différente** pour les serveurs **non-premiums** contrairement aux serveurs premiums qui peuve
Je trouve que passer cela en hint est une bonne idée, cela dit je ne suis pas trop ok pour ne pas afficher la limite de notifs avec le premium.

2023-03-21 05:39 UTC, DraftProducts commented
Twitter étant annulé, il faudrait le retirer de la documentation si il avait été ajouté.

2023-03-21 10:15 UTC, Tellvex commented
Twitter n'a pas été mis de mémoire

2023-03-30 20:44 UTC, DraftProducts commented
Excuse moi, j'avais pas vu ton message.
Oui si t'es motivé pour t'en occuper ce serait nice.
Pour ce qui est du screen où on voit Twitter je m'en occuperais :)

2023-04-16 10:40 UTC, ErwanGit requested changes

2023-04-16 10:40 UTC, ErwanGit commented on modules/notifications-sociales.md
> +> Vous trouverez dans cette partie la liste des Notifications Sociales ainsi que leur utilité.
Es-ce vraiment nécessaire ?

2023-04-16 10:40 UTC, ErwanGit commented on modules/notifications-sociales.md
> +### Live Presence
Éventuellement parler d'un cooldown de 30min avant une nouvelle annonce pour éviter le spam

2023-04-16 10:40 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Ce module permet d'envoyer une notification lorsqu'une réduction devient "hot".
Peut-être définir hot en français

2023-04-16 10:40 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Il faut aussi noter que l'administrateur peut configurer le module dealabs uniquement pour certaines catégories (exemples : High-Tech).
```suggestion
Il faut aussi noter que l'administrateur peut configurer le module Dealabs uniquement pour certaines catégories (exemples : High-Tech).
```

2023-04-16 10:40 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Vous retrouverez le nombre maximum d'annonces par plateformes sur <mark style="color:orange;">[le comparatif de Draftbot Premium](https://www.draftbot.fr/premium#diff)</mark> dans la partie <mark sty
```suggestion
Vous retrouverez le nombre maximum d'annonces par plateformes sur <mark style="color:orange;">[le comparatif de DraftBot Premium](https://www.draftbot.fr/premium#diff)</mark> dans la partie <mark style="color:orange;">Notifications sociales</mark>.
```

2023-04-16 10:40 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Vous retrouverez le nombre maximum d'annonces par plateformes sur <mark style="color:orange;">[le comparatif de Draftbot Premium](https://www.draftbot.fr/premium#diff)</mark> dans la partie <mark sty
Vraiment nécessaire vu que les limites sont indiqués dans chaque partie ?

2023-04-16 10:40 UTC, ErwanGit commented on modules/notifications-sociales.md
> +{% tab title="Configuration via le <mark style="color:orange;">[Panel](https://www.draftbot.fr/panel)</mark>" %}
Le markdown ne marche pas sur les titres de tableaux

2023-04-16 10:40 UTC, ErwanGit commented on modules/notifications-sociales.md
> +{% tab title="Configuration via le `/config`" %}
Le markdown ne marche pas sur les titres de tableaux
```suggestion
{% tab title="Configuration via le /config" %}
```

2023-04-16 10:40 UTC, ErwanGit commented on modules/notifications-sociales.md
> +{% endhint %}
C'est faux normalement avec les modifications de Nicolas

2023-04-16 10:40 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Ce module permet d'afficher des bandes dessinées en lien avec le métier de développeur.
Voir pour développer avec les configurations possibles par l'administrateur

2023-04-16 10:40 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Ce module permet d'envoyer une annonce lorsqu'un jeu gratuit est disponible sur GOG.
Voir pour développer avec les configurations possibles par l'administrateur

2023-04-16 10:40 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Ce module permet d'envoyer une annonce lorsqu'un jeu gratuit est disponible sur Steam.
Voir pour développer avec les configurations possibles par l'administrateur

2023-04-16 10:40 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Ce module permet d'envoyer une annonce lorsqu'un jeu gratuit est disponible sur l'Epic Games Store.
Voir pour développer avec les configurations possibles par l'administrateur

2023-04-16 12:08 UTC, Tellvex commented on modules/notifications-sociales.md
> +Vous retrouverez le nombre maximum d'annonces par plateformes sur <mark style="color:orange;">[le comparatif de Draftbot Premium](https://www.draftbot.fr/premium#diff)</mark> dans la partie <mark sty
C'est toujours mieux de laisser ça, si jamais c'est pas clair pour eux ils pourront voir les avantages sur le premium#diff

2023-04-16 12:10 UTC, Tellvex commented on modules/notifications-sociales.md
> +{% endhint %}
On ne peut pas configurer la couleur de l'embed pour les "modules" -> je suis d'accord avec toi pour ce qui est des socialnotifs youtube, twitch, etc... mais par exemple on ne peut pas modifier la couleur de l'embed epicgames
![image](https://user-images.githubusercontent.com/78918215/232308939-c53a01a0-ee40-4d34-960f-c95cd551c0d3.png)

2023-04-16 12:12 UTC, Tellvex commented on modules/notifications-sociales.md
> +> Vous trouverez dans cette partie la liste des Notifications Sociales ainsi que leur utilité.
Je pense que c'est nécessaire : ça permet de mieux ordonner le sommaire de la page

2023-04-16 12:18 UTC, Tellvex commented on modules/notifications-sociales.md
> +Ce module permet d'afficher des bandes dessinées en lien avec le métier de développeur.
Je vois pas les configurations possibles pour ce socialnotif

2023-04-16 12:18 UTC, Tellvex commented on modules/notifications-sociales.md
> +Ce module permet d'envoyer une annonce lorsqu'un jeu gratuit est disponible sur l'Epic Games Store.
Je vois pas les configurations possibles pour ce socialnotif

2023-04-16 12:19 UTC, Tellvex commented on modules/notifications-sociales.md
> +Ce module permet d'envoyer une annonce lorsqu'un jeu gratuit est disponible sur Steam.
Je vois pas les configurations possibles pour ce socialnotif puisqu'il n'y a pas différents types de promos gratuites

2023-04-16 12:19 UTC, Tellvex commented on modules/notifications-sociales.md
> +Ce module permet d'envoyer une annonce lorsqu'un jeu gratuit est disponible sur GOG.
Je vois pas les configurations possibles pour ce socialnotif puisqu'il n'y a pas différents types de promos gratuites

2023-04-16 15:15 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Ce module permet d'envoyer une annonce lorsqu'un jeu gratuit est disponible sur l'Epic Games Store.
Salon, mention, couleur

2023-04-16 15:15 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Ce module permet d'envoyer une annonce lorsqu'un jeu gratuit est disponible sur Steam.
Salon mention couleur

2023-04-16 15:15 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Ce module permet d'afficher des bandes dessinées en lien avec le métier de développeur.
Salon mention couleur

2023-04-16 15:16 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Ce module permet d'envoyer une annonce lorsqu'un jeu gratuit est disponible sur GOG.
Salon mention couleur

2023-04-16 15:26 UTC, ErwanGit requested changes

2023-04-16 15:26 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Ce module permet d'afficher des bandes dessinées en lien avec le métier de développeur.
Developper cette partie

2023-04-16 15:26 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Ce module permet d'envoyer une notification lorsqu'une réduction devient "hot". Il s'agit du stade où la promotion est jugée intéressante par les utilisateurs.
```suggestion
Ce module permet d'envoyer une notification lorsqu'une réduction devient "hot" (brûlante). Il s'agit du stade où la promotion est jugée intéressante par les utilisateurs du site.
```

2023-04-16 15:26 UTC, ErwanGit commented on modules/notifications-sociales.md
> +{% endhint %}
Il a fait des modifications hier ou avant-hier, peut-être pas encore publié sur PTB

2023-04-20 13:50 UTC, ErwanGit requested changes

2023-04-20 13:50 UTC, ErwanGit commented on modules/notifications-sociales.md
> +L'annonce est entièrement **customisable**. Cela permet donc aux administrateurs de configurer **un rôle notifié**, activer **la publication sur les autres serveurs**, la **couleur** de l'embed d'ann
```suggestion
L'annonce est entièrement **customisable**. Cela permet donc aux administrateurs de configurer **un rôle notifié**, activer **la publication sur les autres serveurs**, la **couleur** de l'embed d'annonce (reservé aux <mark style="color:orange;"> [serveurs premiums](https://www.draftbot.fr/premium)</mark>), ainsi que d'autres éléments visuels.
```

2023-04-20 13:50 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Il peut y avoir **une seule chaîne <mark style="color:orange;">[YouTube](https://www.youtube.com/)</mark> différente** pour les serveurs **non-premiums** contrairement aux serveurs premiums qui peuve
```suggestion
Il peut y avoir **une seule chaîne <mark style="color:orange;">[YouTube](https://www.youtube.com/)</mark> différente** pour les serveurs **non-premiums** contrairement aux serveurs premiums qui peuvent avoir jusqu'à 5 chaînes YouTube différentes actuellement.
```

2023-04-20 13:50 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Afin d'éviter un spam d'embed, un délai de 30 minutes a été mis en place entre deux annonces.
```suggestion
Afin d'éviter un spam d'embed, un délai de 30 minutes a été mis en place entre deux annonces de la même personne.
```

2023-04-20 13:50 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Ce module permet d'envoyer une annonce lorsqu'un jeu gratuit est disponible sur l'Epic Games Store.
Peut-être ajouter un hyperlink sur le mot Epic Games Store qui redirige vers le site du store Epic ?

2023-04-20 13:50 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Le rôle mentionné, la couleur de l'annonce ainsi que le salon d'envoi peuvent être configurés par l'administrateur
```suggestion
Le rôle mentionné, la couleur de l'annonce ainsi que le salon d'envoi peuvent être configurés par l'administrateur.
```

2023-04-20 13:50 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Ce module permet d'envoyer une annonce lorsqu'un jeu gratuit est disponible sur Steam.
Eventuellement la même chose qu'au dessus

2023-04-20 13:50 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Le rôle mentionné, la couleur de l'annonce ainsi que le salon d'envoi peuvent être configurés par l'administrateur
```suggestion
Le rôle mentionné, la couleur de l'annonce ainsi que le salon d'envoi peuvent être configurés par l'administrateur.
```

2023-04-20 13:50 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Ce module permet d'envoyer une annonce lorsqu'un jeu gratuit est disponible sur GOG.
Même chose qu'au dessus

2023-04-20 13:50 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Le rôle mentionné, la couleur de l'annonce ainsi que le salon d'envoi peuvent être configurés par l'administrateur
```suggestion
Le rôle mentionné, la couleur de l'annonce ainsi que le salon d'envoi peuvent être configurés par l'administrateur.
```

2023-04-20 13:50 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Le rôle mentionné, la couleur de l'annonce ainsi que le salon d'envoi peuvent être configurés par l'administrateur
```suggestion
Le rôle mentionné, la couleur de l'annonce ainsi que le salon d'envoi peuvent être configurés par l'administrateur.
```

2023-04-20 13:50 UTC, ErwanGit commented on modules/notifications-sociales.md
> +### Dealabs
Ajouter les options supplémentaires configurables par l'administrateur (filtre, mention, couleur, ...)

2023-04-20 13:50 UTC, ErwanGit commented on modules/notifications-sociales.md
> +{% tab title="Configuration via le Panel" %}
```suggestion
{% tab title="Configuration via le panel" %}
```

2023-04-20 13:50 UTC, ErwanGit commented on modules/notifications-sociales.md
> +{% tab title="Configuration via le Panel" %}
Peut-être ajouter un lien vers le panel ?

2023-04-20 13:50 UTC, ErwanGit commented on modules/notifications-sociales.md
> +{% endhint %}
Disponible sur le panel, même en production
```suggestion
```

2023-04-20 18:44 UTC, ErwanGit requested changes

2023-04-20 18:44 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Ce module permet d'envoyer une annonce lorsqu'un jeu gratuit est disponible sur l'<mark style="color:orange;">[Epic Games Store](https://www.epicgames.com/site/fr/home)</mark>.
```suggestion
Ce module permet d'envoyer une annonce lorsqu'un jeu gratuit est disponible sur l'<mark style="color:orange;">[Epic Games Store](https://store.epicgames.com/fr/)</mark>.
```

2023-04-20 18:44 UTC, ErwanGit commented on modules/notifications-sociales.md
> +Lien vers le panel : <mark style="color:orange;">https://www.draftbot.fr/dashboard/user</mark>
Le lien n'est pas cliquable

2023-04-20 20:02 UTC, ErwanGit approved these changes

2023-04-20 20:55 UTC, DraftProducts approved these changes

2023-04-20 20:55 UTC, IIbey approved these changes

2023-04-20 20:56 UTC, ToutouilleDev approved these changes

2023-04-20 20:58 UTC, DraftProducts commented
Gg pour la finalisation de cette PR ! 🔥

2023-04-20 20:58 UTC, merged