MAJ - Page config Tickets
DraftBot/Documentation pull request #23
Opened 2023-02-16 19:14 UTC by ToutouilleDev

Début de rédaction, suite à venir très prochainement

2023-02-24 20:28 UTC, ErwanGit requested changes

2023-02-24 20:28 UTC, ErwanGit commented on slash/configuration/tickets.md
>  # 🎟 Tickets
Je pense qu'il faut retirer ce titre, ça fait doublon avec le titre principal

2023-02-24 20:28 UTC, ErwanGit commented on slash/configuration/tickets.md
>  {% endhint %}
Si l'option raison obligatoire, DraftBot demandera une raison obligatoire donc bon, je ne pense pas que cette phrase soit utile

2023-02-24 20:28 UTC, ErwanGit commented on slash/configuration/tickets.md
> +Les administrateurs du serveur et modérateurs de tickets disposent des commandes suivantes permettant un contrôle supplémentaire sur les accès aux tickets.
Je trouve cette phrase trop longue, surtout sur la partie "Les administrateurs du serveur et modérateurs de tickets", c'est généralement les administrateurs et les modérateurs du serveur

2023-02-24 20:28 UTC, ErwanGit commented on slash/configuration/tickets.md
> +La réception des demandes de tickets dans ce salon nécessite obligatoirement que les ouvertures de demandes soient configurées en mode **Manuel**
```suggestion
La réception des demandes de tickets dans ce salon nécessite obligatoirement que les ouvertures de demandes soient configurées en mode **Manuel**. 
```

2023-02-24 20:28 UTC, ErwanGit commented on slash/configuration/tickets.md
> +
Ça va devenir faux avec les nouveautés pour les suggestions, on a rendu ces commandes clic droit exclusif au système de suggestion
```suggestion
```

2023-02-24 20:28 UTC, ErwanGit commented on slash/configuration/tickets.md
> +> <mark style="color:green;">**Demande du motif d'ouverture**</mark> ➜ Permet d'obliger les membres ou non à indiquer une raison d'ouverture du ticket. La raison fournie est indiquée dans le message
Pourquoi avoir mis la couleur verte ici ?

2023-02-24 20:28 UTC, ErwanGit commented on slash/configuration/tickets.md
> +![Alt text](../../.gitbook/assets/tickets/Ticket%20panel%20config.png)
Modifier le texte + Problème au niveau de l'url, il y a pas d'espace normalement sur les noms de fichiers

2023-02-24 20:28 UTC, ErwanGit commented on slash/configuration/tickets.md
> +![Alt text](../../.gitbook/assets/tickets/Ticket%20menu%20no%20config.png)
Les noms de fichiers ne doivent pas avoir d'espace

2023-02-24 20:28 UTC, ErwanGit commented on slash/configuration/tickets.md
> +Sur le panel, dans la catégorie **Communautaire** vous retrouverez sur la partie des **Tickets**, les mêmes possibilités de configuration qu'avec les commandes Slash sur Discord excepté le message d'
```suggestion
Sur le panel, dans la catégorie **Communautaire** vous retrouverez sur la partie des **Tickets**, les mêmes possibilités de configuration qu'avec les commandes Slash sur Discord excepté le message d'ouverture à l'heure actuelle.
```

2023-02-24 20:28 UTC, ErwanGit commented on slash/configuration/tickets.md
> +* **Suppression automatique (admin)** ➜ Lorsque cette option est activée, les tickets sont directement supprimés si un membre Administrateur ferme un ticket.
```suggestion
* **Suppression automatique (admin)** ➜ Lorsque cette option est activée, les tickets sont directement supprimés si un administrateur ferme un ticket.
```

2023-02-24 20:28 UTC, ErwanGit commented on slash/configuration/tickets.md
> +* **Mention des modérateurs** ➜ Permet d'activer la mention automatique des modérateurs lors de l'ouverture d'un ticket
```suggestion
* **Mention des modérateurs** ➜ Permet d'activer la mention automatique des modérateurs lors de l'ouverture d'un ticket.
```

2023-02-24 20:28 UTC, ErwanGit commented on slash/configuration/tickets.md
> +* **Validation des tickets** ➜ Lorsque la validation est activée ("Assignation manuelle" depuis /config), les demandes de tickets sont transférées dans le **salon de réception** et doivent être accep
Je ne comprends pas ces redirections vers le `/config` alors qu'on est sur la partie panel

2023-02-24 20:28 UTC, ErwanGit commented on slash/configuration/tickets.md
> +{% tab title="Via le panel" %}
Peut-être voir pour aérer cette partie, je trouve ça "oppressant" à lire

2023-02-24 20:40 UTC, ToutouilleDev commented on slash/configuration/tickets.md
> +Les administrateurs du serveur et modérateurs de tickets disposent des commandes suivantes permettant un contrôle supplémentaire sur les accès aux tickets.
Je suis également d'accord mais comment préciser le plus rapidement que les non administrateurs doivent avoir un rôle présent dans les rôles modérateurs de tickets ? Ou alors on le précise pas ici et je le spécifie dans l'option "Rôles modérateurs" ?

2023-02-24 20:51 UTC, ToutouilleDev commented on slash/configuration/tickets.md
> +> <mark style="color:green;">**Demande du motif d'ouverture**</mark> ➜ Permet d'obliger les membres ou non à indiquer une raison d'ouverture du ticket. La raison fournie est indiquée dans le message
Certains noms de catégories avaient des couleurs à la base, je les ai donc repris mais si tu préfères sans, ok. (Valable pour le bouton "Supprimer le système" en rouge ou uniquement celui là ?

2023-02-24 20:51 UTC, ToutouilleDev commented on slash/configuration/tickets.md
> +{% tab title="Via le panel" %}
J'avais tenté de mettre des sauts de lignes mais soit je ne m'y suis pas pris de la bonne manière soit on peut pas en faire plusieurs.
Je regarderai pour un changement de présentation des options, je trouve ça également un peu compact

2023-02-24 20:51 UTC, ToutouilleDev commented on slash/configuration/tickets.md
> +* **Validation des tickets** ➜ Lorsque la validation est activée ("Assignation manuelle" depuis /config), les demandes de tickets sont transférées dans le **salon de réception** et doivent être accep
C'est une comparaison entre ce paramètre disponible sur le panel mais pas depuis /config autrement qu'en supprimant le système (cf #améliorations). Je t'avoue ne pas être fan de la tournure, je savais pas trop quoi mettre.

2023-02-24 21:09 UTC, ErwanGit commented on slash/configuration/tickets.md
> +* **Validation des tickets** ➜ Lorsque la validation est activée ("Assignation manuelle" depuis /config), les demandes de tickets sont transférées dans le **salon de réception** et doivent être accep
La personne cherche à configurer sur le panel, elle ne cherche pas la méthode sur le `/config` car elle va dans le tab à côté pour faire cela

2023-02-24 21:13 UTC, ToutouilleDev commented on slash/configuration/tickets.md
>  {% endhint %}
J'ai changé en : "La variable `raison` bien que facultative, peut être rendue obligatoire par les gérants de serveur. Il est conseillé de toujours la remplir de manière générale."
Qu'en penses-tu ?

2023-02-24 21:15 UTC, ErwanGit commented on slash/configuration/tickets.md
>  {% endhint %}
gérants = administrateurs 
Sinon c'est bon pour moi

2023-02-24 22:00 UTC, ErwanGit requested changes

2023-02-24 22:00 UTC, ErwanGit commented on slash/configuration/tickets.md
> +![Alt text](../../.gitbook/assets/tickets/Ticket-menu-no-config.png)
```suggestion
![Alt text](../../.gitbook/assets/tickets/ticket-menu-no-config.png)
```

2023-02-24 22:00 UTC, ErwanGit commented on slash/configuration/tickets.md
> +![Alt text](../../.gitbook/assets/tickets/Ticket-panel-config.png)
```suggestion
![Alt text](../../.gitbook/assets/tickets/ticket-panel-config.png)
```

2023-03-23 21:06 UTC, IIbey submitted a review, later dismissed

2023-03-23 21:06 UTC, IIbey commented on slash/configuration/tickets.md
> +* <mark style="color:orange;">/ticketmod ouvrir </mark> ➜ Permet d'ouvrir un ticket pour un membre dans un objectif de contact privé
```suggestion
* <mark style="color:orange;">/ticketmod ouvrir </mark> ➜ Permet d'ouvrir un ticket pour un membre dans un objectif de contact privé.

2023-03-23 21:06 UTC, IIbey commented on slash/configuration/tickets.md
> +Le salon de réception des tickets se trouve par défaut dans la catégorie que vous avez indiquée mais peut être déplacé dans une autre catégorie.
```suggestion
Le salon de réception des tickets se trouve par défaut dans la catégorie que vous avez indiquée, mais peut être déplacé dans une autre catégorie.

2023-03-23 21:06 UTC, IIbey commented on slash/configuration/tickets.md
> +> **Demande de confirmation** ➜ Permet de modifier le message de confirmation affiché lorsqu'un ticket est demandé. (Modifiable uniquement si la validation des tickets est en mode **Manuel**). Vous p
```suggestion
> **Demande de confirmation** ➜ Permet de modifier le message de confirmation affiché lorsqu'un ticket est demandé (modifiable, uniquement, si la validation des tickets est en mode **Manuel**). Vous pouvez choisir la présentation "Par défaut" de DraftBot ou votre texte personnalisé en cliquant sur "Modifier".

2023-03-23 21:06 UTC, IIbey commented on slash/configuration/tickets.md
> +Sur le panel, dans la catégorie **Communautaire** vous retrouverez sur la partie des **Tickets**, les mêmes possibilités de configuration qu'avec les commandes Slash sur Discord excepté le message d'
```suggestion
Sur le panel, dans la catégorie **Communautaire**, vous retrouverez sur la partie des **Tickets**, les mêmes possibilités de configuration qu'avec les commandes Slash sur Discord, excepté le message d'ouverture à l'heure actuelle.

2023-03-23 21:06 UTC, IIbey commented on slash/configuration/tickets.md
> +* **Catégorie des tickets** ➜ Permet de définir la catégorie de création des tickets. La catégorie doit avoir été préalablement créée. Pensez à actualiser la page du panel si vous avre créé une catég
```suggestion
* **Catégorie des tickets** ➜ Permet de définir la catégorie de création des tickets. La catégorie doit avoir été préalablement créée. Pensez à actualiser la page du panel si vous avez créé une catégorie entre-temps.

2023-03-23 21:06 UTC, IIbey commented on slash/configuration/tickets.md
> +* **Validation des tickets** ➜ Lorsque la validation est activée, les demandes de tickets sont transférées dans le **salon de réception** et doivent être acceptées / refusées par les **modérateurs de
```suggestion
* **Validation des tickets** ➜ Lorsque la validation est activée, les demandes de tickets sont transférées dans le **salon de réception** et doivent être acceptées/refusées par les **modérateurs de tickets** ou administrateurs.

2023-03-23 21:06 UTC, IIbey commented on slash/configuration/tickets.md
> +* **Motif d'ouverture** ➜ Permet d'astreindre ou non les membres à spécifier un motif d'ouverture du ticket lors de l'utilisation de <mark style="color:orange;">/ticket</mark>. Son activation est con
```suggestion
* **Motif d'ouverture** ➜ Permet d'astreindre ou non les membres à spécifier un motif d'ouverture du ticket lors de l'utilisation de <mark style="color:orange;">/ticket</mark>. Son activation est conseillée afin d'éviter les abus de création de tickets ou les demandes sans raison particulière.

2023-04-06 14:25 UTC, Tellvex requested changes
Il faudrait modifier le sommaire pour que la page soit affichée directement sur le menu des slash commandes au lieu de le laisser dans le dossier, de cette façon : 
![image](https://user-images.githubusercontent.com/78918215/230407987-ccd74150-0cf5-4372-8ea7-4797e2436cb6.png)

2023-04-08 19:03 UTC, Tellvex requested changes
Le sommaire n'est toujours pas le bon

2023-04-09 10:59 UTC, Tellvex approved these changes

2023-04-24 18:38 UTC, ErwanGit requested changes

2023-04-24 18:38 UTC, ErwanGit commented on modules/tickets.md
> +![Alt text](../../.gitbook/assets/tickets/ticket-menu-no-config.png)
Modifier le texte

2023-04-24 18:38 UTC, ErwanGit commented on modules/tickets.md
> +![Alt text](../../.gitbook/assets/tickets/ticket-panel-config.png)
Modifier le texte

2023-04-24 18:38 UTC, ErwanGit commented on modules/tickets.md
> +> **Mentionner les modérateurs** ➜ Activer / désactiver la mention automatique des rôles indiqués comme rôles modérateurs à chaque nouveau ticket ouvert. Si cette option est activée, tous les rôles m
```suggestion
> **Mentionner les modérateurs** ➜ Activer/désactiver la mention automatique des rôles indiqués comme rôles modérateurs à chaque nouveau ticket ouvert. Si cette option est activée, tous les rôles modérateurs seront mentionnés, il n'est actuellement pas possible de choisir les rôles à mentionner parmi la liste des rôles modérateurs.
```

2023-05-23 11:45 UTC, ToutouilleDev commented on modules/tickets.md
> +> **Suppression admin** ➜ Lorsque cette option est activée, les tickets sont directement supprimés si un membre Administrateur ferme un ticket.
```suggestion
> **Suppression admin** ➜ Les tickets sont directement supprimés si un administrateur de serveur ferme un ticket.
```

2023-05-28 15:49 UTC, DraftProducts approved these changes

2023-05-30 19:36 UTC, ErwanGit requested changes

2023-05-30 19:36 UTC, ErwanGit commented on modules/tickets.md
> +Vous pouvez créer ou demander la création d'un ticket en utilisant <mark style="color:orange;">/ticket</mark>.
```suggestion
Vous pouvez créer ou demander la création d'un ticket en utilisant la commande <mark style="color:orange;">/ticket</mark>.
```

2023-05-30 19:36 UTC, ErwanGit commented on modules/tickets.md
> +Le salon de réception des tickets permet de recevoir les demandes de tickets des membres qu'elles soient réalisées via l'utilisation de <mark style="color:orange;">/ticket</mark> ou bien via un **mes
```suggestion
Le salon de réception des tickets permet de recevoir les demandes de tickets des membres, qu'elles soient réalisées via l'utilisation de la commande <mark style="color:orange;">/ticket</mark> ou bien via un **message d'ouverture**.
```

2023-05-30 19:36 UTC, ErwanGit commented on modules/tickets.md
> +> **Message d'accueil** ➜ Permet de modifier la description du message d'accueil d'un ticket **uniquement** lorsqu'il a été ouvert via <mark style="color:orange;">/ticketmod ouvrir</mark>. Lorsqu'un
```suggestion
> **Message d'accueil** ➜ Permet de modifier la description du message d'accueil d'un ticket **uniquement** lorsqu'il a été ouvert via la commande <mark style="color:orange;">/ticketmod ouvrir</mark>. Lorsqu'un ticket est ouvert via la commande <mark style="color:orange;">/ticket</mark> la description du message d'accueil contient alors la raison indiquée par le membre.
```

2023-05-30 19:36 UTC, ErwanGit commented on modules/tickets.md
> +[Menu de configuration](../../.gitbook/assets/tickets/ticket-panel-config.png)
Cela n'affiche pas d'image

2023-05-30 19:36 UTC, ErwanGit commented on modules/tickets.md
> +Sur le panel, dans la catégorie **Communautaire**, vous retrouverez sur la partie des **Tickets**, les mêmes possibilités de configuration qu'avec les commandes Slash sur Discord, excepté le message
Reformuler dans le cas ou le message d'ouverture est disponible sur le panel mais que la documentation n'est pas à jour

2023-05-30 19:36 UTC, ErwanGit commented on modules/tickets.md
> +Pour configurer le système de tickets, vous pouvez utiliser <mark style="color:orange;">/config</mark> puis cliquer dans la section "Tickets".
```suggestion
Pour configurer le système de tickets, vous pouvez utiliser la commande <mark style="color:orange;">/config</mark> puis cliquer dans la section "Tickets".
```

2023-05-30 19:36 UTC, ErwanGit commented on modules/tickets.md
> +Lors de sa première configuration, depuis <mark style="color:orange;">/config</mark> dans la section **Tickets** puis en cliquant sur "Message d'ouverture", vous devrez sélectionner le type de messag
```suggestion
Lors de sa première configuration, depuis la commande <mark style="color:orange;">/config</mark> dans la section **Tickets** puis en cliquant sur "Message d'ouverture", vous devrez sélectionner le type de message d'ouverture souhaité :
```

2023-05-30 19:36 UTC, ErwanGit commented on modules/tickets.md
> +Vous pouvez vous servir d'un message préalablement créé depuis l'Embed Creator sur le panel en cliquant sur "Message existant" sur la question posée après sélection du type de message d'ouverture pou
ou /say

2023-06-11 11:06 UTC, bariboo requested changes

2023-06-11 11:06 UTC, bariboo commented on modules/tickets.md
> +> <mark style="color:red;">**Supprimer le système**</mark> ➜ Permet de réinitialiser le système et revenir au bouton "Configurer le système".
```suggestion
> <mark style="color:red;">**Supprimer le système**</mark> ➜ Permet de réinitialiser le système et revenir au bouton "Configurer le système".

{% hint style="warning" %}
Cette action est irréversible, toute la configuration sera perdue.
{% endhint %}

```

2023-06-11 11:06 UTC, bariboo commented on modules/tickets.md
> +> **Demande du motif d'ouverture**</mark> ➜ Permet d'obliger les membres ou non à indiquer une raison d'ouverture du ticket. La raison fournie est indiquée dans le message d'accueil du ticket ainsi q
```suggestion
> **Demande du motif d'ouverture**</mark> ➜ Permet d'obliger les membres à indiquer une raison d'ouverture du ticket. La raison fournie est indiquée dans le message d'accueil du ticket ainsi que sur la demande d'ouverture si la validation des tickets est en mode **Manuel**.
```

2023-06-14 10:28 UTC, DraftProducts requested changes

2023-06-14 10:28 UTC, DraftProducts commented on modules/tickets.md
> +[Menu de configuration](../../.gitbook/assets/tickets/ticket-panel-config.png)
```suggestion
![Menu de configuration](../../.gitbook/assets/tickets/ticket-panel-config.png)
```

2023-06-14 16:14 UTC, bariboo commented on modules/tickets.md
> +Les administrateurs et modérateurs de tickets disposent des commandes suivantes permettant un contrôle supplémentaire sur les accès aux tickets.
```suggestion
Les administrateurs et modérateurs de tickets disposent des commandes suivantes permettant un contrôle supplémentaire sur les accès aux tickets :
```

2023-06-14 16:16 UTC, bariboo commented on modules/tickets.md
> +La réception des demandes de tickets dans ce salon nécessite obligatoirement que les ouvertures de demandes soient configurées en mode **Manuel**.
```suggestion
{% hint style="info" %}
La réception des demandes de tickets dans ce salon nécessite obligatoirement que les ouvertures de demandes soient configurées en mode **Manuel**.
{% endhint %}
```

2023-06-14 16:18 UTC, bariboo commented on modules/tickets.md
> +> **Rôles modérateurs** ➜ Ajouter ou retirer des rôles n'ayant pas la permission Administrateur qui auront accès aux tickets. Plusieurs rôles peuvent être ajoutés.
```suggestion
> **Rôles modérateurs** ➜ Ajouter ou retirer des rôles n'ayant pas la permission "Administrateur" qui auront accès aux tickets. Plusieurs rôles peuvent être ajoutés.
```

2023-06-14 16:20 UTC, bariboo commented on modules/tickets.md
> +> ⚠️ Une fois vos modifications effectuées, n'oubliez pas d'enregistrer avec le bouton "Enregistrer" situé en bas de la page.
```suggestion
> ⚠️ Une fois vos modifications effectuées, n'oubliez pas d'enregistrer avec le bouton "Enregistrer" situé en bas de la page.
```

À voir si c'est utile car maintenant, tu ne peux plus quitter le panel sans enregistrer (ou en tout cas involontairement).

2023-06-14 16:20 UTC, bariboo commented on modules/tickets.md
> +
Une petite image du panel ?

2023-06-14 16:21 UTC, bariboo commented on modules/tickets.md
> +[Menu de configuration](../../.gitbook/assets/tickets/ticket-panel-config.png)
```suggestion
<mark style="color:blue;">[Menu de configuration](../../.gitbook/assets/tickets/ticket-panel-config.png)</mark>
```

2023-06-14 16:52 UTC, ToutouilleDev commented
Normalement tout est bon ça peut être merge, @bariboo @ErwanGit & @DraftProducts si vous voulez revérifier ✌️

2023-06-15 12:59 UTC, ErwanGit approved these changes

2023-06-16 06:50 UTC, IIbey requested changes
Hormis cela, c'est bon pour moi.

2023-06-16 06:51 UTC, IIbey commented on modules/tickets.md
> +Vous pouvez vous servir d'un message préalablement créé depuis l'Embed Creator sur le panel en cliquant sur "Message existant" sur la question posée après sélection du type de message d'ouverture pou
```suggestion
Vous pouvez vous servir d'un message préalablement créé depuis l'Embed Creator sur le panel en cliquant sur "Message existant" sur la question posée après sélection du type de message d'ouverture pour personnaliser à votre guise l'embed de présentation ou via la commande <mark style="color:orange;">/envoyer</mark>.

2023-06-16 07:49 UTC, IIbey approved these changes

2023-06-16 10:06 UTC, merged