Ajout Captcha
DraftBot/Documentation pull request #25
Opened 2023-02-19 14:12 UTC by Hugo-broc

Ajout de la page de captcha. 
En attente de si on met une table ou un avertissement pour l'impossibilité de configurer le captcha sur le panel

2023-02-22 11:27 UTC, ErwanGit approved these changes
Il faudra le déplacer de destination

2023-02-22 11:34 UTC, Hugo-broc commented
La page a été mise à la suite mais sera réordonnée dans #28.

2023-02-22 11:36 UTC, ErwanGit requested changes

2023-02-22 11:36 UTC, ErwanGit commented on SUMMARY.md
> +- [🔒 Captcha](modules/configuration/captcha.md)
```suggestion
- [🔒 Captcha](modules/captcha.md)
```

2023-02-22 15:49 UTC, ErwanGit approved these changes

2023-02-28 14:46 UTC, DraftProducts approved these changes

2023-02-28 22:16 UTC, Hugo-broc commented
@IIbey , tu pourras checker cela afin de pouvoir la merge ?
Merci d'avance !

2023-02-28 22:55 UTC, IIbey approved these changes

2023-03-01 04:29 UTC, DraftProducts commented
Bien joué @Hugo-broc ! 🔥

2023-03-01 04:29 UTC, merged

2023-03-01 07:06 UTC, Hugo-broc commented
@DraftProducts , je vois que la page a été merge mais elle ne s'affiche pas dans les dernières pages faites, alors que j'avais bien modifié le sommaire. Comment cela se fait-il ?

2023-03-01 13:36 UTC, DraftProducts commented
![image](https://user-images.githubusercontent.com/29425008/222154303-b10677b9-f2c8-4065-8712-bf7fb3ac7346.jpeg)