Refonte de la page des rôle-réactions
DraftBot/Documentation pull request #27
Opened 2023-02-19 20:51 UTC by MrPRAINGLE

Bon ben... Tout est dit. Refonte de la page des rôle-réactions avec, notamment, l'ajout des deux sections "Supprimer un rôle-réaction" et "Changer le mode du message".

2023-02-19 20:52 UTC, MrPRAINGLE commented
À rôle-réaction, il y a un tiret ou pas ? Il y a une majuscule à "réaction" ou pas (comme dans le code) ? Il y a un "s" à "rôle" au pluriel ou pas ? 😅 J'ai pas mal de doutes

2023-02-21 00:20 UTC, IIbey requested changes

2023-02-21 00:20 UTC, IIbey commented on slash/configuration/role-reactions.md
>    Avec le système de rôle réactions, vos membres pourront facilement choisir des
```suggestion
  Avec le système de rôles-réactions, vos membres pourront facilement choisir des

2023-02-21 00:20 UTC, IIbey commented on slash/configuration/role-reactions.md
>  # 🔘 Rôle réactions
```suggestion
# 🔘 Rôles-réactions

2023-02-21 00:20 UTC, IIbey commented on slash/configuration/role-reactions.md
> +* ***Message existant de DraftBot*** ➜ Récupèrera un message de DraftBot ayant déjà été envoyé.
```suggestion
* ***Message existant de DraftBot*** ➜ Récupérera un message de DraftBot ayant déjà été envoyé.

2023-02-21 00:20 UTC, IIbey commented on slash/configuration/role-reactions.md
> +\
Faut corriger l'anti-slash ici

![image](https://user-images.githubusercontent.com/111301542/220216437-efb03c37-b9ca-425d-8697-a57dac0753aa.png)

2023-02-21 00:20 UTC, IIbey commented on slash/configuration/role-reactions.md
> +2. Sélectionnez <mark style="color:green;">"Oui"</mark> ou <mark style="color:red;">"Non"</mark> selon si vous souhaitez afficher un texte personnalisé sur le bouton à la place du nom du rôle ou non.
```suggestion
1. Sélectionnez <mark style="color:green;">"Oui"</mark> ou <mark style="color:red;">"Non"</mark>, si vous souhaitez que votre bouton contienne un émoji ou non. \
   Si <mark style="color:green;">"Oui"</mark>, alors envoyez l'émoji que vous souhaitez afficher sur votre bouton.
2. Sélectionnez <mark style="color:green;">"Oui"</mark> ou <mark style="color:red;">"Non"</mark>, si vous souhaitez afficher un texte personnalisé sur le bouton à la place du nom du rôle ou non. \

2023-02-21 00:20 UTC, IIbey commented on slash/configuration/role-reactions.md
> +Et votre bouton de rôle-réaction est bien créé avec les paramètres que vous avez definis !
```suggestion
Et votre bouton de rôle-réaction est bien créé avec les paramètres que vous avez définis !

2023-02-21 00:20 UTC, IIbey commented on slash/configuration/role-reactions.md
> +1. Sélectionnez <mark style="color:green;">"Oui"</mark> ou <mark style="color:red;">"Non"</mark> selon si vous souhaitez que votre ligne contienne un émoji ou non. \
```suggestion
1. Sélectionnez <mark style="color:green;">"Oui"</mark> ou <mark style="color:red;">"Non"</mark>, si vous souhaitez que votre ligne contienne un émoji ou non. \

2023-02-21 00:20 UTC, IIbey commented on slash/configuration/role-reactions.md
> +2. Sélectionnez <mark style="color:green;">"Oui"</mark> ou <mark style="color:red;">"Non"</mark> selon si vous souhaitez afficher un texte personnalisé à la place du nom du rôle ou non. \
```suggestion
2. Sélectionnez <mark style="color:green;">"Oui"</mark> ou <mark style="color:red;">"Non"</mark>, si vous souhaitez afficher un texte personnalisé à la place du nom du rôle ou non. \

2023-02-21 00:20 UTC, IIbey commented on slash/configuration/role-reactions.md
> +3. Sélectionnez <mark style="color:green;">"Oui"</mark> ou <mark style="color:red;">"Non"</mark> selon si vous souhaitez ajouter une description au rôle dans le sélecteur ou non. \
```suggestion
3. Sélectionnez <mark style="color:green;">"Oui"</mark> ou <mark style="color:red;">"Non"</mark>, si vous souhaitez ajouter une description au rôle dans le sélecteur ou non. \

2023-02-21 00:20 UTC, IIbey commented on slash/configuration/role-reactions.md
> +Et votre sélécteur de rôle-réaction est créé avec succès !
```suggestion
Et votre sélecteur de rôle-réaction est créé avec succès !

2023-02-21 00:20 UTC, IIbey commented on slash/configuration/role-reactions.md
> +Si vous choisissez de modifier des réactions, vous ne pouvez modifier **que le rôle qu'attribue la réaction**, et **pas la réaction elle-même**. Suivez alors les instructions du bot qui vous demander
```suggestion
Si vous choisissez de modifier des réactions, vous ne pouvez modifier **que le rôle qu'attribue la réaction**, et **pas la réaction elle-même**. Suivez alors les instructions du bot qui vous demandera de choisir le rôle-réaction que vous souhaitez modifier, puis d'indiquer par quel rôle vous souhaitez le remplacer.\

2023-02-21 00:20 UTC, IIbey commented on slash/configuration/role-reactions.md
>  {% tab title="Sélécteurs" %}
```suggestion
{% tab title="Sélecteurs" %}

2023-02-21 10:22 UTC, MrPRAINGLE commented on slash/configuration/role-reactions.md
> +\
C'est sur la page du site de la doc ?

2023-02-21 10:59 UTC, IIbey commented on slash/configuration/role-reactions.md
> +\
Il est présent en tout cas

2023-02-21 14:32 UTC, IIbey requested changes

2023-02-21 14:32 UTC, IIbey commented on slash/configuration/role-reactions.md
> +* Vous pouvez ajouter, modifier ou supprimer un rôle-réaction dans la section en-dessous du sélecteur de mode.
```suggestion
* Vous pouvez modifier le mode du rôle-réaction à l'aide du sélecteur se trouvant juste en dessous de l'embed Creator.
* Vous pouvez ajouter, modifier ou supprimer un rôle-réaction dans la section en dessous du sélecteur de mode.

2023-02-21 18:54 UTC, Hugo-broc requested changes
Très bien dans l'ensemble ! 🎉
Je ne comprend juste pas la partie "Accéder à la configuration" car tu rappelles à chaque fois comment y aller. Pour moi cette partie est alors totalement inutile.

2023-02-21 18:54 UTC, Hugo-broc commented on slash/configuration/role-reactions.md
> +  des émojis.
```suggestion
  des réactions.
```

2023-02-21 18:54 UTC, Hugo-broc commented on slash/configuration/role-reactions.md
> +* *Par la commande <mark style="color:orange;">/envoyer</mark>, aussi présente sous le nom de <mark style="color:orange;">/send</mark>* : Permet d'envoyer un message simple sous l'identité de DraftBo
```suggestion
* *Depuis la commande <mark style="color:orange;">/envoyer</mark> : Permet d'envoyer un message simple sous l'identité de **DraftBot**.
```

2023-02-21 18:54 UTC, Hugo-broc commented on slash/configuration/role-reactions.md
> +* *Depuis l'Embed Creator du [panel web](https://www.draftbot.fr/dashboard)* : Permet la création complète et facile d'un message ou d'un embed entièrement personnalisable (description, champs, image
```suggestion
* *Depuis l'Embed Creator du <mark style="color:blue;">[panel](https://www.draftbot.fr/dashboard)</mark>* : Permet la création complète et facile d'un message ou d'un embed entièrement personnalisable (description, champs, image...).
```

2023-02-21 18:54 UTC, Hugo-broc commented on slash/configuration/role-reactions.md
> +* ***Créer un nouveau rôle-réaction*** ➜ Accède au menu de [création d'un nouveau rôle-réaction](role-reactions.md#créer-un-nouveau-rôle-réaction).
```suggestion
* ***Créer un nouveau rôle-réaction*** ➜ Permet d'accéder au menu de [création d'un nouveau rôle-réaction](role-reactions.md#créer-un-nouveau-rôle-réaction).
```

2023-02-21 18:54 UTC, Hugo-broc commented on slash/configuration/role-reactions.md
> +![Commande /config système: Rôles-Réactions]()../../.gitbook/assets/rolereact/view.png)
La parenthèse en trop ne permettait pas d'afficher l'image.
```suggestion
![Commande /config système: Rôles-Réactions](../../.gitbook/assets/rolereact/view.png)
```

2023-02-21 18:54 UTC, Hugo-broc commented on slash/configuration/role-reactions.md
> +![](../../.gitbook/assets/rolereact/question.png)
Je t'invite à mettre ici un texte alternatif entre les `[]`.

2023-02-21 18:54 UTC, Hugo-broc commented on slash/configuration/role-reactions.md
> +Une fois fait, DraftBot vous demandera à partir de quel message vous souhaitez créer votre rôle-réaction :
```suggestion
Une fois fait, **DraftBot** vous demandera à partir de quel message vous souhaitez créer votre rôle-réaction :
```

2023-02-21 18:54 UTC, Hugo-broc commented on slash/configuration/role-reactions.md
> +À droite de cette page, vous retrouverez la liste de tous les rôles-réactions existants sur le serveur. Pour en modifier un, cliquer sur "Modifier" sur sa "carte".
C'était quoi ce "cliquez sur "Modifier" **sur sa carte**" ? 😅 
```suggestion
À droite de cette page, vous retrouverez la liste de tous les rôles-réactions existants sur le serveur. Pour en modifier un, cliquez sur "Modifier".
```

2023-02-21 18:54 UTC, Hugo-broc commented on slash/configuration/role-reactions.md
> +* Vous pouvez modifier le mode du rôle-réaction à l'aide du sélecteur se trouvant juste en-dessous de l'embed Creator.
Tu as mis un "E" majuscule partout sauf ici :wink:
```suggestion
* Vous pouvez modifier le mode du rôle-réaction à l'aide du sélecteur se trouvant juste en-dessous de l'Embed Creator.
```

2023-02-21 18:55 UTC, Hugo-broc commented on slash/configuration/role-reactions.md
> +* ***Message existant de DraftBot*** ➜ Récupérera un message de DraftBot ayant déjà été envoyé.
```suggestion
* ***Message existant de DraftBot*** ➜ Récupérera un message de **DraftBot** ayant déjà été envoyé.
```

2023-02-21 20:58 UTC, ErwanGit requested changes
Quelques petits trucs à modifier mais globalement très propre

2023-02-21 20:58 UTC, ErwanGit commented on slash/configuration/role-reactions.md
> +![Message de gestion des rôles-réactions](../../.gitbook/assets/rolereact/gestion.png)
J'ai l'impression qu'il y a un soucis de colorimétrie, j'ai l'impression que les boutons sont violet

2023-02-21 20:58 UTC, ErwanGit commented on slash/configuration/role-reactions.md
> +Vous pouvez donner des noms personnalisés aux rôles-réactions dans la partie à droite de la page. Pour cela, modifiez le texte de la zone de texte présente en haut à gauche de la "carte" d'un rôle-ré
Voir pour remplacer le mot carte par autre chose, j'ai pas d'idée en tête comme ça

2023-02-21 20:58 UTC, ErwanGit commented on slash/configuration/role-reactions.md
> +* Vous pouvez modifier le mode du rôle-réaction à l'aide du sélecteur se trouvant juste en dessous de l'embed Creator.
```suggestion
* Vous pouvez modifier le mode du rôle-réaction à l'aide du sélecteur se trouvant juste en dessous de l'Embed Creator.
```

2023-02-21 21:34 UTC, MrPRAINGLE commented on slash/configuration/role-reactions.md
> +À droite de cette page, vous retrouverez la liste de tous les rôles-réactions existants sur le serveur. Pour en modifier un, cliquer sur "Modifier" sur sa "carte".
Ah ça 😅 La "carte" (le nom est à revoir selon Erwan et franchement il a raison) d'un rolereact c'est le petit rectangle à droite de la page, qui présente son salon et son nom

2023-02-22 11:15 UTC, Hugo-broc commented on slash/configuration/role-reactions.md
> +![Message de gestion des rôles-réactions](../../.gitbook/assets/rolereact/gestion.png)
Effectivement, je les vois violet aussi 😅

2023-02-24 20:45 UTC, ErwanGit requested changes
Je pense qu'une partie concernant les modes des rolereacts pourrait être intéressants 
Peut-être aussi un peu développé le fait qu'on peut ajouter des rolereacts en forme de réactions, sélecteur ou bouton et indiquer les limites

Il faut penser que cette documentation peut-être utilisé par des personnes qui cherche à s'informer sur le fonctionnement de la fonctionnalité avant de le configurer

2023-02-24 20:45 UTC, ErwanGit commented on slash/configuration/role-reactions.md
> +![Message de gestion des rôles-réactions](../../.gitbook/assets/rolereact/gestion.png)
J'aurai du te donner une image avec un vrai footer, voici la nouvelle image : 
![image](https://user-images.githubusercontent.com/24718500/221286827-7bb64429-4a81-43b6-8713-1826ba8b5969.png)

2023-02-24 20:45 UTC, ErwanGit commented on slash/configuration/role-reactions.md
> +![Commande /config système: Rôles-Réactions](../../.gitbook/assets/rolereact/view.png)
Même si c'est correct, peut-être trouvé une meilleure formulation pour le titre

2023-02-24 20:45 UTC, ErwanGit commented on slash/configuration/role-reactions.md
> +* *Depuis la configuration des rôles-réactions, via <mark style="color:orange;">/config système:Rôles-Réactions</mark>* : Permet de créer un embed au titre personnalisé et au footer prédéfini.
Même si c'est correct, peut-être trouvé une meilleure formulation pour le nom de la commande

2023-02-25 00:40 UTC, ToutouilleDev requested changes
@MrPRAINGLE As-tu un endroit dans ta rédaction de documentation ou tu spécifies que le message du rôle réaction doit impérativement être envoyé par DraftBot ? Cela peut sembler évident mais au vu d'autres bots qui proposent une fonctionnalité d'attribution au message de son choix / membres sur le support posant cette question, je pense qu'il serait important de le préciser si cela n'a pas déjà été fait

2023-02-26 11:09 UTC, MrPRAINGLE commented on slash/configuration/role-reactions.md
> +* *Depuis la configuration des rôles-réactions, via <mark style="color:orange;">/config système:Rôles-Réactions</mark>* : Permet de créer un embed au titre personnalisé et au footer prédéfini.
Pour "/config système:Rôles-Réactions"?

2023-02-26 11:10 UTC, MrPRAINGLE commented
Oui oui, je l'ai mis tout tout au dessus (première phrase en-dessous du titre de la page, ligne 11)

2023-02-26 11:36 UTC, ErwanGit commented on slash/configuration/role-reactions.md
> +* *Depuis la configuration des rôles-réactions, via <mark style="color:orange;">/config système:Rôles-Réactions</mark>* : Permet de créer un embed au titre personnalisé et au footer prédéfini.
Oui

2023-03-02 14:49 UTC, Hugo-broc commented
Je regarde tout cela demain aprèm.
Par contre, à première vue, je vois tout de suite que la page n'est pas dans la bonne catégorie et qu'elle n'est aussi pas déplacée là où les pages finies sont faites.
Si cela n'est pas corrigé avant, je le ferai demain.
![Illustration de mes dires](https://user-images.githubusercontent.com/120671943/222462392-5e788170-60e3-49ed-8ac6-d073bbfcd701.png)

2023-03-02 14:50 UTC, Hugo-broc requested changes
Je regarde tout cela demain aprèm.
Par contre, à première vue, je vois tout de suite que la page n'est pas dans la bonne catégorie et qu'elle n'est aussi pas déplacée là où les pages finies sont faites.
Si cela n'est pas corrigé avant, je le ferai demain.
![Illustration de mes dires](https://user-images.githubusercontent.com/120671943/222462676-ba008dc0-3ad8-4a01-9630-7a9554cf0165.png)

2023-03-03 17:48 UTC, Hugo-broc commented
> Très bien dans l'ensemble ! 🎉 Je ne comprend juste pas la partie "Accéder à la configuration" car tu rappelles à chaque fois comment y aller. Pour moi cette partie est alors totalement inutile.

Message de ma part il y a quelques temps mais qui n'a pas été pris en compte. Je le redescend afin qu'il ne soit pas oublié.

2023-03-06 22:55 UTC, ls62 commented on modules/roles-reactions.md
> +Vous devrez ensuite indiquer le lien ou l'[identifiant du message](../autres/recuperer-un-identifiant.md#identifiant-dun-message) sur lequel se trouve le rôle-réaction que vous souhaitez modifier.
Peut-être mettre "l'identifiant du message" en couleur pour bien l'identifié comme un lien qui redirige à une page ?

2023-03-12 20:20 UTC, MrPRAINGLE commented on modules/roles-reactions.md
> +Vous devrez ensuite indiquer le lien ou l'[identifiant du message](../autres/recuperer-un-identifiant.md#identifiant-dun-message) sur lequel se trouve le rôle-réaction que vous souhaitez modifier.
Pas sûr, je crois que ça se voit déjà

2023-03-15 18:15 UTC, bariboo reviewed
Voilà les choses que je vois à améliorer.

- Mettre également les boutons en couleur sera cohérant par rapport au reste de la documentation.

2023-03-15 18:15 UTC, bariboo commented on modules/roles-reactions.md
> +* Si vous voulez créer un nouveau message, créez un message et/ou un embed grâce à l'Embed Creator se trouvant au centre de la page.
```suggestion
<mark style="color:blue;">[Accéder au panel de **DraftBot**](https://draftbot.fr/dashboard)</mark>

* Si vous voulez créer un nouveau message, créez un message et/ou un embed grâce à l'Embed Creator se trouvant au centre de la page.
```

2023-03-15 18:15 UTC, bariboo commented on modules/roles-reactions.md
> +{% tab title="Via le panel" %}
```suggestion
{% tab title="Via le panel" %}

<mark style="color:blue;">[Accéder au panel de **DraftBot**](https://draftbot.fr/dashboard)</mark>
```

2023-03-15 18:15 UTC, bariboo commented on modules/roles-reactions.md
> +Puis, dans le sélecteur situé en haut de l'Embed Creator, sélectionnez un salon dans lequel envoyer le message de rôle-réaction.
```suggestion
Puis, dans le sélecteur situé en haut de l'Embed Creator, sélectionnez le salon dans lequel sera envoyé le message de rôle-réaction.
```

2023-03-15 18:15 UTC, bariboo commented on modules/roles-reactions.md
> +Vous devrez ensuite indiquer le lien ou l'[identifiant du message](../autres/recuperer-un-identifiant.md#identifiant-dun-message) sur lequel se trouve le rôle-réaction que vous souhaitez modifier.
Je suis d'accord avec Lucas.

2023-03-15 18:15 UTC, bariboo commented on modules/roles-reactions.md
> +  rôles parmi une liste définie, que ce soit par un sélecteur, des boutons, ou
```suggestion
  rôles parmi une liste définie, que ce soit depuis un sélecteur, des boutons, ou
```

2023-03-16 21:47 UTC, Hugo-broc commented
@MrPRAINGLE, je ne peux pas faire de review sans savoir si ce qui t'a été proposé avant a été corrigé ou non. 🤔 
Je vois encore des propositions de bariboo non réglée donc si cela a été fait ou bien vu avec lui, fait "Résoudre une conversation".
Je regarderai quand cela sera fait, ce serait bête de remonter les mêmes fautes que les autres.

2023-03-27 18:42 UTC, Hugo-broc requested changes

2023-03-27 18:42 UTC, Hugo-broc commented on modules/roles-reactions.md
> +{% hint style="info" %}
J'aurais mis tout cette astuce plus tard, dans "Créer un nouveau rôle-réaction" plutôt car là, ce n'est pas trop sa place.

2023-03-27 18:42 UTC, Hugo-broc commented on modules/roles-reactions.md
> +Pour créer un nouveau rôle-réaction, [accédez à la configuration](#accéder-à-la-configuration) des rôles-réactions via la commande <mark style="color:orange;">/config</mark>.
Ajouter de la couleur sur le lien.
```suggestion
Pour créer un nouveau rôle-réaction, <mark style="color:orange;">[accédez à la configuration](#accéder-à-la-configuration)</mark des rôles-réactions via la commande <mark style="color:orange;">/config</mark>.
```

2023-03-27 18:42 UTC, Hugo-broc commented on modules/roles-reactions.md
> +Pour gérer un rôle-réaction existant, [accédez à la configuration](#accéder-à-la-configuration) des rôles-réactions via la commande <mark style="color:orange;">/config</mark>.
```suggestion
Pour gérer un rôle-réaction existant, <mark style="color:orange;">[accédez à la configuration](#accéder-à-la-configuration)</mark> des rôles-réactions via la commande <mark style="color:orange;">/config</mark>.
```

2023-03-27 18:42 UTC, Hugo-broc commented on modules/roles-reactions.md
> +Vous aurez ensuite accès au menu de gestion de rôle-réaction :
```suggestion
Vous aurez ensuite accès au menu de gestion des rôles-réactions :
```

2023-03-27 18:42 UTC, Hugo-broc commented on modules/roles-reactions.md
> +Pour gérer un rôle-réaction existant, [accédez à la configuration](#accéder-à-la-configuration) des rôles-réactions via le panel.
```suggestion
Pour gérer un rôle-réaction existant, <mark style="color:orange;">[accédez à la configuration](#accéder-à-la-configuration)</mark> des rôles-réactions via le panel.
```

2023-04-24 17:13 UTC, bariboo commented
Normalement, c'est tout bon !

2023-06-15 20:03 UTC, DraftProducts commented
Closed and superseded by a free branch due to inactivity : [`role-reactions-page`](https://github.com/DraftBot/Documentation/tree/feat/role-reactions-page)

2023-06-15 20:03 UTC, closed without merging