MAJ Sommaire
DraftBot/Documentation pull request #28
Opened 2023-02-21 21:57 UTC by Hugo-broc

PR ayant pour but de mettre à jour le sommaire de la documentation.

2023-02-21 22:18 UTC, Hugo-broc commented
**On regardera en vocal cela demain avant que tu la merges, j'ai des choses qui ne me plaisent pas dedans.**

2023-02-22 03:56 UTC, DraftProducts approved these changes

2023-02-22 15:55 UTC, ErwanGit approved these changes

2023-02-22 15:55 UTC, ErwanGit commented on modules/commandes-personnalisees.md
> +</details>
Aucun saut de ligne

2023-02-22 15:55 UTC, ErwanGit requested changes
^

2023-02-22 16:09 UTC, Hugo-broc commented on modules/commandes-personnalisees.md
> +</details>
Oui, j'ai vu ça mais je pensais refaire une autre PR pour ne pas tout mélanger.
Je vais faire le correctif ici du coup.

2023-02-28 14:54 UTC, merged