Création "🗃 Logs"
DraftBot/Documentation pull request #29
Opened 2023-02-22 12:23 UTC by Hugo-broc

Tout est dans le titre !
Création car la page n'existait pas du tout avant.

2023-02-22 14:57 UTC, Hugo-broc commented
@DraftProducts, @ErwanGit, @IIbey et @ToutouilleDev, vous pouvez regarder la page, elle est **terminée**. :tada:

2023-02-22 15:26 UTC, IIbey requested changes

2023-02-22 15:26 UTC, IIbey commented on modules/logs.md
> +Les logs sont des embeds qui sont envoyés non pas par **DraftBot** mais par des webhooks. Un webhook vous permet d'envoyer un message avec une photo de profil, un nom et un contenu personnalisé.
```suggestion
Les logs sont des embeds qui sont envoyés non pas par **DraftBot**, mais par des webhooks. Un webhook vous permet d'envoyer un message avec une photo de profil, un nom et un contenu personnalisé.

2023-02-22 15:26 UTC, IIbey commented on modules/logs.md
> +Sous ce message se trouvent des boutons, servant à la configuration des logs :
```suggestion
Sous ce message, se trouvent des boutons servant à la configuration des logs :

2023-02-22 15:26 UTC, IIbey commented on modules/logs.md
> +Dans les boutons en-dessous du message, sélectionnez "Modules"
```suggestion
Dans les boutons en dessous du message, sélectionnez "Modules".

2023-02-22 15:29 UTC, Hugo-broc commented on modules/logs.md
> +Sous ce message se trouvent des boutons, servant à la configuration des logs :
Je ne suis personnellement pas d'accord avec ta proposition.
Je ne saurais pas dire exactement pourquoi mais la phrase sonne plus juste avec une virgule après "boutons". Elle permet de faire une pause et de montrer que l'on va détailler à quoi servent les boutons par la suite.

2023-02-22 15:34 UTC, IIbey commented on modules/logs.md
> +Sous ce message se trouvent des boutons, servant à la configuration des logs :
Je ne suis pas fan du message de base aussi... 🤔 

" Ci-dessous se trouvent les boutons permettant à configuration des logs : "

2023-02-22 15:41 UTC, Hugo-broc commented on modules/logs.md
> +Sous ce message se trouvent des boutons, servant à la configuration des logs :
Si je met plutôt cela @IIbey, cela t'irait mieux ?
```suggestion
Sous le message, retrouvez les boutons permettant de configurer les logs :
```

2023-02-22 15:44 UTC, IIbey commented on modules/logs.md
> +Sous ce message se trouvent des boutons, servant à la configuration des logs :
Hmm... C'est mieux. Mais laisse en " sous ce message ".

```suggestion
Sous ce message, retrouvez les boutons permettant de configurer les logs :

2023-02-22 15:46 UTC, ErwanGit approved these changes

2023-02-22 22:36 UTC, IIbey requested changes

2023-02-22 22:36 UTC, IIbey commented on modules/logs.md
> +Vous avez en haut de la page la configuration par défaut des logs.
La phrase est un peu bizarre... On a vu ça avec Toutouille.

```suggestion
En haut de la page, vous trouverez la configuration des logs globaux par défaut.

2023-02-22 23:14 UTC, ToutouilleDev requested changes
Petites corrections de formulation vues avec Ibey et proposition d'ajout d'un suivi des différentes questions de configuration d'un module de log via /config

2023-02-22 23:14 UTC, ToutouilleDev commented on modules/logs.md
> +Les boutons bleus signifient que leur configuration doit être entièrement faite pour que le système de logs soit opérationnel, lors de la première configuration.
```suggestion
Les boutons bleus signifient que leur configuration doit être entièrement réalisée pour que le système de logs soit opérationnel, lors de la première configuration.
```

2023-02-22 23:14 UTC, ToutouilleDev commented on modules/logs.md
> +
```suggestion
* Pour changer le salon d'envoi : Indiquez la mention ou l'ID du salon voulu.
* Pour changer la photo de profil du log, lors de l'envoi : Envoyez une image respectant les normes indiquées dans la description de la question correspondante. ***(✨ premium)***
* Pour changer la couleur du log, lors de l'envoi : Indiquez un code couleur au format hexadécimal ***(✨ premium)***
```

2023-02-23 01:06 UTC, ToutouilleDev commented on modules/logs.md
> +
@Hugo-broc J'ajoute à cela l'idée d'ajouter un encadré "warning" pour dire à l'utilisateur de redéfinir ses salons de logs un par un via /config de préférence dans le cas ou un bug les enverrait ailleurs.
Un certain nombre de membres sont confrontés à cela, mais il n'y a pas vraiment d'explication. La solution est de redéfinir les salons.

2023-02-23 09:41 UTC, Hugo-broc commented on modules/logs.md
> +
Je ne comprend pas c'est quoi le problème... Il n'y a pas de problème de salon ou alors s'il y en a, il faudrait corriger ce bug, non ?

2023-02-24 16:16 UTC, IIbey approved these changes

2023-02-24 16:24 UTC, ToutouilleDev approved these changes
C'est tout bon pour moi.

2023-02-24 20:15 UTC, ErwanGit requested changes

2023-02-24 20:15 UTC, ErwanGit commented on modules/logs.md
> +* Pour changer le salon d'envoi : Indiquez la mention ou l'ID du salon voulu.
```suggestion
* Pour changer le salon d'envoi : Indiquez la mention ou l'identifiant du salon voulu.
```

2023-02-24 23:30 UTC, Hugo-broc commented on modules/logs.md
> +{% endhint %}
À la demande de Toutouille. Tu penses qu'il n'y a pas besoin de mettre ça (en analysant ta réaction) ?

2023-02-25 14:34 UTC, ErwanGit commented on modules/logs.md
> +{% endhint %}
S'il est mal configuré par l'utilisateur, c'est pas notre problème
Le message indiqué fait penser qu'il y a un bug de notre côté

2023-02-25 21:34 UTC, Hugo-broc commented on modules/logs.md
> +{% endhint %}
Donc on l'enlève, c'est ça que tu veux dire @ErwanGit ?
Je ne sais pas si le bug vient de notre côté ou non ; le message de @ToutouilleDev me donne l'impression que cela vient de DraftBot.

2023-02-26 11:38 UTC, ErwanGit commented on modules/logs.md
> +{% endhint %}
Oui

2023-02-28 14:42 UTC, DraftProducts commented on modules/logs.md
> +{% endhint %}
Je suis d'accord 👍 
```suggestion
```

2023-02-28 14:43 UTC, DraftProducts approved these changes

2023-02-28 17:54 UTC, ErwanGit approved these changes

2023-02-28 18:57 UTC, Hugo-broc commented
@DraftProducts, je crois que tout est bon pour cette page !
Merci pour les quelques changements que tu as fait ! 👍

2023-03-01 04:34 UTC, DraftProducts commented
Merci à toi pour tout ce taff ! 🔥

2023-03-01 04:34 UTC, merged

2023-03-01 07:04 UTC, Hugo-broc commented
> Merci à toi et félicitations pour tout ce taff ! 🔥 

Pas de problème ! Par contre, j'avais mis la page des logs dans les pages faites du menu à gauche mais je vois qu'elle n'y est plus, comment cela se fait-il ?

2023-03-01 13:37 UTC, DraftProducts commented
![image](https://user-images.githubusercontent.com/29425008/222154335-7e9efbae-9ff0-41ed-961d-bc2fbca3d40a.jpeg)