Ajout de la page reactions de mots
DraftBot/Documentation pull request #30
Opened 2023-02-26 23:35 UTC by Wapiti13

2023-02-27 13:00 UTC, IIbey commented on modules/reactions-de-mots.md
> +Pour **ajouter** une réaction à un mot, il vous suffit de faire la commande `/config`, aller sur `Réactions de mots` puis `Ajouter`.
```suggestion
Pour ajouter une réaction à un mot, il vous suffit de faire la commande <mark style="color:orange;">/config</mark>, aller dans le système **"Réactions de mots"** puis cliquez sur le bouton **"Ajouter"**.

2023-02-27 13:03 UTC, IIbey commented on modules/reactions-de-mots.md
> +Pour qu'une réaction de mots soit pris en compte, il doit être situé en **début de message**. Si le mot est au milieu ou à la fin d'un message, aucune réaction ne sera ajoutée.
```suggestion
Pour qu'une réaction de mots soit prise en compte, il doit être situé en **début de message**. Si le mot est au milieu ou à la fin d'un message, aucune réaction ne sera ajoutée.

2023-02-27 13:07 UTC, IIbey commented on modules/reactions-de-mots.md
> +Un sélecteur s'affichera et vous permettra de choisir la réaction de mots a supprimer.\
```suggestion
## Supprimer des réactions de mots <a href="#delete" id="delete"></a>

Si vous souhaitez supprimer une réaction en particulier, il vous suffira d'utiliser la commande <mark style="color:orange;">/config</mark> puis aller dans le système **"Réactions de mots"** et enfin, cliquez sur le bouton **"Retirer"**.\
Un sélecteur s'affichera et vous permettra de choisir la réaction de mots à supprimer.\

2023-02-27 13:08 UTC, IIbey commented on modules/reactions-de-mots.md
> +Si vous souhaitez supprimer **toutes les réactions de mots**, vous pouvez utiliser la commande `/config`, aller dans `réaction de mots` et terminer par `Réinitialiser`
```suggestion
Si vous souhaitez supprimer **toutes** les réactions de mots, vous pouvez utiliser la commande <mark style="color:orange;">/config</mark>, toujours dans le système **"Réactions de mots"** et de cliquer sur **"Réinitialiser"**.

2023-02-27 13:10 UTC, IIbey commented on modules/reactions-de-mots.md
> +Une fois effectuée, une réinitialisation est irréversible.Elle remettra les trois réactions de mots de base. C'est à dire : hey, coucou et salut.
```suggestion
Une réinitialisation est irréversible ! Une fois effectuée, elle remettra les trois réactions de mots de base. C'est à dire : "hey", "coucou" et "salut".

2023-02-27 13:12 UTC, IIbey commented on modules/reactions-de-mots.md
> +Vous pouvez voir les réaction de mots du serveur avec la commande `/config` et aller sur `Réactions de mots`.
```suggestion
Vous pouvez voir les réactions de mots du serveur avec la commande <mark style="color:orange;">/config</mark> et vous rendre simplement dans le système **"Réactions de mots"**.

2023-02-27 13:40 UTC, Wapiti13 commented on modules/reactions-de-mots.md
> +Pour **ajouter** une réaction à un mot, il vous suffit de faire la commande `/config`, aller sur `Réactions de mots` puis `Ajouter`.
Pourquoi dire aller dans le système Réactions de mots ? C'est mieux de dire : sélectionnez (le système Réactions de rôles), non ?

2023-02-27 16:10 UTC, IIbey requested changes

2023-02-27 16:10 UTC, IIbey commented on modules/reactions-de-mots.md
> +## Activer / désactiver le système de réactions de mots <a href="#on-off" id="on-off"></a>
```suggestion
## Activer / désactiver le système de réactions de mots

2023-02-27 16:10 UTC, IIbey commented on modules/reactions-de-mots.md
> +## Ajouter des réactions de mots <a href="#add" id="add"></a>
```suggestion
## Ajouter des réactions de mots

2023-02-27 16:10 UTC, IIbey commented on modules/reactions-de-mots.md
> +## Supprimer des réactions de mots <a href="#delete" id="delete"></a>
```suggestion
## Supprimer des réactions de mots

2023-02-27 16:10 UTC, IIbey commented on modules/reactions-de-mots.md
> +## Lister les réactions de mots<a href="#view" id="view"></a>
```suggestion
## Lister les réactions de mots

2023-02-27 16:10 UTC, IIbey commented on modules/reactions-de-mots.md
> +## <mark style="color:red;">Réinitialiser le système</mark>
```suggestion
## Réinitialiser le système

2023-02-27 16:10 UTC, IIbey commented on slash/wordreact.md
>  ## Lister les réactions de mots<a href="#view" id="view"></a>
```suggestion
## Lister les réactions de mots

2023-02-27 16:21 UTC, ls62 commented on modules/reactions-de-mots.md
> +Si vous ne possédez pas le [premium](https://draftbot.fr/premium), vous serez limité à 10 réactions de mots.\
Peut-être mettre le mot "premium" en orange ?

2023-02-27 16:45 UTC, Tellvex requested changes
Hello @Wapiti13, ayant vu ta PR et celle des autres, je pense que tu auras certainement besoin de modifier des éléments / catégories.
En effet, lorsque tu regardes le #Documentation (sur DB - Support), une sorte de schéma a été établi :

 - En premier lieu, il serait important de décrire globalement le wordreact ainsi qu'éventuellement une photo de Draftbot réagissant à un message.

- Dans un second temps, il faudrait éventuellement faire un "tab" montrant la configuration à la fois sur **Discord** et sur le **Panel** (Tu peux voir la pr #12 pour avoir un aperçu).
> Tu peux également voir avec @IIbey pour toutes les corrections de fautes.

Je te passe le lien du message expliquant la doc : https://discord.com/channels/422112414964908042/1074761114610569359/1075453775579467806

2023-02-28 00:19 UTC, IIbey requested changes

2023-02-28 00:19 UTC, IIbey commented on modules/reactions-de-mots.md
> +Pour désactiver le système, il vous faudra également utiliser la commande <mark style="color:orange;">/config</mark>, puis dans le système `Réactions de mots` et **"Désactiver le système"** . Cela dé
```suggestion
Pour désactiver le système, il vous faudra également utiliser la commande <mark style="color:orange;">/config</mark>, puis dans le système **"Réactions de mots"** puis **"Désactiver le système"** . Cela désactivera le système automatiquement.

2023-02-28 00:19 UTC, IIbey commented on modules/reactions-de-mots.md
> +Un sélecteur s'affichera et vous permettra de choisir la réaction de mots à supprimer.\
Tu feras attention aux \ " visibles sur la doc pour cette partie :3

![image](https://user-images.githubusercontent.com/111301542/221718592-ef0a9437-19a0-4684-8797-8834e54797ef.png)

2023-02-28 00:19 UTC, IIbey commented on modules/reactions-de-mots.md
> +Une réinitialisation est irréversible ! Une fois effectuée, elle remettra les trois réactions de mots de base. C'est à dire : "hey", "coucou" et "salut".
```suggestion
Une réinitialisation est irréversible ! Une fois effectuée, elle remettra les trois réactions de mots de base. C'est-à-dire : "hey", "coucou" et "salut".

2023-02-28 00:19 UTC, IIbey commented on modules/reactions-de-mots.md
> +## Qu'est ce que le système de réactions de mots et à quoi sert il ?
```suggestion
## Qu'est-ce que le système de réactions de mots et à quoi sert-il ?

2023-02-28 00:56 UTC, Tellvex commented on modules/reactions-de-mots.md
> +## Qu'est ce que le système de réactions de mots et à quoi sert il ?
Je proposerai éventuellement à la place de "à quoi sert-il?" **"et quelle est son utilité ?"**

2023-02-28 12:54 UTC, IIbey commented
@Wapiti13 tu as mis mes corrections en **resolved** mais je ne vois aucune correction/modification de ton côté 🤔

2023-02-28 13:49 UTC, DraftProducts commented
1. Où sont passées les images qui étaient bien présentes dans la PR de @Tellvex ? (wordreact.md)
2. L'objectif de cette PR n'est pas de reprendre mot pour mot le texte écrit par @Tellvex dans sa PR et de te l'approprier mais bien d'améliorer son contenu (plus que de changer le markdown).
3. Si une image est déjà correcte, rien ne sert de la refaire.

2023-02-28 14:19 UTC, Tellvex commented on modules/reactions-de-mots.md
> +## Qu'est ce que le système de réactions de mots et à quoi sert il ?
@IIbey tu en penses quoi ?

2023-02-28 14:39 UTC, IIbey commented on modules/reactions-de-mots.md
> +## Qu'est ce que le système de réactions de mots et à quoi sert il ?
Je suis d'accord 👆

2023-02-28 14:51 UTC, Wapiti13 commented
@IIbey  Les modifications ont été appliqué sur la version que je travail. Cette version sera disponible dès que j'aurais terminé l'interface de la présentation. : )

2023-02-28 17:39 UTC, ErwanGit requested changes

2023-02-28 17:39 UTC, ErwanGit commented on modules/reactions-de-mots.md
> +![](../../.gitbook/assets/wordreact/exemplesystème.png)
Les noms de fichiers doivent être en anglais et sans accents

2023-02-28 18:49 UTC, Tellvex reviewed
![image](https://user-images.githubusercontent.com/78918215/221949570-eed1a826-400d-45a0-8707-ad5f066a34fc.png)
![image](https://user-images.githubusercontent.com/78918215/221949844-10117dcd-0453-4d7c-997f-f1f1ae2c524c.png)

* @Wapiti13, pourrais-tu m'expliquer pourquoi tu as supprimé et réupload cette image ? Sachant que le nom du fichier que tu as créé n'est pas valide ( le fichier est pas en anglais et a des espaces) ?

2023-02-28 19:14 UTC, Tellvex requested changes
Globalement, il reste pas mal de choses a corriger sur l'esthétique ainsi que sur toute la partie respect des normes de nomenclature.

Comme tu peux le voir dans le commentaire du dessus, je ne vois pas pourquoi tu as supprimé un fichier pour remettre exactement le même, sous un nom différent et qui ne respecte pas la nomenclature.

Concernant les "tab", il ne sont certes pas affichés sur le gitbook mais ils sont inutiles dans ce système comme tu l'as très bien dit sur discord.

![image](https://user-images.githubusercontent.com/78918215/221954747-cb9cace0-466b-4ff3-b37c-2e6bef80174b.png)

* Pour terminer, comme l'a très bien dit @DraftProducts plus haut (mais tu l'as visiblement ignoré), je ne vois pas l'intérêt de changer des images existantes pour avoir ta pdp affichée (en témoigne cette image) : ![image2](../.gitbook/assets/wordreact/view.png)

* De plus, **l'intégralité du contenu de ta pull request** provient du #7 , et le fait de réouvrir cette pull request pour l'indexer aurait été plus intéressant que de rouvrir une autre pull request qui se base sur son contenu mais qui change des images inutilement.

2023-02-28 19:14 UTC, Tellvex commented on modules/reactions-de-mots.md
> +\
```suggestion

```

2023-02-28 19:14 UTC, Tellvex commented on modules/reactions-de-mots.md
> +Pour ajouter une réaction à un mot, il vous suffit de faire la commande <mark style="color:orange;">/config</mark>, aller dans le système **"Réactions de mots"** puis cliquez sur le bouton **"Ajouter
Tu peux également passer cela en orange car il s'agit du module de la commande
```suggestion
Pour ajouter une réaction à un mot, il vous suffit de faire la commande <mark style="color:orange;">/config</mark>, aller dans le système <mark style="color:orange;">**"Réactions de mots"**</mark> puis cliquez sur le bouton **"Ajouter"**.

```

2023-02-28 19:14 UTC, Tellvex commented on modules/reactions-de-mots.md
> +![](../../.gitbook/assets/wordreact/exemplesystème.png)
Ce serait mieux d'avoir **"view_wordreact"** en nom de fichier

2023-02-28 19:16 UTC, Tellvex commented
Je pense aussi que l'image d'exemple pourrait être faite avec un profil du type "Utilisateur" ou autre afin de garder une certaine neutralité :)

2023-03-10 14:34 UTC, Hugo-broc commented
Hello @Wapiti13 ! Je vois qu'il y a pas mal de changements en attente...
N'oublie pas alors de "Résoudre une conversation" quand tu as bien résolu quelque chose afin que l'on puisse voir l'avancée.
Je regarderai personnellement tout cela quand toutes les modifications à faire seront faites car je ne veux pas risquer de me répéter (possibilité de me mentionner pour que je regarde quand cela sera fait, pour que je sache que c'est bon).

2023-03-17 10:35 UTC, Wapiti13 commented
Salut, @Tellvex ! Je vais répondre à tes nombreux messages demandant pourquoi ai je supprimé une image et que j'ai remis une image identique. 

Cela s'explique à une erreur de réflexion de ma part. En effet, après avoir supprimé et rajouté une nouvelle image pour le panel de configuration pour le système de réactions de mots avec la commande /config , je m'étais dis que probablement la question posée pour l'ajout de réactions de mots allait être différente du au changement de préfix ainsi que la refonte du panel de configuration du système. Je n'ai pas vérifié si cela avait changé et c'est ce qui a couté la bête erreur et tes nombreux messages ainsi qu'un message de Nicolas. 

Après avoir lu vos messages et après avoir revue mes actes, je me suis rendu compte de mon erreur qu'à ce moment la. J'ai tenté pas mal de chose pour essayer de récupérer ton image mais en vain. C'et pourquoi je m'excuse pour l'erreur commise de mon côté et je vais tout faire pour ne plus reproduire ce type d'erreur. 

En ce qui concerne le fond et la forme de la pr, je le dis et je me répète je ne les pas fini. Mon but n'était pas de te plagiat mais bien de replacer les différents éléments et information que je devais avoir pour former la pr dont je souhaitais. Mais une review c'est lancé pour une raison que j'ignore. Review involontaire on va dire. 

Pour l'instant, je continue la production de ma pr. Je testes des petites chose comme des tabs et autres. En parlant de tabs, si j'ai écris que le début, donc {% tabs %} et pas la fin donc {% endtabs %}, c'est parce que je n'avais plus le temps de continuer et que je pouvais continuer la prouction de ma pr que dans des jours à venir. 

J'ignore aucun message ni commentaire, Tellvex. Si je ne répond pas, c'est que soit je réfléchis à une bonne formulation de mon message pour être très claire ou alors je n'ai juste pas le temps de répondre. Des messages de quelques ne suffisent pas trop pour être claire et précis. Il m'arrive aussi d'oublier de répondre et dans ces cas la, tu peux me ping dans le salon Documentation sur Discord en disant : @Wapiti13 , tu pourrais répondre à mon message stp. Je répondrai alors à ton commentaire / message avec plaisir. ce n'est pas en disant : oui wapiti tu ignores mes messages. Lire ce genre de message n'est pas vraiment cool pour la personne en face, vois tu.

Voila, j'espère avoir répondu à ta question et celle de @DraftProducts. Si vous avez des questions, n'hésitez surtout pas ! Bonne journée à vous deux : )

2023-03-17 10:43 UTC, Tellvex commented
Puisque tu t'es basé sur le contenu de mon ancienne pr, pourquoi n'as-tu pas regardé la date de création des fichiers, car le /config existait au moment de mon ancienne pr et la page a été créée à partir de cela.
Concernant les images, tu peux les "restaurer" (si tu veux on peux en parler ce soir en voc), donc ce n'est pas grave.

Bon après-midi @Wapiti13

2023-03-17 10:45 UTC, Wapiti13 commented
On peut en parler ce soir en voc : )

2023-03-17 21:48 UTC, Tellvex commented on modules/reactions-de-mots.md
> +![Exemple du Système](../../.gitbook/assets/wordreact/view_wordreact.png)
```suggestion
![Exemple du Système](../../.gitbook/assets/wordreact/view_wordreact.jpg)

```

2023-03-17 21:53 UTC, Tellvex approved these changes

2023-03-18 00:54 UTC, IIbey requested changes

2023-03-18 00:54 UTC, IIbey commented on modules/reactions-de-mots.md
> +Le système de réactions de mots, aussi appelé wordreact, permet de faire en sorte que DraftBot réagit avec des réactions à des messages qui commence par un mots spécial. Petit exemple illustré ci des
```suggestion
Le système de réactions de mots, aussi appelé "wordreact", permet de faire en sorte que DraftBot réagit avec des réactions à des messages qui commencent par un mot spécial. Petit exemple illustré ci-dessus :

2023-03-18 00:54 UTC, IIbey commented on modules/reactions-de-mots.md
> +![Exemple du Système](../../.gitbook/assets/wordreact/view_wordreact.jpg)
```suggestion
![Exemple du système](../../.gitbook/assets/wordreact/view_wordreact.jpg)

2023-03-18 00:54 UTC, IIbey commented on modules/reactions-de-mots.md
> +* Pour activer le système de réactions de mots, il vous suffit de faire la commande <markt style="color:orange;">/config</mark>, puis d'aller dans le système **"Réactions de mots"** et de cliquer sur
```suggestion
* Pour activer le système de réactions de mots, il vous suffit de faire la commande <markt style="color:orange;">/config</mark>, puis d'aller dans le système **"Réactions de mots"** et de cliquer sur **"Activer le système"**.

2023-03-18 00:54 UTC, IIbey commented on modules/reactions-de-mots.md
> +Si vous ne possédez pas le [<mark style="color:orange;">premium</mark>](https://draftbot.fr/premium), vous serez limité à 10 réactions de mots. En possedant le premium de DraftBot, vous pourrez créer
```suggestion
Si vous ne possédez pas le [<mark style="color:orange;">premium</mark>](https://draftbot.fr/premium), vous serez limité à 10 réactions de mots. En possédant le premium de DraftBot, vous pourrez créer des réactions de mots de manière illimitée. Pour qu'une réaction de mots soit prise en compte, il doit être situé en **début de message**. Si le mot est au milieu ou à la fin d'un message, aucune réaction ne sera ajoutée.

2023-03-18 13:05 UTC, ErwanGit requested changes

2023-03-18 13:05 UTC, ErwanGit commented on modules/reactions-de-mots.md
> +Un sélecteur s'affichera et vous permettra de choisir la réaction de mots à supprimer.
```suggestion
Un sélecteur s'affichera et vous permettra de choisir le réaction de mot à supprimer.

```

2023-03-18 17:47 UTC, ls62 commented on modules/reactions-de-mots.md
> +Le système de réactions de mots, aussi appelé "wordreact", permet de faire en sorte que DraftBot réagit avec des réactions à des messages qui commencent par un mot spécial. Petit exemple illustré ci-
Le mot "spécial" ne conviens pas à une bonne explication, peu-être utilisé le mot "prédéfinie"

2023-03-18 17:52 UTC, ls62 commented on modules/reactions-de-mots.md
> +Vous pouvez également utiliser <mark style="color:orange;">/config Système: Réactions de mots</mark> pour afficher directement la page.
Peut-être retirer ce message cars, il est déjà spécifié au-dessus.

2023-03-18 17:54 UTC, ls62 commented on modules/reactions-de-mots.md
> +Vous pouvez voir les réactions de mots sur votre serveur avec la commande <mark style="color:orange;">/config</mark> et vous rendre simplement dans le système **Réactions de mots**.
Il manque des guillemets à `Réactions de mots`.

2023-03-18 17:55 UTC, ErwanGit requested changes

2023-03-18 17:55 UTC, ErwanGit commented on modules/reactions-de-mots.md
> +Le système de réactions de mots, aussi appelé "wordreact", permet de faire en sorte que DraftBot réagit avec des réactions à des messages qui commencent par un mot spécial. Petit exemple illustré ci-
Pas convaincu du "Petit exemple"

2023-03-18 17:55 UTC, ErwanGit commented on modules/reactions-de-mots.md
> +![Exemple du système](../../.gitbook/assets/wordreact/view_wordreact.jpg)
Pas convaincu du "Exemple du système"

2023-03-18 17:55 UTC, ErwanGit commented on modules/reactions-de-mots.md
> +![Exemple du message](../../.gitbook/assets/wordreact/question.png)
Pas convaincu du exemple du message

2023-03-18 17:55 UTC, ErwanGit commented on modules/reactions-de-mots.md
> +{% endhint %}
```suggestion
Si vous ne possédez pas le [<mark style="color:orange;">premium</mark>](https://draftbot.fr/premium), vous serez limité à 10 réactions de mots. En possédant le premium de DraftBot, vous pourrez créer des réactions de mots de manière illimitée.
Pour qu'une réaction de mots soit prise en compte, il doit être situé en **début de message**. Si le mot est au milieu ou à la fin d'un message, aucune réaction ne sera ajoutée.
{% endhint %}

```

2023-03-18 17:55 UTC, ErwanGit commented on modules/reactions-de-mots.md
> +Une réinitialisation est irréversible ! Une fois effectuée, elle remettra les trois réactions de mots de base. C'est-à-dire : "hey", "coucou" et "salut".
```suggestion
Une réinitialisation est irréversible ! Une fois effectuée, elle remettra les trois réactions de mots de base, c'est-à-dire : "hey", "coucou" et "salut".

```

2023-03-18 18:04 UTC, ls62 commented on modules/reactions-de-mots.md
> +![Exemple du message](../../.gitbook/assets/wordreact/question.png)
Peut-être refaire les bords de l'image cars, ce n'est pas bien coupé ^^"

2023-03-19 02:07 UTC, IIbey commented on modules/reactions-de-mots.md
> +![Exemple du système](../../.gitbook/assets/wordreact/view_wordreact.jpg)
"Aperçu" ?

2023-03-28 22:15 UTC, DraftProducts commented
Superseded by branch [`feat/reactions-de-mots`](https://github.com/DraftBot/Documentation/tree/feat/reactions-de-mots) (open to new pull-request)

2023-03-28 22:15 UTC, closed without merging