Mise à jour "💡 Suggestions"
DraftBot/Documentation pull request #31
Opened 2023-03-01 15:17 UTC by Hugo-broc

2023-03-03 19:27 UTC, ErwanGit requested changes

2023-03-03 19:27 UTC, ErwanGit commented on modules/suggestions.md
> +![Menu de création d'une suggestion](../.gitbook/assets/suggestions/create_a_suggestion.png)
J'aurai plutôt mis ça comme nom de fichier
```suggestion
![Menu de création d'une suggestion](../.gitbook/assets/suggestions/create_suggestion.png)
```

2023-03-03 19:27 UTC, ErwanGit commented on modules/suggestions.md
> +Pour accepter une suggestion, faites un clic droit (sur pc) ou appuyez longtemps (sur portable) sur la suggestion en question et appuyez sur "Applications".\
```suggestion
Pour accepter une suggestion, faites un clic droit (sur ordinateur) ou appuyez longtemps (sur mobile) sur la suggestion en question et appuyez sur "Applications".\
```

2023-03-03 19:27 UTC, ErwanGit commented on modules/suggestions.md
> +Pour refuser une suggestion, faites un clic droit (sur pc) ou appuyez longtemps (sur portable) sur la suggestion en question et appuyez sur "Applications".\
```suggestion
Pour refuser une suggestion, faites un clic droit (sur ordinateur) ou appuyez longtemps (sur mobile) sur la suggestion en question et appuyez sur "Applications".\
```

2023-03-03 19:27 UTC, ErwanGit commented on modules/suggestions.md
> +Si vous ne souhaitez pas mettre de raison de refus, appuyez directement sur "<mark style="color:blue;">Envoyer</mark>" sans rentrer de texte dans la case.
Une raison est obligatoire pour les refus

2023-03-29 20:01 UTC, Tellvex commented
La pull request est terminée ? Car je vois que l'onglet configuration est un peu vierge.

2023-04-09 09:24 UTC, DraftProducts approved these changes

2023-06-15 19:46 UTC, DraftProducts commented
Closed and superseded by a free branch due to inactivity : https://github.com/DraftBot/Documentation/tree/feat/suggestions-page

2023-06-15 19:46 UTC, closed without merging