[Module] - Wordreact
DraftBot/Documentation pull request #32
Opened 2023-04-15 20:08 UTC by Tellvex

Remise a niveau du wordreact, basé sur la pull-request de wapiti13 ( #30 ) et la mienne( #7 )

### Modifications

-> Passage de la configuration dans un "tab"

### Ajouts

-> Update côté web ( nouvelle page panel )

2023-04-15 21:05 UTC, Tellvex commented
J'aimerais avoir l'avis d' @IIbey et de @ErwanGit  par rapport aux éventuelles fautes/incompréhensions de la partie configuration avec le /config

Dans un second temps je ferais la partie "panel" de la page

2023-04-16 10:46 UTC, ErwanGit requested changes

2023-04-16 10:46 UTC, ErwanGit commented on .gitbook/assets/wordreact/view_wordreact.jpg
Peut-être mettre une heure pile pour l'envoi du message

2023-04-16 10:46 UTC, ErwanGit commented on modules/reactions-de-mots.md
> +> Vous trouverez ci-dessous la configuration des réactions de mot avec le `/config`
Il y a une répétition la avec le titre du tableau

2023-04-16 10:46 UTC, ErwanGit commented on modules/reactions-de-mots.md
> +> Vous trouverez ci-dessous la configuration des réactions de mots sur le panel.
Répétition également

2023-04-16 10:46 UTC, ErwanGit commented on modules/reactions-de-mots.md
> +Vous pourrez activer ou désactiver en haut à droite de la page grâce à un "switch".
Il faut utiliser un autre mot que switch, ça fait trop anglais et incompréhensible pour un utilisateur lambda

2023-04-16 10:46 UTC, ErwanGit commented on modules/reactions-de-mots.md
> +Le sélecteur d'émoji du panel ne permet pas de mettre des émojis provenant d'autres serveurs. Dans ce cas-là, il est préférable de privilégier le `/config`.
C'est pas possible normalement de configurer des emojis de d'autres serveurs dans le /config

2023-04-16 12:20 UTC, Tellvex commented on .gitbook/assets/wordreact/view_wordreact.jpg
A quel endroit @ErwanGit ?

2023-04-16 12:22 UTC, Tellvex commented on modules/reactions-de-mots.md
> +> Vous trouverez ci-dessous la configuration des réactions de mot avec le `/config`
Avec l'aperçu de GitBook, je trouve cela mieux de mettre une ligne de "description" dans chaque tab de la configuration.

2023-04-16 12:22 UTC, Tellvex commented on modules/reactions-de-mots.md
> +> Vous trouverez ci-dessous la configuration des réactions de mots sur le panel.
Avec l'aperçu de GitBook, je trouve cela mieux de mettre une ligne de "description" dans chaque tab de la configuration.

2023-04-16 12:22 UTC, Tellvex commented on modules/reactions-de-mots.md
> +Vous pourrez activer ou désactiver en haut à droite de la page grâce à un "switch".
Tu me conseillerais quoi ?

2023-04-16 12:24 UTC, Tellvex commented on modules/reactions-de-mots.md
> +Le sélecteur d'émoji du panel ne permet pas de mettre des émojis provenant d'autres serveurs. Dans ce cas-là, il est préférable de privilégier le `/config`.
Yep, je corrige ça

2023-04-16 18:36 UTC, ErwanGit commented on modules/reactions-de-mots.md
> +Vous pourrez activer ou désactiver en haut à droite de la page grâce à un "switch".
bouton ?

2023-04-16 18:36 UTC, ErwanGit commented on modules/reactions-de-mots.md
> +Vous pourrez activer ou désactiver en haut à droite de la page grâce à un "switch".
Switch est trop anglais, il faut dans tous les cas modifié je pense

2023-04-20 13:42 UTC, ErwanGit approved these changes

2023-04-20 21:28 UTC, IIbey approved these changes

2023-04-20 21:28 UTC, DraftProducts approved these changes

2023-04-24 18:31 UTC, ErwanGit requested changes

2023-04-24 18:31 UTC, ErwanGit commented on modules/reactions-de-mots.md
> +> Vous trouverez ci-dessous la configuration des réactions de mot avec le `/config`.
Style du /config pas uniforme avec les autres pages

2023-04-24 18:31 UTC, ErwanGit commented on modules/reactions-de-mots.md
> +Pour désactiver le système, il suffira de faire la même procédure : le bouton **"Activer le système"** est remplacé **"Désactiver le système"**. Il faudra le sélectionner et le système sera désactivé
Eventuellement faire un saut de ligne pour la dernière phrase

2023-04-24 18:31 UTC, ErwanGit commented on modules/reactions-de-mots.md
> +Voir le <mark style="color:orange;">[comparatif entre version gratuite et premium](https://www.draftbot.fr/premium#diff)</mark>.
Je pense que cela pourrait être mis sous la forme d'une vrai phrase

2023-04-24 20:18 UTC, Hugo-broc requested changes
Quelques changements de mise en page sinon la page est parfaitement bien faite ! 👍

2023-04-24 20:18 UTC, Hugo-broc commented on modules/reactions-de-mots.md
> +Si vous souhaitez supprimer une réaction en particulier, il vous suffira de cliquer sur le bouton **"Retirer"**. Un sélecteur s'affichera et vous permettra de choisir la réaction de mots à supprimer.
```suggestion
Si vous souhaitez supprimer une réaction en particulier, il vous suffira de cliquer sur le bouton "Retirer". Un sélecteur s'affichera et vous permettra de choisir la réaction de mot à supprimer.

```

2023-04-24 20:18 UTC, Hugo-broc commented on modules/reactions-de-mots.md
> +Vous pouvez voir les réactions de mots sur votre serveur depuis l'onglet de configuration des réactions de mot. Vous aurez alors une liste avec toutes vos réactions de mots.
```suggestion
Vous pouvez voir les réactions de mots sur votre serveur depuis l'onglet de configuration des réactions de mots. Vous aurez alors une liste avec toutes vos réactions de mots.

```

2023-04-24 20:18 UTC, Hugo-broc commented on modules/reactions-de-mots.md
> +Si vous souhaitez supprimer **toutes** les réactions de mots, il suffira d'appuyer sur le bouton **"Réinitialiser"**.
```suggestion
Si vous souhaitez supprimer **toutes** les réactions de mots, il suffira d'appuyer sur le bouton "Réinitialiser".

```

2023-04-24 20:18 UTC, Hugo-broc commented on modules/reactions-de-mots.md
> +Une réinitialisation est irréversible ! Une fois effectuée, elle remettra les trois réactions de mots par défaut, à savoir : "hey", "coucou" et "salut" avec la réaction "👋".
```suggestion
Une réinitialisation est irréversible ! Une fois effectuée, elle remettra les trois réactions de mots par défaut, à savoir : "hey", "coucou" et "salut" avec la réaction 👋.

```

2023-04-24 20:18 UTC, Hugo-broc commented on modules/reactions-de-mots.md
> +> Vous trouverez ci-dessous la configuration des réactions de mots sur le panel.
```suggestion
<mark style="color:blue;">[Accéder au panel de **DraftBot**](https://draftbot.fr/dashboard)</mark>

> Vous trouverez ci-dessous la configuration des réactions de mots sur le panel.

```

2023-04-24 20:18 UTC, Hugo-broc commented on modules/reactions-de-mots.md
> +Vous pourrez activer ou désactiver la réaction de mot en haut à droite de la page grâce à un bouton.
```suggestion
Vous pouvez activer ou désactiver la réaction de mot en haut à droite de la page grâce à un bouton.

```

2023-04-24 20:18 UTC, Hugo-broc commented on modules/reactions-de-mots.md
> +Vous pouvez ajouter une réaction de mot en mettant un **émoji** dans la case d'émoji et en mettant le mot concerné dans la case **"Entrez un début de phrase"**. Vous pourrez alors **"Ajouter"** la ré
```suggestion
Vous pouvez ajouter une réaction de mot en mettant un **émoji** dans la case d'émoji et en mettant le mot concerné dans la case "Entrez un début de phrase". Vous pourrez alors "Ajouter" la réaction de mot.

```

2023-04-24 20:18 UTC, Hugo-broc commented on modules/reactions-de-mots.md
> +Pour modifier une réaction de mot, cliquez sur le bouton **"modifier"** de la réaction de mot concernée. Les cases en haut se prérempliront : vous pourrez y modifier l'émoji et le mot. Il vous suffir
```suggestion
Pour modifier une réaction de mot, cliquez sur le bouton "Modifier" de la réaction de mot concernée. Les cases en haut se prérempliront : vous pourrez y modifier l'émoji et le mot. Il vous suffira de "Remplacer" pour que la modification soit prise en compte.

```

2023-04-24 20:18 UTC, Hugo-broc commented on modules/reactions-de-mots.md
> +Pour supprimer une réaction de mot, cliquez sur le bouton **"supprimer"** de la réaction de mot concernée.
```suggestion
Pour supprimer une réaction de mot, cliquez sur le bouton "Supprimer" de la réaction de mot concernée.

```

2023-04-24 20:18 UTC, Hugo-broc commented on modules/reactions-de-mots.md
> +Si vous ne possédez pas le <mark style="color:orange;">[premium](https://draftbot.fr/premium)</mark>, vous serez limité à 10 réactions de mots. En possédant le premium de DraftBot, vous pourrez créer
```suggestion
Si vous ne possédez pas le <mark style="color:blue;">[premium](https://draftbot.fr/premium)</mark>, vous serez limité à 10 réactions de mots. En possédant le premium de **DraftBot**, vous pourrez créer des réactions de mots de manière illimitée.

```

2023-04-24 20:18 UTC, Hugo-broc commented on modules/reactions-de-mots.md
> +Voir le <mark style="color:orange;">[comparatif entre version gratuite et premium](https://www.draftbot.fr/premium#diff)</mark>.
Je suis d'accord avec Erwan en plus de cette suggestion d'amélioration.
```suggestion
Voir le <mark style="color:blue;">[comparatif entre version gratuite et premium](https://www.draftbot.fr/premium#diff)</mark>.
```

2023-04-24 22:49 UTC, Tellvex commented on modules/reactions-de-mots.md
> +Le système de réactions de mots, aussi appelé "wordreact", fait réagir DraftBot à des messages qui commencent par un mot prédéfini avec une réaction définie. Un aperçu du message est disponible ci-de
Je n'avais pas regardé la partie explication car il me semblait que tout avait été corrigé dans la PR de wapiti.

2023-04-24 22:51 UTC, Tellvex commented on modules/reactions-de-mots.md
> +Pour activer le système de réactions de mots, il faudra aller dans le système **"Réactions de mots"** et de cliquer sur **"Activer le système"**.
Je ne sais pas ce que tu en penses mais ce serait aussi mieux de passer ce qui entre guillemets en orange non ?

2023-04-24 22:53 UTC, Tellvex commented on modules/reactions-de-mots.md
> +Pour désactiver le système, il suffira de faire la même procédure : le bouton **"Activer le système"** est remplacé **"Désactiver le système"**. Il faudra le sélectionner et le système sera désactivé
Éventuellement passer les noms des boutons en mark orange ?

2023-04-24 22:54 UTC, Tellvex commented on modules/reactions-de-mots.md
> +Pour ajouter une réaction à un mot, il vous suffit de cliquer sur le bouton **"Ajouter"**. Vous obtiendrez alors le message ci-dessous :
Éventuellement passer les noms des boutons en mark orange ?

2023-04-24 22:54 UTC, Tellvex commented on modules/reactions-de-mots.md
> +Si vous souhaitez supprimer une réaction en particulier, il vous suffira de cliquer sur le bouton **"Retirer"**. Un sélecteur s'affichera et vous permettra de choisir la réaction de mots à supprimer.
Éventuellement passer les noms des boutons en mark orange ?

2023-04-24 22:55 UTC, Tellvex commented on modules/reactions-de-mots.md
> +Si vous souhaitez supprimer **toutes** les réactions de mots, il suffira d'appuyer sur le bouton **"Réinitialiser"**.
Éventuellement passer les noms des boutons en mark orange ?

2023-04-24 22:56 UTC, Tellvex commented on modules/reactions-de-mots.md
> +Une réinitialisation est irréversible ! Une fois effectuée, elle remettra les trois réactions de mots par défaut, à savoir : "hey", "coucou" et "salut" avec la réaction "👋".
Pour le coup, je pense que c'est mieux de laisser l'emoji entre guillemets. Ça permet de le mettre en valeur pour l'utilisateur

2023-04-24 22:57 UTC, Tellvex commented on modules/reactions-de-mots.md
> +Vous pouvez ajouter une réaction de mot en mettant un **émoji** dans la case d'émoji et en mettant le mot concerné dans la case **"Entrez un début de phrase"**. Vous pourrez alors **"Ajouter"** la ré
Éventuellement passer les noms des boutons en mark orange ?

2023-04-24 22:58 UTC, Tellvex commented on modules/reactions-de-mots.md
> +Pour modifier une réaction de mot, cliquez sur le bouton **"modifier"** de la réaction de mot concernée. Les cases en haut se prérempliront : vous pourrez y modifier l'émoji et le mot. Il vous suffir
Éventuellement passer les noms des boutons en mark orange ?

2023-04-24 22:59 UTC, Tellvex commented on modules/reactions-de-mots.md
> +Pour supprimer une réaction de mot, cliquez sur le bouton **"supprimer"** de la réaction de mot concernée.
Éventuellement passer les noms des boutons en mark orange ?

2023-04-24 23:00 UTC, Tellvex commented on modules/reactions-de-mots.md
> +Voir le <mark style="color:orange;">[comparatif entre version gratuite et premium](https://www.draftbot.fr/premium#diff)</mark>.
Pourquoi en bleu ?

2023-05-05 19:52 UTC, ErwanGit requested changes
Commentaires plus haut non résolus

2023-06-10 10:18 UTC, bariboo requested changes
Hello !

Quelques petites reformulations ainsi que corrections orthographiques !

Beau boulot !

*désoler pour le retard...*

2023-06-10 10:18 UTC, bariboo commented on modules/reactions-de-mots.md
> +Le bot ne réagira que lorsque le mot est en **début de phrase**.
```suggestion
Le bot réagira que lorsque le mot est en **début de phrase**.

```

Pourquoi utiliser une négation ici ?

2023-06-10 10:18 UTC, bariboo commented on modules/reactions-de-mots.md
> +> Vous trouverez ci-dessous la configuration des réactions de mot avec la commande <mark style="color:orange;">/config</mark>.
```suggestion
> Vous trouverez ci-dessous la configuration des réactions de mots avec la commande <mark style="color:orange;">/config</mark>.

```

2023-06-10 10:18 UTC, bariboo commented on modules/reactions-de-mots.md
> +Pour activer le système de réactions de mots, il faudra aller dans le système "👀 Réactions de mots" et de cliquer sur "Activer le système".
```suggestion
Pour activer le système de réactions de mots, il faudra aller dans le système "👀 Réactions de mots" puis cliquer sur "Activer le système".

```

2023-06-10 10:18 UTC, bariboo commented on modules/reactions-de-mots.md
> +Il faudra le sélectionner et le système sera désactivé.
```suggestion
Pour désactiver le système, il suffira d'effectuer la même procédure : cliquer sur le bouton "Activer le système" qui sera devenu "Désactiver le système".\
```

2023-06-10 10:18 UTC, bariboo commented on modules/reactions-de-mots.md
> +### Supprimer des réactions de mots
```suggestion
### Supprimer une réaction de mot

```

Puisque l'on parle d'une réaction en particulier.

2023-06-10 10:18 UTC, bariboo commented on modules/reactions-de-mots.md
> +Si vous souhaitez supprimer **toutes** les réactions de mots, il suffira d'appuyer sur le bouton "Réinitialiser".
```suggestion
Si vous souhaitez supprimer **toutes** les réactions de mots, il suffira d'appuyer sur le bouton <mark style="color:red;">"Réinitialiser"</mark>.

```

2023-06-10 10:18 UTC, bariboo commented on modules/reactions-de-mots.md
> +### Ajouter des réactions de mots
```suggestion
### Ajouter une réactions de mot

```

On parle d'ajouter 1 réaction, pas plusieurs

2023-06-22 13:51 UTC, Tellvex commented on modules/reactions-de-mots.md
> +Le bot ne réagira que lorsque le mot est en **début de phrase**.
Car c'est du français, tu ne peux pas mettre "... réagira que ...", y'a une négation à mettre. Tu peux voir ça avec @IIbey si tu as des doutes

2023-06-22 13:58 UTC, Tellvex commented on modules/reactions-de-mots.md
> +### Ajouter des réactions de mots
Je pense que c'est mieux de laisser ça au pluriel, notamment car en général tu fais cette procédure pour en ajouter plusieurs.
Et puis le reste aussi est au pluriel.
_Ps: "réactions" doit aussi passer au singulier dans ta suggestion_

2023-06-22 16:51 UTC, merged