Ajout de la page d'anniversaire
DraftBot/Documentation pull request #33
Opened 2023-04-20 01:53 UTC by kazotka

2023-04-20 02:29 UTC, kazotka reviewed
Je me suis trompé de titre dans les commits le fichier feat/birthday devrai s'appeler WIP page d'anniversaire (2), désolé.

2023-04-20 10:08 UTC, Tellvex requested changes
Je trouve que c'est plutôt bon côté explications, cela dit je pense que tu devrais jeter un coup d'oeil aux autres pull request pour voir comment les "tabs" sont organisés.

Il manque également la modification du "summary.md" afin d'ajouter la page -> Tu peux éventuellement passer en vocal si tu as besoin d'aide là dessus.
> Le gros problème, c'est que tant que le summary.md est pas mis à jour, on ne pourra pas voir ta page sur GitBook.

2023-04-20 10:08 UTC, Tellvex commented on modules/anniversaires.md
> +- _ Premièrement *:*
Je trouve que la structure ici est pas très cohérente avec les autres pages de la documentation.

2023-04-20 10:08 UTC, Tellvex commented on modules/anniversaires.md
> +- _ Troisimement *:*
Je trouve que la structure ici est pas très cohérente avec les autres pages de la documentation.

2023-04-20 10:08 UTC, Tellvex commented on modules/anniversaires.md
> +- _ Cinquièmement & finnalement *:* Réinitialiser totallement le système d'anniversaire
Je trouve que la structure ici est pas très cohérente avec les autres pages de la documentation.

2023-04-20 10:08 UTC, Tellvex commented on modules/anniversaires.md
> +- _ Quatrièmement *:*
Je trouve que la structure ici est pas très cohérente avec les autres pages de la documentation.

2023-04-20 10:08 UTC, Tellvex commented on modules/anniversaires.md
> +Aussi, vous pouvez voir la liste de tous les anniversaires défini sur le serveur grâce à la commande <mark style="color:orange;">/anniversaire liste</mark>.
```suggestion
Vous pouvez également voir la liste de tous les anniversaires définis sur le serveur grâce à la commande <mark style="color:orange;">/anniversaire liste</mark>.

```

2023-04-20 11:52 UTC, kazotka commented on modules/anniversaires.md
> +- _ Premièrement *:*
Je n'ai pas fini cette partie donc c'est normal qu'elle ne soit pas compréhensive pour le moment.

2023-04-20 13:40 UTC, ErwanGit requested changes

2023-04-20 13:40 UTC, ErwanGit commented on .gitbook/assets/birthday/command_preview.png
Normalement, le format c'est JJ/MM/AAAA

2023-04-20 13:40 UTC, ErwanGit commented on modules/anniversaires.md
> +Attention, vous pouvez changer uniquement votre date d'anniversaire une fois par jour avec l'aide encore une fois de la commande <mark style="color:orange;">/anniversaire définir \[date]</mark>.
Il y a un cooldown progressif, c'est pas tout le temps une fois par jour (et heureusement)

- 1er changement : 1 jour
- 2ème : 2 jours
- 3ème : 6 mois
- 4 et plus : 1 an

2023-04-20 13:40 UTC, ErwanGit commented on modules/anniversaires.md
> +Lorsque vous voulez paramètre le message d'anniversaire, vous pouvez choisir entre prendre le message par défaut et un message personnaliser. Si vous prenez la deuxième option, n'oubliez pas d'utilis
```suggestion
Lorsque vous voulez paramètre le message d'anniversaire, vous pouvez choisir entre prendre le message par défaut et un message personnalisé. Si vous prenez la deuxième option, n'oubliez pas d'utiliser les variables ci-dessous et le markdown de Discord.

```

2023-04-20 20:08 UTC, Tellvex approved these changes

2023-04-20 21:02 UTC, IIbey commented on modules/anniversaires.md
> +*Vous pouvez accèder à différant paramêtre en cliquant sur le bouton 'Annonces' :*
```suggestion
Vous pouvez accéder à différents paramètres en cliquant sur le bouton "Annonces" :

2023-04-20 21:11 UTC, kazotka commented on .gitbook/assets/birthday/command_preview.png
C'est le cas ?

2023-04-20 22:45 UTC, DraftProducts approved these changes

2023-04-20 23:27 UTC, IIbey requested changes

2023-04-20 23:27 UTC, IIbey commented on modules/anniversaires.md
> +- Pour conclure avec le sixième bouton *(Rôles interdits)*, vous bloquer l'annonce d'un anniversaire à tous les membres qui possède le rôle.
```suggestion
- Avec l'aide du quatrième bouton *(Heure d'envoi)*, vous pouvez définir leur à laquelle le message d'annonce d'anniversaire sera envoyé dans le salon que vous aurez défini au préalable. 
- Grâce à ce cinquième bouton *(Mention)*, vous pouvez décider de mentionner un rôle lors de l'annonce qui sera envoyer lorsque quelqu'un fêtera son anniversaire.
- Pour conclure avec le sixième bouton *(Rôles interdits)*, vous bloquez l'annonce d'un anniversaire à tous les membres qui possède le rôle interdit.

2023-04-20 23:27 UTC, IIbey commented on modules/anniversaires.md
> +- Avec le deuxième bouton *(Rôles interdits)*, vous avez la possibilité de désactiver le fait qu'un membre récupèrera un rôle temporaire le jour de son anniversaire grâce à un rôle.
```suggestion
- Grâce au premier bouton *(Rôle)*, vous pouvez choisir un rôle temporaire qui mettra en avant le membre qui fêtera son anniversaire. Celui-ci conservera temporairement le rôle temporairement jusqu'à la fin de la journée.
- Avec le deuxième bouton *(Rôles interdits)*, vous pouvez désactiver la possibilité qu'un membre récupère le rôle temporaire le jour de son anniversaire grâce à un rôle interdit.

2023-04-20 23:35 UTC, kazotka commented on modules/anniversaires.md
> +- Pour conclure avec le sixième bouton *(Rôles interdits)*, vous bloquer l'annonce d'un anniversaire à tous les membres qui possède le rôle.
Merci beaucoup !

2023-04-20 23:35 UTC, kazotka commented on modules/anniversaires.md
> +- Avec le deuxième bouton *(Rôles interdits)*, vous avez la possibilité de désactiver le fait qu'un membre récupèrera un rôle temporaire le jour de son anniversaire grâce à un rôle.
Merci de l'aide !

2023-04-21 10:13 UTC, IIbey requested changes

2023-04-21 10:13 UTC, IIbey commented on modules/anniversaires.md
> +## Votre Anniversaire
```suggestion
## Votre anniversaire

2023-04-21 10:13 UTC, IIbey commented on modules/anniversaires.md
> +Grâce à l'option annonce, vous pouvez paramétrer l'envoi d'un message général à tous les membres lors du jour de lors du jour de leur anniversaire.
```suggestion
Grâce à l'option "Annonces", vous pouvez paramétrer l'envoi d'un message général à tous les membres lors du jour de leur anniversaire.

2023-04-21 10:13 UTC, IIbey commented on modules/anniversaires.md
> +- Avec l'aide du quatrième bouton *(Heure d'envoi)*, vous pouvez définir leur à laquelle le message d'annonce d'anniversaire sera envoyé dans le salon que vous aurez défini au préalable.
```suggestion
- Avec l'aide du quatrième bouton *(Heure d'envoi)*, vous pouvez définir l'heure à laquelle le message d'annonce d'anniversaire sera envoyé dans le salon que vous aurez défini au préalable.

2023-04-21 10:13 UTC, IIbey commented on modules/anniversaires.md
> +Avec l'option Rôle, vous pouvez gérer le fait d'un membre recevra un rôle exclusif uniquement le jour de son anniversaire.
```suggestion
Avec l'option "Rôle", vous pouvez gérer le fait d'un membre recevra un rôle exclusif uniquement le jour de son anniversaire.

2023-04-21 10:13 UTC, IIbey commented on modules/anniversaires.md
> +![Aperçu des options offerte avec le menu Cadeaux](../.gitbook/assets/birthday/birthday_config_gift.png)
```suggestion
![Aperçu des options offertes avec le menu "Cadeaux"](../.gitbook/assets/birthday/birthday_config_gift.png)

2023-04-21 10:13 UTC, IIbey commented on modules/anniversaires.md
> +En cliquant sur le premier bouton *(Crée)*, vous pouvez choisir entre les quatre options ci-dessous pour créer une récompense/cadeau à offrir à vos membres qui fêteront leur anniversaire *:*
```suggestion
En cliquant sur le premier bouton "Créer", vous pouvez choisir entre les quatre options ci-dessous pour créer une récompense ou un cadeau à offrir à vos membres qui fêteront leur anniversaire :

2023-04-21 10:13 UTC, IIbey commented on modules/anniversaires.md
> +niveau donc pour ce cadeau basé vous sur le fait qu'un membre reçoit par défaut 15 à 25 points d'expérience par message.
Le mieux est de diriger les utilisateurs vers la page des "niveaux" plutôt que de faire une nouvelle phrase explicative de ce genre :3

2023-04-21 10:13 UTC, IIbey commented on modules/anniversaires.md
> +- Avec le deuxième bouton du menu déroulant de l'option 'Crée', vous permet de donner de l'argent au membre qui fêtera son anniversaire.
```suggestion
- Avec le deuxième bouton du menu déroulant de l'option "Créer", vous permet de donner de l'argent au membre qui fêtera son anniversaire.

2023-04-21 10:13 UTC, IIbey commented on modules/anniversaires.md
> +- Troisième et finalement avec le bouton, vous pouvez réinitialiser l'entièreté du système de Cadeaux.
```suggestion
*Avec les deux boutons restant du menu des "Cadeaux", vous pouvez modifier et supprimer les paramètres enregistrés avec l'aide du premier bouton :*

- À l'aide du deuxième bouton, vous pouvez modifier les options préalablement enregistrées.
- Troisième et finalement avec le bouton, vous pouvez réinitialiser l'entièreté du système de "Cadeaux".

2023-04-21 10:24 UTC, Tellvex requested changes
Globalement, la structure est bonne malgré le nom du second titre.

Cela dit, je vois pas pourquoi tu as numéroté les boutons puisque leur nom suffit  à les identifier

2023-04-21 10:24 UTC, Tellvex commented on modules/anniversaires.md
> +*Vous pouvez accéder à différents paramètres de cette option en cliquant sur le bouton "Annonces" :*
Je suis pas fan de la phrase en italique et des guillemets. Je trouve beaucoup plus visuel le fait de mettre le nom des boutons en couleur.

```suggestion
Vous pouvez accéder à différents paramètres de cette option en cliquant sur le bouton <mark style="color:orange;">Annonces</mark> :

```

2023-04-21 10:24 UTC, Tellvex commented on modules/anniversaires.md
> +*Vous pouvez accéder à différents paramètres de cette option en cliquant sur le bouton "Cadeaux" :*
```suggestion
Vous pouvez accéder à différents paramètres de cette option en cliquant sur le bouton </mark style="color:orange;">Cadeaux</mark> :

```

2023-04-21 10:24 UTC, Tellvex commented on modules/anniversaires.md
> +- Avec le deuxième bouton *(Salon)*, vous pouvez choisir le salon dans lequel le bot enverra l'annonce d'anniversaire.
```suggestion
- Avec le bouton <mark style="color:orange;">Salon</mark>, vous pouvez choisir le salon dans lequel le bot enverra l'annonce d'anniversaire.

```

2023-04-21 10:24 UTC, Tellvex commented on modules/anniversaires.md
> +- En cliquant sur le premier bouton *(Système activer/désactiver)*, vous pouvez activé ou désactiver le système d'annonce d'anniversaire.
```suggestion
- En cliquant sur le bouton <mark style="color:orange;">Système activer/désactiver</mark>, vous pouvez activer ou désactiver le système d'annonce d'anniversaire.

```
Je suis pas fan de "numéroter" les boutons. Juste leur nom suffirait a les identifier

2023-04-21 10:24 UTC, Tellvex commented on modules/anniversaires.md
> +- Grâce au troisième bouton *(Message)*, vous pouvez paramétrer le message d'annonce.
```suggestion
- Grâce au bouton <mark style="color:orange;">Message</mark>, vous pouvez paramétrer le message d'annonce.

```

2023-04-21 10:24 UTC, Tellvex commented on modules/anniversaires.md
> +- Avec l'aide du quatrième bouton *(Heure d'envoi)*, vous pouvez définir leur à laquelle le message d'annonce d'anniversaire sera envoyé dans le salon que vous aurez défini au préalable.
```suggestion
- Avec l'aide du bouton <mark style="color:orange;">Heure d'envoi</mark>, vous pouvez définir leur à laquelle le message d'annonce d'anniversaire sera envoyé dans le salon que vous aurez défini au préalable. 

```

2023-04-21 10:24 UTC, Tellvex commented on modules/anniversaires.md
> +- Grâce à ce cinquième bouton *(Mention)*, vous pouvez décider de mentionner un rôle lors de l'annonce qui sera envoyer lorsque quelqu'un fêtera son anniversaire.
```suggestion
- Grâce au bouton <mark style="color:orange;">Mention</mark>, vous pouvez décider de mentionner un rôle lors de l'annonce qui sera envoyer lorsque quelqu'un fêtera son anniversaire.

```

2023-04-21 10:24 UTC, Tellvex commented on modules/anniversaires.md
> +- Pour conclure avec le sixième bouton *(Rôles interdits)*, vous bloquez l'annonce d'un anniversaire à tous les membres qui possède le rôle interdit.
```suggestion
- Pour finir, avec le bouton <mark style="color:orange;">Rôles interdits</mark>, vous bloquez l'annonce d'un anniversaire à tous les membres qui possède le rôle interdit. 

```

2023-04-21 10:24 UTC, Tellvex commented on modules/anniversaires.md
> +*Vous pouvez accéder à différents paramètres de cette option en cliquant sur le bouton "Rôle" :*
```suggestion
Vous pouvez accéder à différents paramètres de cette option en cliquant sur le bouton <mark style="color:orange;">Rôle</mark> :

```

2023-04-21 10:24 UTC, Tellvex commented on modules/anniversaires.md
> +- Grâce au premier bouton *(Rôle)*, vous pouvez choisir un rôle temporaire qui mettra en avant le membre qui fêtera son anniversaire. Celui-ci conservera temporairement le rôle jusqu'à la fin de la j
```suggestion
- Grâce au bouton <mark style="color:orange;">Rôle</mark>, vous pouvez choisir un rôle temporaire qui mettra en avant le membre qui fêtera son anniversaire. Celui-ci conservera temporairement le rôle jusqu'à la fin de la journée.

```

2023-04-21 10:24 UTC, Tellvex commented on modules/anniversaires.md
> +- Avec le deuxième bouton *(Rôles interdits)*, vous pouvez désactiver la possibilité qu'un membre récupère le rôle temporaire le jour de son anniversaire grâce à un rôle interdit.
```suggestion
- Avec le bouton <mark style="color:orange;">Rôles interdits</mark>, vous pouvez désactiver la possibilité qu'un membre récupère le rôle temporaire le jour de son anniversaire grâce à un rôle interdit.

```

2023-04-21 10:24 UTC, Tellvex commented on modules/anniversaires.md
> +En cliquant sur le premier bouton *(Crée)*, vous pouvez choisir entre les quatre options ci-dessous pour créer une récompense/cadeau à offrir à vos membres qui fêteront leur anniversaire *:*
```suggestion
En cliquant sur le bouton <mark style="color:orange;">Créer</mark>, vous pouvez choisir entre les quatre options ci-dessous pour créer une récompense/cadeau à offrir à vos membres qui fêteront leur anniversaire *:*

```

2023-04-21 12:15 UTC, IIbey commented on modules/anniversaires.md
> +## La configuration
"sur le serveur", c'est un peu trop pour moi.

2023-04-21 14:44 UTC, Tellvex approved these changes

2023-04-21 23:16 UTC, IIbey requested changes

2023-04-21 23:16 UTC, IIbey commented on modules/anniversaires.md
> +- Grâce à ce cinquième bouton <mark style="color:orange;">Mention</mark>, vous pouvez décider de mentionner un rôle lors de l'annonce qui sera envoyer lorsque quelqu'un fêtera son anniversaire.
```suggestion
- Grâce à ce cinquième bouton <mark style="color:orange;">Mention</mark>, vous pouvez décider de mentionner un rôle lors de l'annonce qui sera envoyée lorsque quelqu'un fêtera son anniversaire.

2023-04-21 23:16 UTC, IIbey commented on modules/anniversaires.md
> +Je vous conseille de vous diriger vers <mark style="color:blue;">[le page de niveaux](niveaux.md)</mark> pour en apprendre plus sur les niveaux et donc potentiellement mieux paramétrer cette fonction
```suggestion
Je vous conseille de vous diriger vers <mark style="color:blue;">[la page de niveaux](niveaux.md)</mark> pour en apprendre plus sur le système de niveaux et donc potentiellement mieux paramétrer cette fonctionnalité !

2023-04-21 23:16 UTC, IIbey commented on modules/anniversaires.md
> +- Grâce au troisième option <mark style="color:orange;">Objet</mark>, vous pouvez donner un objet d'inventaire à la personne qui fête son anniversaire.
```suggestion
- Avec la deuxième option du menu déroulant <mark style="color:orange;">Argent</mark>, vous permet de donner de l'argent au membre qui fêtera son anniversaire.
- Grâce à la troisième option <mark style="color:orange;">Objet</mark>, vous pouvez donner un objet d'inventaire à la personne qui fête son anniversaire.

2023-04-21 23:16 UTC, IIbey commented on modules/anniversaires.md
> +- La dernière option <mark style="color:orange;">Cadeaux personnalisé</mark>, vous permet d'envoyer un message privé à la personne qui fête son anniversaire, cette fonctionnalité est pratique si par
```suggestion
- La dernière option <mark style="color:orange;">Cadeaux personnalisés</mark>, vous permet d'envoyer un message privé à la personne qui fête son anniversaire, cette fonctionnalité est pratique si par exemple, vous souhaitez lui offrir un Nitro ou alors juste lui écrire un petit message.

2023-04-21 23:16 UTC, IIbey commented on modules/anniversaires.md
> +- Premièrement avec le bouton <mark style="color:orange;">Créer</mark>, vous pouvez accéder à deux options.
```suggestion
- Premièrement, avec le bouton <mark style="color:orange;">Créer</mark>, vous pouvez accéder à deux options.

2023-04-21 23:16 UTC, IIbey commented on modules/anniversaires.md
> +- À l'aide de l'option <mark style="color:orange;">Membres ayant un rôle</mark>, vous pouvez créer une annonce personnalisée lors de l'anniversaire de tous les membres qui possèderont le rôle.
```suggestion
- À l'aide de l'option <mark style="color:orange;">Membres ayant un rôle</mark>, vous pouvez créer une annonce personnalisée lors de l'anniversaire de tous les membres qui posséderont le rôle.

2023-04-21 23:16 UTC, IIbey commented on modules/anniversaires.md
> +- Avec le bouton <mark style="color:orange;">Supprimer</mark>, vous pouvez supprimer une annonce personnaliser que vous auriez créé au paravent.
```suggestion
- Avec le bouton <mark style="color:orange;">Supprimer</mark>, vous pouvez supprimer une annonce personnalisée que vous aurez créée auparavant.

2023-04-23 21:56 UTC, Hugo-broc requested changes
Ta PR m'a demandé un boulot monstre mais elle est revue ! 
Je vérifierai cela dans les prochains jours.
N'hésite pas si tu as des remarques ou interrogations sur ce que je te propose en réagissant en dessous des propositions.
Très bon boulot en tout cas ! Ce que j'apporte n'est que du détail qui est souvent la même chose, il ne faut pas s'inquiéter par la quantité. 😉

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +![Aperçu des variables diponible pour l'annonce d'anniversaire](../.gitbook/assets/birthday/birthday_config_message_edit.png)
Au lieu de la capture, je propose plutôt une liste déroulante.
Je ne contrôle pas parfaitement la mise en page de cette liste déroulante donc si tout se met à la suite, il faut doubler les sauts de ligne.
```suggestion
<details>

<summary>Variables disponibles</summary>
Membre :
`{​user}` ➜ Mention du membre
`{​user.id}` ➜ Identifiant du membre
`{​user.tag}` ➜ Tag du membre (Pseudo#0000)
`{​user.username}` ➜ Pseudo du membre
`{​user.nickname}` ➜ Surnom ou pseudo du membre

`{birthday}` ➜ Date d'anniversaire du membre *(uniquement si le système est activé)*

Serveur :
`{​server}` ou `{​server.name}` ➜ Nom du serveur
`{​server.id}` ➜ Identifiant du serveur
`{​server.membercount}` ➜ Nombre de membres sur le serveur

Salon  :
`{​channel}` ➜ Mentions du salon
`{​channel.id}` ➜ Identifiant du salon
`{​channel.name}` ➜ Nom du salon

Temps :
`{​date}` ➜ Date actuelle (JJ/MM/AAAA)
`{​time}` ➜ Heure actuelle (HH:MM)
`{​timestamp}` ➜ Timestamp actuel en secondes
</details>

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Avec l'aide du quatrième bouton <mark style="color:orange;">Heure d'envoi</mark>, vous pouvez définir l'heure à laquelle le message d'annonce d'anniversaire sera envoyé dans le salon que vous aurez
```suggestion
- Avec l'aide du quatrième bouton "Heure d'envoi", vous pouvez définir l'heure à laquelle le message d'annonce d'anniversaire sera envoyé dans le salon que vous aurez défini au préalable. 

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Grâce à ce cinquième bouton <mark style="color:orange;">Mention</mark>, vous pouvez décider de mentionner un rôle lors de l'annonce qui sera envoyer lorsque quelqu'un fêtera son anniversaire.
```suggestion
- Grâce à ce cinquième bouton "Mention", vous pouvez décider de mentionner un rôle lors de l'annonce qui sera envoyée lorsque quelqu'un fêtera son anniversaire.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Pour finir, avec le bouton <mark style="color:orange;">Rôles interdits</mark>, vous bloquez l'annonce d'un anniversaire à tous les membres qui possède le rôle interdit.
```suggestion
- Pour finir, avec le bouton "Rôles interdits", vous pouvez bloquer l'annonce d'un anniversaire à tous les membres qui possède un certain rôle. 

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +Vous pouvez accéder à différents paramètres de cette option en cliquant sur le bouton <mark style="color:orange;">Rôle</mark> :
Pas nécessaire, on dit déjà au-dessus que la configuration se fait via les boutons.
```suggestion

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +Avec l'option <mark style="color:orange;">Rôle</mark>, vous pouvez gérer le fait d'un membre recevra un rôle exclusif uniquement le jour de son anniversaire.
```suggestion
Avec l'option "Rôle", vous pouvez gérer le fait qu'un membre recevra un rôle exclusif uniquement le jour de son anniversaire.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Grâce au bouton <mark style="color:orange;">Rôle</mark>, vous pouvez choisir un rôle temporaire qui mettra en avant le membre qui fêtera son anniversaire. Celui-ci conservera temporairement le rôle
```suggestion
- Grâce au bouton "Rôle", vous pouvez choisir un rôle temporaire qui mettra en avant le membre qui fêtera son anniversaire. Celui-ci conservera temporairement le rôle jusqu'à la fin de la journée.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Avec le bouton <mark style="color:orange;">Rôles interdits</mark>, vous pouvez désactiver la possibilité qu'un membre récupère le rôle temporaire le jour de son anniversaire grâce à un rôle interdi
```suggestion
- Avec le bouton "Rôles interdits", vous pouvez désactiver la possibilité qu'un membre récupère le rôle temporaire le jour de son anniversaire grâce à un rôle interdit.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +## Cadeaux
```suggestion
## "<mark style="color:blue;">Cadeaux</mark>"

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +## Rôle
```suggestion
## "<mark style="color:blue;">Rôle</mark>"

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +## Annonces
```suggestion
## "<mark style="color:blue;">Annonces</mark>"

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +Vous pouvez accéder à différents paramètres de cette option en cliquant sur le bouton <mark style="color:orange;">Cadeaux</mark> :
Pas nécessaire, on dit déjà au-dessus que la configuration se fait via les boutons.
```suggestion
```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +Proposer une magnifique surprise à vos membres le jour de leur anniversaire. Ils seront sûrement ravis par votre générosité !
```suggestion
Proposez une magnifique surprise à vos membres le jour de leur anniversaire ! Ils seront sûrement ravis par votre générosité !

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +En cliquant sur le bouton <mark style="color:orange;">Créer</mark>, vous pouvez choisir entre les quatre options ci-dessous pour créer une récompense ou un cadeau à offrir à vos membres qui fêteront
```suggestion
En cliquant sur le bouton "<mark style="color:blue;">Créer</mark>", vous pouvez choisir entre les quatre options ci-dessous pour créer une récompense ou un cadeau à offrir à vos membres qui fêteront leur anniversaire :

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +*Avec les deux boutons restant du menu des <mark style="color:orange;">Cadeaux</mark>, vous pouvez modifier et supprimer les paramètres enregistrés avec l'aide du premier bouton :*
```suggestion
*Avec les deux boutons restants du menu des cadeaux, vous pouvez modifier et supprimer les récompenses crées avec l'aide du premier bouton :*

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Premièrement avec la première option du menu déroulant <mark style="color:orange;">Expériance</mark>, vous pouvez donner de l'expérance de niveau en cadeau à un membre.
```suggestion
- Avec la première option du menu déroulant, "Rôles", vous pouvez donner un rôle au membre qui fêtera son anniversaire.
- Avec la deuxième option du menu déroulant, "Expérience", vous pouvez donner de l'expérience de niveau au membre qui fêtera son anniversaire.
```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Avec la deuxième option du menu déroulant <mark style="color:orange;">Argent</mark>, vous permet de donner de l'argent au membre qui fêtera son anniversaire.
```suggestion
- Avec la troisième option du menu déroulant, "Argent", vous pouvez donner de l'argent au membre qui fêtera son anniversaire.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Grâce à la troisième option <mark style="color:orange;">Objet</mark>, vous pouvez donner un objet d'inventaire à la personne qui fête son anniversaire.
```suggestion
- Grâce à la quatrième option du menu déroulant, "Objet", vous pouvez donner un objet d'inventaire au membre qui fêtera son anniversaire.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- À l'aide du deuxième bouton <mark style="color:orange;">Modifier</mark>, vous pouvez modifier les options préalablement enregistrées.
```suggestion
- À l'aide du deuxième bouton "<mark style="color:blue;">Modifier</mark>", vous pouvez modifier les récompenses préalablement crées.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Troisième et finalement avec le bouton <mark style="color:orange;">Suprimer</mark>, vous pouvez réinitialiser l'entièreté du système de <mark style="color:orange;">Cadeaux</mark>.
```suggestion
- Le troisième bouton, "<mark style="color:blue;">Supprimer</mark>", vous permet de supprimer une récompense préalablement crée.
- Le quatrième bouton, "<mark style="color:red;">Réinitialiser</mark>", vous permet de réinitialiser l'entièreté du système de cadeaux.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +## Annonces personnalisées *(Avantage premium 💎)*
Mise en page générale de la documentation.
```suggestion
## Annonces personnalisées ***(✨ premium)***

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Premièrement, avec le bouton <mark style="color:orange;">Créer</mark>, vous pouvez accéder à deux options.
```suggestion
- Premièrement, avec le bouton "<mark style="color:blue;">Créer</mark>", vous pouvez accéder à deux options :

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Avec l'option <mark style="color:orange;">Un seul membre</mark>, vous pouvez créer une annonce personnalisée lors de l'anniversaire de ce membre uniquement.
```suggestion
- Avec l'option "<mark style="color:blue;">Un seul membre</mark>", vous pouvez créer une annonce personnalisée lors de l'anniversaire de ce membre uniquement.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- À l'aide de l'option <mark style="color:orange;">Membres ayant un rôle</mark>, vous pouvez créer une annonce personnalisée lors de l'anniversaire de tous les membres qui posséderont le rôle.
```suggestion
- Avec l'option "<mark style="color:blue;">Membres ayant un rôle</mark>", vous pouvez créer une annonce personnalisée lors de l'anniversaire de tous les membres qui posséderont le rôle.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +*Avec les deux boutons restant du menu des <mark style="color:orange;">Annonces personnalisées</mark>, vous pouvez supprimer et réinitialiser les paramètres enregistrés avec l'aide du premier bouton
```suggestion
*Avec les deux boutons restants du menu des annonces personnalisées, vous pouvez supprimer et réinitialiser les paramètres enregistrés avec l'aide du premier bouton :*

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Avec le bouton <mark style="color:orange;">Supprimer</mark>, vous pouvez supprimer une annonce personnalisée que vous aurez créée auparavant.
```suggestion
- Avec le bouton "<mark style="color:blue;">Supprimer</mark>", vous pouvez supprimer une annonce personnalisée que vous aurez créée auparavant.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Grâce au bouton <mark style="color:orange;">Réinitialiser</mark>, vous pouvez réinitialiser l'entièreté du système d'<mark style="color:orange;">Annonces personnalisées.</mark>
```suggestion
- Grâce au bouton "<mark style="color:red;">Réinitialiser</mark>é, vous pouvez réinitialiser l'entièreté du système d'annonces personnalisées.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +Grâce au <mark style="color:blue;">[panel de draftbot](https://www.draftbot.fr/dashboard/)</mark> vous pouvez paramétrer plusieurs options du système d'anniversaire.
```suggestion
<mark style="color:blue;">[Accéder au panel de **DraftBot**](https://www.draftbot.fr/dashboard/)</mark>

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +*Avec les boutons présentés ci-dessous, vous pouvez :*
```suggestion
Retrouvez ci-dessous les fonctionnalités configurables sur le panel.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +Comme vous le voyez sous vos yeux, vous avez accès aux fonctionnalités suivantes : <mark style="color:orange;">Message d'annonce</mark>, <mark style="color:orange;">Rôle temporaire</mark>, <mark styl
```suggestion
```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +Premièrement, par défaut cette option est désactivée, vous devrez donc l'activer dans la section anniversaire du <mark style="color:blue;">[panel de Draftbot](https://www.draftbot.fr/dashboard/user)<
```suggestion
{% hint style="info" %}
Par défaut cette option est désactivée. Vous devrez donc l'activer dans la catégorie "Anniversaire".

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +![Aperçu des variables diponible pour l'annonce d'anniversaire](../.gitbook/assets/birthday/birthday_config_message_edit.png)
Au lieu de la capture, je propose plutôt une liste déroulante.
Je ne contrôle pas parfaitement la mise en page de cette liste déroulante donc si tout se met à la suite, il faut doubler les sauts de ligne.
```suggestion
<details>
<summary>Variables disponibles</summary>
Membre :
`{​user}` ➜ Mention du membre
`{​user.id}` ➜ Identifiant du membre
`{​user.tag}` ➜ Tag du membre (Pseudo#0000)
`{​user.username}` ➜ Pseudo du membre
`{​user.nickname}` ➜ Surnom ou pseudo du membre
`{birthday}` ➜ Date d'anniversaire du membre *(uniquement si le système est activé)*
Serveur :
`{​server}` ou `{​server.name}` ➜ Nom du serveur
`{​server.id}` ➜ Identifiant du serveur
`{​server.membercount}` ➜ Nombre de membres sur le serveur
Salon  :
`{​channel}` ➜ Mentions du salon
`{​channel.id}` ➜ Identifiant du salon
`{​channel.name}` ➜ Nom du salon
Temps :
`{​date}` ➜ Date actuelle (JJ/MM/AAAA)
`{​time}` ➜ Heure actuelle (HH:MM)
`{​timestamp}` ➜ Timestamp actuel en secondes
</details>
```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +![Option de message d'annonce d'anniversaire](../.gitbook/assets/birthday/birthday_annoncement_message.png)
```suggestion
![Option de message d'annonce d'anniversaire](../.gitbook/assets/birthday/birthday_annoncement_message.png)
{% endhint %}
```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +Lorsque l'option est activée, vous avez accès à 5 options de personnalisation ainsi que d'une prévisualisation. Dans les points ci-dessous se trouve des descriptions des options personnalisables.
```suggestion
Lorsque l'option est activée, vous avez accès à 5 options de personnalisation ainsi qu'une prévisualisation. Dans les points ci-dessous se trouve des descriptions des options personnalisables.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Avec la première option <mark style="color:orange;">Salon</mark>, vous pouvez choisir le salon dans lequel le bot enverra l'annonce d'anniversaire.
```suggestion
- Avec la première option `SALON`, vous pouvez choisir le salon dans lequel le bot enverra l'annonce d'anniversaire.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Avec l'aide de la deuxième option <mark style="color:orange;">Heure d'envoi</mark>, vous pouvez définir l'heure à laquelle le message d'annonce d'anniversaire sera envoyé dans le salon que vous aur
```suggestion
- Avec l'aide de la deuxième option `HEURE D'ENVOI`, vous pouvez définir l'heure à laquelle le message d'annonce d'anniversaire sera envoyé dans le salon que vous aurez défini au préalable. 

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Grâce à la troisième option <mark style="color:orange;">Mention</mark>, vous pouvez décider de mentionner un rôle lors de l'annonce qui sera envoyer lorsque quelqu'un fêtera son anniversaire.
```suggestion
- Grâce à la troisième option `MENTION`, vous pouvez décider de mentionner un rôle lors de l'annonce qui sera envoyer lorsque quelqu'un fêtera son anniversaire.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Pour finir, avec le bouton <mark style="color:orange;">Rôles interdits/autorisés</mark>, vous bloquez/autorisez l'annonce d'un anniversaire à tous les membres qui possède le rôle interdit/autorisé.
```suggestion
- Pour finir, avec le bouton `RÔLES AUTORISES / INTERDITS`, vous autorisez / bloquez l'annonce d'un anniversaire à tous les membres qui possède le rôle autorisé / interdit.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +N'oubliez pas que vous pouvez cliquer sur les boutons interdits/autorisés pour bien définir la fonctionnalité que vous souhaitez utiliser.
```suggestion
N'oubliez pas que vous pouvez cliquer sur les textes `AUTORISES / INTERDITS` pour bien définir la fonctionnalité que vous souhaitez utiliser.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +![Aperçu des boutons interdits/autorisés](../.gitbook/assets/birthday/birthday_config_role_access.png)
```suggestion
![Aperçu des boutons interdits/autorisés](../.gitbook/assets/birthday/birthday_config_role_access.png)
```suggestionautorisés
![Aperçu des boutons autorisés / interdits](../.gitbook/assets/birthday/birthday_config_role_access.png)

```
```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +- Grâce à la dernière option <mark style="color:orange;">Message</mark>, vous pouvez paramétrer le message d'annonce.
```suggestion
- Grâce à la dernière option `MESSAGE`, vous pouvez paramétrer le message d'annonce.

```

2023-04-23 21:56 UTC, Hugo-broc commented on modules/anniversaires.md
> +Lorsque vous voulez paramètre le message d'anniversaire, vous pouvez choisir entre prendre le message par défaut et un message personnalisé. Si vous prenez la deuxième option, n'oubliez pas d'utilise
```suggestion
Lorsque vous voulez paramètrer le message d'anniversaire, vous pouvez choisir entre prendre le message par défaut et un message personnalisé. Si vous prenez la deuxième option, n'oubliez pas d'utiliser les variables ci-dessous et le markdown de Discord.

```

2023-04-24 01:26 UTC, kazotka commented on modules/anniversaires.md
> +![Aperçu des boutons interdits/autorisés](../.gitbook/assets/birthday/birthday_config_role_access.png)
Je comprend pas le changement ici ?

2023-04-24 01:30 UTC, kazotka commented on modules/anniversaires.md
> +- En cliquant sur le bouton <mark style="color:orange;">Système activer/désactiver</mark>, vous pouvez activer ou désactiver le système d'annonce d'anniversaire.
J'avais fait cela à la base, mais Tellvex ma dit de faire autrement

2023-04-24 01:31 UTC, kazotka commented on modules/anniversaires.md
> +- Avec le bouton <mark style="color:orange;">Salon</mark>, vous pouvez choisir le salon dans lequel le bot enverra l'annonce d'anniversaire.
J'avais fait cela à la base, mais Tellvex ma dit de faire autrement

2023-04-24 01:33 UTC, kazotka commented
> Ta PR m'a demandé un boulot monstre mais elle est revue ! Je vérifierai cela dans les prochains jours. N'hésite pas si tu as des remarques ou interrogations sur ce que je te propose en réagissant en dessous des propositions. Très bon boulot en tout cas ! Ce que j'apporte n'est que du détail qui est souvent la même chose, il ne faut pas s'inquiéter par la quantité. 😉

À propos des boutons, si je dois les mentions entre '' ou les mettre de couleur orange, j'aimerais que vous vous mettiez d'accord avec tellvex car j'aimerais ne pas recommencer la page 100 fois. Donc pour l'instant je stop les changements !

2023-04-24 14:27 UTC, DraftProducts commented on modules/anniversaires.md
> +![Aperçu des boutons interdits/autorisés](../.gitbook/assets/birthday/birthday_config_role_access.png)
Il y a eu une erreur je pense

2023-04-24 14:28 UTC, DraftProducts commented on modules/anniversaires.md
> +![Aperçu des boutons interdits/autorisés](../.gitbook/assets/birthday/birthday_config_role_access.png)
J'ai edit sa proposition.

2023-04-25 00:13 UTC, kazotka commented on modules/anniversaires.md
> +![Aperçu des boutons interdits/autorisés](../.gitbook/assets/birthday/birthday_config_role_access.png)
ok

2023-04-26 14:22 UTC, bariboo requested changes

2023-04-26 14:22 UTC, bariboo commented on modules/anniversaires.md
> +Lorsque vous voulez paramètre le message d'anniversaire, vous pouvez choisir entre prendre le message par défaut et un message personnalisé. Si vous prenez la deuxième option, n'oubliez pas d'utilise
```suggestion
Lorsque vous voulez paramètrer le message d'anniversaire, vous pouvez choisir entre le message par défaut et un message personnalisé. Si vous choisissez la deuxième option, ayez en tête qu'il est possible d'utiliser les variables ci-dessous et le markdown de Discord.

```

2023-04-26 14:22 UTC, bariboo commented on modules/anniversaires.md
> +- Grâce à ce cinquième bouton "Mention", vous pouvez décider de mentionner un rôle lors de l'annonce qui sera envoyer lorsque quelqu'un fêtera son anniversaire.
```suggestion
- Grâce à ce cinquième bouton "Mention", vous pouvez décider de mentionner un rôle dans le message d'annonce.

```

2023-04-26 14:22 UTC, bariboo commented on modules/anniversaires.md
> +- Pour finir, avec le bouton "Rôles interdits", vous bloquez l'annonce d'un anniversaire à tous les membres qui possède le rôle interdit.
```suggestion
- Pour finir, avec le bouton "Rôles interdits", vous pouvez interdire l'annonce d'un anniversaire à tous les membres qui possèderont ce rôle. 

```

2023-04-26 14:22 UTC, bariboo commented on modules/anniversaires.md
> +Avec l'option <mark style="color:blue;">"Rôle"</mark>, vous pouvez gérer le fait d'un membre recevra un rôle exclusif uniquement le jour de son anniversaire.
```suggestion
Avec l'option <mark style="color:blue;">"Rôle"</mark>, vous pouvez décider de donner un rôle de votre choix aux membres le jour de leurs anniversaire.

```

2023-04-26 14:22 UTC, bariboo commented on modules/anniversaires.md
> +Vous pouvez accéder à différents paramètres de cette option en cliquant sur le bouton <mark style="color:blue;">"Cadeaux"</mark> :
```suggestion
Vous pouvez accéder aux différents paramètres de cette option en cliquant sur le bouton <mark style="color:blue;">"Cadeaux"</mark> :

```

2023-04-26 14:22 UTC, bariboo commented on modules/anniversaires.md
> +![Aperçu des options offertes avec le menu "Cadeaux"](../.gitbook/assets/birthday/birthday_config_gift.png)
```suggestion
![Aperçu des options de configuration via le menu "Cadeaux"](../.gitbook/assets/birthday/birthday_config_gift.png)

```

2023-04-26 14:22 UTC, bariboo commented on modules/anniversaires.md
> +{% endhint %}
```suggestion
- Premièrement avec la première option du menu déroulant "Expérience", vous pouvez donner de l'[expérience](https://docs.draftbot.fr/modules/niveaux) en cadeau à un membre.

```

2023-04-26 14:22 UTC, bariboo commented on modules/anniversaires.md
> +- Avec la deuxième option du menu déroulant "Argent", vous permet de donner de l'argent au membre qui fêtera son anniversaire.
```suggestion
- La deuxième option du menu déroulant "Argent", vous permet de donner de l'[argent](https://docs.draftbot.fr/modules/economie) au membre qui fêtera son anniversaire.

```

2023-04-26 14:22 UTC, bariboo commented on modules/anniversaires.md
> +- Grâce à la troisième option "Objet", vous pouvez donner un objet d'inventaire à la personne qui fête son anniversaire.
```suggestion
- Grâce à la troisième option "Objet", vous pouvez donner un [objet d'inventaire](https://docs.draftbot.fr/modules/economie#objets-dinventaire) à la personne qui fête son anniversaire. 

```

2023-04-26 14:22 UTC, bariboo commented on modules/anniversaires.md
> +- La dernière option "Cadeaux personnalisés", vous permet d'envoyer un message privé à la personne qui fête son anniversaire, cette fonctionnalité est pratique si par exemple, vous souhaitez lui offr
```suggestion
- La dernière option "Cadeaux personnalisés", vous permet d'envoyer un message privé à la personne qui fête son anniversaire, cette fonctionnalité est pratique si par exemple, vous souhaitez lui offrir un Nitro ou alors juste lui écrire un petit message.

```

2023-04-26 14:22 UTC, bariboo commented on modules/anniversaires.md
> +- À l'aide du deuxième bouton "Modifier", vous pouvez modifier les options préalablement enregistrées.
```suggestion
- À l'aide du deuxième bouton "Modifier", vous pouvez modifier les options préalablement configurées.

```

2023-04-26 14:22 UTC, bariboo commented on modules/anniversaires.md
> +![Aperçu des options du menu des annnonces personnalisées](../.gitbook/assets/birthday/birthday_config_special_annoucement.png)
```suggestion
![Aperçu des options du menu de configuration des annonces personnalisées](../.gitbook/assets/birthday/birthday_config_special_annoucement.png)

```

2023-04-26 14:22 UTC, bariboo commented on modules/anniversaires.md
> +- Premièrement, avec le bouton "Créer", vous pouvez accéder à deux options.
```suggestion
- Premièrement, avec le bouton "Créer", vous pouvez accéder à deux options :

```

2023-04-29 08:28 UTC, ErwanGit requested changes

2023-04-29 08:28 UTC, ErwanGit commented on modules/anniversaires.md
> +- En cliquant sur le bouton "Système activer/désactiver", vous pouvez activer ou désactiver le système d'annonce d'anniversaire.
```suggestion
- En cliquant sur le bouton "Système activé/désactivé", vous pouvez activer ou désactiver le système d'annonce d'anniversaire.

```

2023-05-04 09:42 UTC, IIbey submitted a review, later dismissed

2023-05-04 09:42 UTC, IIbey commented on modules/anniversaires.md
> +- Grâce à la troisième option "Mention", vous pouvez décider de mentionner un rôle lors de l'annonce qui sera envoyer lorsque quelqu'un fêtera son anniversaire.
```suggestion
- Grâce à la troisième option "Mention", vous pouvez décider de mentionner un rôle dans le message d'annonce.

2023-05-04 09:42 UTC, IIbey commented on modules/anniversaires.md
> +{% endhint %}
Premièrement & première, un effet de répétition pas top top.

```suggestion
- La première option du menu déroulant "Expérience", vous pouvez donner de l'[expérience](https://docs.draftbot.fr/modules/niveaux) en cadeau à un membre.

2023-05-04 09:42 UTC, IIbey commented on modules/anniversaires.md
> +- Troisième et finalement avec le bouton "Suprimer", vous pouvez réinitialiser l'entièreté du système de "Cadeaux".
```suggestion
- Troisième et finalement avec le bouton "Supprimer", vous pouvez réinitialiser l'entièreté du système de "Cadeaux".

2023-05-04 09:42 UTC, IIbey commented on modules/anniversaires.md
> +Par défaut cette option est désactivée. Vous devrez donc l'activer dans la catégorie "Anniversaire".
```suggestion
Par défaut, cette option est désactivée. Vous devrez donc l'activer dans la catégorie "Anniversaire".

2023-05-04 09:42 UTC, IIbey commented on modules/anniversaires.md
> +Lorsque l'option est activée, vous avez accès à 5 options de personnalisation ainsi que d'une prévisualisation. Dans les points ci-dessous se trouvent des descriptions concernant les options personna
```suggestion
Lorsque l'option est activée, vous avez accès à 5 options de personnalisation ainsi que d'une prévisualisation. Dans les points, ci-dessous se trouvent des descriptions concernant les options personnalisables.

2023-05-04 09:42 UTC, IIbey commented on modules/anniversaires.md
> +- Pour finir, avec le bouton "Rôles autorisés / interdits", vous autorisez / bloquez l'annonce d'un anniversaire à tous les membres qui possède le rôle autorisé / interdit.
```suggestion
- Pour finir, avec le bouton "Rôles autorisés/interdits", vous autorisez/bloquez l'annonce d'un anniversaire à tous les membres qui possède le rôle autorisé/interdit.

2023-05-04 09:42 UTC, IIbey commented on modules/anniversaires.md
> +- Avec le bouton "Rôles autorisés/interdits", vous pouvez activer/désactiver la possibilité qu'un membre récupère le rôle temporaire le jour de son anniversaire grâce à un rôle autorisés/interdit.
```suggestion
- Avec le bouton "Rôles autorisés/interdits", vous pouvez activer/désactiver la possibilité qu'un membre récupère le rôle temporaire le jour de son anniversaire grâce à un rôle autorisé/interdit.

2023-05-21 02:25 UTC, kazotka commented
La version "anniversaire (45)" est la version presque finale de la page. Il reste vos correctifs à apporter et l'ajustement des Assets à faire. Merci de votre soutien et de votre aide pour ceci !

2023-05-21 16:37 UTC, DraftProducts approved these changes

2023-05-28 14:31 UTC, ErwanGit requested changes

2023-05-28 14:31 UTC, ErwanGit commented on modules/anniversaires.md
> +- 4 et plus : 1 an
```suggestion
- 4ème et plus : 1 an

```

2023-05-28 14:31 UTC, ErwanGit commented on modules/anniversaires.md
> +Grâce à la commande <mark style="color:orange;">/config \[système:anniversaires]</mark> vous pouvez paramétrer plusieurs options du système d'anniversaire.
```suggestion
Grâce à la commande <mark style="color:orange;">/config \[système:Anniversaires]</mark> vous pouvez paramétrer plusieurs options du système d'anniversaire.

```

2023-05-28 14:31 UTC, ErwanGit commented on modules/anniversaires.md
> +## <mark style="color:blue;">"Annonces"</mark>
Je ne pense pas que les guillemets sont nécessaires dans ce cas

2023-05-28 14:31 UTC, ErwanGit commented on modules/anniversaires.md
> +## <mark style="color:blue;">"Rôle"</mark>
Je ne pense pas que les guillemets sont nécessaires dans ce cas

2023-05-28 14:31 UTC, ErwanGit commented on modules/anniversaires.md
> +## <mark style="color:blue;">"Cadeaux"</mark>
Je ne pense pas que les guillemets sont nécessaires dans ce cas

2023-05-28 14:31 UTC, ErwanGit commented on modules/anniversaires.md
> +## <mark style="color:blue;">"Annonces personnalisées *(Avantage premium 💎)*"</mark>
Je ne pense pas que les guillemets sont nécessaires dans ce cas

2023-05-28 14:31 UTC, ErwanGit commented on modules/anniversaires.md
> +## <mark style="color:blue;">"Message d'annonce"</mark>
Je ne pense pas que les guillemets sont nécessaires dans ce cas

2023-05-28 14:31 UTC, ErwanGit commented on modules/anniversaires.md
> +## <mark style="color:blue;">"Rôle temporaire"</mark>
Je ne pense pas que les guillemets sont nécessaires dans ce cas

2023-05-28 14:31 UTC, ErwanGit commented on modules/anniversaires.md
> +## <mark style="color:blue;">"Cadeaux d'anniversaire"</mark>
Je ne pense pas que les guillemets sont nécessaires dans ce cas

2023-05-28 14:31 UTC, ErwanGit commented on modules/anniversaires.md
> +## <mark style="color:blue;">"Annonces personnalisées *(Avantage premium 💎)*"</mark>
Je ne pense pas que les guillemets sont nécessaires dans ce cas

2023-05-28 14:31 UTC, ErwanGit commented on modules/anniversaires.md
> +Lorsque vous voulez paramètrer le message d'anniversaire, vous pouvez choisir entre prendre le message par défaut et un message personnalisé. Si vous prenez la deuxième option, n'oubliez pas d'utilis
Pas fan du "n'oubliez pas", c'est pas forcément obligatoire

2023-05-28 14:31 UTC, ErwanGit commented on modules/anniversaires.md
> +Je vous conseille de vous diriger vers <mark style="color:blue;">[la page de niveaux](niveaux.md)</mark> pour en apprendre plus sur le système de niveaux et donc potentiellement mieux paramétrer cett
Modifié la personne utilisée, on ne sait pas qui est "Je"

2023-05-28 14:31 UTC, ErwanGit commented on modules/anniversaires.md
> +## <mark style="color:blue;">"Annonces personnalisées *(Avantage premium 💎)*"</mark>
Sur le bot avant l'émoji personnalisé, c'était ✨ qui était utilisé pour les avantages premiums
```suggestion
## <mark style="color:blue;">"Annonces personnalisées *(Avantage premium ✨)*"</mark>
```

2023-05-28 17:00 UTC, bariboo requested changes

2023-05-28 17:04 UTC, bariboo commented
Hello !

Pour rappel, je t'avais déjà fait une review plus haut et il y en a 10 que tu n'as pas corrigé !

2023-05-30 18:52 UTC, ErwanGit requested changes

2023-05-30 18:52 UTC, ErwanGit commented on modules/anniversaires.md
> +- Grâce à la troisième option "Objet", vous pouvez donner un [objet d'inventaire](https://docs.draftbot.fr/modules/economie#objets-dinventaire) à la personne qui fête son anniversaire.
Les hyperlinks sont quasiment invisible sur la documentation, peut-être les rendre plus visible ?

2023-05-30 18:52 UTC, ErwanGit commented on modules/anniversaires.md
> +![Option de message d'annonce d'anniversaire](../.gitbook/assets/birthday/birthday_annoncement_message.png)
L'image n'est pas assez lisible

2023-05-30 18:52 UTC, ErwanGit commented on modules/anniversaires.md
> +Lorsque l'option est activée, vous avez accès à 5 options de personnalisation ainsi que d'une prévisualisation. Dans les points ci-dessous, se trouvent des descriptions concernant les options personn
Pas hyper pour de dire "vous avez accès à 5 options de personnalisation", car si on rajoute des fonctionnalités, cela sera 100% faux

2023-05-30 18:52 UTC, ErwanGit commented on modules/anniversaires.md
> +- Pour finir, avec le bouton "Rôles autorisés/interdits", vous autorisez/bloquez l'annonce d'un anniversaire à tous les membres qui possède le rôle autorisé/interdit.
Il peut y avoir plusieurs rôle autorisés interdits
```suggestion
- Pour finir, avec le bouton "Rôles autorisés/interdits", vous autorisez/bloquez l'annonce d'un anniversaire à tous les membres qui possède au moins un des rôles autorisés ou interdits.
```

2023-05-30 18:52 UTC, ErwanGit commented on modules/anniversaires.md
> +<details>
Reprendre ce qui avait été mis pour la partie /config

2023-05-30 18:52 UTC, ErwanGit commented on modules/anniversaires.md
> +- Premièrement, grâce à l'option "Membre ou rôle" vous pouvez paramétrer une annonce selon si un ou des membres ont un rôle. Ou bien, individuellement avec seulement la mention du membre.
```suggestion
- Premièrement, grâce à l'option "Membre ou rôle", vous pouvez paramétrer une annonce selon si un ou des membres ont un rôle. Ou bien, individuellement avec seulement la mention du membre.

```

2023-05-30 18:52 UTC, ErwanGit commented on modules/anniversaires.md
> +- Troisièmement et finalement, vous pouvez créer un message avec l'outil de création de message ou bien d'Embed de Draftbot.
```suggestion
- Troisièmement et finalement, vous pouvez créer un message avec l'outil de création de message ou bien d'Embed de DraftBot.

```

2023-05-30 18:52 UTC, ErwanGit commented on modules/anniversaires.md
> +- Troisièmement et finalement, vous pouvez créer un message avec l'outil de création de message ou bien d'Embed de Draftbot.
Je suis pas 100% convaincu par le "Troisièmement et finalement" 🤔

2023-05-30 18:52 UTC, ErwanGit commented on modules/anniversaires.md
> +Attention, pour changer votre date de naissance, il y a un cooldown progressif *(il augmente à chaque changement)*.
Cooldown est ok mais certains membres ne peuvent pas comprendre le terme
```suggestion
Attention, pour changer votre date de naissance, il y a un délai d'attente progressif *(il augmente à chaque changement)*.

```

2023-05-30 21:40 UTC, kazotka commented on modules/anniversaires.md
> +![Option de message d'annonce d'anniversaire](../.gitbook/assets/birthday/birthday_annoncement_message.png)
Malheureusement, c'est à cause du hint, je ne peux pas vraiment le changer, mais on peut toujours cliquer dessus pour zoomer. Je te laisse la décision de laissé ou supprimé.

2023-05-30 21:58 UTC, DraftProducts approved these changes

2023-05-30 21:58 UTC, DraftProducts commented on modules/anniversaires.md
> +{% endhint %}
Information non pertinente, tous les modules sont désactivés par défaut.

2023-05-30 21:58 UTC, DraftProducts commented on .gitbook/assets/birthday/birthday_annoncement_message.png
Tu peux donc supprimer cette image

2023-06-04 21:37 UTC, Kebintok commented
0.1.0.0.0.1.1.0.1.0

2023-06-09 16:50 UTC, bariboo reviewed
Dernière petites modifications !

2023-06-09 16:50 UTC, bariboo commented on modules/anniversaires.md
> +Lorsque vous voulez paramètrer le message d'anniversaire, vous pouvez choisir entre prendre le message par défaut et un message personnalisé. Si vous prenez la deuxième option, vous pouvez utiliser l
```suggestion
Lorsque vous voulez paramétrer le message d'anniversaire, vous pouvez choisir entre prendre le message par défaut et un message personnalisé. Si vous prenez la deuxième option, vous pouvez utiliser les variables ci-dessous et le markdown de Discord.

```

2023-06-11 10:10 UTC, IIbey requested changes

2023-06-11 10:10 UTC, IIbey commented on modules/anniversaires.md
> +- Pour finir, avec le bouton "Rôles interdits", vous pouvez interdire l'annonce d'un anniversaire à tous les membres qui possèderont ce rôle.
```suggestion
- Pour finir, avec le bouton "Rôles interdits", vous pouvez interdire l'annonce d'un anniversaire à tous les membres qui posséderont ce rôle.

2023-06-11 10:10 UTC, IIbey commented on modules/anniversaires.md
> +- Avec le bouton "Rôles autorisés/interdits", vous pouvez activer/désactiver la possibilité qu'un membre récupère le rôle temporaire le jour de son anniversaire grâce à un rôle autorisés/interdit.
```suggestion
- Avec le bouton "Rôles autorisés/interdits", vous pouvez activer/désactiver la possibilité qu'un membre récupère le rôle temporaire le jour de son anniversaire grâce à un rôle autorisé/interdit.

2023-06-11 10:10 UTC, IIbey commented on modules/anniversaires.md
> +Grâce au <mark style="color:blue;">[panel de Draftbot](https://www.draftbot.fr/dashboard/)</mark> vous pouvez paramétrer plusieurs options du système d'anniversaire.
```suggestion
Grâce au <mark style="color:blue;">[panel de Draftbot](https://www.draftbot.fr/dashboard/)</mark>, vous pouvez paramétrer plusieurs options du système d'anniversaire.

2023-06-12 07:03 UTC, IIbey approved these changes

2023-06-13 21:05 UTC, ErwanGit approved these changes

2023-06-17 09:07 UTC, bariboo requested changes
Je crois qu'après ça on a finit pour de bon 😜

2023-06-17 09:07 UTC, bariboo commented on modules/anniversaires.md
> +## <mark style="color:blue;">Annonces personnalisées *(Avantage premium ✨)*</mark>
```suggestion
## <mark style="color:blue;">Annonces personnalisées *(Avantage premium💎)*</mark>

```

Le bot a changé le signe premium✨par 💎

2023-06-17 09:07 UTC, bariboo commented on modules/anniversaires.md
> +Comme vous le voyez sous vos yeux, vous avez accès aux fonctionnalités suivantes : <mark style="color:blue;">Message d'annonce</mark>, <mark style="color:blue;">Rôle temporaire</mark>, <mark style="c
```suggestion
Comme vous le voyez sous vos yeux, vous avez accès aux fonctionnalités suivantes : <mark style="color:blue;">Message d'annonce</mark>, <mark style="color:blue;">Rôle temporaire</mark>, <mark style="color:blue;">Cadeaux d'anniversaire</mark> et <mark style="color:blue;">Annonces personnalisées</mark> *(Avantage premium💎)*.

```

2023-06-17 09:07 UTC, bariboo commented on modules/anniversaires.md
> +## <mark style="color:blue;">Annonces personnalisées *(Avantage premium ✨)*</mark>
```suggestion
## <mark style="color:blue;">Annonces personnalisées *(Avantage premium💎)*</mark>

```

2023-06-17 09:07 UTC, bariboo commented on modules/anniversaires.md
> +Grâce aux commandes <mark style="color:orange;">/anniversaire activer</mark> & <mark style="color:orange;">/anniversaire désactiver</mark>, vous pouvez *(par serveur individuel)* activer ou désactive
```suggestion
Grâce aux commandes <mark style="color:orange;">/anniversaire activer</mark> & <mark style="color:orange;">/anniversaire désactiver</mark>, vous pouvez *(par serveur individuel)* activer ou désactiver la visibilité de votre anniversaire. Vous pouvez aussi modifier ces paramètres depuis le panel (dans la rubrique <mark style="color:blue;">[profil](https://www.draftbot.fr/dashboard/user/profil))</mark>.

```

2023-06-17 09:07 UTC, bariboo requested changes
hjdkwed

2023-06-18 10:57 UTC, bariboo commented
@kazotka il faut que tu ajoutes aussi le mode public / privé sur les anniversaires du coup (Suite à la MAJ PTB).

2023-06-18 14:35 UTC, kazotka commented on modules/anniversaires.md
> +## <mark style="color:blue;">Annonces personnalisées *(Avantage premium ✨)*</mark>
Après une demande aux autres membres de l'équipe, c'est : NON, car ce changement avait déjà été proposé.

2023-06-18 16:36 UTC, bariboo commented
@kazotka tu as pas remplacé les ✨ par 💎 pour le premium 🤔

2023-06-18 16:54 UTC, bariboo approved these changes

2023-06-18 16:54 UTC, merged

2024-02-04 00:38 UTC, Ejeghenje approved these changes
Good