[Module] - Privateroom
DraftBot/Documentation pull request #34
Opened 2023-04-20 15:45 UTC by Tellvex

### Ajout

Ajout de la page des privaterooms dans la documentation des modules

### Modifications

* Update summary.md
* Réorganisation des dossiers d'image des privaterooms

2023-04-20 15:53 UTC, Tellvex commented
Pour le moment, la Pull request est encore en écriture, je me base sur l'ancienne page des privaterooms.

2023-04-21 22:24 UTC, DraftProducts requested changes

2023-04-21 22:24 UTC, DraftProducts commented on modules/privateroom.md
> +{% tab title="via le /config" %}
```suggestion
{% tab title="Via la commande /config" %}
```

2023-04-21 22:24 UTC, DraftProducts commented on modules/privateroom.md
> +### Ajouter les Salons Vocaux Temporaires
```suggestion
### Créer un hub de salons vocaux temporaires
```

2023-04-21 22:24 UTC, DraftProducts commented on modules/privateroom.md
> +### Supprimer les Salons Vocaux Temporaires
```suggestion
### Supprimer un hub de salons vocaux temporaires
```

2023-04-21 22:24 UTC, DraftProducts commented on modules/privateroom.md
> +### Modifier les Salons Vocaux Temporaires
```suggestion
### Modifier un hub de salons vocaux temporaires
```

Et faire pareil pour les autres :v:

2023-04-23 18:30 UTC, Hugo-broc requested changes
Il y aura sûrement d'autres choses à corriger sur la forme générale mais j'attend un premier correctif orthographique pour donner plus de détails.
Me mentionner sur le salon de la documentation une fois fait.

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +### Modifier les Salons Vocaux Temporaires
```suggestion
### Modifier un hub de salons vocaux temporaires
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +# Salons Vocaux Temporaires
```suggestion
# Salons vocaux temporaires
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +## Utilisation des Salons Vocaux Temporaires
```suggestion
## Utilisation des salons vocaux temporaires
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +### Ajouter les Salons Vocaux Temporaires
```suggestion
### Créer un hub pour les salons vocaux temporaires
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +Pour activer les privaterooms, il vous suffit d'aller dans le menu <mark style="color:orange;">Salons Vocaux Temporaires</mark> du <mark style="color:orange;">/config</mark> et de cliquer sur le bout
```suggestion
Pour activer les salons vocaux temporaires, il vous suffit d'aller dans le menu <mark style="color:orange;">Salons vocaux temporaires</mark> de la commande <mark style="color:orange;">/config</mark> et de cliquer sur le bouton <mark style="color:orange;">Créer un hub</mark>.
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +### Supprimer les Salons Vocaux Temporaires
```suggestion
### Supprimer un hub de salons vocaux temporaires
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +Pour modifier des Salons Vocaux Temporaires, vous devez accéder au menu ci-dessous en allant dans le système <mark style="color:orange;">Salons Vocaux Temporaires</mark> du <mark style="color:orange;
```suggestion
Pour modifier un hub de salons vocaux temporaires, vous devez accéder au menu en allant dans le système <mark style="color:orange;">Salons vocaux temporaires</mark> de la commande <mark style="color:orange;">/config</mark>. Vous devez ensuite <mark style="color:orange;">Modifier un hub</mark>.
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +![Modification des Salons Vocaux Temporaires](../.gitbook/assets/privateroom/view_edit.png)
```suggestion
![Modification des salons vocaux temporaires](../.gitbook/assets/privateroom/view_edit.png)
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +#### Activer/Désactiver un Hub
```suggestion
#### Activer/Désactiver un hub
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +Pour activer ou désactiver des Salons Vocaux Temporaires, vous devez cliquer sur le bouton <mark style="color:orange;">Activer le système</mark>. Vous verrez alors le menu se mettre à jour.
```suggestion
Pour activer ou désactiver des salons vocaux temporaires, vous devez cliquer sur le bouton <mark style="color:orange;">Activer le système</mark>. Vous verrez alors le menu se mettre à jour.
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +Lorsque le hub est déjà activé, le bouton se nomme <mark style="color:orange;">Sytème Activé</mark>.
```suggestion
Lorsqu'un hub est déjà activé, le bouton se nomme <mark style="color:orange;">Sytème activé</mark>.
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +Pour qu'un salon soit conservé dans la catégorie sans être supprimé une fois qu'il n'a plus de membres, il faut appuyer sur le bouton <mark style="color:orange;">Salons Permanents</mark>. Un menu s'o
```suggestion
Pour qu'un salon soit conservé dans la catégorie sans être supprimé une fois qu'il n'a plus de membres, il faut appuyer sur le bouton <mark style="color:orange;">Salons permanents</mark>. Un menu s'ouvrira alors et vous pourrez ajouter ou supprimer les salons vocaux permanents de votre choix.
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +#### Changer la catégorie des Salons Vocaux Temporaires
```suggestion
#### Changer la catégorie des salons vocaux temporaires
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +## Informations Supplémentaires
Manque le contenu sous ce titre.
```suggestion
## Informations supplémentaires
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +### Liste des Variables
```suggestion
### Liste des variables
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +### Limite d'hubs de Salons Vocaux Temporaires
```suggestion
### Limite d'hubs de salons vocaux temporaires
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +### Panel
Lien du panel à mettre plus haut.
```suggestion
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +Lien vers le panel : <mark style="color:orange;">[https://www.draftbot.fr/dashboard/user](https://www.draftbot.fr/dashboard/user)</mark>
```suggestion
```

2023-04-23 18:30 UTC, Hugo-broc commented on modules/privateroom.md
> +{% tab title="via le /config" %}
```suggestion
{% tab title="via le /config" %}

[Accéder au panel de **DraftBot**](https://draftbot.fr/dashboard)
```

2023-04-23 18:35 UTC, Tellvex commented on modules/privateroom.md
> +Lien vers le panel : <mark style="color:orange;">[https://www.draftbot.fr/dashboard/user](https://www.draftbot.fr/dashboard/user)</mark>
Pourquoi supprimer cela ?

2023-04-23 18:36 UTC, Tellvex commented on modules/privateroom.md
> +### Panel
Pourquoi supprimer cela ?

2023-04-23 20:26 UTC, Hugo-broc commented on modules/privateroom.md
> +### Panel
Car c'est la mise en page générale de la documentation. On met toujours le lien vers le panel en premier, ça permet de pouvoir y aller directement et pas à la fin des renseignements.

2023-04-23 20:27 UTC, Hugo-broc commented on modules/privateroom.md
> +Lien vers le panel : <mark style="color:orange;">[https://www.draftbot.fr/dashboard/user](https://www.draftbot.fr/dashboard/user)</mark>
Pareil qu'au dessus. C'est la continuité du titre.

2023-04-23 20:29 UTC, Tellvex commented on modules/privateroom.md
> +{% tab title="via le /config" %}
> Pour le moment, la Pull request est encore en écriture, je me base sur l'ancienne page des privaterooms.

2023-04-23 20:32 UTC, Tellvex commented on modules/privateroom.md
> +### Panel
C'est totalement annexe à la page, le sujet c'est les privaterooms, pas le panel, donc je pense que c'est mieux de le laisser à la fin, comme pour toutes les infos annexes à la page.
Je préfère qu'on en discute tous ensemble sur la doc et éventuellement qu'on en fasse un sondage

2023-04-23 20:32 UTC, Tellvex commented on modules/privateroom.md
> +Lien vers le panel : <mark style="color:orange;">[https://www.draftbot.fr/dashboard/user](https://www.draftbot.fr/dashboard/user)</mark>
> C'est totalement annexe à la page, le sujet c'est les privaterooms, pas le panel, donc je pense que c'est mieux de le laisser à la fin, comme pour toutes les infos annexes à la page. Je préfère qu'on en discute tous ensemble sur la doc et éventuellement qu'on en fasse un sondage

2023-04-23 20:35 UTC, Tellvex commented on modules/privateroom.md
> +## Informations Supplémentaires
Pas besoin de contenu, le header est juste là pour l'organisation du sommaire de la page

2023-04-24 18:06 UTC, ErwanGit requested changes

2023-04-24 18:06 UTC, ErwanGit commented on modules/privateroom.md
> +{% endhint %}
Les salons déjà existants sont rendu permanent par défaut, sans configuration de l'administrateur.

2023-04-24 18:06 UTC, ErwanGit commented on modules/privateroom.md
> +> Message en question : "Êtes-vous sûr de vouloir supprimer la seule catégorie de salons vocaux temporaires du serveur ?"
S'il y a plusieurs privateroom, le message est incorrect

2023-04-24 18:06 UTC, ErwanGit commented on modules/privateroom.md
> +Lorsque le hub est déjà activé, le bouton se nomme <mark style="color:orange;">Sytème Activé</mark>.
```suggestion
Lorsqu'un hub est déjà activé, le bouton se nomme <mark style="color:orange;">Système Activé</mark>.
```

2023-04-24 18:06 UTC, ErwanGit commented on modules/privateroom.md
> +Pour changer le salon vocal qui vous redirigera dans votre salon temporaire, il suffit d'appuyer sur le bouton <mark style="color:orange;">Hub (salon)</mark>. Un message vous demandera alors <mark st
```suggestion
Pour changer le salon vocal qui vous redirigera dans votre salon temporaire, il suffit d'appuyer sur le bouton <mark style="color:orange;">Hub (salon)</mark>. Un message vous demandera alors <mark style="color:orange;">[l'identifiant du salon](https://docs.draftbot.fr/autres/recuperer-un-identifiant)</mark>.
```

2023-04-24 18:06 UTC, ErwanGit commented on modules/privateroom.md
> +Pour changer la catégorie des salons vocaux temporaires, il vous suffit de cliquer sur le bouton <mark style="color:orange;">Catégorie</mark>. DraftBot demandra s'il faut créer une nouvelle catégorie
```suggestion
Pour changer la catégorie des salons vocaux temporaires, il vous suffit de cliquer sur le bouton <mark style="color:orange;">Catégorie</mark>. DraftBot demandra s'il faut créer une nouvelle catégorie ou attribuer une catégorie **déjà existante**.
```

2023-04-24 18:06 UTC, ErwanGit commented on modules/privateroom.md
> +Vous pouvez changer le nom par défaut des salons
+ rediriger vers les arguments, je trouve cette partie vide
```suggestion
Vous pouvez changer le nom par défaut des salons.
```

2023-04-24 22:40 UTC, Tellvex commented on modules/privateroom.md
> +Lorsque le hub est déjà activé, le bouton se nomme <mark style="color:orange;">Sytème Activé</mark>.
Je ne suis pas vraiment d'accord
-> Puisque l'on définit le hub à modifier (via le "modifier un hub"), je pense sur le plus adapté serait de laisser tel quel.

2023-04-24 22:44 UTC, Tellvex commented on modules/privateroom.md
> +Vous pouvez changer le nom par défaut des salons
J'avais pas terminé cette partie, et c'était prévu (faut que je me serve du titre du header donc je le ferai plus tard)

2023-05-04 09:08 UTC, IIbey requested changes

2023-05-04 09:08 UTC, IIbey commented on modules/privateroom.md
> +Lorsque le hub est déjà activé, le bouton se nomme <mark style="color:orange;">Sytème Activé</mark>.
```suggestion
Lorsqu'un hub est déjà activé, le bouton se nomme <mark style="color:orange;">Système activé</mark>.

2023-05-04 09:08 UTC, IIbey commented on modules/privateroom.md
> +Pour changer la catégorie des salons vocaux temporaires, il vous suffit de cliquer sur le bouton <mark style="color:orange;">Catégorie</mark>. DraftBot demandra s'il faut créer une nouvelle catégorie
```suggestion
Pour changer la catégorie des salons vocaux temporaires, il vous suffit de cliquer sur le bouton <mark style="color:orange;">Catégorie</mark>. DraftBot demandera s'il faut créer une nouvelle catégorie ou attribuer une catégorie **déjà existante**.

2023-06-22 09:59 UTC, DraftProducts commented
Closed and superseded by a free branch due to inactivity : [`privateroom-page`](https://github.com/DraftBot/Documentation/tree/feat/privateroom-page)

2023-06-22 09:59 UTC, closed without merging