Ajout de la page "Messages récurrents"
DraftBot/Documentation pull request #36
Opened 2023-04-22 22:44 UTC by Thims24

2023-04-22 22:45 UTC, Wernoxx commented
Pépépé

2023-04-24 18:18 UTC, ErwanGit requested changes

2023-04-24 18:18 UTC, ErwanGit commented on modules/messages-recurrents.md
> +Ensuite, suivez les instructions de **DraftBot**
Revoir cette phrase, si je me place en tant qu'utilisateur, la documentation ne sert pas à grand chose dans ce cas-là

2023-04-24 18:29 UTC, Thims24 commented on modules/messages-recurrents.md
> +description: Des annonces régulières à faire ? Oui oui c'est possible !
D'accord, à vrai dire, moi non plus, elle était déjà présente lorsque j'ai commencé l'édition de la page, j'ai pensé que ça venait des devs et je n'avait pas d'idées de description alors je l'ai laissé mais je vais la modifié.

2023-04-24 18:30 UTC, Thims24 commented on modules/messages-recurrents.md
> +Ensuite, suivez les instructions de **DraftBot**
Ok mais dans ce cas il n'y a pas grand chose à mettre, je qualifie ça plus d'une "phrase d'introduction", je ne sais pas quoi mettre sinon

2023-04-29 08:24 UTC, ErwanGit commented on modules/messages-recurrents.md
> +Ensuite, suivez les instructions de **DraftBot**
Développer, afficher les options possibles (ex: heure de récurrence, jour, options message collant, etc.)

2023-04-29 08:26 UTC, ErwanGit requested changes

2023-04-29 08:26 UTC, ErwanGit commented on modules/messages-recurrents.md
> +L'heure d'envoi des messages récurrents se base sur le fuseau horaire français (UTC+2).
Peut-être pas la meilleur phrase, mais il se pourrait que nous proposons l'option de modifier le fuseau horaire dans le futur
```suggestion
L'heure d'envoi des messages récurrents se base actuellement seulement sur le fuseau horaire français (UTC+2).
```

2023-05-04 11:08 UTC, Tellvex reviewed
Je suis pas super fan de la structure de la configuration

Pourquoi faire plusieurs tabs ?
-> Tu peux juste mettre des headers dans les tabs pour "séparer" les parties/explications
> En procédant avec un seul tab, toutes les explications du panel ou du /config sont "réunies" donc je pense que le lecteur sera moins perdu.

⚠️ C'est une suggestion, il faudrait se renseigner sur les avis des autres reviewers

2023-06-16 10:07 UTC, DraftProducts commented
Closed due to inactivity.

2023-06-16 10:07 UTC, closed without merging