REPERTOIRE DE MISE EN PAGE
DraftBot/Documentation pull request #37
Opened 2023-04-23 22:09 UTC by Hugo-broc

PR ayant pour but de créer une page interne à la documentation permettant d'unifier la mise en page de la documentation.

2023-04-24 16:12 UTC, DraftProducts requested changes

2023-04-24 18:28 UTC, ErwanGit requested changes

2023-04-24 18:28 UTC, ErwanGit commented on SUMMARY.md
> +- [REPERTOIRE DE MISE EN PAGE](REPERTOIRE%20DE%20MISE%20EN%20PAGE.md)
Je ne pense pas que cela ait vocation à être en public sur le repo, en tant que "README" sur la documentation, pourquoi pas, en public pour tous les lecteurs de la documentation, je suis plutôt contre
Eventuellement voir si c'est pas possible d'accéder à la page avec un lien non répertorié

2023-04-24 18:28 UTC, ErwanGit commented on REPERTOIRE DE MISE EN PAGE.md
> +**DraftBot** peut ? uniquement si vous disposez de la permission "*Permission*" ou que l'un de vos rôles peut utiliser la commande <mark style="color:orange;">?</mark> sur votre serveur.
???

2023-04-24 18:28 UTC, ErwanGit commented on REPERTOIRE DE MISE EN PAGE.md
> +![](.gitbook/assets/repertoire-mep/code_permissions-necessaires.png)
???

2023-04-24 18:28 UTC, ErwanGit commented on REPERTOIRE DE MISE EN PAGE.md
> +**DraftBot** peut ? uniquement si vous disposez de la permission "*Permission*" ou que l'un de vos rôles peut utiliser la commande <mark style="color:orange;">?</mark> sur votre serveur.
???

2023-04-24 18:28 UTC, ErwanGit commented on REPERTOIRE DE MISE EN PAGE.md
> +Rendu : <mark style="color:blue;">[Général](REPERTOIRE%20DE%20MISE%20EN%20PAGE.md#general)</mark>
A modifier avec le retour de Nicolas sur le nom du fichier

2023-04-24 18:28 UTC, ErwanGit commented on REPERTOIRE DE MISE EN PAGE.md
> +Rendu : ![](.gitbook/assets/repertoire-mep/#%20Titre%203.png)
Modifier le nom des liens

2023-04-24 18:28 UTC, ErwanGit commented on REPERTOIRE DE MISE EN PAGE.md
> +Si un élément ne figure pas dans cette page mais qu'il le devrait, merci de contacter <mark style="color:orange;">[DraftMan - Nicolas](discord:/users/207190782673813504)</mark> ou bien <mark style="c
Ce n'est pas possible d'utiliser ce type de lien avec GitBook qui redirige en HTTP

2023-04-24 18:28 UTC, ErwanGit commented on REPERTOIRE DE MISE EN PAGE.md
> +# CONSIGNES
Si tu veux vraiment le mettre en valeur, un émoji ?
```suggestion
# Consignes
```

2023-04-24 19:42 UTC, Hugo-broc commented on SUMMARY.md
> +- [REPERTOIRE DE MISE EN PAGE](REPERTOIRE%20DE%20MISE%20EN%20PAGE.md)
Cela ne sera pas mit dans le sommaire final, c'est prévu que cela soit supprimé avant de merge.
C'est juste pour retrouver la page et pouvoir voir les modifs que je fais sinon je ne peux la voir nulle part.

2023-04-25 13:25 UTC, Hugo-broc commented on REPERTOIRE DE MISE EN PAGE.md
> +![](.gitbook/assets/repertoire-mep/code_permissions-necessaires.png)
De quoi `???` ?
Si tu détailles pas, je ne peux pas savoir c'est quoi le problème... 😅

2023-04-25 13:25 UTC, Hugo-broc commented on REPERTOIRE DE MISE EN PAGE.md
> +**DraftBot** peut ? uniquement si vous disposez de la permission "*Permission*" ou que l'un de vos rôles peut utiliser la commande <mark style="color:orange;">?</mark> sur votre serveur.
De quoi ??? ? Si tu détailles pas, je ne peux pas savoir c'est quoi le problème... 😅

2023-04-25 14:09 UTC, DraftProducts commented on REPERTOIRE DE MISE EN PAGE.md
> +**DraftBot** peut ? uniquement si vous disposez de la permission "*Permission*" ou que l'un de vos rôles peut utiliser la commande <mark style="color:orange;">?</mark> sur votre serveur.
ça veut juste dire qu'il ne comprend pas ce qu'il y a là 🤣

2023-04-25 14:11 UTC, DraftProducts commented on REPERTOIRE DE MISE EN PAGE.md
> +![](.gitbook/assets/repertoire-mep/code_permissions-necessaires.png)
Je n'ai pas compris non plus 🤔 
Peut être le caption qui a pas été ajouté 🤔 (entre les [ ])

2023-04-25 20:29 UTC, Hugo-broc commented on REPERTOIRE DE MISE EN PAGE.md
> +![](.gitbook/assets/repertoire-mep/code_permissions-necessaires.png)
Ca va être rempli alors ! Un oubli de ma part.
Je laisse cette discussions ouverte en attendant l'avis d'@ErwanGit sur le sujet.

2023-04-29 08:15 UTC, ErwanGit commented on REPERTOIRE DE MISE EN PAGE.md
> +**DraftBot** peut ? uniquement si vous disposez de la permission "*Permission*" ou que l'un de vos rôles peut utiliser la commande <mark style="color:orange;">?</mark> sur votre serveur.
`peut ? uniquement` ?
Cela ne veut rien dire

2023-04-29 08:15 UTC, ErwanGit commented on REPERTOIRE DE MISE EN PAGE.md
> +**DraftBot** peut ? uniquement si vous disposez de la permission "*Permission*" ou que l'un de vos rôles peut utiliser la commande <mark style="color:orange;">?</mark> sur votre serveur.
`peut ? uniquement` ?
Cela ne veut rien dire

2023-04-29 08:18 UTC, ErwanGit commented on REPERTOIRE DE MISE EN PAGE.md
> +![](.gitbook/assets/repertoire-mep/code_permissions-necessaires.png)
La photo et l'histoire des points d'interrogations dans le message/image

2023-05-06 08:38 UTC, DraftProducts requested changes
Il manque la configuration des tabs en bas de page, sinon tout le reste me semble bon, gg 🔥

2024-01-24 09:23 UTC, closed without merging