Ajout du compteur
DraftBot/Documentation pull request #38
Opened 2023-04-24 16:39 UTC by DRIXEREX

2023-04-24 18:11 UTC, ErwanGit requested changes

2023-04-24 18:11 UTC, ErwanGit commented on modules/compteur.md
> +* Choisir si le design de compteur soit sur plusieurs salon ou un catégorie
```suggestion
Vous aurez alors le choix :
* D'activer ou non le compteur de membres.
* Choisir si le design de compteur soit sur plusieurs salons ou une catégorie.
```

2023-04-24 18:11 UTC, ErwanGit commented on modules/compteur.md
> +# 🧮 Compteur
```suggestion
# 🧮 Compteur de membres
```

2023-04-24 18:11 UTC, ErwanGit commented on modules/compteur.md
> +# 🧮 Compteur
Le titre n'apparait pas sur la preview

2023-04-24 18:11 UTC, ErwanGit commented on modules/compteur.md
> +DraftBot va vous demander le design du compteur, pour notre cas nous allons choisir "Catégorie".
Il faut couvrir les deux cas d'une manière ou d'une autre

2023-04-24 18:11 UTC, ErwanGit commented on modules/compteur.md
> +Et voilà ! Vous avez terminé la configuration du compteur
```suggestion
Et voilà ! Vous avez terminé la configuration du compteur.

```

2023-04-24 18:11 UTC, ErwanGit commented on modules/compteur.md
> +Puis DraftBot va vous demander si vous voulez affiché le nombre de bots sur le compteur, pour notre cas nous allons choisir "Oui"
```suggestion
Puis DraftBot va vous demander si vous voulez affiché le nombre de bots sur le compteur, pour notre cas nous allons choisir "Oui".

```

2023-04-24 18:11 UTC, ErwanGit commented on modules/compteur.md
> +{% endhint %}
Répétition avec le haut

2023-04-24 18:11 UTC, ErwanGit commented on modules/compteur.md
> +Vous pouvez configurer le système de compteur sur votre serveur à l'aide de la commande <mark style="color:orange;">/config</mark>, en vous rendant ensuite dans l'onglet "Compteur de membres" du séle
Eventuellement afficher la page d'accueil du /config

2023-04-24 18:11 UTC, ErwanGit commented on modules/compteur.md
> +    Le système de compteur permet d'afficher le nombre de membres, rôles ou salon
```suggestion
    Le système de compteur permet d'afficher le nombre de membres, rôles ou salon.
```

2023-05-04 11:01 UTC, Tellvex requested changes
### Review

Globalement, certaines points sont à revoir : 

- [ ] La façon de stocker les fichiers n'est pas bonne
- [ ] Certaines formulations sont à revoir.
- [ ] Il manque des images importantes (menu /config) et les images ne sont pas détourées

>  Si tu as besoin de détourer/prendre des captures d'écran, tu peux le faire toi-même ou demander à @DraftProducts lorsqu'il sera en voc.

2023-05-04 11:08 UTC, IIbey commented on modules/compteur.md
> +Et voilà ! Vous avez terminé la configuration du compteur
Etant donné que les autres pages ne possèdent pas ce genre de phrase, elle peut être retirée.

2023-06-15 20:18 UTC, DraftProducts commented
Closed and superseded by a free branch due to inactivity : [`membercount-page`](https://github.com/DraftBot/Documentation/tree/feat/membercount-page)

2023-06-15 20:18 UTC, closed without merging