Amélioration page gestion des messages
DraftBot/Documentation pull request #39
Opened 2023-05-01 16:49 UTC by Titoto289

J'ai ajouté le fait qu'il faut (pour les commandes /effacer message et /effacer conversation) que les message datent d'il y a moins de 14j

2023-05-04 08:16 UTC, IIbey requested changes
Je ne suis pas allée plus loin pour le moment, car je vois trop de répétition avec les warning. Le mieux, c'est de les mettre à la fin de la page à mon avis...

2023-05-04 08:17 UTC, IIbey requested changes

2023-05-04 08:17 UTC, IIbey commented on SUMMARY.md
> +- [💬 Commandes de convesations](modules/gestion-des-messages.md)
```suggestion
- [💬 Commandes de conversations](modules/gestion-des-messages.md)

2023-05-04 08:17 UTC, IIbey commented on modules/gestion-des-messages.md
> +**DraftBot** peut supprimer des messages via la commande <mark style="color: #cd6e57;">/effacer messages \[nombre]</mark>. uniquement si les message datent d'il y a moins de **14** jours. Cependant l
```suggestion
**DraftBot** peut supprimer des messages via la commande <mark style="color: #cd6e57;">/effacer messages \[nombre]</mark>, uniquement, si les message datent d'il y a moins de **14** jours. Cependant la commande <mark style="color: #cd6e57;">/vider-salon</mark> peut le faire.

2023-05-04 09:45 UTC, IIbey commented on modules/gestion-des-messages.md
> +**DraftBot** peut supprimer des messages via la commande <mark style="color: #cd6e57;">/effacer messages \[nombre]</mark>. uniquement si les message datent d'il y a moins de **14** jours. Cependant l
"/effacer channel" n'existe pas, la bonne commande est "/vider-salon" pour effacer la conversation d'un salon.

2023-05-27 12:05 UTC, DraftProducts approved these changes

2023-05-27 12:05 UTC, DraftProducts commented on modules/gestion-des-messages.md
> +* <mark style="color: #cd6e57;">\[utilisateur]</mark> pour supprimer le nombre de messages, les plus récents, envoyés par cet utilisateur. Utile pour supprimer les messages d'un membre banni de votre
```suggestion
* <mark style="color: #cd6e57;">\[utilisateur]</mark> pour supprimer le nombre de messages, les plus récents, envoyés par cet utilisateur. Utile pour supprimer les messages d'un membre banni de votre serveur.
```

2023-05-27 12:30 UTC, ErwanGit requested changes

2023-05-27 12:30 UTC, ErwanGit commented on modules/gestion-des-messages.md
> +**DraftBot** peut supprimer des messages via la commande <mark style="color: #cd6e57;">/effacer messages \[nombre]</mark>. uniquement si les message datent d'il y a moins de **14** jours. Cependant l
La commande n'est pas mis en valeur
![image](https://github.com/DraftBot/Documentation/assets/24718500/58adeabc-0018-4a83-b5b3-e0ca2588257c)

2023-05-27 12:30 UTC, ErwanGit commented on modules/gestion-des-messages.md
>  #### :warning: Attention, cette action est <mark style="color:red;">**irréversible**</mark> !
Pas uniforme avec les autres pages

2023-05-27 12:30 UTC, ErwanGit commented on modules/gestion-des-messages.md
> +Pour faire cela, vous pouvez utiliser la slash commande <mark style="color: #cd6e57;">/vider-salon</mark>. Si vous souhaitez vider un salon autre que celui où vous faites la commande, utilisez l'opti
Commande pas mentionné
![image](https://github.com/DraftBot/Documentation/assets/24718500/6236a3bb-26c7-4a93-bf07-bd86047e40ec)

2023-05-27 12:30 UTC, ErwanGit commented on modules/gestion-des-messages.md
> +
Commandes pas mentionnés
![image](https://github.com/DraftBot/Documentation/assets/24718500/e148548a-e486-4412-871a-96e6bde86194)

2023-05-27 12:30 UTC, ErwanGit commented on modules/gestion-des-messages.md
> +Vous pouvez sauvegarder une conversation avec la slash commande <mark style="color: #cd6e57;">/enregistrer conversation \[premier\_message] \[dernier\_message]</mark>.
Commande pas mentionné

2023-06-22 10:03 UTC, closed without merging