Ajout de l'explication de la migration des niveaux
DraftBot/Documentation pull request #42
Opened 2023-05-22 09:39 UTC by Wernoxx

2023-05-22 09:52 UTC, Tellvex requested changes
Petite erreur de structuration dans le sommaire de la page, sinon tout semble ok. A voir avec @IIbey en cas de fautes d'orthographe

2023-05-22 09:52 UTC, Tellvex commented on modules/niveaux.md
> +# Migration
```suggestion
## Migration
```
Le header 1 est réservé au titre de la page

2023-05-22 10:03 UTC, Tellvex approved these changes

2023-05-22 10:04 UTC, Tellvex commented
Oops, my bad, sur tel c'est pas ouf de review et j'ai Missclick

2023-05-22 11:15 UTC, IIbey commented on modules/niveaux.md
> +Il faut impérativement que le bot MEE6 soit sur votre serveur lors de la migration et que le classement soit publique.
```suggestion
Il faut impérativement que le bot MEE6 soit sur votre serveur lors de la migration et que le classement soit public.

2023-05-23 08:23 UTC, IIbey approved these changes

2023-05-23 09:34 UTC, Tellvex approved these changes

2023-05-25 12:20 UTC, merged