Ajout de la page des interserveurs
DraftBot/Documentation pull request #45
Opened 2023-05-27 16:23 UTC by Wernoxx

2023-05-28 14:35 UTC, ErwanGit requested changes

2023-05-28 14:35 UTC, ErwanGit commented on SUMMARY.md
> +- [🐷 Interserveurs](modules/interserveurs.md)
Non

2023-05-28 14:35 UTC, ErwanGit commented on modules/interserveurs.md
> +**Félicitations !** Vos deux salons on bien étés configurés.
```suggestion
**Félicitations !** Vos deux salons ont bien été configurés.

```

2023-05-28 14:35 UTC, ErwanGit commented on modules/interserveurs.md
> +![Réponse de Draftbot lors de l'exécution de la commande](../.gitbook/assets/interservers/interserver_generate.png)
```suggestion
![Réponse de DraftBot lors de l'exécution de la commande](../.gitbook/assets/interservers/interserver_generate.png)

```

2023-05-28 14:35 UTC, ErwanGit commented on modules/interserveurs.md
> +<mark style="color:orange;">`/interserveur gérer`</mark> Gérer la liaison interserveur du salon.
Cette commande n'est pas décrite davantage

2023-05-28 15:52 UTC, Wernoxx commented on modules/interserveurs.md
> +<mark style="color:orange;">`/interserveur gérer`</mark> Gérer la liaison interserveur du salon.
Quelle commande?

2023-05-28 15:53 UTC, Wernoxx commented on SUMMARY.md
> +- [🐷 Interserveurs](modules/interserveurs.md)
Oui, je ne sais pas lequel mettre

2023-05-28 19:32 UTC, DraftProducts approved these changes

2023-05-30 18:57 UTC, ErwanGit requested changes

2023-05-30 18:57 UTC, ErwanGit commented on SUMMARY.md
Je ne sais pas d'ou cela viens mais il y a pas le même espace que les autres modules
<img width="276" alt="image" src="https://github.com/DraftBot/Documentation/assets/24718500/73f55b28-6f6f-4a86-9521-7a7d1b640744">

2023-05-30 18:57 UTC, ErwanGit commented on modules/interserveurs.md
Indiquer le cooldown obligatoire et pourquoi ?

2023-05-30 18:57 UTC, ErwanGit commented on modules/interserveurs.md
> +Si vous perdez vos fréquences, pour les retrouvées, faites la commande <mark style="color:orange;">`/interserveur gérer`</mark> dans le salon où le module est activé.
Il faudrait reformuler le "Si vous perdez vos fréquences", je suis vraiment pas fan de la tournure de cette partie

2023-05-30 18:59 UTC, Wernoxx commented on SUMMARY.md
C'est dû à l'emoteje pense, je regarde ça dans la soirée (ai si que pour les autres reviews)

2023-05-30 22:11 UTC, Wernoxx commented on modules/interserveurs.md
> +Si vous perdez vos fréquences, pour les retrouvées, faites la commande <mark style="color:orange;">`/interserveur gérer`</mark> dans le salon où le module est activé.
Je suis nul en ça, comment faire?

2023-06-04 01:31 UTC, Wernoxx commented on SUMMARY.md
J'ai essayer avec différents émoji et l'espace est péter et je vois pas d'où ça vient

2023-06-04 17:24 UTC, ElBaguetto commented on modules/interserveurs.md
> +Si vous perdez vos fréquences, pour les retrouvées, faites la commande <mark style="color:orange;">`/interserveur gérer`</mark> dans le salon où le module est activé.
Peut être en mode: Vous pouvez retrouver l'ensemble des fréquences configurées pour un salon en utilisant la commande `/interserveur gérer` dans le salon correspondant.

2023-06-09 09:23 UTC, closed without merging