Ajout du module interserveur
DraftBot/Documentation pull request #52
Opened 2023-06-16 13:56 UTC by Wernoxx

2023-06-16 15:21 UTC, ErwanGit requested changes

2023-06-16 15:21 UTC, ErwanGit commented on modules/interserveurs.md
> +Une fois la fréquence créée, utilisez la commande <mark style="color:orange;">`/interserveur lier`</mark> dans le salon du serveur que vous souhaitez relier au premier salon.
On ne peut pas relier plus de deux salons à une même liaison actuellement
```suggestion
Une fois la fréquence créée, utilisez la commande <mark style="color:orange;">`/interserveur lier`</mark> dans le salon du serveur que vous souhaitez relier au second salon.
```

2023-06-16 15:21 UTC, ErwanGit commented on modules/interserveurs.md
> +Un coldown est présent sur l'envoi des messages, il a été mis en place par sécurité afin d'éviter à Draftbot de se faire rate-limit.
```suggestion
Un coldown est présent sur l'envoi des messages, il a été mis en place par sécurité afin d'éviter à DraftBot des abus.
```

2023-06-16 15:21 UTC, ErwanGit commented on modules/interserveurs.md
> +Vous pouvez retrouver la fréquence configurée pour un salon en utilisant la commande <mark style="color:orange;">`/interserveur gérer`</mark> gérer dans le salon correspondant.
```suggestion
Vous pouvez retrouver la fréquence configurée pour un salon en utilisant la commande <mark style="color:orange;">`/interserveur gérer`</mark> dans le salon correspondant.
```

2023-06-16 15:28 UTC, ErwanGit approved these changes

2023-06-16 15:28 UTC, ErwanGit commented on modules/interserveurs.md
> +Une fois la fréquence créée, utilisez la commande <mark style="color:orange;">`/interserveur lier`</mark> dans le salon du serveur que vous souhaitez relier au second salon.
```suggestion
Une fois la fréquence créée, utilisez la commande <mark style="color:orange;">`/interserveur lier`</mark> dans le salon du serveur que vous souhaitez relier au premier salon.

```

2023-06-17 00:20 UTC, DraftProducts approved these changes

2023-06-17 09:30 UTC, bariboo requested changes
Il manque aussi le nombre maximum d'interserveur si on est premium ou non.

2023-06-17 09:30 UTC, bariboo commented on modules/interserveurs.md
> +<mark style="color:orange;">`/interserveur gérer`</mark> Gérer la liaison interserveur du salon.
```suggestion
> <mark style="color:orange;">/interserveur générer</mark> Générer une fréquence pour un interserveur.\
<mark style="color:orange;">/interserveur lier</mark> Lier ce salon à une fréquence d'interserveur.\
<mark style="color:orange;">/interserveur gérer</mark> Gérer la liaison interserveur du salon.

```

Sur les autres pages, nous n'avons pas mis les commandes entre "``".

2023-06-17 09:30 UTC, bariboo commented on modules/interserveurs.md
> +**Trois commandes sont à disposition pour gérer vos liaisons de salon.**
```suggestion
**Trois commandes sont à disposition pour gérer vos liaisons de salon :**

```

2023-06-17 09:30 UTC, bariboo commented on modules/interserveurs.md
> +  Relier deux salons distinct de deux serveurs.
```suggestion
  Relier deux salons distincts de deux serveurs.

```

2023-06-17 09:30 UTC, bariboo commented on modules/interserveurs.md
> +- Pour lier deux salons, il faut tout d'abord créer une fréquence, cette fréquence est unique à votre salon.
```suggestion
- Pour lier deux salons, il vous faut tout d'abord créer une fréquence, cette dernière est unique à chaque salon.

```

2023-06-17 09:30 UTC, bariboo commented on modules/interserveurs.md
> +- Pour créer une fréquence, utilisez la commande <mark style="color:orange;">`/interserveur générer`</mark>.
```suggestion
- Pour créer une fréquence, utilisez la commande <mark style="color:orange;">/interserveur générer</mark>.

```

2023-06-17 09:30 UTC, bariboo commented on modules/interserveurs.md
> +Une fois la fréquence créée, utilisez la commande <mark style="color:orange;">`/interserveur lier`</mark> dans le salon du serveur que vous souhaitez relier au premier salon.
```suggestion
Une fois la fréquence créée, utilisez la commande <mark style="color:orange;">/interserveur lier</mark> dans le salon que vous souhaitez relier au premier.

{% hint style="info" %}
Vous ne pouvez pas lier deux salons du même serveur.
{% endhint %}
```

2023-06-17 09:30 UTC, bariboo commented on modules/interserveurs.md
> +Un coldown est présent sur l'envoi des messages, il a été mis en place par sécurité afin d'éviter à DraftBot des abus.
```suggestion
Un coldown est présent sur l'envoi des messages, il a été mis en place par sécurité afin d'éviter des abus.

```

2023-06-17 09:30 UTC, bariboo commented on modules/interserveurs.md
> +Vous pouvez retrouver la fréquence configurée pour un salon en utilisant la commande <mark style="color:orange;">`/interserveur gérer`</mark> dans le salon correspondant.
```suggestion
Vous pouvez retrouver la fréquence configurée pour un salon en utilisant la commande <mark style="color:orange;">/interserveur gérer</mark> dans le salon correspondant.

```

2023-06-17 09:30 UTC, bariboo commented on modules/interserveurs.md
> +**Félicitations !** Vos deux salons ont bien été configurés.
```suggestion
**Félicitations !** L'interserveur est maintenant configuré sur votre serveur !
```

2023-06-17 11:25 UTC, Wernoxx commented
> Il manque aussi le nombre maximum d'interserveur si on est premium ou non.

Je fais ça dans la journée

2023-06-17 13:55 UTC, IIbey requested changes

2023-06-17 13:55 UTC, IIbey commented on modules/interserveurs.md
> +Un coldown est présent sur l'envoi des messages, il a été mis en place par sécurité afin d'éviter des abus.
```suggestion
Un cooldown est présent sur l'envoi des messages, il a été mis en place par sécurité afin d'éviter des abus.

2023-06-18 10:53 UTC, bariboo approved these changes

2023-06-18 16:58 UTC, IIbey approved these changes

2023-06-18 18:16 UTC, merged