Ajout Page 💡Suggestions
DraftBot/Documentation pull request #54
Opened 2023-06-17 09:35 UTC by bariboo

2023-06-17 14:49 UTC, ErwanGit requested changes

2023-06-17 14:49 UTC, ErwanGit commented on .gitbook/assets/suggestions/suggest_menu.png
L'image transparent

2023-06-17 14:49 UTC, ErwanGit commented on modules/suggestions.md
> +Ce système n'étant disponible que depuis peu, il n'est pas possible de répertorier les suggestions qui datent d'avant le 12 décembre 2022.
La 5.0.0 date d'avant décembre, sûr et certain, elle avait été publié fin août
Après je pense qu'on peut le retirer sur la doc + bot, ça fait un long moment maintenant

2023-06-17 14:49 UTC, ErwanGit commented on modules/suggestions.md
> +**Vous avez oublié une information lors de la création de votre suggestion ou vous voulez ajouter un commentaire à cette dernière ?**\
```suggestion
**Vous avez oublié une information lors de la publication de votre suggestion ou vous voulez ajouter un commentaire à cette dernière ?**\
```

2023-06-17 14:49 UTC, ErwanGit commented on modules/suggestions.md
> +**DraftBot** vous propose de pouvoir accepter,refuser une suggestion.\
Rajouter les nouveaux types
```suggestion
**DraftBot** vous propose de pouvoir accepter, refuser une suggestion.\
```

2023-06-17 14:49 UTC, ErwanGit commented on .gitbook/assets/suggestions/suggest_refuse.gif
GIF pas ok (pixel)

2023-06-17 14:49 UTC, ErwanGit commented on .gitbook/assets/suggestions/suggest_accept.gif
GIF pas ok (pixel)

2023-06-17 14:49 UTC, ErwanGit commented on modules/suggestions.md
> +![](<../../.gitbook/assets/suggestions/view.png>)
Il faudra modifié l'image

2023-06-17 17:35 UTC, bariboo commented on .gitbook/assets/suggestions/suggest_refuse.gif
les gifs viennent de Hugo, je repris une PR qui avait été abandonné par Hugo.

2023-06-17 17:35 UTC, bariboo commented on .gitbook/assets/suggestions/suggest_accept.gif
Même chose ici

2023-06-18 11:21 UTC, bariboo commented on .gitbook/assets/suggestions/suggest_menu.png
je demanderai à Draftman à la fin

2023-06-18 12:48 UTC, bariboo commented on modules/suggestions.md
> +Ce système n'étant disponible que depuis peu, il n'est pas possible de répertorier les suggestions qui datent d'avant le 12 décembre 2022.
Je suis d'accord, surtout que c'est écrit dans le menu des suggestions

2023-06-24 12:22 UTC, DraftProducts requested changes

2023-06-24 12:22 UTC, DraftProducts commented on .gitbook/assets/suggestions/set_suggestion_confirmation.png
Il faudrait que tu prennes tes screens sans theme s'il te plait, avec les dégradés, ça devient vraiment crad quand on les détoure.

2023-06-28 16:34 UTC, IIbey requested changes

2023-06-28 16:34 UTC, IIbey commented on modules/suggestions.md
> +Cette commande vous permet de soumettre de nouvelles suggestions, accéder à celles-ci (en cliquant sur leurs titres) ou encore, voir leur état. C'est à dire que vous pourrez voir le pourcentage de vo
```suggestion
Cette commande vous permet de soumettre de nouvelles suggestions, accéder à celles-ci (en cliquant sur leurs titres) ou encore, voir leur état. C'est-à-dire que vous pourrez voir le pourcentage de votes de vos suggestions, mais aussi si elles ont été acceptées, refusées ou si elles sont prévues.

2023-06-28 16:34 UTC, IIbey commented on modules/suggestions.md
> +Vous pourrez également y décider de vous faire notifié ou non en cas d'un changement de <mark style="color:blue;">[status](suggestions.md#gerer-une-suggestion)</mark> sur l'une de vos suggestions.
```suggestion
Vous pourrez également décider de vous faire notifier ou non en cas d'un changement de <mark style="color:blue;">[statut](suggestions.md#gerer-une-suggestion)</mark> sur l'une de vos suggestions.

2023-06-28 16:34 UTC, IIbey commented on modules/suggestions.md
> +Il faut que l'option "Notification lors du changement de statut" soit <mark style="color:blue;">[activée](suggestions.md#tri-des-suggestions)</mark> sur le serveur. Si ce n'est pas le cas, vous ne ve
```suggestion
Il faut que l'option "Notification lors du changement de statut" soit <mark style="color:blue;">[activée](suggestions.md#tri-des-suggestions)</mark> sur le serveur. Si ce n'est pas le cas, vous ne verrez pas le bouton "Me notifier en cas de changement de statut"

2023-06-28 16:34 UTC, IIbey commented on modules/suggestions.md
> +* Titre ➜ Le titre à donner à votre suggestion. Il permettra aussi de la référencer dans le menu des [menu des suggestions](suggestions.md#menu-des-suggestions).
```suggestion
* Titre ➜ Le titre à donner à votre suggestion. Il permettra aussi de la référencer dans le [menu des suggestions](suggestions.md#menu-des-suggestions).

2023-06-28 16:34 UTC, IIbey commented on modules/suggestions.md
> +Il faut que <mark style="color:blue;">[commentaire après publication](suggestions.md#membres)</mark> soit activé.
```suggestion
Il faut que "<mark style="color:blue;">[commentaire après publication](suggestions.md#membres)</mark>" soit activé.

2023-06-28 16:34 UTC, IIbey commented on modules/suggestions.md
> +Vous avez besoin de la permission "*Gérer les messages*" pour pouvoir accepter, refuser ou prevoir une suggestion.
```suggestion
Vous avez besoin de la permission "*Gérer les messages*" pour pouvoir accepter, refuser ou prévoir une suggestion.

2023-06-28 16:34 UTC, IIbey commented on modules/suggestions.md
> +Pour accepter une suggestion, vous pouvez utiliser la commande <mark style="color:orange;">/suggestmod accepter</mark>. Vous devrez ensuite saisir l'<mark style="color:blue;">[identifiant](https://do
```suggestion
Pour accepter une suggestion, vous pouvez utiliser la commande <mark style="color:orange;">/suggestmod accepter</mark>. Vous devrez ensuite saisir l'<mark style="color:blue;">[identifiant](https://docs.draftbot.fr/autres/recuperer-un-identifiant#message)</mark> du message (donc de la suggestion à accepter). Finalement, un menu s'ouvrira afin de vous demander la raison d'acceptation.

2023-06-28 16:34 UTC, IIbey commented on modules/suggestions.md
> +Pour refuser une suggestion, vous pouvez utiliser la commande <mark style="color:orange;">/suggestmod refuser</mark>. Vous devrez ensuite saisir l'<mark style="color:blue;">[identifiant](https://docs
```suggestion
Pour refuser une suggestion, vous pouvez utiliser la commande <mark style="color:orange;">/suggestmod refuser</mark>. Vous devrez ensuite saisir l'<mark style="color:blue;">[identifiant](https://docs.draftbot.fr/autres/recuperer-un-identifiant#message)</mark> du message (donc de la suggestion à refuser). Finalement, un menu s'ouvrira afin de vous demander la raison de refus.

2023-06-28 16:34 UTC, IIbey commented on modules/suggestions.md
> +Pour prévoir une suggestion, vous pouvez utiliser la commande <mark style="color:orange;">/suggestmod prevue</mark>. Vous devrez ensuite saisir l'<mark style="color:blue;">[identifiant](https://docs.
```suggestion
Pour prévoir une suggestion, vous pouvez utiliser la commande <mark style="color:orange;">/suggestmod prevue</mark>. Vous devrez ensuite saisir l'<mark style="color:blue;">[identifiant](https://docs.draftbot.fr/autres/recuperer-un-identifiant#message)</mark> du message (donc de la suggestion à prévoir). Finalement, un menu s'ouvrira afin de vous demander la raison de prévision.

2023-06-29 07:17 UTC, IIbey requested changes

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +"Masquer le nom du modérateur" ➜ Cette option sert masquer le nom de la personne qui aura [géré la suggestion](suggestions.md#gerer-une-suggestion).
```suggestion
"Masquer le nom du modérateur" ➜ Cette option sert à masquer le nom de la personne qui aura [géré la suggestion](suggestions.md#gerer-une-suggestion).

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +    "Mention désactivée par défaut" ➜ Une fois cette option activée, les membres ne seront pas notifié lors du changement de statut.
```suggestion
    "Mention désactivée par défaut" ➜ Une fois cette option activée, les membres ne seront pas notifiés lors du changement de statut.

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +Pour les deux dernières options citées ci-dessus, il sera possible pour vos membres de modifier le paramètre par défaut en passant par "<mark style="color:orange;">/suggest</mark>" puis "Me notifié e
```suggestion
Pour les deux dernières options citées ci-dessus, il sera possible pour vos membres de modifier le paramètre par défaut en passant par "<mark style="color:orange;">/suggest</mark>" puis "Me notifier en cas de changement de statut".

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +
Essaye de faire un retour à la ligne.

![image](https://github.com/DraftBot/Documentation/assets/111301542/31c5ceb0-7661-43da-8a6c-6a85f183202e)

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +![Menu de configuration des notifications lors du chnagement de statut](../.gitbook/assets/suggestions/set_suggestion_notification.png)
```suggestion
![Menu de configuration des notifications lors du changement de statut](../.gitbook/assets/suggestions/set_suggestion_notification.png)

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +"<mark style="color:blue;">Définir le fil des suggestions refusée</mark>" ➜ Une fois le fil défini, toute les suggestions refusées se rendront automatiquement dans ce fil.
Pareil, des retours à la ligne.

![image](https://github.com/DraftBot/Documentation/assets/111301542/7feb7d60-fb8f-4258-9a44-5dbf0de8285c)

```suggestion
"<mark style="color:blue;">Définir le fil des suggestions acceptées</mark>" ➜ Une fois le fil défini, toutes les suggestions acceptées se rendront automatiquement dans ce fil.
"<mark style="color:blue;">Définir le fil des suggestions refusée</mark>" ➜ Une fois le fil défini, toutes les suggestions refusées se rendront automatiquement dans ce fil.

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +"Limiter les suggestions en attentes" ➜ Grâce à ce bouton, vous pouvez décider de limiter le nombre de suggestion que vos membres pourront envoyer.
```suggestion
"Limiter les suggestions en attente" ➜ Grâce à ce bouton, vous pouvez décider de limiter le nombre de suggestion que vos membres pourront envoyer.

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +Une fois la suggestions [traitée](suggestions.md#gerer-une-suggestion), le membre pourra renvoyer une suggestion.
```suggestion
Une fois la suggestion [traitée](suggestions.md#gerer-une-suggestion), le membre pourra renvoyer une suggestion.

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +"Modifier le nom du fil" ➜ Vous pourrez mofifier le nom du fil qui s'ouvrira sous chaque suggestion.
Pareil, des retours à la ligne.
De plus, on était pas resté sur des ✨ ?
Et pourquoi **deux** fils automatiques ? Il va falloir reprendre ceci.

![image](https://github.com/DraftBot/Documentation/assets/111301542/9f851232-1c43-47af-b14b-540fc2b62e92)

```suggestion
### ✨ Fils de discussions automatiques

En cliquant sur le bouton "✨ Fils de discussions automatiques", vous aurez accès à ce menu :

"Activer l'ouverture d'un fil" ➜ Une fois cette option activée, **DraftBot** ouvrira un fil sous chaque suggestion soumise.
"Modifier le nom du fil" ➜ Vous pourrez modifier le nom du fil qui s'ouvrira sous chaque suggestion.

{% hint style="info" %}
Vous pouvez mettre différentes variables dans le nom du fil :

### ✨ Fils de discussions automatiques (*Avantage Premium*)

En cliquant sur le bouton "✨ Fils de discussions automatiques", vous aurez accès à ce menu :

"Activer l'ouverture d'un fil" ➜ Une fois cette option activée, **DraftBot** ouvrira un fil sous chaque suggestion soumise.
"Modifier le nom du fil" ➜ Vous pourrez modifier le nom du fil qui s'ouvrira sous chaque suggestion.

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +Si vous n'avez pas encore configurer le système, vous tomberez sur cette page :
```suggestion
Si vous n'avez pas encore configuré le système, vous tomberez sur cette page :

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +En cliquant sur "Configurer en quelques secondes" vous tomberez sur ce pop-up :
```suggestion
En cliquant sur "Configurer en quelques secondes", vous tomberez sur ce pop-up :

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +"Salons des suggestions" ➜ Paramétré le salon dans lequel seront envoyées les suggestions.
```suggestion
"Salons des suggestions" ➜ Paramétrer le salon dans lequel seront envoyées les suggestions.

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +"Rôle à mentionner" ➜ Paraméter le rôle qui sera mentionné lors de l'envoi d'une nouvelle suggestion.
```suggestion
"Rôle à mentionner" ➜ Paramétrer le rôle qui sera mentionné lors de l'envoi d'une nouvelle suggestion.

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +Cette option n'est pas désactivable, si vous décidez de ne pas la personnalisée, voici le message qui sera envoyé :
```suggestion
Cette option n'est pas désactivable, si vous décidez de ne pas la personnaliser, voici le message qui sera envoyé :

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +Le vote "neutre" peut être retirer des réactions.
```suggestion
Le vote "neutre" peut être retiré des réactions.

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +"Demande de confirmation" ➜ Une fois la suggestion envoyé, **DraftBot** proposera une dernière fois au membre de pouvoir modifier sa suggestion ou encore y ajouter une image.
```suggestion
"Demande de confirmation" ➜ Une fois la suggestion envoyée, **DraftBot** proposera une dernière fois au membre de pouvoir modifier sa suggestion ou encore y ajouter une image.

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +"Ouverture automatique d'un fil de discussion" (💎) ➜ Paraméter l'ouverture automatique d'un fil lorsqu'une nouvelle suggestion est envoyée.
```suggestion
"Ouverture automatique d'un fil de discussion" (💎) ➜ Paramétrer l'ouverture automatique d'un fil lorsqu'une nouvelle suggestion est envoyée.

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +Vous pouvez mettre diffrérentes variables dans le nom du fil :
```suggestion
Vous pouvez mettre différentes variables dans le nom du fil :

2023-06-29 07:17 UTC, IIbey commented on modules/suggestions.md
> +"Notification de changements" ➜ Lorsque la suggestion change de statut, c'est à dire quelle est acceptée, refusée, ou prévue, l'auteur de la suggestion sera mentionné soit dans le fil de la suggestio
Retour à la ligne

![image](https://github.com/DraftBot/Documentation/assets/111301542/b8c2d1a8-602b-4a82-bdef-311e477f0703)

```suggestion
"Supression des réactions" ➜ Lorsqu'une suggestion sera <mark style="color:blue;">[traitée](suggestions.md#gerer-une-suggestion)</mark>, les réactions seront retirées de la suggestion.
"Commentaire de la part de l'auteur" ➜ Une fois activé, vos membres pourront ajouter un commentaire sur leur suggestion s'ils ont oublié un détail.
"Masquer le pseudo du modérateur" ➜ Le nom de la personne ayant <mark style="color:blue;">[traitée](suggestions.md#gerer-une-suggestion)</mark> la suggestion ne sera pas affiché sur la suggestion.
"Fils de tri" ➜ Une fois les suggestions <mark style="color:blue;">[traitées](suggestions.md#gerer-une-suggestion)</mark>, elles seront automatiquement dans les fils configurés ici.
"Notification de changements" ➜ Lorsque la suggestion change de statut, c'est-à-dire si elle est acceptée, refusée, ou prévue. L'auteur de la suggestion sera mentionné soit dans le fil de la suggestion (si l'option est activée), dans les fils de tri ou dans les messages privés.

2023-06-29 07:39 UTC, IIbey commented
Et forcément, reprendre les images pour mettre les fonds en transparent.

2023-06-29 10:04 UTC, DraftProducts requested changes

2023-06-29 10:04 UTC, DraftProducts commented on .gitbook/assets/suggestions/set_suggestipn.png
Petit problème au niveau du nom du fichier : `set_suggestion`

2023-06-29 16:04 UTC, bariboo commented on modules/suggestions.md
> +
Dans le fichier il y a les retours à la ligne mais pas dans la preview, je ne sais pas pourquoi, je demamderai à DraftMan.

2023-06-29 16:04 UTC, bariboo commented on modules/suggestions.md
> +"<mark style="color:blue;">Définir le fil des suggestions refusée</mark>" ➜ Une fois le fil défini, toute les suggestions refusées se rendront automatiquement dans ce fil.
Dans le fichier il y a les retours à la ligne mais pas dans la preview, je ne sais pas pourquoi, je demamderai à DraftMan.

2023-06-29 16:15 UTC, bariboo commented on modules/suggestions.md
> +"Notification de changements" ➜ Lorsque la suggestion change de statut, c'est à dire quelle est acceptée, refusée, ou prévue, l'auteur de la suggestion sera mentionné soit dans le fil de la suggestio
Dans le fichier il y a les retours à la ligne mais pas dans la preview, je ne sais pas pourquoi, je demamderai à DraftMan.

2023-06-29 16:36 UTC, IIbey requested changes

2023-06-29 16:36 UTC, IIbey commented on modules/suggestions.md
> +    "Mention désactivée par défaut" ➜ Une fois cette option activée, les membres ne seront pas notifiés lors du changement de statut.
Pour les retours à la ligne.

```suggestion
"Activer le tri des suggestions" ➜ Sert à activer / désactiver le tri des suggestions.\
"Masquer le nom du modérateur" ➜ Cette option sert à masquer le nom de la personne qui aura [géré la suggestion](suggestions.md#gerer-une-suggestion)..\
"Activer les notifications" ➜ Une fois cette option activée le membre qui aura fait la suggestion pourra, ou non être notifié lorsque sa suggestion changera de [statut](suggestions.md#gerer-une-suggestion).
"<mark style="color:red;">Désactiver</mark>" ➜ Désactiver le système de notifications lors du changement de statut..\
"<mark style="color:blue;">Mention activée par défaut</mark>" ➜ Une fois cette option activée, les membres seront toujours notifié lors du changement de statut.\
"Mention désactivée par défaut" ➜ Une fois cette option activée, les membres ne seront pas notifiés lors du changement de statut.

2023-06-30 08:23 UTC, IIbey requested changes
Pour les retours à la ligne.

2023-06-30 08:23 UTC, IIbey commented on modules/suggestions.md
> +Vous pourrez également décider de vous faire notifier ou non en cas d'un changement de <mark style="color:blue;">[status](suggestions.md#gerer-une-suggestion)</mark> sur l'une de vos suggestions.
```suggestion
Vous pourrez également décider de vous faire notifier ou non en cas d'un changement de <mark style="color:blue;">[statut](suggestions.md#gerer-une-suggestion)</mark> sur l'une de vos suggestions.

2023-06-30 08:23 UTC, IIbey commented on modules/suggestions.md
> +"Couleur en fonction des votes" ➜ Une fois cette option activée, **DraftBot** changera la couleur de l'embed en fonction du pourcentage de vote pour ou contre.
```suggestion
"<mark style="color:blue;">Activer le système</mark>" ➜ Permet d'activer ou désactiver le système.\
"<mark style="color:blue;">Salon de réception</mark>" ➜ Sert à définir le salon où seront envoyées les suggestions.\
"Mention" ➜ Paramétrer un rôle qui sera mentionné lors de l'envoi d'une nouvelle suggestion.\
"Couleur en fonction des votes" ➜ Une fois cette option activée, **DraftBot** changera la couleur de l'embed en fonction du pourcentage de vote pour ou contre.

2023-06-30 08:23 UTC, IIbey commented on modules/suggestions.md
> +"Vote neutre" ➜ Paramétrer l'émoji sous la suggestion pour de donné un avis neutre.
```suggestion
"Activer le retrait des réactions après traitement" ➜ Une fois la suggestion <mark style="color:blue;">[traitée](suggestions.md#gerer-une-suggestion)</mark>, **DraftBot** retirera les réactions sous la suggestion.\
"Vote favorable" ➜ Définir l'émoji sous la suggestion pour donner un avis positif.\
"Vote neutre" ➜ Paramétrer l'émoji sous la suggestion pour de donné un avis neutre.

2023-06-30 08:23 UTC, IIbey commented on modules/suggestions.md
> +"<mark style="color:blue;">Définir le fil des suggestions refusée</mark>" ➜ Une fois le fil défini, toutes les suggestions refusées se rendront automatiquement dans ce fil.
```suggestion
"<mark style="color:blue;">Définir le fil des suggestions acceptées</mark>" ➜ Une fois le fil défini, toutes les suggestions acceptées se rendront automatiquement dans ce fil.\
"<mark style="color:blue;">Définir le fil des suggestions refusée</mark>" ➜ Une fois le fil défini, toutes les suggestions refusées se rendront automatiquement dans ce fil.

2023-06-30 08:23 UTC, IIbey commented on modules/suggestions.md
> +"Modifier le nom du fil" ➜ Vous pourrez modifier le nom du fil qui s'ouvrira sous chaque suggestion.
```suggestion
"Activer l'ouverture d'un fil" ➜ Une fois cette option activée, **DraftBot** ouvrira un fil sous chaque suggestion soumise.\
"Modifier le nom du fil" ➜ Vous pourrez modifier le nom du fil qui s'ouvrira sous chaque suggestion.

2023-06-30 08:23 UTC, IIbey commented on modules/suggestions.md
> +"Modération des suggestions" ➜ Une fois cette option activée, les suggestions pourront être [refusées, acceptées ou prévues](suggestions.md#gerer-une-suggestion).
```suggestion
"Suggestions par membre" ➜ Vous pourrez y limiter le nombre de suggestion <mark style="color:blue;">[non-traitée](suggestions.md#gerer-une-suggestion)</mark> par membre.\
"Rôle à mentionner" ➜ Paraméter le rôle qui sera mentionné lors de l'envoi d'une nouvelle suggestion.\
"Modération des suggestions" ➜ Une fois cette option activée, les suggestions pourront être [refusées, acceptées ou prévues](suggestions.md#gerer-une-suggestion).

2023-06-30 08:23 UTC, IIbey commented on modules/suggestions.md
> +"Notification de changements" ➜ Lorsque la suggestion change de statut, c'est-à-dire si elle est acceptée, refusée, ou prévue. L'auteur de la suggestion sera mentionné soit dans le fil de la suggesti
```suggestion
"Supression des réactions" ➜ Lorsqu'une suggestion sera <mark style="color:blue;">[traitée](suggestions.md#gerer-une-suggestion)</mark>, les réactions seront retirées de la suggestion.\
"Commentaire de la part de l'auteur" ➜ Une fois activé, vos membres pourront ajouter un commentaire sur leur suggestion s'ils ont oublié un détail.\
"Masquer le pseudo du modérateur" ➜ Le nom de la personne ayant <mark style="color:blue;">[traitée](suggestions.md#gerer-une-suggestion)</mark> la suggestion ne sera pas affiché sur la suggestion.\
"Fils de tri" ➜ Une fois les suggestions <mark style="color:blue;">[traitées](suggestions.md#gerer-une-suggestion)</mark>, elles seront automatiquement dans les fils configurés ici.\
"Notification de changements" ➜ Lorsque la suggestion change de statut, c'est-à-dire si elle est acceptée, refusée, ou prévue. L'auteur de la suggestion sera mentionné soit dans le fil de la suggestion (si l'option est activée), dans les fils de tri ou dans les messages privés.

2023-07-01 11:09 UTC, bariboo commented
@DraftProducts pourrai tu regarder pour les images ? 

Ce serait possible que mettes à jour aussi la branche car j'ai que les pages d'il y a longtemps et je pense que ça va résoudre les conflict !

2023-07-01 12:40 UTC, ErwanGit requested changes

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +
La partie commentaires n'est pas du tout mentionné ici

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +Vous pouvez alors sélectionner le bouton "<mark style="color:blue;">Ajouter un commentaire sur l'une de ces suggestions</mark>" pour en ajouter un !
Je sais pas trop pour cette partie avec la question rhétorique

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +
On peut aussi réutiliser le type de la suggestion via le menu clic droit, ou l'on aura le choix entre modifier la raison ou remettre en attente

Par exemple, si la suggestion est acceptée, il suffit de faire clic droit, "Suggestion acceptée", puis aura le menu qui s'affichera entre les deux choix "Remettre en attente" et "Modifier la raison"

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +{% endhint %}
Dans toute cette partie, il y a des antislash qui sont affichés très souvent en fin de phrase
![image](https://github.com/DraftBot/Documentation/assets/24718500/5dec4009-0aed-4bbf-b984-99e74e5477c5)

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +* "Salons des suggestions" ➜ Paramétrer le salon dans lequel seront envoyées les suggestions.
```suggestion
* "Salon des suggestions" ➜ Paramétrer le salon dans lequel seront envoyées les suggestions.
```

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +* "Modération des suggestions" ➜ Une fois cette option activée, les suggestions pourront être [refusées, acceptées ou prévues](suggestions.md#gerer-une-suggestion).
Encore le problème des anti slash

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +* "Activer la confirmation avant envoi" ➜ Cette option sert à ce que le membre puisse modifier sa suggestion s'il se rend compte qu'il a fait une erreur ou à ajouter une image.
```suggestion
* "Activer la confirmation avant envoi" ➜ Cette option sert à ce que le membre puisse modifier sa suggestion s'il se rend compte qu'il a fait une erreur ou à ajouter une image avant de l'envoyer.
```

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +* "Mention désactivée par défaut" ➜ Une fois cette option activée, les membres ne seront pas notifiés lors du changement de statut.
**Par défaut**, ce n'est pas parce que l'option "Mention activée par défaut" est activé que le membre sera toujours notifié, même si le paragraphe d'après indique bien que c'est gérable par le membre

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +Le nombre de suggestions en simultané peut varier de **1** à **10**.
J'aime pas trop comment est employé le mot "varié", le nombre maximum de suggestions en simultané ne varie pas sauf si l'administrateur modifie la configuration

Proposition, à voir si tu as une meilleure idée
```suggestion
Le nombre de suggestions en simultané peut être compris entre **1** et **10**.
```

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +Une fois la suggestion [traitée](suggestions.md#gerer-une-suggestion), le membre pourra renvoyer une suggestion.
Proposition
```suggestion
Une fois la suggestion [traitée](suggestions.md#gerer-une-suggestion), elle ne sera plus comptabilisé dans le nombre de suggestions simultanées par membre.  
```

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +Pour accepter une suggestion, vous pouvez utiliser la commande <mark style="color:orange;">/suggestmod accepter</mark>. Vous devrez ensuite saisir l'<mark style="color:blue;">[identifiant](https://do
Pas sûr pour le "acceptée" mais j'aime pas trop personnellement le texte entre parenthèse 
```suggestion
Pour accepter une suggestion, vous pouvez utiliser la commande <mark style="color:orange;">/suggestmod accepter</mark>. Vous devrez ensuite saisir l'<mark style="color:blue;">[identifiant](https://docs.draftbot.fr/autres/recuperer-un-identifiant#message)</mark> du message de la suggestion à acceptée. Finalement, un menu s'ouvrira afin de vous demander la raison d'acceptation.
```

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +Pour refuser une suggestion, vous pouvez utiliser la commande <mark style="color:orange;">/suggestmod refuser</mark>. Vous devrez ensuite saisir l'<mark style="color:blue;">[identifiant](https://docs
```suggestion
Pour refuser une suggestion, vous pouvez utiliser la commande <mark style="color:orange;">/suggestmod refuser</mark>. Vous devrez ensuite saisir l'<mark style="color:blue;">[identifiant](https://docs.draftbot.fr/autres/recuperer-un-identifiant#message)</mark> du message de la suggestion à refusée. Finalement, un menu s'ouvrira afin de vous demander la raison de refus.
```

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +Pour prévoir une suggestion, vous pouvez utiliser la commande <mark style="color:orange;">/suggestmod prevue</mark>. Vous devrez ensuite saisir l'<mark style="color:blue;">[identifiant](https://docs.
```suggestion
Pour prévoir une suggestion, vous pouvez utiliser la commande <mark style="color:orange;">/suggestmod prevue</mark>. Vous devrez ensuite saisir l'<mark style="color:blue;">[identifiant](https://docs.draftbot.fr/autres/recuperer-un-identifiant#message)</mark> du message de la suggestion à marquée comme prévue. Finalement, un menu s'ouvrira afin de vous demander la raison de prévision.
```

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +Vous vous rendez compte que vous avez fait une erreur ? Vous pouvez toujours repasser une suggestion en attente via la commande <mark style="color:orange;">/suggestmod attente</mark>. Vous aurez ensu
```suggestion
Vous vous rendez compte que vous avez fait une erreur ? Vous pouvez toujours repasser une suggestion en attente via la commande <mark style="color:orange;">/suggestmod attente</mark>. Vous aurez ensuite à saisir l'<mark style="color:blue;">[identifiant](https://docs.draftbot.fr/autres/recuperer-un-identifiant#message)</mark> du message de la suggestion.
```

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +Pour accepter une suggestion, vous pouvez utiliser la commande <mark style="color:orange;">/suggestmod accepter</mark>. Vous devrez ensuite saisir l'<mark style="color:blue;">[identifiant](https://do
Il y a pas de modal d'ouvert lorsque la commande est utilisée 🤔

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +Pour refuser une suggestion, vous pouvez utiliser la commande <mark style="color:orange;">/suggestmod refuser</mark>. Vous devrez ensuite saisir l'<mark style="color:blue;">[identifiant](https://docs
Il y a pas de modal d'ouvert lorsque la commande est utilisée 🤔

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +Pour prévoir une suggestion, vous pouvez utiliser la commande <mark style="color:orange;">/suggestmod prevue</mark>. Vous devrez ensuite saisir l'<mark style="color:blue;">[identifiant](https://docs.
Il y a pas de modal d'ouvert lorsque la commande est utilisée 🤔

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +Vous avez aussi la possibilité de faire un clic droit (sur ordinateur) ou appuyez longtemps (sur mobile) sur la suggestion en question puis d'appuyez sur "Applications". Vous aurez ensuite la possibi
```suggestion
Vous avez aussi la possibilité de faire un clic droit (sur ordinateur) ou d'appuyer longtemps (sur mobile) sur la suggestion en question puis d'aller dans "Applications". Vous aurez ensuite la possibilité de refuser la suggestion.
```

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +Vous avez aussi la possibilité de faire un clic droit (sur ordinateur) ou appuyez longtemps (sur mobile) sur la suggestion en question puis d'appuyez sur "Applications". Vous aurez ensuite la possibi
```suggestion
Vous avez aussi la possibilité de faire un clic droit (sur ordinateur) ou d'appuyer longtemps (sur mobile) sur la suggestion en question puis d'aller dans "Applications". Vous aurez ensuite la possibilité d'accepter la suggestion.
```

2023-07-01 12:40 UTC, ErwanGit commented on modules/suggestions.md
> +Vous avez aussi la possibilité de faire un clic droit (sur ordinateur) ou appuyez longtemps (sur mobile) sur la suggestion en question puis d'appuyez sur "Applications". Vous aurez ensuite la possibi
```suggestion
Vous avez aussi la possibilité de faire un clic droit (sur ordinateur) ou d'appuyer longtemps (sur mobile) sur la suggestion en question puis d'aller dans "Applications". Vous aurez ensuite la possibilité de "prévoir" la suggestion.
```

2023-07-01 12:40 UTC, ErwanGit commented on .gitbook/assets/suggestions/create_suggestion.png
J'ai un doute sur l'accent à "ou" dans la description de la suggestion

2023-07-01 12:40 UTC, ErwanGit commented on .gitbook/assets/suggestions/set_suggestion.png
Il faudrait refaire les captures d'écrans avec DraftBot et non DraftBot PTB

2023-07-01 12:40 UTC, ErwanGit commented on .gitbook/assets/suggestions/set_suggestion_automatic_thread.png
Il faudrait refaire les captures d'écrans avec DraftBot et non DraftBot PTB

2023-07-01 12:40 UTC, ErwanGit commented on .gitbook/assets/suggestions/suggest_menu.png
Il faudrait refaire les captures d'écrans avec DraftBot et non DraftBot PTB
Aussi, j'avais retiré le "warning" concernant dans la description concernant la 5.0.0 récemment

2023-07-02 12:25 UTC, bariboo commented on modules/suggestions.md
> +* "Mention désactivée par défaut" ➜ Une fois cette option activée, les membres ne seront pas notifiés lors du changement de statut.
Donc je retire le "toujours" ?

2023-07-02 12:55 UTC, bariboo commented on .gitbook/assets/suggestions/create_suggestion.png
Pas compris.

2023-07-02 12:59 UTC, bariboo commented on .gitbook/assets/suggestions/set_suggestion_automatic_thread.png
Sachant que le nom du bot et la photo de profil ne seront pas visiblement une fois que @DraftProducts aura retiré les fonds, est ce que ça vaut réellement le coup ? Ca ne va rien changer puisque que PTB n'a rien de plus que DraftBot sur ce screen.

2023-07-02 13:03 UTC, bariboo commented on .gitbook/assets/suggestions/set_suggestion.png
Cette image était dupliquée, je l'ai retiré (par set_suggestion_automatic_thread).

2023-07-02 13:03 UTC, bariboo commented on .gitbook/assets/suggestions/create_suggestion.png
De toute façon cette image était dupliquée, je l'ai supprimée.

2023-07-02 13:04 UTC, bariboo commented on .gitbook/assets/suggestions/set_suggestion.png
Image dupliquée = supprimée

2023-07-02 14:26 UTC, DraftProducts approved these changes

2023-07-02 18:26 UTC, ErwanGit commented on modules/suggestions.md
> +* "Mention désactivée par défaut" ➜ Une fois cette option activée, les membres ne seront pas notifiés lors du changement de statut.
Oui

2023-07-02 18:37 UTC, ErwanGit requested changes

2023-07-02 18:37 UTC, ErwanGit commented on .gitbook/assets/suggestions/create_suggestion.png
et/où => et/ou ?

2023-07-02 18:37 UTC, ErwanGit commented on .gitbook/assets/suggestions/set_suggestion_automatic_thread.png
On a une image de DraftBot PTB, pour un utilisateur lambda, il va pas comprendre pourquoi il y a un "DraftBot bleu"

2023-07-02 18:37 UTC, ErwanGit commented on .gitbook/assets/suggestions/view.png
C'est une vieille photo ça, en plus, j'ai l'impression qu'elle est utilisée nul part

2023-07-02 18:37 UTC, ErwanGit commented on modules/suggestions.md
> +* "Vote neutre" ➜ Paramétrer l'émoji sous la suggestion pour de donné un avis neutre.
```suggestion
* "Vote neutre" ➜ Paramétrer l'émoji sous la suggestion pour donner un avis neutre.
```

2023-07-02 18:37 UTC, ErwanGit commented on modules/suggestions.md
> +* "Vote défavorable" ➜ Permet de définir l'émoji sous la suggestion pour de donné un avis négatif.
```suggestion
* "Vote défavorable" ➜ Permet de définir l'émoji sous la suggestion pour donner un avis négatif.
```

2023-07-03 09:09 UTC, bariboo commented on .gitbook/assets/suggestions/set_suggestion_automatic_thread.png
@DraftProducts possible de regarder ça ? Je ne peux pas faire de screen puisque je suis pas premium.

2023-07-03 14:08 UTC, ErwanGit requested changes

2023-07-03 14:08 UTC, ErwanGit commented on modules/suggestions.md
> +Vous avez besoin de la permission "Gérer les messages" pour pouvoir accepter, refuser ou prévoir une suggestion.
On peut normalement modifier les permissions directement sur Discord

2023-07-03 14:08 UTC, ErwanGit commented on .gitbook/assets/suggestions/set_suggestion_automatic_thread.png
Capture prise avec PTB et non DraftBot

2023-07-03 14:30 UTC, IIbey requested changes

2023-07-03 14:30 UTC, IIbey commented on modules/suggestions.md
> +Il faut que l'option "Notification lors du changement de statut" soit <mark style="color:blue;">[activée](suggestions.md#tri-des-suggestions)</mark> sur le serveur. Si ce n'est pas le cas, vous ne ve
```suggestion
Il faut que l'option "Notification lors du changement de statut" soit <mark style="color:blue;">[activée](suggestions.md#tri-des-suggestions)</mark> sur le serveur. Si ce n'est pas le cas, vous ne verrez pas le bouton "Me notifier en cas de changement de statut".

2023-07-03 14:30 UTC, IIbey commented on modules/suggestions.md
> +Vous avez aussi la possibilité de repasser une suggestion en attente ou en changer la raison en passant depuis le menu "Applications" puis sélectionner la même option de classement (accepter si la su
```suggestion
Vous avez aussi la possibilité de repasser une suggestion en attente ou en changer la raison en passant depuis le menu "Applications" puis de sélectionner la même option de classement (accepter si la suggestion est acceptée).

2023-07-03 14:30 UTC, IIbey commented on modules/suggestions.md
> +Si vous êtes souscrit à un abonnement <mark style="color:pink;">[premium](https://draftbot.fr/premium)</mark>, vous pourrez chosir les couleurs du dégradé, en cliquant sur "✨ Dégradé personnalisé".
```suggestion
Si vous êtes souscrit à un abonnement <mark style="color:pink;">[premium](https://draftbot.fr/premium)</mark>, vous pourrez choisir les couleurs du dégradé, en cliquant sur "✨ Dégradé personnalisé".

2023-07-03 14:30 UTC, IIbey commented on modules/suggestions.md
> +Une fois la suggestion [traitée](suggestions.md#gerer-une-suggestion), elle ne sera plus comptabilisé dans le nombre de suggestions simultanées par membre.
```suggestion
Une fois la suggestion [traitée](suggestions.md#gerer-une-suggestion), elle ne sera plus comptabilisée dans le nombre de suggestions simultanées par membre.

2023-07-03 14:30 UTC, IIbey commented on modules/suggestions.md
> +* "Rôle à mentionner" ➜ Paraméter le rôle qui sera mentionné lors de l'envoi d'une nouvelle suggestion.
```suggestion
* "Rôle à mentionner" ➜ Paramétrer le rôle qui sera mentionné lors de l'envoi d'une nouvelle suggestion.

2023-07-03 14:30 UTC, IIbey commented on modules/suggestions.md
> +- `{user.tag}` ➜ Tag du membre _(Pseudo#0000)_
Le {user.tag}, on le laisse ? Vu que ça ne sera bientôt plus d'actualité. 🤔 
@DraftProducts @ErwanGit

2023-07-03 14:42 UTC, ErwanGit commented on modules/suggestions.md
> +- `{user.tag}` ➜ Tag du membre _(Pseudo#0000)_
Je l'avais retiré de l'ensemble du bot lors des questions mais il est encore fonctionnel 

```
{user}
{user.id}
{user.username}
{user.globalname}
{user.nickname}
{server}
{server.id}
{server.name}
{server.membercount}
{channel}
{channel.id}
{channel.name}
{date}
{time}
{timestamp}
```

2023-07-03 14:43 UTC, IIbey commented on modules/suggestions.md
> +- `{user.tag}` ➜ Tag du membre _(Pseudo#0000)_
Donc autant le retirer sur la doc ?

2023-07-03 14:44 UTC, ErwanGit commented on modules/suggestions.md
> +- `{user.tag}` ➜ Tag du membre _(Pseudo#0000)_
Oui

2023-07-03 14:45 UTC, IIbey commented on modules/suggestions.md
> +- `{user.tag}` ➜ Tag du membre _(Pseudo#0000)_
D'accord, merci pour tes précisions :)

2023-07-05 21:00 UTC, bariboo commented on .gitbook/assets/suggestions/set_suggestion_automatic_thread.png
Faut voir avec DraftMan. J'ai pas premium sur DraftBot stable.

2023-07-05 21:13 UTC, bariboo commented
@DraftProducts si tu peux voir pour cette image (automatic thread) se serait top +

2023-07-11 08:08 UTC, bariboo commented
@ErwanGit @IIbey tout bon ?

2023-07-17 20:49 UTC, ErwanGit requested changes

2023-07-17 20:49 UTC, ErwanGit commented on modules/suggestions.md
> +Vous avez besoin de la permission "Gérer les messages" pour pouvoir accepter, refuser ou prévoir une suggestion. Toutefois, vous pouvez toujours modifier cette permission depuis les paramètres de vot
La commande `/suggesmod` n'est pas mise en valeur avec le markdown
Je trouve aussi le texte assez gros et il ne donne pas du tout envie de le lire, peut-être mieux espacer/ajouter des sauts de ligne
<img width="779" alt="image" src="https://github.com/DraftBot/Documentation/assets/24718500/d02cbb74-6702-4939-8f55-365c4f122cc2">

2023-07-17 20:49 UTC, ErwanGit commented on modules/suggestions.md
> +Vous avez aussi la possibilité de repasser une suggestion en attente ou en changer la raison en passant depuis le menu "Applications" puis de sélectionner la même option de classement (accepter si la
Je n'aime pas du tout la formulation "option de classement"

2023-07-17 20:49 UTC, ErwanGit commented on .gitbook/assets/suggestions/set_suggestion_confirmation.png
Je préférerai un autre nom pour le serveur de la capture d'écran, autre que "DraftBot BETA"

2023-07-17 20:49 UTC, ErwanGit commented on .gitbook/assets/suggestions/set_suggestion_member.png
Je préférerai un autre nom pour le serveur de la capture d'écran, autre que "DraftBot BETA"

2023-07-17 20:49 UTC, ErwanGit commented on .gitbook/assets/suggestions/set_suggestion_reactions.png
Je préférerai un autre nom pour le serveur de la capture d'écran, autre que "DraftBot BETA"

2023-07-17 20:49 UTC, ErwanGit commented on .gitbook/assets/suggestions/set_suggestion_sorting.png
Je préférerai un autre nom pour le serveur de la capture d'écran, autre que "DraftBot BETA"

2023-07-17 20:49 UTC, ErwanGit commented on .gitbook/assets/suggestions/suggest_menu.png
Je préférerai un autre nom pour le serveur de la capture d'écran, autre que "DraftBot BETA n°2"

2023-07-18 05:57 UTC, bariboo commented on .gitbook/assets/suggestions/suggest_menu.png
Un exemple ?  DraftBot Documentation ?

2023-07-18 09:04 UTC, ErwanGit commented on .gitbook/assets/suggestions/suggest_menu.png
DraftBot Support comme les autres captures d'écran m'allait très bien

2023-08-24 15:08 UTC, bariboo commented on .gitbook/assets/suggestions/set_suggestion_member.png
@DraftProducts est il possible de modifier ce qui est écrit dans un texte avec Ps ? Puisque c'est uniquement pour un nom de server, je souhaiterai savoir si tu pourrais t'en charger (si c'est possible via Ps, si non je m'en charge).

2023-08-24 15:11 UTC, bariboo commented
Oups je me suis trompé 🤐

2023-08-24 15:12 UTC, bariboo commented on .gitbook/assets/suggestions/suggest_menu.png
Avant je mettais "Examen de DraftBot", je n'ai jamais mis "*DraftBot Support*".

(Tu mettais dans ton message que DraftBot support t'allais très bien.)

2023-09-07 16:34 UTC, DraftProducts approved these changes

2023-09-14 12:45 UTC, IIbey approved these changes

2023-09-15 18:57 UTC, ErwanGit approved these changes

2023-09-15 18:58 UTC, ErwanGit approved these changes

2023-09-15 21:00 UTC, merged

2023-09-15 21:00 UTC, DraftProducts commented
Félicitations pour cette page 🔥