Création de la page "inventaires"
DraftBot/Documentation pull request #59
Opened 2023-06-23 08:26 UTC by IIbey

2023-06-23 09:29 UTC, ErwanGit requested changes

2023-06-23 09:29 UTC, ErwanGit commented on modules/inventaire.md
> +- **Le dropitem** : Qui fait apparaître un message où vous devez être le plus rapide pour récupérer l'objet.
```suggestion
- **La commande /dropitem** : Qui fait apparaître un message où vous devez être le plus rapide pour récupérer l'objet.

```

2023-06-23 09:29 UTC, ErwanGit commented on modules/inventaire.md
> +## Le dropitem
```suggestion
## La commande /dropitem
```

2023-06-23 09:36 UTC, IIbey commented on modules/inventaire.md
> +## Le dropitem
Elle a changé de nom entre temps en /objet drop, je me rends compte mdr

2023-06-23 10:06 UTC, ErwanGit requested changes

2023-06-23 10:06 UTC, ErwanGit commented on modules/inventaire.md
> +- **La commande /objet drop** : Qui génère un message où vous devez être le plus rapide pour récupérer l'objet.
Il y a le /dropitem (give admin) et le /objet drop, provenant de l'inventaire du membre

2023-06-23 10:09 UTC, IIbey commented on modules/inventaire.md
> +- **La commande /objet drop** : Qui génère un message où vous devez être le plus rapide pour récupérer l'objet.
Ah mais les fonctions sont les mêmes fiou 😂 
Va falloir que je le précise pour les deux !

2023-06-23 11:45 UTC, ErwanGit requested changes

2023-06-23 11:45 UTC, ErwanGit commented on modules/inventaire.md
> +Les commandes <mark style="color:orange;">/dropitem</mark> et <mark style="color:orange;">/objet drop</mark> ont pour but de générer un message et d'offrir l'objet à la première personne qui clique s
```suggestion
Les commandes <mark style="color:orange;">/dropitem</mark> et <mark style="color:orange;">/objet drop</mark> ont pour but de générer un message et d'offrir l'objet à la première personne qui clique sur le bouton **"Récupérer !"** dans un délai de 60 secondes. 
```

2023-06-23 11:48 UTC, ErwanGit approved these changes

2023-06-23 11:56 UTC, Tellvex commented on modules/inventaire.md
> +- **Les commandes <mark style="color:orange;">/dropitem</mark> et <mark style="color:orange;">/objet drop</mark>** : Elles génèrent un message où vous devez être le plus rapide pour récupérer l'objet
C'est pas un peu répétitif avec la partie en bas ?

2023-06-23 11:58 UTC, DraftProducts requested changes

2023-06-23 11:58 UTC, DraftProducts commented on modules/inventaire.md
> +- **Les commandes <mark style="color:orange;">/dropitem</mark> et <mark style="color:orange;">/objet drop</mark>** : Elles génèrent un message où vous devez être le plus rapide pour récupérer l'objet
Il manque peut être une petite ligne pour le giveaway et les anniversaires.

2023-06-23 12:01 UTC, DraftProducts commented on modules/inventaire.md
> +- **Les commandes <mark style="color:orange;">/dropitem</mark> et <mark style="color:orange;">/objet drop</mark>** : Elles génèrent un message où vous devez être le plus rapide pour récupérer l'objet
C'est une énumération, si elle enlevait les parties répétitives ce serait moins clair je pense.
T'aurais une proposition ?

2023-06-23 12:03 UTC, IIbey commented on modules/inventaire.md
> +- **Les commandes <mark style="color:orange;">/dropitem</mark> et <mark style="color:orange;">/objet drop</mark>** : Elles génèrent un message où vous devez être le plus rapide pour récupérer l'objet
Je l'ai fait exprès pour ensuite plus détaillé.

2023-06-23 16:23 UTC, IIbey commented
@bariboo Je dirais que ce n'est pas dramatique, car ça n'aurait pas de grand intérêt si je retire tout ce qui touche les inventaires de ma page. Et puis de toute façon, j'ai fait un lien vers ta page économie pour la configuration.

2023-06-23 23:27 UTC, DraftProducts approved these changes

2023-06-24 09:51 UTC, bariboo requested changes

2023-06-24 09:51 UTC, bariboo commented on modules/inventaire.md
> +- **Les commandes <mark style="color:orange;">/dropitem</mark> et <mark style="color:orange;">/objet drop</mark>** : Elles génèrent un message où vous devez être le plus rapide pour récupérer l'objet
```suggestion
- **Les récompenses de niveaux** : Configurable depuis la commande <mark style="color:orange;">/config</mark> ➜ "[Niveaux](https://docs.draftbot.fr/modules/niveaux)" ou via le [panel web](https://www.draftbot.fr/dashboard/user).
- **L'achat dans la boutique** : Configurable depuis la commande <mark style="color:orange;">/config</mark> ➜ "[Économie](https://docs.draftbot.fr/modules/economie)" ou via le [panel web](https://www.draftbot.fr/dashboard/user).
- **Les cadeaux d'anniversaires** : Configurable depuis la commande <mark style="color:orange;">/config</mark> ➜ "[Anniversaires](https://docs.draftbot.fr/modules/anniversaires)" ou via le [panel web](https://www.draftbot.fr/dashboard/user).
- **Les concours (giveaway)** : Lorsqu'on utilise la commande <mark style="color:orange;">/concours créer item</mark>.
- **Les échanges entre membres** : Avec la commande <mark style="color:orange;">/objet</mark>.
- **Les commandes <mark style="color:orange;">/dropitem</mark> et <mark style="color:orange;">/objet drop</mark>** : Elles génèrent un message où vous devez être le plus rapide pour récupérer l'objet.
```

2023-06-24 09:52 UTC, bariboo commented on modules/inventaire.md
> +- **Les commandes <mark style="color:orange;">/dropitem</mark> et <mark style="color:orange;">/objet drop</mark>** : Elles génèrent un message où vous devez être le plus rapide pour récupérer l'objet
Je pense pas ça valle la peine de le mettre en couleur, il y en aurait trop, mais au moins l'utilisateur peut y accéder plus facilement.

2023-06-24 10:08 UTC, IIbey commented on modules/inventaire.md
> +- **Les commandes <mark style="color:orange;">/dropitem</mark> et <mark style="color:orange;">/objet drop</mark>** : Elles génèrent un message où vous devez être le plus rapide pour récupérer l'objet
C'est volontaire.

Je préfère laisser comme tel et pour que les membres puissent se focaliser sur les pages de configuration des anniversaires, économie, etc... sinon, je l'aurais déjà mis.

2023-06-24 10:24 UTC, bariboo commented on modules/inventaire.md
> +- **Les commandes <mark style="color:orange;">/dropitem</mark> et <mark style="color:orange;">/objet drop</mark>** : Elles génèrent un message où vous devez être le plus rapide pour récupérer l'objet
Ok !

2023-06-24 10:24 UTC, bariboo approved these changes

2023-06-24 11:44 UTC, DraftProducts commented
Il avait déjà dit que c'était bon pour lui via ces réactions.

2023-06-24 11:44 UTC, merged