Création de la page "Compteur de membres"
DraftBot/Documentation pull request #61
Opened 2023-06-27 09:26 UTC by IIbey

2023-06-27 12:03 UTC, DraftProducts approved these changes

2023-06-27 13:45 UTC, DraftProducts requested changes

2023-06-27 13:56 UTC, DraftProducts requested changes

2023-06-27 13:56 UTC, DraftProducts commented on modules/compteur-de-membres.md
> +{% endhint %}
```suggestion
{% hint style="info" %}
Tous les caractères avant le " - " dans le nom de la catégorie peuvent être modifiés.
{% endhint %}
```

2023-06-27 13:56 UTC, DraftProducts commented on modules/compteur-de-membres.md
> +
```suggestion

{% hint style="info" %}
Tous les caractères avant le " : " dans le nom des salons peuvent être modifiés.
{% endhint %}

```

2023-06-27 16:30 UTC, DraftProducts approved these changes

2023-06-27 18:27 UTC, ErwanGit approved these changes

2023-06-27 18:27 UTC, ErwanGit commented on modules/compteur-de-membres.md
> +Lors de la configuration de la fonctionnalité en vous rendant dans la commande <mark style="color:orange;">/config</mark> ➜ **"🧮 Compteur de membres"**, vous aurez le choix entre deux design :
J'ai un doute 
```suggestion
Lors de la configuration de la fonctionnalité en vous rendant dans la commande <mark style="color:orange;">/config</mark> ➜ **"🧮 Compteur de membres"**, vous aurez le choix entre deux designs :
```

2023-06-28 15:51 UTC, DraftProducts approved these changes

2023-06-28 17:00 UTC, merged