Création de la page "Commandes d'informations"
DraftBot/Documentation pull request #62
Opened 2023-06-29 09:17 UTC by IIbey

2023-06-29 16:05 UTC, DraftProducts approved these changes

2023-06-29 18:42 UTC, ErwanGit requested changes

2023-06-29 18:42 UTC, ErwanGit commented on modules/commandes-informations.md
> +- Quelques badges : s'il possède le premium et s'il est membre de la HypeSquad de Discord.
Pas d'accord avec ça, il y a aussi d'autres badges comme ceux de Discord avec les partenaires, "développeur actif", les membres de l'équipe de DraftBot, etc

2023-06-29 18:42 UTC, ErwanGit commented on modules/commandes-informations.md
> +Il est possible de voir les informations d'un utilisateur autre que le vôtre en le **mentionnant** ou en utilisant son **pseudonyme** après la commande. Par exemple : <mark style="color:orange;">/inf
Ou son identifiant, et on le mentionne pas vraiment

2023-06-29 18:42 UTC, ErwanGit commented on modules/commandes-informations.md
> +Pour différencier un salon et une catégorie, une icône "📁" apparaîtra à côté du nom de la catégorie.
Il y a aussi une icône pour les salons vocaux, d'annonces, etc

2023-06-29 18:42 UTC, ErwanGit commented on modules/commandes-informations.md
> +Il est possible de voir le profil d'un utilisateur autre que le vôtre en le **mentionnant** ou en utilisant son **pseudonyme** après la commande. Par exemple : <mark style="color:orange;">/profil [me
Même chose que plus haut

2023-06-29 18:42 UTC, ErwanGit commented on modules/commandes-informations.md
> +Vous pouvez ajouter une petite description sur votre profil avec la commande <mark style="color:orange;">/description</mark>.
Un peu de mal avec le "**petite** description"

2023-06-29 18:42 UTC, ErwanGit commented on modules/commandes-informations.md
> +## Info utilisateur
Un peu de mal avec les titres, peut-être /info utilisateur, etc directement ?

2023-06-29 19:42 UTC, IIbey commented on modules/commandes-informations.md
> +## Info utilisateur
J'ai repris le genre de titre comme je l'avais fait pour :

![image](https://github.com/DraftBot/Documentation/assets/111301542/9d859f9a-18c1-439f-86d4-d707e820e5ca)

2023-06-29 19:45 UTC, ErwanGit requested changes

2023-06-29 19:45 UTC, ErwanGit commented on modules/commandes-informations.md
> +## La commande /info utilisateur
"La commande" trop redondant je pense et puis ne se voie pas/mal sur le côté 
<img width="227" alt="image" src="https://github.com/DraftBot/Documentation/assets/24718500/257ab298-9397-4d54-a5d5-c7d8dc771854">

2023-06-29 19:47 UTC, IIbey commented on modules/commandes-informations.md
> +## La commande /info utilisateur
Oki, je vais retirer du coup :)

2023-06-29 20:21 UTC, ErwanGit approved these changes

2023-06-30 08:06 UTC, IIbey commented
Je n'ai plus grand chose à modifier/ajouter, si vous voulez merge la page @DraftProducts @ErwanGit :3

2023-06-30 08:40 UTC, Tellvex reviewed
Petits détails qui seraient éventuellement à corriger/modifier. Ce n'est qu'une suggestion, donc ce n'est pas grave si cela n'est pas pris en compte.

2023-06-30 08:40 UTC, Tellvex commented on modules/commandes-informations.md
> +- L'identifiant de l'utilisateur.
Il manquerait également la mention de l'utilisateur (bien que cela soit inutile)

2023-06-30 08:40 UTC, Tellvex commented on modules/commandes-informations.md
> +
Il faudrait également rajouter le fait qu'il soit "catégorisé" ou non (comme le montre l'embed d'exemple)

2023-06-30 08:40 UTC, Tellvex commented on modules/commandes-informations.md
> +- La localité.
Elle n'apparaît que si le membre l'a configuré

2023-06-30 08:40 UTC, Tellvex commented on modules/commandes-informations.md
> +- L'argent en sa possession sur le serveur.
Et son classement

2023-06-30 08:40 UTC, Tellvex commented on modules/commandes-informations.md
> +- Le nombre de membres, de salons, de fils, de rôles, d'émojis, de bots et de boosts.
Pour les boosts, on pourrait éventuellement rajouter le niveau de boost

2023-06-30 08:46 UTC, IIbey commented on modules/commandes-informations.md
> +- L'argent en sa possession sur le serveur.
Déjà mis

2023-06-30 08:46 UTC, IIbey commented on modules/commandes-informations.md
> +- Le nombre de membres, de salons, de fils, de rôles, d'émojis, de bots et de boosts.
Ca revient plus ou moins au même 🤔

2023-06-30 08:50 UTC, Tellvex commented on modules/commandes-informations.md
> +- L'argent en sa possession sur le serveur.
Pour l'argent aussi ?

2023-06-30 08:51 UTC, IIbey commented on modules/commandes-informations.md
> +- L'argent en sa possession sur le serveur.
" - Le niveau et le rang dans le classement du serveur.
- L'argent en sa possession sur le serveur. "

2023-07-01 10:57 UTC, bariboo approved these changes

2023-07-01 12:02 UTC, ErwanGit approved these changes

2023-07-01 12:05 UTC, IIbey commented
Pour ma part, la page est complètement terminée :)

2023-07-02 14:42 UTC, DraftProducts approved these changes

2023-07-04 08:27 UTC, Tellvex approved these changes

2023-07-04 08:29 UTC, merged