Mise à jour des rôles automatiques sur le panel
DraftBot/Documentation pull request #63
Opened 2023-07-01 14:27 UTC by bariboo

- Ajout d'une partie panel aux rôles automatiques en live.
- Correction du nom des pages et des images pour configurer les rôles en live sur le panel.
- Corrections & améliorations diverses et variées.

2023-07-01 21:56 UTC, IIbey requested changes

2023-07-01 21:56 UTC, IIbey commented on modules/roles-automatiques.md
> +Veuillez d'abord vous rendre sur le <mark style="color:blue;">[panel](https://draftbot.fr/dashboard/user/)</mark> ➜ Rôles automatiques
```suggestion
Veuillez d'abord vous rendre sur le <mark style="color:blue;">[panel](https://draftbot.fr/dashboard/user/)</mark> ➜ Rôles automatiques.

2023-07-01 21:56 UTC, IIbey commented on modules/roles-automatiques.md
> +Vous pouvez demander à **DraftBot** de donner le rôle de live aux membres possédant un rôle spécifique défini. Pour définir ce rôle cliquez sur le deuxième sélecteur nommé "Rôles Autorisés" puis séle
```suggestion
Vous pouvez demander à **DraftBot** de donner le rôle de live aux membres possédant un rôle spécifique défini. Pour définir ce rôle, cliquez sur le deuxième sélecteur nommé "Rôles autorisés" puis sélectionnez le rôle voulu.

2023-07-02 18:47 UTC, ErwanGit requested changes

2023-07-02 18:47 UTC, ErwanGit commented on modules/roles-automatiques.md
> +![Menu d'accueil de la configuration des rôles automatiques en vocal](../.gitbook/assets/autoroless/voice.png)
```suggestion
![Menu d'accueil de la configuration des rôles automatiques en vocal](../.gitbook/assets/autoroles/voice.png)
```

2023-07-02 18:47 UTC, ErwanGit commented on modules/roles-automatiques.md
> +{% endhint %}
Au lieu de les mettre deux fois dans les tabs (panel et /config), peut-être les sortir des tabs pour avoir à maintenir qu'une seule fois le texte

2023-07-03 14:11 UTC, ErwanGit approved these changes

2023-07-03 14:58 UTC, DraftProducts approved these changes

2023-07-04 06:41 UTC, IIbey approved these changes

2023-07-04 08:29 UTC, merged