Page de commandes de jeux et de fun
DraftBot/Documentation pull request #66
Opened 2023-07-19 14:06 UTC by IIbey

2023-07-26 19:45 UTC, ErwanGit requested changes

2023-07-26 19:45 UTC, ErwanGit commented on modules/commandes-jeux-fun.md
> +La commande <mark style="color:orange;">/tv</mark> vous permet d'accéder à des informations sur **un film ou une série** disponible sur le site <mark style="color:blue;">[The Movie Database](https://
```suggestion
La commande <mark style="color:orange;">/tv</mark> vous permet d'accéder à des informations sur **un film ou une série** disponible sur le site <mark style="color:blue;">[The Movie Database](https://www.themoviedb.org/)</mark> (TMDB). Ainsi il vous suffira de définir le nom du film ou de la série que vous recherchez à la suite de la commande.

```

2023-07-31 15:52 UTC, DraftProducts requested changes

2023-08-05 20:04 UTC, DraftProducts approved these changes

2023-08-11 19:58 UTC, ErwanGit approved these changes

2023-08-11 22:58 UTC, IIbey commented
Si vous voulez la merge, c'est good. Je n'ai rien à rajouter de plus :3

2023-08-15 19:31 UTC, ErwanGit approved these changes

2023-08-15 20:42 UTC, merged