Ajout de la page signalements
DraftBot/Documentation pull request #67
Opened 2023-07-23 11:34 UTC by Rababio4579

2023-08-01 06:39 UTC, IIbey requested changes

2023-08-01 06:39 UTC, IIbey commented on modules/reports.md
> +## configuration
```Suggestion
## Configuration

2023-08-01 06:39 UTC, IIbey commented on modules/reports.md
> +- "Aciver l'ouverture d'un thread" ➜ Si activé, DraftBot ouvrira un fil quand un signalement est envoyé. <mark style="color:blue;">[premium](https://draftbot.fr/premium)</mark>
```Suggestion
- "Activer l'ouverture d'un thread" ➜ Si activé, DraftBot ouvrira un fil quand un signalement est envoyé. <mark style="color:blue;">[premium](https://draftbot.fr/premium)</mark>

2023-08-06 00:03 UTC, IIbey requested changes

2023-08-06 00:03 UTC, IIbey commented on modules/reports.md
> +- "Activer l'ouverture d'un thread" ➜ Si activé, DraftBot ouvrira un fil quand un signalement est envoyé. <mark style="color:blue;">[premium](https://draftbot.fr/premium)</mark>
Vaut mieux reprendre le même style que les autres pages pour le premium.

``` Suggestion
- "Activer l'ouverture d'un thread" ➜ Si activé, DraftBot ouvrira un fil quand un signalement est envoyé. **_([✨ premium](https://draftbot.fr/premium))_**

2023-08-06 00:03 UTC, IIbey commented on modules/reports.md
> +- Message de confirmation ➜ Défini le message qui sera envoyé à la paersonne qui fait le signalement.
```suggestion
- Message de confirmation ➜ Défini le message qui sera envoyé à la personne qui fait le signalement.

2023-08-06 00:03 UTC, IIbey commented on modules/reports.md
> +-Fil de tri <mark style="color:blue;">[premium](https://draftbot.fr/premium)</mark> ➜ Permet de de définir les fils pour les signalements résolus, refusés et sanctionnés.
```suggestion
- Fil de tri **_([✨ premium](https://draftbot.fr/premium))_** ➜ Permet de de définir les fils pour les signalements résolus, refusés et sanctionnés.

2023-08-28 07:32 UTC, IIbey requested changes

2023-08-28 07:32 UTC, IIbey commented on modules/reports.md
> +Signalements
```suggestion
Veuillez d'abord vous rendre dans la commande <mark style="color:orange;">/config</mark> ➜ 🚨 Signalements.

2023-08-28 07:32 UTC, IIbey commented on modules/reports.md
> +- `{timestamp}` ➜ Timestamp actuel en secondes
```suggestion
- `{user}` ➜ Mention du membre
- `{user.id}` ➜ Identifiant du membre
- `{user.username}` ➜ Pseudo du membre
- `{user.nickname}` ➜ Surnom ou pseudo du membre
- `{server}` ➜ Nom du serveur
- `{server.id}` ➜ Identifiant du serveur
- `{server.name}` ➜ Nom du serveur
- `{server.membercount}` ➜ Nombre de membres sur le serveur
- `{channel}` ➜ Mentions du salon
- `{channel.id}` ➜ Identifiant du salon
- `{channel.name}` ➜ Nom du salon
- `{date}` ➜ Date actuelle (JJ/MM/AAAA)
- `{time}` ➜ Heure actuelle (HH:MM)
- `{timestamp}` ➜ Timestamp actuel en secondes

2023-08-28 07:32 UTC, IIbey commented on modules/reports.md
> +- Fil de tri **_([✨ premium](https://draftbot.fr/premium))_** ➜ Permet de de définir les fils pour les signalements résolus, refusés et sanctionnés.
```suggestion
- Fil de tri **_([✨ premium](https://draftbot.fr/premium))_** ➜ Permet de définir les fils pour les signalements résolus, refusés et sanctionnés.

2023-08-28 07:32 UTC, IIbey commented on modules/reports.md
> +Pour configurer le système de signalments, accédez au panel via le lien ci-dessus et rendez-vous dans la catégorie "Signalements" sur le serveur de votre choix.
```suggestion
Pour configurer le système de signalements, accédez au panel via le lien ci-dessus et rendez-vous dans la catégorie "Signalements" sur le serveur de votre choix.

2023-09-15 18:45 UTC, ErwanGit requested changes

2023-09-15 18:45 UTC, ErwanGit commented on .gitbook/assets/report/config-report.JPG
L'image est super pixélisé

2023-09-15 18:45 UTC, ErwanGit commented on .gitbook/assets/report/traitement-du-signalement.jpg
Pixelisé

2023-09-15 18:45 UTC, ErwanGit commented on .gitbook/assets/report/dashboard.jpg
Pas fan d'avoir le logo de PTB et un nom de serveur "DraftBot test" pour une documentation principalement utilisé pour DraftBot "classique"

2023-09-15 18:45 UTC, ErwanGit commented on modules/reports.md
> +<mark style="color:blue;">"prendre en charge"</mark> ➜ Permet de montrer que vous êtes en train de régler le signalement.
```suggestion
<mark style="color:blue;">"Prendre en charge"</mark> ➜ Permet de montrer que vous êtes en train de régler le signalement.

```

2023-09-15 18:45 UTC, ErwanGit commented on modules/reports.md
> +<mark style="color:green;">Marquer comme traité</mark> ➜ Marque le signalement comme résolu.
Soit il faut ajouter des guillemets à Marquer comme traité, soit les retiré plus haut

2023-09-15 18:45 UTC, ErwanGit commented on modules/reports.md
> +Une fois la raison séléctionnée, vous pourrez ajouter un commentaire ou non.
Proposition pour le facultatif
```suggestion
Une fois la raison sélectionnée, vous pourrez ajouter un commentaire facultatif.

```

2023-09-15 18:45 UTC, ErwanGit commented on modules/reports.md
> +Vous pourez donc :
Proposition, éventuellement a améliorer, cela fait un peu vide sur la documentation 
![image](https://github.com/DraftBot/Documentation/assets/24718500/0636e608-2e50-42e2-ae60-74bdb60c5c19)

```suggestion
Vous aurez alors la possibilité entre :

```

2023-10-06 13:24 UTC, IIbey commented
Il va falloir reprendre les images, du moins celles qui sont du côté Discord pour qu'elles aient un fond transparent comme sur les autres pages

2023-10-07 22:55 UTC, DraftProducts commented
Images trop pixélisés, il faudrait les refaire en utilisant ShareX, meilleure qualité (surtout sur les petits écrans) + format png.

2023-10-23 09:30 UTC, bariboo requested changes

2023-10-23 09:30 UTC, bariboo commented on modules/reports.md
> +  Permettez-lui de vous les signaler avec le système de signalement DraftBot !
```suggestion
  Permettez-lui de vous les signaler avec le système de signalement de DraftBot !

```

2023-10-23 09:30 UTC, bariboo commented on modules/reports.md
> +<!--> Vous trouverez ci-dessous la configuration des signalements avec la commande <mark style="color:orange;">/config</mark>.-->
```suggestion
<!--> Vous trouverez ci-dessous la configuration des signalements avec la commande <mark style="color:orange;">/config</mark> :-->

```

Pour quoi il y a cette flèche (-->) après le texte ?

2023-10-23 09:30 UTC, bariboo commented on modules/reports.md
> +Une fois qu'une personne aura signalée un utilisateur ou un message, vous aurez ce message dans le salon que vous aurez défini auparavant :
```suggestion
Une fois qu'une personne aura signalé un utilisateur ou un message, vous aurez ce message dans le salon que vous aurez défini auparavant :

```

2023-10-23 09:30 UTC, bariboo commented on modules/reports.md
> +Vous pourrez toujours remettre le signalement en attente via un bouton sur le message de signalement.
```suggestion
Vous pourrez toujours remettre le signalement en attente via un bouton sur le message de signalement.

```

J'aime pas le "un bouton", l'utilisateur doit savoir de quel bouton on parle pas d'"un bouton". (= mettre "le" ?)

2023-10-23 09:30 UTC, bariboo commented on modules/reports.md
> +Vous aurez alors la possibilité entre :
```suggestion
Vous aurez alors différentes possibilités :

```

2023-10-23 09:30 UTC, bariboo commented on modules/reports.md
> +- Message de confirmation ➜ Défini le message qui sera envoyé à la personne qui fait le signalement.
```suggestion
- "Message de confirmation" ➜ Défini le message qui sera envoyé à la personne qui fait le signalement.

```

2023-10-23 09:30 UTC, bariboo commented on modules/reports.md
> +- "Activer l'ouverture d'un thread" ➜ Si activé, DraftBot ouvrira un fil quand un signalement est envoyé. **_([✨ premium](https://draftbot.fr/premium))_**
```suggestion
- "Activer l'ouverture d'un fil" ➜ Si activé, DraftBot ouvrira un fil quand un signalement est envoyé. **_([✨ premium](https://draftbot.fr/premium))_**

```

2023-10-29 19:48 UTC, Rababio4579 commented on modules/reports.md
> +<!--> Vous trouverez ci-dessous la configuration des signalements avec la commande <mark style="color:orange;">/config</mark>.-->
Parce que j'ai oublié de la retirer 🙂

2023-11-05 14:10 UTC, IIbey requested changes
Les images venant de Discord (même si c'est le bon format), n'ont pas de fond transparent.

2023-12-01 22:12 UTC, ErwanGit requested changes

2023-12-01 22:12 UTC, ErwanGit commented on .gitbook/assets/report/config-report.png
Image trop pixelisé

2023-12-01 22:12 UTC, ErwanGit commented on .gitbook/assets/report/report.png
Image trop pixelisé

2023-12-01 22:12 UTC, ErwanGit commented on modules/reports.md
> +- "Activer l'ouverture d'un fil" ➜ Si activé, DraftBot ouvrira un fil quand un signalement est envoyé. **_([✨ premium](https://draftbot.fr/premium))_**
Le lecteur qui fait pas attention peut comprendre sur le message du membre signalé
```suggestion
- "Activer l'ouverture d'un fil" ➜ Si activé, DraftBot ouvrira un fil pour les modérateurs quand un signalement est envoyé. **_([✨ premium](https://draftbot.fr/premium))_**

```

2023-12-01 22:12 UTC, ErwanGit commented on modules/reports.md
> +Sur le panel, vous retrouverez sur une même page, les mêmes possibilités de configuration qu'avec les commandes Slash sur Discord.
Si acceptée, il faudra ajouter le markdown sur le /config
```suggestion
Sur le panel, vous retrouverez sur une même page, les mêmes possibilités de configuration qu'avec la commande /config sur Discord.
```

2023-12-14 17:30 UTC, IIbey requested changes

2023-12-14 17:30 UTC, IIbey commented on modules/reports.md
> +Vous pouvez ensuite séléctionner la raison de la résolution du signalement parmis :
```suggestion
Vous pouvez ensuite sélectionner la raison de la résolution du signalement parmi :

2023-12-14 17:30 UTC, IIbey commented on modules/reports.md
> +"Sanctionner le membre" ➜ Permet de sanctionner le membre signalé avec une sanction prédéfinie (disponible uniquement si des sanctions prédéfinies sont enregistrées).
```suggestion
"Ouvrir un ticket" ➜ Permet d'ouvrir un ticket pour le membre pour le <mark style="color:red;">membre accusé</mark> ou le <mark style="color:blue;">membre signalant</mark> (disponible, uniquement, si le système de tickets est activé).

"Sanctionner le membre" ➜ Permet de sanctionner le membre signalé avec une sanction prédéfinie (disponible, uniquement, si des sanctions prédéfinies sont enregistrées).

2023-12-16 09:28 UTC, Tellvex commented on modules/reports.md
> +Vous pouvez ensuite séléctionner la raison de la résolution du signalement parmis :
```suggestion
"<mark style="color:green;">Marquer comme traité</mark>" ➜ Marque le signalement comme résolu.

Vous pouvez ensuite séléctionner la raison de la résolution du signalement parmis :

```

Il faut effectuer un double saut de ligne pour un retour à la ligne

2023-12-16 09:36 UTC, Tellvex commented on modules/reports.md
> +Vous pourrez toujours remettre le signalement en attente via le bouton sur le message de signalement.
Il faudrait peut-être mettre le nom du bouton et lui mettre une couleur ?

```suggestion
Vous pourrez toujours remettre le signalement en attente via le bouton <mark style="color:orange;">nom_du_bouton</mark> se trouvant sur le message.

```

2023-12-27 12:28 UTC, bariboo requested changes

2023-12-27 12:28 UTC, bariboo commented on modules/reports.md
> +"Sanctionner le membre" ➜ Permet de sanctionner le membre signalé avec une sanction prédéfinie (disponible uniquement si des sanctions prédéfinies sont enregistrées).
```suggestion
"Ouvrir un ticket" ➜ Permet d'ouvrir un ticket pour le <mark style="color:red;">membre accusé</mark> ou le <mark style="color:blue;">membre signalant</mark>. 

{% hint style="info" %}
Il faut que le système de <mark style="color:blue;">[tickets](modules/tickets.md)</mark> soit activé.
{% endhint %}

"Sanctionner le membre" ➜ Permet de sanctionner le membre signalé via une sanction prédéfinie.

{% hint style="info" %}
Il faut qu'il y ait des sanctions prédéfinies enregistrées.
{% endhint %}
```

2023-12-31 12:12 UTC, Rababio4579 commented on modules/reports.md
> +"Sanctionner le membre" ➜ Permet de sanctionner le membre signalé avec une sanction prédéfinie (disponible uniquement si des sanctions prédéfinies sont enregistrées).
Cette formulation pose quelques problèmes, dont le fait que les *infos* sont trop séparés des textes, et que deux *infos* s'enchaines à la fin, sans séparation, ce qui rend la lecture et la compréhension difficile 😉

2023-12-31 16:34 UTC, ErwanGit requested changes

2023-12-31 16:34 UTC, ErwanGit commented on modules/reports.md
> +"Sanctionner le membre" ➜ Permet de sanctionner le membre signalé avec une sanction prédéfinie (disponible, uniquement, si des sanctions prédéfinies sont enregistrées).
```suggestion
"Sanctionner le membre" ➜ Permet de sanctionner le membre signalé avec une sanction prédéfinie (disponible uniquement si des sanctions prédéfinies sont enregistrées).
```

2023-12-31 16:34 UTC, ErwanGit commented on modules/reports.md
> +"Sanctionner le membre" ➜ Permet de sanctionner le membre signalé avec une sanction prédéfinie (disponible, uniquement, si des sanctions prédéfinies sont enregistrées).
Peut-être mettre des tirets avant chaque point ?

2024-01-23 20:31 UTC, ErwanGit approved these changes

2024-01-24 09:22 UTC, DraftProducts approved these changes

2024-01-24 09:36 UTC, IIbey requested changes
Hormis ça, le reste c'est bon

2024-01-24 09:36 UTC, IIbey commented on modules/reports.md
> +- `{channel}` ➜ Mentions du salon
```suggestion
- `{channel}` ➜ Mention du salon

2024-01-24 09:36 UTC, IIbey commented on modules/reports.md
> +- "<mark style="color:blue;">Prendre en charge</mark>" ➜ Permet de montrer que vous êtes en train de vous occupez du signalement.
```suggestion
- "<mark style="color:blue;">Prendre en charge</mark>" ➜ Permet de montrer que vous êtes en train de vous occuper du signalement.

2024-01-24 09:36 UTC, IIbey commented on modules/reports.md
> +- "Ouvrir un ticket" ➜ Permet d'ouvrir un ticket pour le membre pour le <mark style="color:red;">membre accusé</mark> ou le <mark style="color:blue;">membre signalant</mark> (disponible uniquement si
```suggestion
- "Ouvrir un ticket" ➜ Permet d'ouvrir un ticket pour le <mark style="color:red;">membre accusé</mark> ou le <mark style="color:blue;">membre signalant</mark> (disponible uniquement si le système de tickets est activé).

2024-01-24 09:37 UTC, IIbey commented on modules/reports.md
> +- "Ouvrir un ticket" ➜ Permet d'ouvrir un ticket pour le membre pour le <mark style="color:red;">membre accusé</mark> ou le <mark style="color:blue;">membre signalant</mark> (disponible uniquement si
Ici, ça fait répétition bizarre :  " Permet d'ouvrir un ticket **pour le membre pour le membre accusé** ... "

2024-01-24 10:39 UTC, DraftProducts commented
Félicitations @Rababio4579 pour cette nouvelle page de documentation ! 
Un grand merci à tous ceux qui ont pris le temps de review cette PR @IIbey @ErwanGit @bariboo @Tellvex ! 🔥

2024-01-24 10:39 UTC, merged