Wordract en slash commands
DraftBot/Documentation pull request #7
Opened 2022-09-16 17:01 UTC by Tellvex

Version update du [wordreact.md](https://github.com/DraftBot/Documentation/blob/main/prefix/prefixe/wordreact.md), montrant cette fois-ci la méthode a utiliser avec le `/config`.

2022-09-16 22:54 UTC, IIbey commented on slash/wordreact.md
> +  dans un message, une réaction soit ajoutée au message.
C'est normal ce retour à la ligne ?

2022-09-16 22:54 UTC, DraftProducts requested changes
Pour l'aspect "technique" de la doc, je ne vois que ça, pour ce qui est de la rédaction je vais laisser un rédacteur prendre la suite de la review :v:

2022-09-16 22:54 UTC, DraftProducts commented on slash/wordreact.md
> +![Exemple d'activation/désactivation](https://github.com/Tellvex/Documentation/blob/main/.gitbook/assets/Capture1.PNG)
```suggestion
<figure><img src="../.gitbook/assets/Capture1.PNG" alt=""><figcaption>Exemple d'activation/désactivation</figcaption></figure>
```

2022-09-16 22:54 UTC, DraftProducts commented on slash/wordreact.md
> +![exemple de la réaction](https://github.com/Tellvex/Documentation/blob/main/.gitbook/assets/Capture2.PNG)
```suggestion
<figure><img src="../.gitbook/assets/Capture2.PNG" alt=""><figcaption>
Exemple de la réaction</figcaption></figure>
```

2022-09-17 05:49 UTC, Tellvex reviewed
@DraftProducts , normalement **tout a été corrigé d'un point de vue technique**. Je modifie juste le **saut de ligne** et tout est good

2022-09-17 05:50 UTC, Tellvex commented on slash/wordreact.md
> +  dans un message, une réaction soit ajoutée au message.
Il n'est pas normal, je corrige ça tout de suite

2022-09-17 13:52 UTC, IIbey requested changes
C'est mieux comme ça je trouve

2022-09-17 20:05 UTC, DraftProducts approved these changes

2022-09-17 20:46 UTC, DraftProducts requested changes

2022-09-17 20:46 UTC, DraftProducts commented on slash/wordreact.md
> +# WordReact
```suggestion
# Réactions de mots
```

2022-09-17 20:46 UTC, DraftProducts commented on slash/wordreact.md
> +## Supprimer des WordReacts <a href="#delete" id="delete"></a>
```suggestion
## Supprimer de réactions de mots <a href="#delete" id="delete"></a>
```

2022-09-17 20:46 UTC, DraftProducts commented on slash/wordreact.md
> +## Ajouter un WordReact <a href="#add" id="add"></a>
```suggestion
## Ajouter des réactions de mots <a href="#add" id="add"></a>
```

2022-09-17 20:46 UTC, DraftProducts commented on slash/wordreact.md
> +## Voir les WordReacts  <a href="#view" id="view"></a>
```suggestion
## Lister les réactions de mots<a href="#view" id="view"></a>
```

2022-09-18 06:56 UTC, Tellvex commented
J'ai changé tout ce qu'il fallait. Normalement c'est good.

2022-09-18 12:58 UTC, DraftProducts approved these changes

2022-09-18 12:59 UTC, merged