Ajout de la page du règlement
DraftBot/Documentation pull request #70
Opened 2023-09-13 09:27 UTC by IIbey

2023-09-14 12:50 UTC, DraftProducts requested changes

2023-09-14 12:50 UTC, DraftProducts commented on .gitbook/assets/rules/rules-modify.png
Ce screen a été tronqué de tous les cotés

2023-09-14 12:50 UTC, DraftProducts commented on .gitbook/assets/rules/rules-remove.png
Celui là aussi.

2023-09-14 12:50 UTC, DraftProducts commented on modules/le-reglement.md
Pour l'url je pense qu'on pourrais aller au plus simple : `modules/reglement`

2023-09-14 12:50 UTC, DraftProducts commented on modules/le-reglement.md
> +{% endhint %}
Comment ça ?

2023-09-14 12:57 UTC, IIbey commented on .gitbook/assets/rules/rules-remove.png
Ah, bizarre ?
J'ai fait exprès d'arrondir les bords 🤔

2023-09-14 13:07 UTC, IIbey commented on modules/le-reglement.md
> +{% endhint %}
![image](https://github.com/DraftBot/Documentation/assets/111301542/85b06702-a910-4e9d-b1c0-f86df8d335d5)

Comme ceci, si on reclique dessus

2023-09-14 14:25 UTC, DraftProducts commented on modules/le-reglement.md
> +{% endhint %}
Faudrait peut être ajouter une question pour demander si on veut que le rôle ne soit pas retiré.

2023-09-14 14:27 UTC, IIbey commented on modules/le-reglement.md
> +{% endhint %}
Je vais le retirer du coup

2023-09-14 14:28 UTC, DraftProducts approved these changes

2023-09-14 16:30 UTC, bariboo submitted a review, later dismissed

2023-09-14 16:30 UTC, bariboo commented on modules/reglement.md
> +Pour commencez, vous allez devoir effectuer la commande <mark style="color:orange;">/reglement créer</mark>. DraftBot vous donnera ensuite la possibilité d'ajouter le rôle que vous souhaitez attribue
```suggestion
Pour commencez, vous allez devoir effectuer la commande <mark style="color:orange;">/reglement créer</mark>. **DraftBot** vous donnera ensuite la possibilité d'ajouter le rôle que vous souhaitez attribuer aux membres, une fois qu'ils ont pris connaissance du règlement et qu'ils ont cliqué sur le bouton "<mark style="color:green;">Accepter le règlement</mark>"**.

```

2023-09-14 16:30 UTC, bariboo commented on modules/reglement.md
> +## Ajouter les règles
```suggestion
## Ajouter des règles

```

Je pense que les règles sont définies non ? 🤔

2023-09-14 16:30 UTC, bariboo commented on modules/reglement.md
> +Vous pouvez modifier vos règles à tout moment, que se soit pour faire une correction ou bien pour le rendre plus esthétique selon vos envies. Vous aurez besoin de la commande <mark style="color:orang
```suggestion
Vous pouvez modifier vos règles à tout moment, que se soit pour faire une correction ou bien pour le rendre plus esthétique selon vos envies. Vous aurez besoin de la commande <mark style="color:orange;">/reglement modifier</mark>. La procédure n'est pas très différente de la commande <mark style="color:orange;">/reglement ajouter</mark>, juste qu'un nouveau champ apparaît : **"règle"**.

```

2023-09-14 16:30 UTC, bariboo commented on modules/reglement.md
> +## Modifier les règles
```suggestion
## Modifier une règle

```

2023-09-14 17:48 UTC, IIbey commented
@bariboo Navrée, mais pour la plupart de tes propositions. Je ne suis pas du tout fan :/

2023-09-14 17:51 UTC, bariboo commented
Pas de soucis 🙂 Au moins j'ai proposé mon point de vue, pour la plupart, je n'étais pas forcément sûr, je trouvais juste que ça sonnait mieux à l'oreille. 😉

2023-09-14 18:02 UTC, IIbey commented
Chill @bariboo J'en ai discuté avec DraftMan tout de même pour avoir son avis, il a réussi à me convaincre pour certaines ~

2023-09-14 18:31 UTC, bariboo commented
Haha 😆

2023-09-15 18:50 UTC, ErwanGit approved these changes

2023-09-15 21:01 UTC, merged

2023-09-15 21:03 UTC, DraftProducts commented
Félicitations @IIbey pour ce speedrun de doc 🔥