Page 🧿 Rôles Réactions
DraftBot/Documentation pull request #71
Opened 2023-09-13 15:21 UTC by bariboo

2023-09-13 15:27 UTC, bariboo commented
@DraftProducts Serait-il possible que tu merges la documentation actuelle dans ce Squash ?

2023-09-14 14:35 UTC, DraftProducts commented
C'est tout bon :v:

2023-09-18 12:38 UTC, ErwanGit approved these changes

2023-09-18 13:08 UTC, IIbey requested changes

2023-09-18 13:08 UTC, IIbey commented on modules/roles-reactions.md
> +Si vous souhaitez par contre créer un message pour votre rôle-réaction voici les différentes possibilitées :
```suggestion
Si vous souhaitez par contre créer un message pour votre rôle-réaction voici les différentes possibilités :

2023-09-18 13:08 UTC, IIbey commented on modules/roles-reactions.md
> +Pour accéder au rôle-réaction, vous devrez rensigner l'<mark style="color:blue;">[identifiant](https://docs.draftbot.fr/autres/recuperer-un-identifiant)</mark> du message contenant le rôle-réaction.
```suggestion
Pour accéder au rôle-réaction, vous devrez renseigner l'<mark style="color:blue;">[identifiant](https://docs.draftbot.fr/autres/recuperer-un-identifiant)</mark> du message contenant le rôle-réaction.

2023-09-18 13:08 UTC, IIbey commented on modules/roles-reactions.md
> +Pour ajouter un nouveau rôle à votre rôle-réaction, vous n'aurez qu'à cliquer sur "<mark style="color:blue;">Ajouter</mark>". Le bot vous demanderas ensuite le rôle à ajouter ainsi que le format.
```suggestion
Pour ajouter un nouveau rôle à votre rôle-réaction, vous n'aurez qu'à cliquer sur "<mark style="color:blue;">Ajouter</mark>". **DraftBot** vous demandera ensuite le rôle à ajouter ainsi que le format.

2023-09-18 13:08 UTC, IIbey commented on modules/roles-reactions.md
> +Si vous souhaiter changer le rôle que le membre recevra en interragissant avec un bouton, une réaction ou un rôle à choix dans un sélecteur, cliquez sur "<mark style="color:blue;">Modifier</mark>". *
```suggestion
Si vous souhaiter changer le rôle que le membre recevra en interagissant avec un bouton, une réaction ou un rôle à choix dans un sélecteur, cliquez sur "<mark style="color:blue;">Modifier</mark>". **DraftBot** vous invitera à sélectionner le rôle à modifier et celui par lequel vous souhaitez le remplacer.

2023-09-18 13:08 UTC, IIbey commented on modules/roles-reactions.md
> +Tous les modes ne sont pas disponibles pour tout les formats de rôle-réaction (bouton ; réaction ; sélecteur).
```suggestion
Tous les modes ne sont pas disponibles pour tous les formats de rôle-réaction (bouton ; réaction ; sélecteur).

2023-09-18 13:08 UTC, IIbey commented on modules/roles-reactions.md
> +Vous pourrez par la suite  modifier les rôles-réactions de différentes façons :
```suggestion
Vous pourrez par la suite modifier les rôles-réactions de différentes façons :

2023-09-29 17:56 UTC, IIbey requested changes

2023-09-29 17:56 UTC, IIbey commented on modules/roles-reactions.md
> +Si vous souhaiter changer le rôle que le membre recevra en interagissant avec un bouton, une réaction ou un rôle à choix dans un sélecteur, cliquez sur "<mark style="color:blue;">Modifier</mark>". **
```suggestion
Si vous souhaitez changer le rôle que le membre recevra en interagissant avec un bouton, une réaction ou un rôle à choix dans un sélecteur, cliquez sur "<mark style="color:blue;">Modifier</mark>". **DraftBot** vous invitera à sélectionner le rôle à modifier et celui par lequel vous souhaitez le remplacer.

2023-09-30 17:02 UTC, IIbey approved these changes

2023-10-07 23:09 UTC, DraftProducts approved these changes

2023-10-07 23:10 UTC, merged