Privaterooms
DraftBot/Documentation pull request #78
Opened 2023-12-14 18:17 UTC by Tellvex

### Reprise de la page des privateroom

#### Modifications à venir

- Ajout de l'embed de configuration
- Fin de la partie config depuis le /config et le panel
- Changement de la structure de la page

#### Anciens commits

Rework des headers de la page
Remplissage "Informations Supplémentaires"
Add Image + tabs
Update "Utilisation des Salons Vocaux Temporaires"
Update Config
Update "config via /config"
chore: 🍱 Remove images backgrounds
Update config from /config
Update modules/privateroom.md
Update modules/privateroom.md
Update modules/privateroom.md
Update modules/privateroom.md
Update /config

2023-12-14 18:26 UTC, Tellvex commented
Hello @IIbey et @DraftProducts ,
Je voulais savoir si vous pouviez juste résoudre le conflit dans la page [summary.md](https://github.com/DraftBot/Documentation/pull/78/files#diff-4f74b24c8cd7466c1c46dc972d8e284ed47091160afda95a432cc000f2eceb4a).
Merci d'avance

2023-12-15 16:33 UTC, Tellvex commented
Merci Nico, j'attaque la page ce soir

2023-12-16 10:57 UTC, ErwanGit requested changes

2023-12-16 10:57 UTC, ErwanGit commented on .gitbook/assets/privateroom/view_edit.png
Il faudrait changer la PP et surtout le nom du serveur

2023-12-16 10:57 UTC, ErwanGit commented on .gitbook/assets/privateroom/view_embed.png
Il faudrait rendre l'image sans fond pour que cela reste consistant avec les autres pages de la documentation
Il faudrait aussi si possible le faire sur un autre serveur à cause de la PP du serveur qui est en mode Noël

2023-12-16 10:57 UTC, ErwanGit commented on modules/privateroom.md
> +Lorsque vous créez un salon vocal temporaire, vous aurez la permission "*Gérer le salon*", qui vous permettra de modifier la limite d'utilisateur, les permissions du salon ainsi que le nom du salon.
C'est plus vrai avec les modifications apportées dans les dernières mises à jour

2023-12-16 10:57 UTC, ErwanGit commented on modules/privateroom.md
> +Les **permissions par défaut** du Salon vocal temporaire correspondent à celles de la **catégorie**.
```suggestion
Les **permissions par défaut** du salon vocal temporaire correspondent à celles de la **catégorie**.
```

2023-12-16 10:57 UTC, ErwanGit commented on modules/privateroom.md
> +Les salons vocaux déjà existants dans cette catégorie seront supprimés par le bot si vous ne les rendez pas permanents.
Proposition ici, ce n'est pas forcément le cas si aucune personne rejoint les salons impactés
```suggestion
Les salons vocaux déjà existants dans cette catégorie peuvent être supprimés par DraftBot si vous ne les rendez pas permanents.
```

2023-12-16 10:57 UTC, ErwanGit commented on modules/privateroom.md
> +> Message en question : "Êtes-vous sûr de vouloir supprimer la seule catégorie de salons vocaux temporaires du serveur ?"
Je ne pense pas qu'il soit utile d'indiquer le message de confirmation dans cette partie-là, le fait que l'action est irréversible une fois le message de confirmation validé me semble suffisant

2023-12-16 10:57 UTC, ErwanGit commented on modules/privateroom.md
> +Cette fonctionnalité est réservée aux <mark style="color:orange;">[serveurs premiums](https://www.draftbot.fr/premium)</mark>.
Il faudrait ajouter l'émoji ✨ pour rester cohérent avec les autres pages

2023-12-16 10:57 UTC, ErwanGit commented on modules/privateroom.md
> +- Voix prioriaire : le son de tous les participants sera diminué lorsque le créateur du salon parle. ⚠ - Cette fonction ne fonctionne que lorsque le créateur est en mode "Appuyer pour parler".
Il faudrait indiquer ici, je pense que certaines actions sont possibles sans en avoir la permission dans le salon via le nouveau menu envoyé lors de la création du salon

2023-12-16 10:57 UTC, ErwanGit commented on modules/privateroom.md
> +Depuis la version [5.4.0](.././autres/changelog.md), lorsque vous créez un vocal un embed apparaît dans le <mark style="color:orange;">salon textuel du vocal</mark>. Il contient toutes les permission
Je ne pense pas qu'il soit utile d'indiquer depuis quand cette partie est disponible, si cela reste pendant des années comme ça, je ne pense pas que cela soit un bon move

2023-12-16 10:57 UTC, ErwanGit commented on modules/privateroom.md
> +> Veuillez donc penser à désactiver cette option si votre serveur a des permissions strictes.
À voir pour ça, mais quand je me mets à la place d'un administrateur, j'active l'A2F soit parce que Discord m'y oblige (notamment pour apparaître dans le Discovery) soit pour "forcer" les membres de mon équipe à l'activer pour la sécurité de leur compte
Mais c'est plutôt un effet indésirable que cela impacte les membres du serveur, donc je serai pour qu'on n'indique pas cette partie

2023-12-16 10:57 UTC, ErwanGit commented on modules/privateroom.md
> +- Purge : La purge permet de déconnecter tous les membres qui ne sont pas dans la liste blanche. Cette règle ne s'applique pas à _l'auteur_ (@IIbey si t'as un autre mot je suis preneur) du salon.
Vu qu'on peut passer la propriété à quelqu'un via le menu
```suggestion
- Purge : La purge permet de déconnecter tous les membres qui ne sont pas dans la liste blanche. Cette règle ne s'applique pas au propriétaire du salon.
```

2023-12-16 10:57 UTC, ErwanGit commented on modules/privateroom.md
> +- Vidéo : Tout comme la fonction précédente, elle permet d' activer/désactiver l'activation de la caméra ainsi que le partage d'écran de tous les participants du salon vocal.
```suggestion
- Vidéo : Tout comme la fonction précédente, elle permet d'activer/désactiver l'activation de la caméra ainsi que le partage d'écran de tous les participants du salon vocal.
```

2023-12-16 10:57 UTC, ErwanGit commented on modules/privateroom.md
> +- Sounboard : cette fonction permet d'activer/désactiver l'utilisation des soundboards pour tous les participants du salon vocal.
```suggestion
- Soundboard : cette fonction permet d'activer/désactiver l'utilisation des soundboards pour tous les participants du salon vocal.
```

2023-12-16 10:57 UTC, ErwanGit commented on modules/privateroom.md
> +Veuillez noter également que vous perdrez l'accès au configurateur de <mark style="color:orange;">[salon vocal](https://docs.draftbot.fr/modules/privateroom#utilisation-du-configurateur-de-salon)</ma
```suggestion
Veuillez noter également que vous perdrez l'accès au configurateur de <mark style="color:orange;">[salon vocal](https://docs.draftbot.fr/modules/privateroom#utilisation-du-configurateur-de-salon)</mark>.
```

2023-12-16 10:57 UTC, ErwanGit commented on modules/privateroom.md
> +Lien vers le panel : <mark style="color:orange;">[https://www.draftbot.fr/dashboard/user](https://www.draftbot.fr/dashboard/user)</mark>
Je serai pour mettre ces informations aux endroits opportuns de la documentation et pas à la fin

2023-12-16 10:58 UTC, Tellvex commented on .gitbook/assets/privateroom/view_edit.png
Sur quelle(s) image ?

2023-12-16 11:00 UTC, Tellvex commented on .gitbook/assets/privateroom/view_embed.png
Pour le moment les images sont temporaires (je vais voir avec nico pour en faire de manière définitive)

2023-12-16 11:02 UTC, Tellvex commented on modules/privateroom.md
> +Lorsque vous créez un salon vocal temporaire, vous aurez la permission "*Gérer le salon*", qui vous permettra de modifier la limite d'utilisateur, les permissions du salon ainsi que le nom du salon.
Yep, j'avais pas lu en relisant, merci

```suggestion
Lorsque vous créez un salon vocal temporaire, vous avez la possibilité de configurer votre salon (selon la configuration des salons faite par l'administrateur)
```

2023-12-16 11:05 UTC, ErwanGit commented on modules/privateroom.md
> +Lorsque vous créez un salon vocal temporaire, vous aurez la permission "*Gérer le salon*", qui vous permettra de modifier la limite d'utilisateur, les permissions du salon ainsi que le nom du salon.
Avec le point à la fin, sinon oui ça me parait bon 👍

2023-12-16 11:07 UTC, Tellvex commented on modules/privateroom.md
> +Lorsque vous créez un salon vocal temporaire, vous aurez la permission "*Gérer le salon*", qui vous permettra de modifier la limite d'utilisateur, les permissions du salon ainsi que le nom du salon.
```suggestion
Lorsque vous créez un salon vocal temporaire, vous avez la possibilité de configurer votre salon (selon la configuration des salons faite par l'administrateur).

2023-12-16 11:08 UTC, Tellvex commented on modules/privateroom.md
> +Les salons vocaux déjà existants dans cette catégorie seront supprimés par le bot si vous ne les rendez pas permanents.
après si y'a un salon vocal, en général il est pas là pour faire joli, y'aura quelqu'un qui va voc à un moment donné

2023-12-16 11:10 UTC, Tellvex commented on modules/privateroom.md
> +> Message en question : "Êtes-vous sûr de vouloir supprimer la seule catégorie de salons vocaux temporaires du serveur ?"
Je comprends, après je trouvais que le hint était un peu "vide" si on mettait que ça. Je demanderais l'avis de tout le monde tout à l'heure

2023-12-16 11:21 UTC, ErwanGit commented on modules/privateroom.md
> +Les salons vocaux déjà existants dans cette catégorie seront supprimés par le bot si vous ne les rendez pas permanents.
Oui, mais on peut supposer qu'il sera supprimé dès la création du privateroom

2023-12-16 11:30 UTC, Tellvex commented on modules/privateroom.md
> +Lien vers le panel : <mark style="color:orange;">[https://www.draftbot.fr/dashboard/user](https://www.draftbot.fr/dashboard/user)</mark>
Je préfère mettre tout ça à la fin et rediriger, plutôt que de me répéter si je dois le mettre plusieurs fois

2023-12-16 11:34 UTC, Tellvex commented on modules/privateroom.md
> +Les salons vocaux déjà existants dans cette catégorie seront supprimés par le bot si vous ne les rendez pas permanents.
Si tu le dis

2023-12-16 14:29 UTC, ErwanGit requested changes
Je le remets pour que cela ne soit pas oublié : 
- Il faudra revoir les images 
- Ajouter la partie panel

2023-12-16 14:29 UTC, ErwanGit commented on modules/privateroom.md
> +Pour activer ou désactiver des Salons Vocaux Temporaires, vous devez cliquer sur le bouton <mark style="color:orange;">Activer le système</mark>. Vous verrez alors le menu se mettre à jour.
```suggestion
Pour activer ou désactiver des salons vocaux temporaires, vous devez cliquer sur le bouton <mark style="color:orange;">Activer le système</mark>. Vous verrez alors le menu se mettre à jour.
```

2023-12-16 14:29 UTC, ErwanGit commented on modules/privateroom.md
> +Veuillez également noter que la limite de membre peut être changée à tout moment par <mark style="color:orange;">le créateur du salon</mark> s'il possède la permission <mark style="color:orange;">Mod
```suggestion
Veuillez également noter que la limite de membre peut être changée à tout moment par <mark style="color:orange;">le créateur du salon</mark> s'il possède la permission <mark style="color:orange;">Modifier le salon</mark>.
```

2023-12-16 14:29 UTC, ErwanGit commented on modules/privateroom.md
> +- Activer l'embed de réglages ► Embed de réglages activé
Pour rester cohérent avec le reste de la documentation
```suggestion
Pour activer ou désactiver l'embed de réglages, il suffit d'appuyer sur le bouton <mark style="color:orange;">Embed de réglages activé</mark>. Suite à cela, le nom du bouton va changer en une autre variante :
- Embed de réglages activé ➜ Activer l'embed de réglages
- Activer l'embed de réglages ➜ Embed de réglages activé
```

2023-12-16 14:29 UTC, ErwanGit commented on modules/privateroom.md
> +{% embed url="https://www.draftbot.fr/dashboard/user" %}
Je ne sais pas s'il est possible de nommer ces liens par autre chose que le nom "par défaut"
Comme ça, on dirait qu'il y a deux fois le site de DraftBot 
![image](https://github.com/DraftBot/Documentation/assets/24718500/e88af716-4cf9-4533-a027-c6aef180cf6d)

2023-12-16 14:40 UTC, Tellvex commented on modules/privateroom.md
> +{% embed url="https://www.draftbot.fr/dashboard/user" %}
C'est justement le problème des embeds, je pensais que ça allait rendre mieux mais on ne peut pas faire autrement.
Je pense que je vais repasser sur des liens classiques

2023-12-19 10:14 UTC, Tellvex reviewed
Je met juste ce commentaire pour indiquer que le contenu **textuel** de la pull request est terminée.
Les seules choses manquantes sont : 
- Les images
- Les corrections sur la structure et/ou l'orthographe.

2023-12-19 21:02 UTC, toutouille-db commented on modules/privateroom.md
> +Pour créer votre systèmes de salons vocaux temporaires, vous devez passer par un salon vocal qui s'occupera de créer le salon temporaire et de donner les permissions requises au propriétaire du salon
```suggestion
Pour créer votre système de salons vocaux temporaires, vous devez passer par un salon vocal qui s'occupera de créer le salon temporaire et de donner les permissions requises au propriétaire du salon. Ce salon se nomme un **Hub**.
```

2023-12-22 21:42 UTC, IIbey requested changes

2023-12-22 21:42 UTC, IIbey commented on modules/privateroom.md
> +- **Changer les permissions** : le créateur peut changer les permissions de son salon vocal, ce qui implique qu'il peut créer des dérogation de rôle, de membre, etc.
```suggestion
- **Changer les permissions** : le créateur peut changer les permissions de son salon vocal, ce qui implique qu'il peut créer des dérogations de rôle, de membre, etc.

2023-12-22 21:42 UTC, IIbey commented on modules/privateroom.md
> +- **Voix prioriaire** : le son de tous les participants sera diminué lorsque le créateur du salon parle. ⚠ - Cette fonction ne fonctionne que lorsque le créateur est en mode "Appuyer pour parler".
```suggestion
- **Voix prioritaire** : le son de tous les participants sera diminué lorsque le créateur du salon parle. ⚠️ - Cette fonction ne fonctionne que lorsque le créateur est en mode "Appuyer pour parler".
Comment

2023-12-22 21:42 UTC, IIbey commented on modules/privateroom.md
> +Par défaut la limite de membres est définie à <mark style="color:orange;">99 participants</mark>.
```suggestion
Par défaut, la limite de membres est définie à <mark style="color:orange;">99 participants</mark>.

2023-12-22 21:42 UTC, IIbey commented on modules/privateroom.md
> +- **Réinitialiser les rôles interdits** : Ce bouton permet d'effacer la configuration des rôles d'accès
```suggestion
- **Réinitialiser les rôles interdits** : Ce bouton permet d'effacer la configuration des rôles d'accès.

2023-12-22 21:42 UTC, IIbey commented on modules/privateroom.md
> +<summary>Autorisation de rôle</summary>
```suggestion
<summary>Autorisation de rôles</summary>

2023-12-22 21:42 UTC, IIbey commented on modules/privateroom.md
> +Cet embed permet notamment d'utiliser toutes les permission de modération, et ce même si le membre n'a pas activé l'A2F (puisque l'utilisateur passe par le bot et non pas par son compte).
```suggestion
Lorsque vous créez un vocal un embed apparaît dans le <mark style="color:orange;">salon textuel du vocal</mark>. Il contient toutes les permissions de modération liées au salon vocal.

{% hint style="warning" %}
Cet embed permet notamment d'utiliser toutes les permissions de modération, et ce même si le membre n'a pas activé l'A2F (puisque l'utilisateur passe par le bot et non pas par son compte).

2023-12-22 21:42 UTC, IIbey commented on modules/privateroom.md
> +- **Liste Blanche** : Cette fonction permet d'ajouter des membres qui seront <mark style="color:orange;">autorisé à rejoindre</mark> le salon en permanence.
```suggestion
- **Ouvert** : Cette fonction permet d'ouvrir le salon à tous les membres, excepté ceux de la <mark style="color:orange;">liste noire</mark>.
- **Fermé** : Cette fonction verrouille le salon à tous les membres, excepté ceux inscrits dans la <mark style="color:orange;">liste blanche</mark>.
- **Liste Blanche** : Cette fonction permet d'ajouter des membres qui seront <mark style="color:orange;">autorisés à rejoindre</mark> le salon en permanence.

2023-12-22 21:42 UTC, IIbey commented on modules/privateroom.md
> +Cette fonction permet notamment de contourner les paramètres de verouillage du salon vocal, donc faites attention à qui vous ajouterez.
```suggestion
Cette fonction permet notamment de contourner les paramètres de verrouillage du salon vocal, donc faites attention à qui vous ajouterez.

2023-12-22 21:42 UTC, IIbey commented on modules/privateroom.md
> +Tout comme la fonction précédente, la liste noire contourne les paramètres de verouillage du salon vocal, donc faites attention à qui vous ajouterez dans cette liste.
```suggestion
Tout comme la fonction précédente, la liste noire contourne les paramètres de verrouillage du salon vocal, donc faites attention à qui vous ajouterez dans cette liste.

2023-12-22 21:42 UTC, IIbey commented on modules/privateroom.md
> +- Créer un salon : Vous devez cliquer sur le bouton "<mark style="color:orange;">Créer</mark>", indiquer un nom et <mark style="color:orange;">Draftbot</mark> se chargera de créer le salon avec les p
```suggestion
- Créer un salon : Vous devez cliquer sur le bouton "<mark style="color:orange;">Créer</mark>", indiquer un nom et <mark style="color:orange;">Draftbot</mark> se chargera de créer le salon avec les permissions adéquates.

2023-12-22 21:42 UTC, IIbey commented on modules/privateroom.md
> +- Utiliser une catégorie existante : En cliquant sur le bouton "<mark style="color:orange;">Sélectionner</mark>", un selecteur apparaîtra et vous pourrez choisir la catégorie à utiliser
```suggestion
- Utiliser une catégorie existante : En cliquant sur le bouton "<mark style="color:orange;">Sélectionner</mark>", un sélecteur apparaîtra et vous pourrez choisir la catégorie à utiliser.

2023-12-22 21:42 UTC, IIbey commented on modules/privateroom.md
> +Nous vous recommendons de choisir une catégorie vierge afin d'éviter les problèmes de suppressions de salons permanents ainsi que le désordre qu'une grande quantité de salons peut provoquer.
```suggestion
Nous vous recommandons de choisir une catégorie vierge afin d'éviter les problèmes de suppressions de salons permanents ainsi que le désordre qu'une grande quantité de salons peut provoquer.

2023-12-22 21:42 UTC, IIbey commented on modules/privateroom.md
> +- En retirant l'accès par défaut à tous les rôles et à ajouter les rôles examptés.
```suggestion
- En retirant l'accès par défaut à tous les rôles et à ajouter les rôles exemptés.

2023-12-22 23:39 UTC, toutouille-db requested changes

2023-12-22 23:39 UTC, toutouille-db commented on modules/privateroom.md
> +Nous vous recommendons de choisir une catégorie vierge afin d'éviter les problèmes de suppressions de salons permanents ainsi que le désordre qu'une grande quantité de salons peut provoquer.
```suggestion
Nous vous recommandons de choisir une catégorie vierge afin d'éviter les problèmes de suppression de salons permanents ainsi que le désordre qu'une grande quantité de salons peut provoquer.
```

2023-12-22 23:39 UTC, toutouille-db commented on modules/privateroom.md
> +- Utiliser une catégorie existante : En cliquant sur le bouton "<mark style="color:orange;">Sélectionner</mark>", un selecteur apparaîtra et vous pourrez choisir la catégorie à utiliser
```suggestion
- Utiliser une catégorie existante : En cliquant sur le bouton "<mark style="color:orange;">Sélectionner</mark>", un sélecteur apparaîtra et vous pourrez choisir la catégorie à utiliser.
```

2023-12-22 23:39 UTC, toutouille-db commented on modules/privateroom.md
> +Pour définir les noms de salons, vous devez juste remplacer le nom existant par celui que vous souhaitez.
```suggestion
Pour définir les noms de salons, vous devez remplacer le nom existant par celui que vous souhaitez.
```

2023-12-22 23:39 UTC, toutouille-db commented on modules/privateroom.md
> +Lorsque vous créez un vocal un embed apparaît dans le <mark style="color:orange;">salon textuel du vocal</mark>. Il contient toutes les permission de modération lié au salon vocal.
```suggestion
Lorsque vous créez un vocal, un embed apparaît dans le <mark style="color:orange;">salon textuel du vocal</mark>. Il contient toutes les permissions de modération liées au salon vocal.
```

2023-12-22 23:39 UTC, toutouille-db commented on modules/privateroom.md
> +Voici donc une liste détaillée de chaque fonction du configurateur :
```suggestion
Voici donc une liste détaillée de chaque fonction de l'embed de configuration :
```

2023-12-22 23:39 UTC, toutouille-db commented on modules/privateroom.md
> +- **Ouvert** : Cette fonction permet d'ouvrir le salon à tous les membres, exepté ceux de la <mark style="color:orange;">liste noire</mark>.
```suggestion
- **Ouvert** : Cette fonction permet d'ouvrir le salon à tous les membres, excepté ceux de la <mark style="color:orange;">liste noire</mark> et des dérogations par défaut.
```

2023-12-22 23:39 UTC, toutouille-db commented on modules/privateroom.md
> +- **Fermé** : Cette fonction vérouille le salon à tous les membres exceptés ceux inscrits dans la <mark style="color:orange;">liste blanche</mark>.
```suggestion
- **Fermé** : Cette fonction verrouille le salon à tous les membres excepté ceux inscrits dans la <mark style="color:orange;">liste blanche</mark> et les dérogations par défaut.
```

2023-12-22 23:39 UTC, toutouille-db commented on modules/privateroom.md
> +- **Liste Blanche** : Cette fonction permet d'ajouter des membres qui seront <mark style="color:orange;">autorisé à rejoindre</mark> le salon en permanence.
```suggestion
- **Liste Blanche** : Cette fonction permet d'ajouter des membres qui seront <mark style="color:orange;">autorisés à rejoindre</mark> le salon en permanence et ne seront pas impactés par les changements de permission (micro, vidéo & soundboards).
```

2023-12-22 23:39 UTC, toutouille-db commented on modules/privateroom.md
> +Cette fonction permet notamment de contourner les paramètres de verouillage du salon vocal, donc faites attention à qui vous ajouterez.
```suggestion
Cette fonction permet notamment de contourner les paramètres de verrouillage du salon vocal, donc faites attention à qui vous ajoutez.
```

2023-12-22 23:39 UTC, toutouille-db commented on modules/privateroom.md
> +Tout comme la fonction précédente, la liste noire contourne les paramètres de verouillage du salon vocal, donc faites attention à qui vous ajouterez dans cette liste.
```suggestion
Tout comme la fonction précédente, la liste noire contourne les paramètres de verrouillage du salon vocal, donc faites attention à qui vous ajoutez dans cette liste.
```

2023-12-22 23:39 UTC, toutouille-db commented on modules/privateroom.md
> +- **Purge** : La purge permet de déconnecter tous les membres qui ne sont pas dans la liste blanche. Cette règle ne s'applique pas au propriétaire du salon du salon.
```suggestion
- **Purge** : La purge permet de déconnecter tous les membres présents dans le salon à l'exception de ceux dans la liste blanche, du propriétaire du salon et des dérogations par défaut.

2023-12-22 23:39 UTC, toutouille-db commented on modules/privateroom.md
> +Les fonctions <mark style="color:orange;">micro, vidéo et soundboard</mark> s'appliquent à tous les membres hormis ceux ayant une dérogation spéciale ainsi qu'au propriétaire du salon.
```suggestion
Les fonctions <mark style="color:orange;">micro, vidéo et soundboard</mark> s'appliquent à tous les membres hormis ceux ayant une dérogation spéciale, les membres de la liste blanche ainsi qu'au propriétaire du salon.
```

2023-12-22 23:39 UTC, toutouille-db commented on modules/privateroom.md
> +Veuillez noter également que vous perdrez l'accès au configurateur de <mark style="color:orange;">[salon vocal](https://docs.draftbot.fr/modules/privateroom#utilisation-du-configurateur-de-salon)</ma
```suggestion
Notez que vous perdrez l'accès à l'embed de configuration du <mark style="color:orange;">[salon vocal](https://docs.draftbot.fr/modules/privateroom#utilisation-du-configurateur-de-salon)</mark>.
```

2024-01-24 11:46 UTC, Tellvex commented on modules/privateroom.md
> +Veuillez également noter que la limite de membre peut être changée à tout moment par <mark style="color:orange;">le créateur du salon</mark> s'il possède la permission <mark style="color:orange;">Mod
Je préfère le rappeler étant donné qu'il s'agit d'une autre partie de la doc, et qu'un membre ne va pas forcément lire autre chose que ce qui l'intéresse

2024-01-25 08:34 UTC, DraftProducts requested changes

2024-01-25 08:34 UTC, DraftProducts commented on .gitbook/assets/privateroom/panel/view_delete.png
Je crois qu'il y a un problème avec ce screen ? 🤔 
Pourquoi il n'y a pas les cases à cocher ?

2024-01-25 08:34 UTC, DraftProducts commented on modules/privateroom.md
> +
Il faudrait également ajouter les modérateurs de salons privés, c'est actuellement disponible sur PTB.

2024-01-25 08:34 UTC, DraftProducts commented on modules/privateroom.md
> +
Je ne vois pas de documentation pour l'option "Rôle d'accès", tu pourrais l'ajouter ?

2024-01-25 08:34 UTC, DraftProducts commented on .gitbook/assets/privateroom/config/view_edit.png
Cette image a changé depuis quelques mises à jours, il faudrait la mettre à jour depuis DraftBot PTB (version la plus à jour).

2024-01-25 08:34 UTC, DraftProducts commented on .gitbook/assets/privateroom/panel/view_edit2.png
Celle ci à changé également, (je peux te faire un screen en longueur en une fois si tu veux).

2024-03-17 14:04 UTC, DraftProducts commented
Abandon de la PR par Tellvex

2024-03-17 14:05 UTC, closed without merging