Ajout de la page Starboard.
DraftBot/Documentation pull request #79
Opened 2023-12-15 20:08 UTC by Wapiti13

2023-12-19 00:56 UTC, Wapiti13 commented
J'ai vu les erreurs sur la version de Gitbook, je corrige ça au plus vite.

2023-12-19 01:19 UTC, Wapiti13 commented
Je t'informerai, DraftMan, quand pour moi il n'y a plus d'erreur.

2023-12-19 05:55 UTC, Tellvex requested changes
Dans cette review j'ai globalement proposé des corrections pour tous les problèmes d'affichage sur GitBook
Si tu as des questions, hésite pas à passer sur discord.

2023-12-19 05:55 UTC, Tellvex commented on modules/starboard.md
> +{% tab title="Par commande" %}
```suggestion
{% tab title="Via le /config" %}
```
C'est pour garder plus de cohérence sur les pages

2023-12-19 05:55 UTC, Tellvex commented on modules/starboard.md
> +### Par commande
```suggestion
### Via le /config
```

2023-12-19 05:55 UTC, Tellvex commented on modules/starboard.md
> +<summary>Liste des variables disponibles pour ce système<summary>
Le details s'affiche mal
![image](https://github.com/DraftBot/Documentation/assets/78918215/b165303e-0399-4501-9f42-2c9383c84bfe)

```suggestion
<summary>Liste des variables disponibles pour ce système</summary>
```

2023-12-19 05:55 UTC, Tellvex commented on modules/starboard.md
> +Pour configuer ce système par commande, il vous suffit de faire la commande <mark style="color:orange;">/config</mark> en sélectionnant le système ⭐<mark style="color:blue;">Starboards</mark>. Il se
Ça serait bien de rédiger l'ensemble des menus de création, de modification et tout (surtout la modification puisque t'as un menu supplémentaire)

2023-12-19 05:55 UTC, Tellvex commented on modules/starboard.md
> +<summary>Liste des variables disponibles pour ce système<summary>
Même problème

```suggestion
<summary>Liste des variables disponibles pour ce système</summary>
```

2023-12-19 05:55 UTC, Tellvex commented on modules/starboard.md
> +- En tant que membre <mark style="color:orange;">[premium](https://www.draftbot.fr/premium/)</mark>, vous pouvez créer jusqu'à 5 starboards.
Pour ce qui est des fonctionnalités premium, c'est mieux de mettre une devant ✨   le mot premium

2023-12-19 05:55 UTC, Tellvex commented on modules/starboard.md
> +### Infos utiles
Je pense que tu pourrais mettre certaines de ces infos directement en "hint" dans ta configuration. Après tu peux toujours voir avec les autres ce qu'ils en pensent

2023-12-31 16:42 UTC, ErwanGit requested changes
- Il faudrait changer tous les noms d'assets en anglais, comme pour les autres pages

2023-12-31 16:42 UTC, ErwanGit commented on .gitbook/assets/starboards/creacdms.png
Il faudra voir pour retirer le fond

2023-12-31 16:42 UTC, ErwanGit commented on .gitbook/assets/starboards/modifcdms.png
Il faudra voir pour retirer le fond

2023-12-31 16:42 UTC, ErwanGit commented on modules/starboard.md
> +# ⭐ Starboard
```suggestion
# ⭐ Starboards
```

2023-12-31 16:42 UTC, ErwanGit commented on modules/starboard.md
Il faudra rajouter le s à starboards dans le nom du fichier pour rester cohérent avec les autres pages

2023-12-31 16:42 UTC, ErwanGit commented on modules/starboard.md
> +  Demarquez certains messages en intéragissant avec un émoji.
Il faudra développer un peu cela pour dire que les messages sont envoyés dans un autre salon, etc

2023-12-31 16:42 UTC, ErwanGit commented on modules/starboard.md
> +Comme vous l'aurez compris, le système de starboard foncionne à base de réaction sous un message. Principalement, cela permet de faire des votes entre certains messages. Mais cela peut servir aussi à
Il faudra revoir un peu ça pour que cela fasse un peu moins pavé sur la documentation à lire
Aussi, je suis pas fan du "Comme vous l'aurez compris" alors qu'il s'agit presque du premier texte de la page
![image](https://github.com/DraftBot/Documentation/assets/24718500/3a64033b-6f7b-4abf-8b37-6f23ecb1a0f5)

2023-12-31 16:42 UTC, ErwanGit commented on modules/starboard.md
> +![Menu de création](../.gitbook/assets/starboard/creacdms.png)
L'image est pas affiché sur la documentation

2023-12-31 16:42 UTC, ErwanGit commented on modules/starboard.md
> +- Pour pouvoir créer jusqu'à 5 starboards et choisir l'émoji en question pour les réactions, il faut être ✨ <mark style="color:orange;">[premium](https://www.draftbot.fr/premium/)</mark>.
```suggestion
Pour pouvoir créer jusqu'à 5 starboards et choisir l'émoji en question pour les réactions, il faut être ✨ <mark style="color:orange;">[premium](https://www.draftbot.fr/premium/)</mark>.
```

2023-12-31 16:42 UTC, ErwanGit commented on modules/starboard.md
> +Pour créer un starboard par commande, il suffit de faire la commande /config en sélectionnant Starboards. Ensuite, cliquez sur Créer. De là, DrafBot vous posera plusieurs afin de configurer au mieux
```suggestion
Pour créer un starboard par commande, il suffit de faire la commande /config en sélectionnant Starboards. Ensuite, cliquez sur Créer. De là, DrafBot vous posera plusieurs afin de configurer au mieux votre premier starboard. 

```

2023-12-31 16:42 UTC, ErwanGit commented on modules/starboard.md
> +Pour modifier un starboard, il faut d'abord faire la commande /config en sélectionnant Starboard. Puis, cliquez sur Modifier. Par la suite, DraftBot vous affichera une sorte de panel de configuration
Il faudrait le revoir, car il fait pavé sur la documentation et ne donne pas envie d'être lu
![image](https://github.com/DraftBot/Documentation/assets/24718500/c342a32b-dfed-4c6c-8608-8c4ba9c8cec8)

```suggestion
Pour modifier un starboard, il faut d'abord faire la commande /config en sélectionnant Starboards. Puis, cliquez sur Modifier. Par la suite, DraftBot vous affichera une sorte de panel de configuration. Exemple ci dessous. Vous pouvez choisir si la représentation du message dans le salon soit dans un embed ou pas mais vous pouvez également chosir dans quel salon vous souhaitez qu'il s'y trouve.
```

2023-12-31 16:42 UTC, ErwanGit commented on modules/starboard.md
> +La forme basique que DraftBot donne lors de la configuration est "{emoji} {emoji.count} | {message.url}".
Proposition
```suggestion
La forme basique que DraftBot donne lors de la configuration est `{emoji} {emoji.count} | {message.url}`.

```

2023-12-31 16:42 UTC, ErwanGit commented on modules/starboard.md
> +- Pour pouvoir créer jusqu'à 5 starboards et choisir l'émoji en question pour les réactions, il faut être ✨ <mark style="color:orange;">[premium](https://www.draftbot.fr/premium/)</mark>.
```suggestion
Pour pouvoir créer jusqu'à 5 starboards et choisir l'émoji en question pour les réactions, il faut être ✨ <mark style="color:orange;">[premium](https://www.draftbot.fr/premium/)</mark>.
```

2023-12-31 16:42 UTC, ErwanGit commented on modules/starboard.md
> +![Explicaton visuelle](../.gitbook/assets/starbaords/astucepanel.png)
L'image n'est pas affiché sur la documentation

2024-01-05 22:56 UTC, Wapiti13 commented on .gitbook/assets/starboards/creacdms.png
Je vais lui demander sur Discord : )

2024-01-06 21:05 UTC, DraftProducts requested changes
Revoir le nom des fichiers en s'inspirant des autres pages.
Astuce: voir les autres dossiers .gitbook/assets

2024-01-10 19:31 UTC, DraftProducts commented on modules/starboard.md
> +  Demarquez certains messages en intéragissant avec un émoji.
```suggestion
  Mettez en avant les meilleurs messages de votre serveur dans un salon dédié en intéragissant avec un émoji.

```

2024-01-24 10:52 UTC, DraftProducts requested changes
Voici quelques propositions !

2024-01-24 10:52 UTC, DraftProducts commented on modules/starboards.md
> +Le système de starboard foncionne à base de réaction sous un message. Principalement, cela permet de faire des votes entre certains messages. Mais cela peut servir aussi à d'autres choses. Lorsqu'un
```suggestion
Le système de starboard met en avant les messages qui reçoivent un certain nombre de réactions. Un message populaire est automatiquement affiché par DraftBot dans un salon dédié, choisi ou créé lors de la configuration.
```

2024-01-24 10:52 UTC, DraftProducts commented on modules/starboards.md
> +Pour modifier un starboard, il faut d'abord faire la commande /config en sélectionnant Starboards. Puis, cliquez sur Modifier. Par la suite, DraftBot vous affichera une sorte de panel de configuratio
```suggestion
Pour modifier un starboard, lancez la commande `/config`, sélectionnez Starboards et cliquez sur Modifier. DraftBot affichera alors un panel de configuration.
```

2024-01-24 10:52 UTC, DraftProducts commented on modules/starboards.md
> +
```suggestion

```

2024-01-24 22:05 UTC, IIbey requested changes

2024-01-24 22:05 UTC, IIbey commented on modules/starboards.md
> +- `{message.url}` = Lien du message.
```suggestion
Les variables sont des morceaux de texte qui évoluent en fonction de la personne, du serveur, du salon ou encore du temps. Voici celles utilisables pour le système de starboard :

- {user} ➜ Surnom du membre sur le serveur.
- {user.username} ➜ Pseudo du compte du membre.
- {user.globalname} ➜ Nom affiché du compte du membre.
- {emoji} ➜ Emoji du starboard.
- {emoji.count} ➜ Nombre de réactions.
- {message.url} ➜ Lien vers le message.

2024-01-25 09:39 UTC, IIbey requested changes

2024-01-25 09:39 UTC, IIbey commented on modules/starboards.md
> +Pour supprimer un starboard, il suffit de faire la commande /config toujours en sélectionnant Starboards. Enfin, il vous faudra cliquer sur Supprimer en rouge.
```suggestion
Pour supprimer un starboard, faites la commande <mark style="color:orange;">/config</mark> toujours en sélectionnant Starboards, puis, cliquer sur "Supprimer" en rouge.

2024-01-25 09:39 UTC, IIbey commented on modules/starboards.md
> +Pour créer un starboard via le <mark style="color:orange;">[panel](https://www.draftbot.fr/dashboard)</mark>, il faut vous rendre dans la catégorie Communautaire. Ensuite, déscendez dans la partie St
```suggestion
Pour créer un starboard via le <mark style="color:orange;">[panel](https://www.draftbot.fr/dashboard)</mark>, il faut vous rendre dans la catégorie "Communautaire". Ensuite, descendez dans la partie "Starboards" et cliquez sur "Créer un hub". Par la suite, DraftBot vous proposera une sorte de menu de configuration pour configurer votre premier starboard.

2024-01-25 09:39 UTC, IIbey commented on modules/starboards.md
> +{% endhint %}
```suggestion
{% hint style="info" %}
Vous avez la possibilité de définir un nombre minimum de réactions, compris entre 1 et 25, avant qu'un message n'apparaisse dans le salon dédié à ce starboard.

{% endhint %}

2024-01-25 09:39 UTC, IIbey commented on modules/starboards.md
> +{% endhint %}
```suggestion
{% hint style="info" %}

Pour créer jusqu'à 5 starboards et choisir l'émoji associé aux réactions, le ✨ <mark style="color:orange;">[premium](https://www.draftbot.fr/premium/)</mark> est nécessaire.

{% endhint %}

2024-01-25 09:39 UTC, IIbey commented on modules/starboards.md
> +Pour supprimer un starboard, cliquez sur le bouton supprimer qui se trouve également dans le <mark style="color:orange;">[panel](https://www.draftbot.fr/dashboard)</mark>, dans la catégorie Communaut
```suggestion
Pour supprimer un starboard, cliquez sur le bouton "Supprimer", situé également sur le <mark style="color:orange;">[panel](https://www.draftbot.fr/dashboard)</mark>, dans la catégorie "Communautaire", puis dans la partie "Starboards"."

2024-01-25 09:39 UTC, IIbey commented on modules/starboards.md
> +Si vous le souhaitez, vous pouvez désactiver votre starboard tout en le conservant, il vous suffit juste de cliquer sur l'encoche à gauche du bouton Modifier.
```suggestion
Si vous le souhaitez, vous avez la possibilité de désactiver votre starboard tout en le conservant. Il vous suffit simplement de décocher la case à gauche du bouton "Modifier"

2024-01-29 13:54 UTC, IIbey requested changes

2024-01-29 13:54 UTC, IIbey commented on modules/starboards.md
> +Pour créer un starboard par commande, il suffit de faire la commande <mark style="color:orange;">/config</mark> en sélectionnant Starboards. Ensuite, cliquez sur Créer et de là, DrafBot vous posera p
```suggestion
Pour créer un starboard par commande, il suffit de faire la commande <mark style="color:orange;">/config</mark> en sélectionnant "Starboards". Ensuite, cliquez sur "Créer", et DrafBot vous posera plusieurs afin de configurer au mieux votre premier starboard.

2024-02-21 20:13 UTC, ErwanGit requested changes

2024-02-21 20:13 UTC, ErwanGit commented on modules/starboards.md
> +Le système de starboard met en avant les messages qui reçoivent un certain nombre de réactions. Un message populaire est automatiquement affiché par DraftBot dans un salon dédié, choisi ou créé lors
Je ne suis vraiment pas fan du terme "Un message populaire est automatiquement affiché"
Il faut qu'il y aient une action des utilisateurs pour qu'il soit affiché dans le salon #starboard 

**Proposition :**
```suggestion
Le système de starboard met en avant les messages qui reçoivent un certain nombre de réactions, qui seront alors affiché par DraftBot dans un salon dédié, choisi ou créé lors de la configuration.
```

2024-02-21 20:13 UTC, ErwanGit commented on modules/starboards.md
> +Pour créer un starboard par commande, il suffit de faire la commande <mark style="color:orange;">/config</mark> en sélectionnant "Starboards". Ensuite, cliquez sur "Créer", et DrafBot vous posera plu
```suggestion
Pour créer un starboard par commande, il suffit de faire la commande <mark style="color:orange;">/config</mark> en sélectionnant "Starboards". Ensuite, cliquez sur "Créer", et DraftBot vous posera plusieurs questions afin de configurer au mieux votre premier starboard. 
```

2024-02-21 20:13 UTC, ErwanGit commented on modules/starboards.md
> +- Pour pouvoir créer jusqu'à 5 starboards et choisir l'émoji en question pour les réactions, il faut être ✨ <mark style="color:orange;">[premium](https://www.draftbot.fr/premium/)</mark>.
Pas fan du tiret ici, cela rend mal sur la documentation
<img width="719" alt="image" src="https://github.com/DraftBot/Documentation/assets/24718500/ff590aba-5967-4e92-a10d-16fbbc3ff1ea">

2024-02-21 20:13 UTC, ErwanGit commented on modules/starboards.md
> +Pour supprimer un starboard, faites la commande /config toujours en sélectionnant "Starboards", puis, cliquer sur "Supprimer" en rouge.
Il faudrait mettre en forme la commande `/config` dans cette phrase

2024-02-21 20:13 UTC, ErwanGit commented on modules/starboards.md
> +Pour créer un starboard via le [panel](https://www.draftbot.fr/dashboard/), Veuillez vous rendre dans la catégorie "Communautaire". Ensuite, descendez dans la partie "Starboards" et cliquez sur "Crée
```suggestion
Pour créer un starboard via le [panel](https://www.draftbot.fr/dashboard/), veuillez vous rendre dans la catégorie "Communautaire". Ensuite, descendez dans la partie "Starboards" et cliquez sur "Créer un hub". Par la suite, DraftBot vous proposera une sorte de menu de configuration pour configurer votre premier starboard.
```

2024-02-21 20:13 UTC, ErwanGit commented on modules/starboards.md
> +Pour configurer le système via le [panel](https://www.draftbot.fr/dashboard/), il vous suffit de vous diriger dans l'onglet <mark style ="color:blue;">Communautaire</mark>. Ensuite, descendez un la l
La dernière phrase ne veut pas dire grand chose en l'état actuelle

2024-02-21 20:13 UTC, ErwanGit commented on modules/starboards.md
> +Pour créer jusqu'à 5 starboards et choisir l'émoji associé aux réactions, le ✨ [premium](https://www.draftbot.fr/) est nécessaire.
Il faudrait mettre en couleur le mot "premium" comme pour la partie bot
En plus, je pense que le lien indiqué pourrait directement être https://www.draftbot.fr/premium plutôt que la page principal

2024-02-21 20:13 UTC, ErwanGit commented on modules/starboards.md
> +{% endhint %}
L'image est illisible dans ce cas précis 
<img width="719" alt="image" src="https://github.com/DraftBot/Documentation/assets/24718500/ba88a47b-ee0e-4987-92f8-de077e7388f1">

2024-02-21 20:13 UTC, ErwanGit commented on .gitbook/assets/starboards/starboards-modify.png
`edit` à la place de `modify` pour rester cohérent 
Il faudra répercuter les changements également dans la page consacré aux starboards

2024-02-21 20:13 UTC, ErwanGit commented on .gitbook/assets/starboards/starboards-modify-2.png
`edit` à la place de `modify` pour rester cohérent 
Il faudra répercuter les changements également dans la page consacré aux starboards

2024-02-21 20:13 UTC, ErwanGit commented on modules/starboards.md
> +  Mettez en avant les meilleurs messages de votre serveur dans un salon dédié en intéragissant avec un émoji.
```suggestion
  Mettez en avant les meilleurs messages de votre serveur dans un salon dédié en interagissant avec un émoji.
```

2024-02-23 15:28 UTC, DraftProducts requested changes

2024-02-23 15:30 UTC, DraftProducts commented on modules/starboards.md
> +{% endhint %}
C'est une compression de gitbook + taille à cause du hint, ce ne sera plus le cas sur la nouvelle doc et l'image est d'assez bonne résolution

2024-06-04 03:34 UTC, DraftProducts commented
Superseeded by https://github.com/DraftBot/Documentation/pull/99

2024-06-04 03:34 UTC, closed without merging