🚧 WIP - Page de Modération
DraftBot/Documentation pull request #83
Opened 2023-12-28 12:30 UTC by bariboo

2023-12-31 11:34 UTC, bariboo commented
J'ai pas encore fini, je la mettrai comme ready for review une fois que j'aurai fini !

2024-07-01 02:40 UTC, kazotka commented
Pour toutes les personnes qui souhaitent faire des reviews, sachez qu'il y a un problème avec les assets en ce moment. Ce problème **ne provient pas de moi**, donc merci d'éviter les reviews à ce sujet, les devs travaillent sur ce problème.

2024-07-01 13:28 UTC, ErwanGit requested changes

2024-07-01 13:28 UTC, ErwanGit commented on 2.modules/5.moderation.md
> +**Vous pouvez avertir un membre** avec la commande \</avertir>. Le membre recevra alors un message privé avec le motif de son avertissement. Si vous souhaitez que seulement les modérateurs puissent v
Peut-être faire en sorte que quand on clique sur note, on est renvoyé plus haut sur la page ?

2024-07-01 13:28 UTC, ErwanGit commented on 2.modules/5.moderation.md
> +  ::
DraftBot n'a besoin d'aucune permission particulière pour cette commande

2024-07-01 13:28 UTC, ErwanGit commented on 2.modules/5.moderation.md
> +Le fait d'expulser un membre fera quitter le membre du serveur, mais il pourra toujours revenir avec une autre invitation. Si vous souhaitez qu'il ne puisse pas revenir, consultez le `bannissement` d
Faire en sorte que le mot bannissement renvoie plus haut sur la page ?

2024-07-01 13:28 UTC, ErwanGit commented on 2.modules/5.moderation.md
> +Le fait de **bannir un membre fera quitter le membre du serveur et il ne pourra jamais y revenir**. Vous pouvez également bannir temporairement le membre en question. Si vous souhaitez qu'il puisse r
Faire en sorte que le mot expulsion renvoie plus haut sur la page ?

2024-07-01 13:28 UTC, ErwanGit commented on 2.modules/5.moderation.md
> +Notez que les commandes </adminreinitialiser sanctions membre> et </adminreinitialiser sanctionsserveur> sont irréversibles.
```suggestion
Notez que les commandes </adminreinitialiser sanctions membre> et </adminreinitialiser sanctions serveur> sont irréversibles.
```

2024-07-01 13:28 UTC, ErwanGit commented on 2.modules/5.moderation.md
> +    Une fois sur le panel de **DraftBot**, rendez-vous dans la rubrique **`🔨 Modération`** et dans les **`Options`**. Vous n'aurez plus qu'à activer les options voulues !
```suggestion
    Une fois sur le panel de **DraftBot**, rendez-vous dans la rubrique **`🔨 Modération`** et dans les **`Options`**. Vous n'aurez plus qu'à activer les options voulues :
```

2024-07-01 13:28 UTC, ErwanGit commented on 2.modules/5.moderation.md
> +      Vous auvez également la possibilitée de retirer toutes les sanctions prédéfinies en cliquant sur **`réinitialiser`**.
```suggestion
      Vous auvez également la possibilitée de retirer toutes les sanctions prédéfinies en cliquant sur le bouton **`Réinitialiser`**.
```

2024-07-01 13:28 UTC, ErwanGit commented on 2.modules/5.moderation.md
> +    [Accéder au panel de ➜ **DraftBot**](/dashboard)
```suggestion
    [Accéder au panel de **DraftBot**](/dashboard)
```

2024-07-08 01:00 UTC, kazotka commented on 2.modules/5.moderation.md
> +**Vous pouvez avertir un membre** avec la commande \</avertir>. Le membre recevra alors un message privé avec le motif de son avertissement. Si vous souhaitez que seulement les modérateurs puissent v
y'a un problème avec cette fonctionnalité DraftMan travaille dessus, pour l'instant j'ai un commit de prêt avec celle-ci

2024-07-08 02:01 UTC, kazotka commented
[ ] Fix assets automod

2024-07-08 02:11 UTC, kazotka commented
Review prête pour la page doc il me reste la page de automod @ErwanGit @DraftProducts @IIbey

2024-08-25 14:31 UTC, Rababio4579 requested changes

2024-08-25 14:31 UTC, Rababio4579 commented on 2.modules/25.auto-moderation.md
> +    Sachez que certaine fonctionnalitée apparaiçant dans le screen ci-dessus *(`Masquer le nom du modérateur en MP`, `Cacher les réponses des commandes` et `Sanctions prédéfinies`)* disponible dans l
```suggestion
    Sachez que certaines fonctionnalités apparaissant dans l'image ci dessus *(`Masquer le nom du modérateur en MP`, `Cacher les réponses des commandes` et `Sanctions prédéfinies`)* disponibles via la commande \</config> n'apparaissent pas sur cette page. **Cette-dernière traite uniquement de l'auto-modération.** Si vous recherchez des informations concernant la modération, consultez la page prévue à cet effet ➜ **[`🔨 Modération`](https://draftbot.fr/docs/modules/moderation)**.
```

2024-08-25 14:31 UTC, Rababio4579 commented on 2.modules/25.auto-moderation.md
> +**DraftBot** propose différents systèmes de modération automatiques tel que l'auto-modération ou encore les auto-sanctions. Par exemple expulser un membre, l'avertir et bien plus encore ! Sans oublie
```suggestion
**DraftBot** propose différents systèmes de modération automatique tel que l'auto-modération ou encore les auto-sanctions.
```

2024-08-25 14:31 UTC, Rababio4579 commented on 2.modules/25.auto-moderation.md
> +    **N'oublier pas à activer le système**, via le premier bouton :
```suggestion
    **N'oubliez pas à activer le système**, via le premier bouton :

```

2024-08-25 14:31 UTC, Rababio4579 commented on 2.modules/25.auto-moderation.md
> +Envie d'automatiser certains actes de modération tel que la censure des invitations discord ou du vocabulaire interdit ? Alors découvrez l'auto-modération de **DraftBot** !
```suggestion
Les infractions servent à bloquer les mauvais comportements tels que les spams, les publicités, ou encore les insultes.

```

Le "teaser" de la fonctionnalité a déjà été fait en haut de la page, pas besoin d'en faire trop 😉

2024-08-26 14:36 UTC, Rababio4579 requested changes
Attention aussi à ne pas avoir trop de hints par rapport au texte normal, ça peut "inonder" la page, et empêcher les membres de lire la page fluidement

2024-08-26 14:36 UTC, Rababio4579 commented on 2.modules/5.moderation.md
> +## Options de confidentialité
"Confidentialité" n'est pas réellement le bon terme

2024-08-26 14:36 UTC, Rababio4579 commented on 2.modules/5.moderation.md
> +  ::
C'est dommage de faire un tab entier pour deux options

2024-08-26 14:36 UTC, Rababio4579 commented on 2.modules/5.moderation.md
> +  Vous pourrez, si vous le souhaitez, acquitter un membre de sa réduction au silence avec la commande \</demute>.
```suggestion
  Vous pouvez, si vous le souhaitez, acquitter un membre de sa réduction au silence avec la commande \</demute>.
```
concordance des temps

2024-08-26 14:36 UTC, Rababio4579 commented on 2.modules/5.moderation.md
> +Grâce aux options de confidentialité, **vous pourrez décider de masquer le nom du modérateur ou les réponses aux commandes de modération**.
```suggestion
Grâce aux options de confidentialité, **vous pouvez décider de masquer le nom du modérateur ou les réponses aux commandes de modération**.
```
concordance des temps

2024-08-26 14:36 UTC, Rababio4579 commented on 2.modules/5.moderation.md
> +Une sanction prédéfinie est **une sanction préconfigurée servant à centraliser différents actes de modération en une seule commande : \</mod>**. Vous pourrez y décider de la sanction à appliquer ains
```suggestion
Une sanction prédéfinie est **une sanction préconfigurée exécutable directement via la commande \</mod>**. Vous pouvez ainsi regrouper des sanctions prédéfinies dans une seule commande, ce qui vous fera gagner du temps pour la modération.
```

2024-08-26 14:36 UTC, Rababio4579 commented on 2.modules/5.moderation.md
> +  Vos modérateurs doivent posséder les permissions nécessaires pour effectuer les sanctions souhaitées via \</mod>.
La formulation n'est pas très claire

2024-08-26 14:40 UTC, IIbey commented on 2.modules/5.moderation.md
> +  Vos modérateurs doivent posséder les permissions nécessaires pour effectuer les sanctions souhaitées via \</mod>.
" Assurez-vous que les modérateurs ont les permissions nécessaires pour exécuter des sanctions via la commande </mod>. " 
Je pense.

2024-08-26 20:16 UTC, Rababio4579 requested changes

2024-08-26 20:16 UTC, Rababio4579 commented on 2.modules/25.auto-moderation.md
> +description: Certains de vos membres vous posent quelques problèmes ? Alors configurez les outils de modération automatiques de DraftBot !
```suggestion
description: Certains de vos membres vous posent quelques problèmes ? Alors configurez les outils de modération automatique de DraftBot !

```

2024-08-28 01:53 UTC, kazotka commented on 2.modules/5.moderation.md
> +::hint{ type="danger" }
Le type danger est ici utilisez dans le but de montrer une potentiel érreur et ce différencier du type warning

2024-08-28 01:56 UTC, kazotka commented on 2.modules/5.moderation.md
> +Le fait d'expulser un membre fera quitter le membre du serveur, mais il pourra toujours revenir avec une autre invitation. Si vous souhaitez qu'il ne puisse pas revenir, consultez-le [**`bannissement
@DraftProducts

2024-08-28 02:10 UTC, kazotka commented on 2.modules/5.moderation.md
> +  ::
Personellement, je trouve cela nécéssaire du à la comparaison entre panel et la commande config

2024-09-01 10:05 UTC, Rababio4579 requested changes

2024-09-01 10:05 UTC, Rababio4579 commented on 2.modules/25.auto-moderation.md
> +    - Limite de messages
Il y a beaucoup, **beaucoup** trop de menus déroulants
Il faudrait simplement donner la liste des options possibles, et leur explication

2024-10-01 18:08 UTC, closed without merging