Création de la page des messages récurrents
DraftBot/Documentation pull request #88
Opened 2024-01-30 20:46 UTC by Ezraaduk

Création de la page des messages récurrents, avec les bases simple. (Non terminé)

2024-01-30 21:47 UTC, Rababio4579 commented
N'oublie pas de rajouter le lien de la page dans le fichier `SUMMARY.md` 😉

2024-02-03 14:34 UTC, Rababio4579 requested changes

2024-02-03 14:34 UTC, Rababio4579 commented on modules/message_récurrent.md
> +Une fois sur le <mark style="color:yellow;">[panel de **DraftBot**](https://draftbot.fr/dashboard/)</mark> ➜ Messages récurrents. <mark style="color:yellow;">Crée</mark>,<mark style="color:orange;">m
Il vaut mieux vouvoyer que tutoyer

2024-02-03 14:34 UTC, Rababio4579 commented on modules/message_récurrent.md
> +Configurable depuis la commande <mark style="color:red;">/config</mark> ➜ Messages récurrents ➜ "<mark style="color:orange;">Créer</mark>. Clique sur <mark style="color:red;">Créer</mark> DraftBot te
Le vouvoiement est plus approprié

2024-02-03 14:34 UTC, Rababio4579 commented on modules/message_récurrent.md
> +Les messages récurrents, sont des messages que DraftBot envoie de façon autonome avec un délai défini à l'avance. Ils sont configurable depuis le panel ou depuis la commande.
Cette phrase serait plutôt à mettre dans la description, en la modifiant un peu

2024-03-05 01:31 UTC, DraftProducts commented
Supreseeded by next documentation

2024-03-05 01:31 UTC, closed without merging