Update gestion-de-leconomie.md
DraftBot/Documentation pull request #9
Opened 2022-10-11 17:10 UTC by bariboo

J'ai fait toute la partie "gestion de l'économie" !

2022-12-16 23:23 UTC, IIbey requested changes

2022-12-16 23:23 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +Tu peux, lors de [https://docs.draftbot.fr/slash/configuration/economie](la configuration), chosir un rôle booster. L'utilitée ? Si une personne boost ton server, tu pourras faire qu'elle reçoive 1.5
```suggestion
Tu peux, lors de [https://docs.draftbot.fr/slash/configuration/economie](la configuration), choisir un rôle booster. L'utilité ? Si une personne boost ton serveur, tu pourras faire qu'elle reçoive 1.5, 2, 2.5 ou 3 fois plus d'argent qu'un membre normal.

2022-12-16 23:23 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +Ceci se fait également via <mark style="color:orange;"> /give \[utilisateur]</mark>\, il vous suffit de cliqué sur le bouton "En échange d'argent" (le premier bouton) en ayant préalablement choisit l
```suggestion
Ceci se fait également via <mark style="color:orange;"> /echanger \[utilisateur]</mark>\, il vous suffit de cliquer sur le bouton "En échange d'argent" (le premier bouton) en ayant préalablement choisi l'utilisateur avec lequel vous souhaitez vendre votre item !

2022-12-16 23:23 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +La commande <mark style="color:orange;"> /give \[utilisateur]</mark>\ a pour but de pouvoir échanger des objets d'inventaire gratuitement, contre des DC ou tout simplement donc un autre objet d'inven
```suggestion
La commande <mark style="color:orange;"> /echanger \[utilisateur]</mark>\ a pour but de pouvoir échanger des objets d'inventaire gratuitement (ou contre de l'argent), ou tout simplement contre un autre objet d'inventaire !

2022-12-16 23:23 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +Le marché noir est tout simplement une variante de la boutique, la différance est que l'embed se supprimera au bout de 30 secondes, ni vu ni connu !
```suggestion
Le marché noir est tout simplement une variante de la boutique, la différence est que l'embed se supprimera au bout de 30 secondes, ni vu ni connu !

2022-12-16 23:23 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +La boutique est l'endroit où vous pourrez acheter les artcicles qui composeront votre inventaire (Voir deux catégories en dessous). Vous pouvez y acheter un rôle temporaire ou un rôle, de l'expérienc
```suggestion
La boutique est l'endroit où vous pourrez acheter les articles qui composeront votre inventaire (voir deux catégories en dessous). Vous pouvez y acheter un rôle temporaire ou un rôle, de l'expérience (voir gestion des niveaux), un objet d'inventaire et plein d'autres choses ! Elle est accessible avec la commande <mark style="color:orange;"> /boutique \[utilisateur]</mark>\.

2022-12-16 23:23 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +Grâce à la commande <mark style="color:orange;"> /topmoney</mark>\ vous avez accès aux leaderboard économique du server.
```suggestion
Grâce à la commande <mark style="color:orange;"> /topargent</mark>\ vous avez accès aux leaderboard économique du serveur.

2022-12-16 23:23 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +Afin d'obtenir de l'argent, il faut que [https://docs.draftbot.fr/slash/gestion-des-niveaux](ce système) soit activé sur le server.
```suggestion
Afin d'obtenir de l'argent, il faut que [https://docs.draftbot.fr/slash/gestion-des-niveaux](ce système) soit activé sur le serveur.

2022-12-16 23:23 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +Vous pouvez voir votre somme d'argent ainsi que celle des autres en indiquant leur pseudo sous "membre" avec <mark style="color:orange;"> /money \[utilisateur]</mark>\
```suggestion
Vous pouvez voir votre somme d'argent ainsi que celle des autres en indiquant leur pseudo sous "membre" avec <mark style="color:orange;"> /argent \[utilisateur]</mark>\

2022-12-23 14:59 UTC, bariboo commented
Merci Ibey pour ces suggestions, j'ai eu le temps de tout modifier, à vous de jouer !

2023-01-21 23:26 UTC, IIbey requested changes

2023-01-21 23:26 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +Grâce à la commande <mark style="color:orange;"> /topargent</mark>\ vous avez accès aux leaderboard économique du serveur.
```suggestion
Grâce à la commande <mark style="color:orange;"> /topargent</mark>\ vous avez accès au leaderboard économique du serveur.

2023-01-21 23:41 UTC, DraftProducts commented
Merci pour ta contribution @bariboo ! 🔥 
Voici le rendu de cette page : https://docs.draftbot.fr/~/revisions/3lMtVMri8tZCgk5TmRf0/slash/gestion-de-leconomie
Si tu veux éventuellement faire quelques derniers correctifs :v:

2023-01-29 22:32 UTC, Hugo-broc approved these changes

2023-01-30 19:16 UTC, ToutouilleDev reviewed
Ajout d'améliorations

2023-01-30 20:49 UTC, Hugo-broc approved these changes

2023-01-30 21:00 UTC, ErwanGit requested changes

2023-01-30 21:00 UTC, ErwanGit commented on slash/gestion-de-leconomie.md
> +**Conseil :** si vous voulez illustrer vos objets d'inventaire et ne pas avoir que du texte, vous pouvez ajouter des émojis. Vous devez par contre récupérer l'ID de celui-ci en mettant un antislash (
```suggestion
**Conseil :** si vous voulez illustrer vos objets d'inventaire et ne pas avoir que du texte, vous pouvez ajouter des émojis. Vous devez par contre récupérer l'identifiant de celui-ci en mettant un antislash (\\) devant celui-ci.
```

2023-01-30 21:00 UTC, ErwanGit commented on slash/gestion-de-leconomie.md
> +Le marché noir est une variante de la boutique. La différence est que la boutique se supprimera au bout de 30 secondes, ni vu ni connu !
```suggestion
Le marché noir est une variante de la boutique. La différence est que la boutique se supprimera au bout de 60 secondes, ni vu ni connu !
```

2023-01-30 23:51 UTC, DraftProducts commented
https://docs.draftbot.fr/~/revisions/JCb9rkysFnptJNkAzYPn/

2023-01-31 07:21 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +**Conseil :** si vous voulez illustrer vos objets d'inventaire et ne pas avoir que du texte, vous pouvez ajouter des émojis. Vous devez par contre récupérer l'identifiant de celui-ci en mettant un an
Pourquoi parler de l'identifiant des émojis ici ? Pour moi, ils mettent simplement un émoji qu'ils copient-collent depuis internet ou Discord.

2023-01-31 07:22 UTC, Hugo-broc requested changes
Onglet info : identifiant des émojis (voir commentaire)

2023-01-31 12:05 UTC, DraftProducts commented on slash/gestion-de-leconomie.md
> +**Conseil :** si vous voulez illustrer vos objets d'inventaire et ne pas avoir que du texte, vous pouvez ajouter des émojis. Vous devez par contre récupérer l'identifiant de celui-ci en mettant un an
Oui, je suis d'accord, il faudrait modifier ça, bien vu @Hugo-broc 👍

2023-02-01 14:29 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +### Topmonnaie
Je ne suis pas fan du terme " monnaie ", et je pense pas besoin de mettre le nom de la commande vu qu'elle est représentée dans la description.

```suggestion
### Classement

2023-02-01 14:29 UTC, IIbey commented on slash/gestion-de-leconomie.md
>  ### Monnaie
```suggestion
### Argent

2023-02-01 18:09 UTC, ToutouilleDev reviewed
Envie d'égayer un peu la vie sur votre serveur ? Alors activez le système d'économie et laissez-vous guider par DraftBot !

Changer par Envie d'égayer davantage la vie sur votre serveur ? Alors activez le système d'économie et laissez-vous guider par DraftBot !

2023-02-03 12:39 UTC, ErwanGit commented on slash/gestion-de-leconomie.md
> +**Conseil :** si vous voulez illustrer vos objets d'inventaire et ne pas avoir que du texte, vous pouvez ajouter des émojis. Vous devez par contre récupérer l'<mark style="color:orange;">[identifiant
C'est valable uniquement panel ça normalement

2023-02-03 14:37 UTC, DraftProducts commented on slash/gestion-de-leconomie.md
> +**Conseil :** si vous voulez illustrer vos objets d'inventaire et ne pas avoir que du texte, vous pouvez ajouter des émojis. Vous devez par contre récupérer l'<mark style="color:orange;">[identifiant
Ouep 👍

2023-02-07 18:25 UTC, bariboo commented
Pas encore fini, je vous dit quand vous pouvez review !

2023-02-07 19:42 UTC, ErwanGit requested changes

2023-02-07 19:42 UTC, ErwanGit commented on slash/gestion-de-leconomie.md
> +- <mark style="color:orange;">/journalier\[membre]</mark> ➜ Commande journalière permettant de gagner un montant défini au préalable par les administrateurs.
```suggestion
- <mark style="color:orange;">/journalier \[membre]</mark> ➜ Commande journalière permettant de gagner un montant défini au préalable par les administrateurs.
```

2023-02-07 19:42 UTC, ErwanGit commented on slash/gestion-de-leconomie.md
> +- <mark style="color:orange;">/dropargent\[membre]</mark> ➜ Créer un message qui offre de l'argent au premier qui clique sur le bouton.
```suggestion
- <mark style="color:orange;">/adminargent ajouter \[membre]</mark> ➜ Ajouter de l'argent à un membre en plus de son montant actuel.
- <mark style="color:orange;">/adminargent définir \[membre]</mark> ➜ Définir l'argent d'un membre en ne tenant pas compte de son montant actuel.
- <mark style="color:orange;">/adminargent retirer \[membre]</mark> ➜ Retirer de l'argent à un membre en se basant sur le montant actuel.
- <mark style="color:orange;">/adminargent réinitialiser serveur</mark> ➜ Remettre à zéro l'argent de tout le serveur.
- <mark style="color:orange;">/dropargent \[membre]</mark> ➜ Créer un message qui offre de l'argent au premier qui clique sur le bouton.
```

2023-02-07 19:42 UTC, ErwanGit commented on slash/gestion-de-leconomie.md
> +Si vous créez par contre vos items depuis le <mark style="color:orange;">[Panel](https://draftbot.fr/dashboard/)</mark>, vous devez par contre récupérer l'<mark style="color:orange;">[identifiant](ht
```suggestion
Si vous créez par contre vos items depuis le <mark style="color:orange;">[panel](https://draftbot.fr/dashboard/)</mark>, vous devez par contre récupérer l'<mark style="color:orange;">[identifiant](https://docs.draftbot.fr/autres/recuperer-un-identifiant#identifiant-dun-emoji)</mark> de celui-ci en mettant un antislash (\\) devant celui-ci.
```

2023-02-07 19:42 UTC, ErwanGit commented on slash/gestion-de-leconomie.md
> +Quand une personne a un rôle booster, elle pourra gagner 1,5 / 2 / 2,5 ou 3 fois plus d'argent qu'un membre normal.
Peut-être mettre en gras les valeurs pour les mettre en valeur ?

2023-02-09 17:35 UTC, ErwanGit requested changes

2023-02-09 17:35 UTC, ErwanGit commented on slash/gestion-de-leconomie.md
> +Quand une personne a un rôle booster, elle pourra gagner **1,5** / **2** / **2,5** ou **3** fois plus d'argent qu'un membre normal.
Problème de personne
Avant, on vouvoie et maintenant on tutoie

2023-02-09 17:45 UTC, ErwanGit approved these changes

2023-02-09 21:52 UTC, IIbey requested changes

2023-02-09 21:52 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +Grâce à la commande <mark style="color:orange;">/topargent</mark> vous avez accès au classement économique du serveur. Vous y verrez les cinq premiers membres ainsi que votre position. Pour voir l'en
```suggestion
Grâce à la commande <mark style="color:orange;">/topargent</mark> vous avez accès au classement économique du serveur. Vous y verrez les cinq premiers membres ainsi que votre position. Pour voir l'ensemble du classement, cliquez sur le bouton **"Voir l'ensemble du classement"** situé sous le message de **DraftBot**.
```
![image](https://user-images.githubusercontent.com/111301542/217945700-1c4ab11f-8711-4f9b-9b28-1f19d087b6cb.png)

2023-02-09 21:52 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +### Argent
```suggestion
### Votre argent

2023-02-09 21:52 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +Afin d'obtenir de l'argent, il faut que [le système d'économie](https://docs.draftbot.fr/slash/configuration/economie) soit activé sur le serveur.
Je ne vois pas trop l'intérêt du retour à la ligne ici.

```suggestion
Vous pouvez voir votre somme d'argent, ainsi que celle des autres membres en indiquant leur pseudo dans l'argument "membre" avec <mark style="color:orange;">/argent \[membre]</mark>. Pour d'obtenir de l'argent, il faut que [le système d'économie](https://docs.draftbot.fr/slash/configuration/economie) soit activé sur le serveur.
```
![image](https://user-images.githubusercontent.com/111301542/217947748-fdd7df2c-eda8-4c7e-b172-7a4f6df46058.png)

2023-02-14 10:16 UTC, DraftProducts requested changes
Voici quelques derniers retours

2023-02-14 10:16 UTC, DraftProducts commented on slash/gestion-de-leconomie.md
> +__**Commandes pour les administrateurs - Argent**__
```suggestion
### Modifier l'argent des utilisateurs
```

2023-02-14 10:16 UTC, DraftProducts commented on slash/gestion-de-leconomie.md
> +- <mark style="color:orange;">/dropargent</mark> ➜ Créer un message qui offre de l'argent au premier qui clique sur le bouton.
Je propose de déplacer cette section à la fin de cette page

2023-02-14 10:16 UTC, DraftProducts commented on slash/gestion-de-leconomie.md
> +Vous pouvez y acheter un rôle (temporaire ou non), de l'expérience, un objet d'inventaire et plein d'autres choses ! Elle est accessible avec la commande <mark style="color:orange;">/boutique</mark>\
```suggestion
Vous pouvez y acheter des rôles (temporaire ou non), de l'expérience, des objets d'inventaire ou des articles personnalisés.
Elle est accessible avec la commande <mark style="color:orange;">/boutique</mark>\.
```

2023-02-14 10:16 UTC, DraftProducts commented on slash/gestion-de-leconomie.md
> +![Boutique de DraftBot](../.gitbook/assets/economy/shop.png)
C'est un screen du marché noir, je propose de faire un screen de la boutique en mode normal et de déplacer ce screen dans le hint info (et de mettre le hint en dessous)

2023-02-14 10:16 UTC, DraftProducts commented on slash/gestion-de-leconomie.md
> +Si vous créez par contre vos items depuis le <mark style="color:orange;">[panel](https://draftbot.fr/dashboard/)</mark>, vous devez par contre récupérer l'<mark style="color:orange;">[identifiant](ht
```suggestion
Si vous créez vos items depuis le <mark style="color:orange;">[panel](https://draftbot.fr/dashboard/)</mark>, vous devrez récupérer l'affichage de l'émoji avec <mark style="color:orange;">[identifiant](https://docs.draftbot.fr/autres/recuperer-un-identifiant#identifiant-dun-emoji)</mark>. (en mettant un antislash (\\) devant celui-ci).
```

2023-02-14 17:03 UTC, bariboo commented on slash/gestion-de-leconomie.md
> +- <mark style="color:orange;">/dropargent</mark> ➜ Créer un message qui offre de l'argent au premier qui clique sur le bouton.
Je ne pense pas car on parle bien du sous titre Argent, je ne vois pas où on pourrait le mettre d'autre, à part si on recrée un sous titre expliquant cela mais je n'y vois pas d'utilitée 🤔

2023-02-14 17:04 UTC, bariboo commented
Du coup, juste l'image de la boutique ( *classique* ) à modifier 👍

2023-02-15 17:00 UTC, DraftProducts approved these changes

2023-02-15 23:08 UTC, Hugo-broc requested changes

2023-02-15 23:08 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Si vous créez vos items depuis le <mark style="color:orange;">[panel](https://draftbot.fr/dashboard/)</mark>, vous devrez récupérer l'affichage de l'émoji avec <mark style="color:orange;">[identifian
Je ne sais pas comment tu veux formuler ta phrase mais c'est bizarre ce "identifiant" tout seul.
Il faudrait mettre "récupérer l'affichage de l'émoji avec **l'identifiant**" ou "récupérer l'affichage de l'émoji avec **son identifiant**".

2023-02-16 19:18 UTC, bariboo commented
Hello ! Je me suis mis à faire la partie configuration mais elle n'est pas finie. Serait il possible de mettre ma PR en **Drafts** ? 
Merci !

2023-02-16 22:34 UTC, ErwanGit commented
C'est fait

2023-02-19 00:58 UTC, IIbey requested changes

2023-02-19 00:58 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +<mark style="color:blue;">Accéder au [panel](https://draftbot.fr/dashboard) de DraftBot</mark>.
```suggestion
<mark style="color:blue;">Accéder au [panel](https://draftbot.fr/dashboard) de DraftBot</mark>

2023-02-19 00:58 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +- "**Argent journalier**" ➜ Permet de définir l'argent que vos membres pourront gagner chaque jour via la commande <mark style="color:orange;">/journalier</mark>
```suggestion
- "**Argent journalier**" ➜ Permet de définir l'argent que vos membres pourront gagner chaque jour via la commande <mark style="color:orange;">/journalier</mark>.

2023-02-19 01:11 UTC, IIbey requested changes

2023-02-19 01:11 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +Pour créer un ****article** dans votre boutique, rendez-vous dans la catégorie "💰 Économie" de la commande <mark style="color:orange;">/config</mark> puis appuyez sur <mark style="color:blue;">"Confi
```suggestion
Pour créer un **article** dans votre boutique, rendez-vous dans la catégorie "💰 Économie" de la commande <mark style="color:orange;">/config</mark> puis appuyez sur <mark style="color:blue;">"Configuration de la boutique"</mark>.

2023-02-19 14:50 UTC, Hugo-broc requested changes
Il y aura encore pas mal de choses à modifier (niveau formulation notamment) mais c'est un début pour y voir plus clair 😅 
A modifier en plus :
- Mettre "DraftBot" en gras : `**DraftBot**`
- Pour le premium, comme le modèle (page "Niveaux"), mettre `***(✨ premium)***` à la fin de la phrase et pas juste l'émoji en début de phrase.

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +### Votre Argent
```suggestion
## Votre Argent
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Vous pouvez voir votre somme d'argent, ainsi que celle des autres membres en indiquant leur pseudo dans l'argument "membre" avec <mark style="color:orange;">/argent \[membre]</mark>. Pour d'obtenir d
```suggestion
Vous pouvez voir votre somme d'argent, ainsi que celle des autres membres en indiquant leur pseudo dans l'argument "Membre" avec <mark style="color:orange;">/argent \[membre]</mark>. Pour d'obtenir de l'argent, il faut que [le système d'économie](https://docs.draftbot.fr/slash/configuration/economie) soit activé sur le serveur.
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +### Modifier l'argent des utilisateurs
```suggestion
## Modifier l'argent des utilisateurs
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +### Classement
```suggestion
## Classement
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
>  ### Boutique
```suggestion
## Boutique
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Vous pouvez y acheter des rôles (temporaire ou non), de l'expérience, des objets d'inventaire ou des articles personnalisés.
```suggestion
Vous pouvez acheter dans la boutique des rôles (temporaire ou non), de l'expérience, des objets d'inventaire ou des articles personnalisés.
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +### Objets d'inventaire
```suggestion
## Objets d'inventaire
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Si vous créez vos items depuis le <mark style="color:orange;">[panel](https://draftbot.fr/dashboard/)</mark>, vous devrez récupérer l'affichage de l'émoji avec son <mark style="color:orange;">[identi
```suggestion
Si vous créez vos items depuis le <mark style="color:orange;">[panel](https://draftbot.fr/dashboard/)</mark>, vous devrez récupérer l'affichage de l'émoji avec son <mark style="color:orange;">[identifiant](https://docs.draftbot.fr/autres/recuperer-un-identifiant#identifiant-dun-emoji)</mark> (en mettant un antislash (\\) devant celui-ci).
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Voici les différants boutons ainsi que leurs utilités :
```suggestion
Voici les différents boutons ainsi que leurs utilités :
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +- "**✨Activer l'argent en vocal**" ➜ Une fois activé, les membres pourront gagner de l'argent en vocal.
```suggestion
- "**Activer l'argent en vocal**" ➜ Une fois activé, les membres pourront gagner de l'argent en vocal ***(✨ premium)***.
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +- "**✨Activer l'argent en vocal**" ➜ Une fois activé, les membres pourront gagner de l'argent en vocal.
Par rapport à la page "Niveaux", qui est la référence de la documentation :
```suggestion
- "**Activer l'argent en vocal**" ➜ Une fois activé, les membres pourront gagner de l'argent en vocal ***(✨ premium)***.
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +- "**✨Devise**" ➜ Permet de définir l'émoji symbolisant la monnaie du serveur.
```suggestion
- "**Devise**" ➜ Permet de définir l'émoji symbolisant la monnaie du serveur ***(✨ premium)***.
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +- "**✨Couleur**" ➜ Paramétrer une couleur pour tout le système d'économie.
```suggestion
- "**Couleur**" ➜ Paramétrer une couleur pour tout le système d'économie ***(✨ premium)***.
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +- "**Argent de départ**" ➜ Une fois activé, vous pourrez de définir l'argent qu'auront vos membres à leurs arrivé sur le serveur.
```suggestion
- "**Argent de départ**" ➜ Une fois activé, vous pourrez définir l'argent qu'auront vos membres à leur arrivée sur le serveur.
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +- "**Salons boosters**" ➜ Permet de donner plus d'argent à un membre si il envoie son message dans un certain salon.
```suggestion
- "**Salons boosters**" ➜ Permet de donner plus d'argent à un membre s'il envoie son message dans un certain salon.
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +- "**Activer le gain d'argent dans les fils**" ➜ Une fois cette option activée, vos membres pourront gagner de l'argent dans les fils et posts de **forum**.
```suggestion
- "**Activer le gain d'argent dans les fils**" ➜ Une fois cette option activée, vos membres pourront gagner de l'argent dans les fils et dans les posts.
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +*Les boutons précédés d'un "✨" indiquent que le <mark style="color:blue;">[premium](https://draftbot.fr/premium)</mark> est nécéssaire.*
```suggestion

```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +<mark style="color:blue;">Accéder au [panel](https://draftbot.fr/dashboard) de DraftBot</mark>
```suggestion
<mark style="color:blue;">Accéder au [panel](https://draftbot.fr/dashboard) de **DraftBot**</mark>
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Une fois sur le panel de DraftBot (accessible depuis le lien ci-dessus), rendez-vous sur la page <mark style="color:orange;">Économie</mark>.
```suggestion
Une fois sur le panel de **DraftBot** (accessible depuis le lien ci-dessus), rendez-vous sur la page <mark style="color:orange;">"Économie"</mark>.
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +- <mark style="color:blue;">"Expérience"</mark> ➜ Vos membres pourront acheter de l'expérience plus d'information [ici](https://docs.draftbot.fr/modules/niveaux)
```suggestion
- <mark style="color:blue;">"Expérience"</mark> ➜ Vos membres pourront acheter de l'expérience (plus d'information [ici](https://docs.draftbot.fr/modules/niveaux))
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +- <mark style="color:blue;">"Personnaliser"</mark> ➜ Vous pouvez vous même décidé de A à Z comment sera votre article (le titre ainsi que la description).
```suggestion
- <mark style="color:blue;">"Personnaliser"</mark> ➜ Créer une récompense personnalisée (quelque chose que **DraftBot** ne peut pas offrir).
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +- <mark style="color:blue;">"Objet"</mark> ➜ Un objet ou un item d'inventaire est un titre qui sera affiché dans la commande <mark style="color:orange;">/config</mark>
```suggestion
- <mark style="color:blue;">"Objet"</mark> ➜ Créer un item qui sera affiché dans votre <mark style="color:orange;">/inventaire</mark>.
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Une fois le bouton <mark style="color:blue;">"Créer"</mark> cliquez un menu va s'ouvrir :
```suggestion
Une fois le bouton <mark style="color:blue;">"Créer"</mark>cliqué, un menu s'ouvrira :
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Concernant le stock de vos articles, vous devez être <mark style="color:blue;">[premium](https://draftbot.fr/premium)</mark> pour pouvoir modifier celui-ci. Si ce n'est pas le cas, le stock est **ill
```suggestion
Vous pouvez avoir 10 articles maximum dans votre boutique. Si vous souhaitez débloquer cette limite et avoir un nombre illimité de récompenses, vous devez être <mark style="color:blue;">[premium](https://draftbot.fr/premium)</mark>.
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +- <mark style="color:blue;">"✨Stock"</mark> ➜ Modifier la quantité d'articles disponible dans la boutique.
```suggestion
- <mark style="color:blue;">"Stock"</mark> ➜ Modifier la quantité d'articles disponible dans la boutique ***(✨ premium)***.
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +*Les boutons précédés d'un "✨" indiquent que le <mark style="color:blue;">[premium](https://draftbot.fr/premium)</mark> est nécéssaire.*
```suggestion

```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Si vous avez plusieurs articles dans votre boutique, vous devrez dans le sélecteur, sélectionner quel article vous souhaitez modifer.
```suggestion
Si vous avez plusieurs articles dans votre boutique, vous devrez, dans le sélecteur, sélectionner l'article que vous voulez modifier.
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Si vous souhaitez supprimer un article, cliquez sur le bouton <mark style="color:blue;">"Supprimer"</mark> puis,  sélectionnez celui que vous souhaitez supprimer (dans le sélecteur).
```suggestion
Si vous souhaitez supprimer un article, cliquez sur le bouton <mark style="color:blue;">"Supprimer"</mark>. Sélectionnez ensuite celui que vous souhaitez supprimer (dans le sélecteur).
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Une fois la boutique réinitiallisée, il vous sera impossible de récupérer ce que vouzs aviez fait.
```suggestion
Une fois la boutique réinitialisée, il vous sera impossible de récupérer ce que vous aviez fait.
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +<mark style="color:blue;">Accéder au [panel](https://draftbot.fr/dashboard) de DraftBot</mark>
```suggestion
<mark style="color:blue;">Accéder au [panel](https://draftbot.fr/dashboard) de **DraftBot**</mark>
```

2023-02-19 14:50 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Pour créer un article, cliquez sur le gros bouton <mark style="color:orange;">Créer un article</mark>
```suggestion
Pour créer un article, cliquez sur le bouton <mark style="color:orange;">Créer un article</mark>
```

2023-02-19 15:43 UTC, ErwanGit requested changes
Les noms de fichiers doivent être en anglais

2023-02-20 19:13 UTC, Hugo-broc requested changes
Après cela sera bon pour moi ! 👍

2023-02-20 19:13 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Une fois sur le panel de **DraftBot** (accessible depuis le lien ci-dessus), rendez-vous sur la page <mark style="color:orange;">"Économie"</mark>.
```suggestion
Une fois sur le panel de **DraftBot** (accessible depuis le lien ci-dessus), rendez-vous sur la page "Économie".
```

2023-02-20 19:13 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +{% hint style="warning" %}
```suggestion

```

2023-02-20 19:13 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +{% endhint %}
```suggestion

```

2023-02-20 19:13 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Une fois fini, n'oubliez pas d'enregistrer vos modifications avec le bouton "Enregistrer" en bas de la page.
```suggestion
> ⚠️ Une fois fini, n'oubliez pas d'enregistrer vos modifications avec le bouton "Enregistrer" en bas de la page.
```

2023-02-20 19:13 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +- <mark style="color:blue;">"Expérience"</mark> ➜ Vos membres pourront acheter de l'expérience (plus d'information [ici](https://docs.draftbot.fr/modules/niveaux))
```suggestion
- <mark style="color:blue;">"Expérience"</mark> ➜ Vos membres pourront acheter de l'expérience (plus d'informations <mark style="color:blue;">[ici](https://docs.draftbot.fr/modules/niveaux)</mark>)
```

2023-02-20 19:13 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Si vous avez plusieurs articles dans votre boutique, vous devrez dans le sélecteur, sélectionner quel article vous souhaitez modifer.
```suggestion
Si vous avez plusieurs articles dans votre boutique, vous devrez, dans le sélecteur, sélectionner quel article vous souhaitez modifer.
```

2023-02-20 19:13 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Si vous avez plusieurs articles dans votre boutique, vous devrez, dans le sélecteur, sélectionner l'article que vous voulez modifier.
```suggestion
Si vous avez plusieurs articles dans votre boutique, vous devrez, dans le sélecteur, sélectionner l'article que vous voulez supprimer.
```

2023-02-20 19:13 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Pour créer un article, cliquez sur le bouton <mark style="color:orange;">Créer un article</mark>
```suggestion
Pour créer un article, cliquez sur le bouton "<mark style="color:orange;">Créer un article</mark>".
```

2023-02-20 19:13 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Pour créer un article, cliquez sur le bouton <mark style="color:orange;">Créer un article</mark>. Les options de configuration sont les mêmes que sur la commande <mark style="color:orange;">/config</
```suggestion
Pour créer un article, cliquez sur le bouton "<mark style="color:orange;">Créer un article</mark>". Les options de configuration sont les mêmes que sur la commande <mark style="color:orange;">/config</mark>. Vous pouvez donc vous rendre dans l'onglet `(Via la commande /config)` pour les comparer.
```

2023-02-20 19:13 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Si vous souhaitez mettre des emojies sur vos items, vous devrez récupérer l'affichage de l'émoji avec son <mark style="color:blue;">[identifiant](https://docs.draftbot.fr/autres/recuperer-un-identifi
```suggestion
Si vous souhaitez mettre des emojis sur vos items, vous devrez récupérer l'affichage de l'émoji avec son <mark style="color:blue;">[identifiant](https://docs.draftbot.fr/autres/recuperer-un-identifiant#identifiant-dun-emoji)</mark> (en mettant un antislash (\\) devant celui-ci).
```

2023-02-20 19:13 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Si vous vous rendez compte qu'une erreur s'est glissée dans un de vos articles, vous pouvez le modifier, en cliquant sur le bouton nommé ci-dessus dans la liste de vos articles.
```suggestion
Si vous vous rendez compte qu'une erreur s'est glissée dans un de vos articles, vous pouvez le modifier en cliquant sur le bouton nommé ci-dessus dans la liste de vos articles.
```

2023-02-20 19:13 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +{% hint style="warning" %}
```suggestion

```

2023-02-20 19:13 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +{% endhint %}
```suggestion

```

2023-02-20 19:13 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Une fois fini, n'oubliez pas d'enregistrer vos modifications avec le bouton "Enregistrer" en bas de la page.
```suggestion
> ⚠️ Une fois fini, n'oubliez pas d'enregistrer vos modifications avec le bouton "Enregistrer" en bas de la page.
```

2023-02-20 19:35 UTC, bariboo commented on slash/gestion-de-leconomie.md
> +Une fois fini, n'oubliez pas d'enregistrer vos modifications avec le bouton "Enregistrer" en bas de la page.
Je ne suis pas d'accord avec celui-ci je trouve mieux présenté la version actuelle.

2023-02-20 19:37 UTC, bariboo commented
Merci @Hugo-broc ! Bon il y avait pas t'en d'imperfection que ça, merci pour ce boulot de dingue :pray: !

@DraftProducts il y aura les images à faire :thumbumsp:

*Je ferai aussi un check de mon côté*

2023-02-21 00:00 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +ne fois la boutique réinitialisée, il vous sera impossible de récupérer ce que vous aviez fait.
```suggestion
Une fois la boutique réinitialisée, il vous sera impossible de récupérer ce que vous aviez fait.

2023-02-21 00:01 UTC, IIbey commented on slash/gestion-de-leconomie.md
> +Si vous souhaitez mettre des emojies sur vos items, vous devrez récupérer l'affichage de l'émoji avec son <mark style="color:blue;">[identifiant](https://docs.draftbot.fr/autres/recuperer-un-identifi
Update
````suggestion
Si vous souhaitez mettre des émojis sur vos items, vous devrez récupérer l'affichage de l'émoji avec son <mark style="color:blue;">[identifiant](https://docs.draftbot.fr/autres/recuperer-un-identifiant#identifiant-dun-emoji)</mark> (en mettant un antislash (\\) devant celui-ci).

2023-02-21 07:58 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Vous pouvez voir votre somme d'argent, ainsi que celle des autres membres en indiquant leur pseudo dans l'argument "Membre" avec <mark style="color:orange;">/argent \[membre]</mark>. Pour d'obtenir d
Oui, effectivement, erreur de ma part.

2023-02-21 08:04 UTC, Hugo-broc commented on slash/gestion-de-leconomie.md
> +Une fois fini, n'oubliez pas d'enregistrer vos modifications avec le bouton "Enregistrer" en bas de la page.
Bah sur la page de référence (Niveaux), c'est pas ce format là. Donc il vaut mieux universaliser les formulations.
![Référence à la doc "Niveaux"](https://user-images.githubusercontent.com/120671943/220284374-14097826-b248-4e5c-894f-bf8119611f2c.png)

2023-02-21 12:19 UTC, DraftProducts commented
Je pense qu'on est bon pour les images :v:

2023-02-21 21:10 UTC, ErwanGit requested changes

2023-02-21 21:10 UTC, ErwanGit commented on modules/economie.md
> +![Carte d'économie](../.gitbook/assets/economy/money.png)
Même si c'est pas prévu qu'on le change pour le moment car Discord n'est pas définitivement ok avec cette nouvelle couleur entre mobile et ordinateur, peut-être trafiquer ou utiliser un bot de dev pour que l'image est le même fond entre le fond de l'embed et l'image

2023-02-21 21:10 UTC, ErwanGit commented on modules/economie.md
> +Il vous faut d'abord configurer ce système.
Peut-être ajouter un hyperlink vers la partie configuration ?

2023-02-21 21:10 UTC, ErwanGit commented on modules/economie.md
> +Le marché noir est une variante de la boutique consistant à se supprimer au bout de 60 secondes d'inactivité, ni vu ni connu ! Plus d'informations [ici](https://docs.draftbot.fr/slash/economie#typede
Peut-être en couleur le mot ici ?

2023-02-21 21:10 UTC, ErwanGit commented on modules/economie.md
> +Le marché noir est une variante de la boutique consistant à se supprimer au bout de 60 secondes d'inactivité, ni vu ni connu ! Plus d'informations [ici](https://docs.draftbot.fr/slash/economie#typede
```suggestion
Le marché noir est une variante de la boutique consistant à se supprimer au bout de 60 secondes d'inactivité, ni vu ni connu ! Plus d'informations [ici](https://docs.draftbot.fr/slash/economie#typedelaboutique).
```

2023-02-21 21:10 UTC, ErwanGit commented on modules/economie.md
> +Si vous ne voyez aucune option, c'est normal car il vous faut activer le système en cliquant sur le bouton d'activation du module. Si vous voulez le désactiver, recliquez sur ce même bouton.
Je trouve cette formulation un peu maladroite, éventuellement voir pour la reformuler

2023-02-21 21:10 UTC, ErwanGit commented on modules/economie.md
> +Comme vous l'avez peut être remarqué, les sous-catégories (voir image) sont les mêmes que sur la commande <mark style="color:orange;">/config</mark>. Vous pouvez donc vous rendre dans l'onglet `(Via
```suggestion
Comme vous l'avez peut être remarqué, les sous-catégories sont les mêmes que sur la commande <mark style="color:orange;">/config</mark>. Vous pouvez donc vous rendre dans l'onglet via la commande `/config` pour comparer les options de configuration.
```

2023-02-21 21:10 UTC, ErwanGit commented on modules/economie.md
> +Comme vous l'avez peut être remarqué, les sous-catégories (voir image) sont les mêmes que sur la commande <mark style="color:orange;">/config</mark>. Vous pouvez donc vous rendre dans l'onglet `(Via
Après, je suis pas fan de cette phrase, tu veux le configurer sur le panel, tu n'as pas besoin de savoir sur le `/config`

2023-02-21 21:10 UTC, ErwanGit commented on modules/economie.md
> +- <mark style="color:blue;">"Expérience"</mark> ➜ Vos membres pourront acheter de l'expérience (plus d'informations [ici](https://docs.draftbot.fr/modules/niveaux))
En plus, peut-être mettre un peu plus en valeur le ici et éventuellement mettre l'hyperlink sur le mot expérience plutôt que de faire une phrase à part
```suggestion
- <mark style="color:blue;">"Expérience"</mark> ➜ Vos membres pourront acheter de l'expérience (plus d'informations [ici](https://docs.draftbot.fr/modules/niveaux)).
```

2023-02-21 21:10 UTC, ErwanGit commented on modules/economie.md
> +- <mark style="color:blue;">"Objet"</mark> ➜ Un objet ou un item d'inventaire est un titre qui sera affiché dans la commande <mark style="color:orange;">/config</mark>
```suggestion
- <mark style="color:blue;">"Objet"</mark> ➜ Un objet ou un item d'inventaire est un titre qui sera affiché dans la commande <mark style="color:orange;">/config</mark>.
```

2023-02-21 21:10 UTC, ErwanGit commented on modules/economie.md
> +{% endhint %}
Je sais pas si c'est vraiment utile de le préciser

2023-02-22 13:18 UTC, bariboo commented on modules/economie.md
> +Comme vous l'avez peut être remarqué, les sous-catégories (voir image) sont les mêmes que sur la commande <mark style="color:orange;">/config</mark>. Vous pouvez donc vous rendre dans l'onglet `(Via
> Après, je suis pas fan de cette phrase, tu veux le configurer sur le panel, tu n'as pas besoin de savoir sur le `/config`

Tu n'as pas bien compris ce que je voulais dire, je parle du tab d'à côté pour voir quelle option correspond à quoi, pour ne pas avoir tout à réécrire, Hugo a mis cela dans sa PR : 
> Sur le panel, vous retrouverez sur une même page, les mêmes possibilités de configuration qu'avec les commandes Slash sur Discord.

Je trouvais plus explicite la manière dont je l'ai mis, si tu veux, je peux aussi mettre cela ! 🙂

2023-02-22 13:22 UTC, bariboo commented on modules/economie.md
> +![Carte d'économie](../.gitbook/assets/economy/money.png)
Je n'ai pas bien compris, je te demanderai en vocal.

2023-02-22 15:48 UTC, ErwanGit commented on modules/economie.md
> +Comme vous l'avez peut être remarqué, les sous-catégories (voir image) sont les mêmes que sur la commande <mark style="color:orange;">/config</mark>. Vous pouvez donc vous rendre dans l'onglet `(Via
Je ne vois pas l'intérêt de cette phrase, si tu veux configurer sur le panel, tu t'en moques du /config

2023-02-24 13:25 UTC, bariboo commented on modules/economie.md
> +Comme vous l'avez peut être remarqué, les sous-catégories (voir image) sont les mêmes que sur la commande <mark style="color:orange;">/config</mark>. Vous pouvez donc vous rendre dans l'onglet `(Via
J'ai mis la mêmme chose que Hugo !

2023-02-24 14:55 UTC, bariboo commented
Il manque plus que ce problème de screen, j'attend de voir en vocal 👌 Après on pourra Merge.

2023-02-24 20:05 UTC, ErwanGit commented on modules/economie.md
> +![Carte d'économie](../.gitbook/assets/economy/money.png)
On voit que le fond n'est pas identique 
<img width="548" alt="image" src="https://user-images.githubusercontent.com/24718500/221280004-bc825e73-c891-4a5f-b9ac-278ad3992733.png">

2023-02-24 20:07 UTC, ErwanGit commented on modules/economie.md
> +Comme vous l'avez peut être remarqué, les sous-catégories (voir image) sont les mêmes que sur la commande <mark style="color:orange;">/config</mark>. Vous pouvez donc vous rendre dans l'onglet `(Via
Ce n'est pas parce que tu as mis la même chose que lui que je suis forcement d'accord

2023-02-24 20:10 UTC, ErwanGit requested changes
Il y a aussi mes deux autres commentaires non résolu plus haut à (re)prendre en compte

2023-02-25 15:31 UTC, bariboo commented on modules/economie.md
> +Comme vous l'avez peut être remarqué, les sous-catégories (voir image) sont les mêmes que sur la commande <mark style="color:orange;">/config</mark>. Vous pouvez donc vous rendre dans l'onglet `(Via
> Ce n'est pas parce que tu as mis la même chose que lui que je suis forcement d'accord

Donc tu penserais plutôt à quoi comme phrase car je n'en est aucune idée 🤔 Je redécrit toute la configuration ?

2023-02-25 15:37 UTC, ErwanGit commented on modules/economie.md
> +Comme vous l'avez peut être remarqué, les sous-catégories (voir image) sont les mêmes que sur la commande <mark style="color:orange;">/config</mark>. Vous pouvez donc vous rendre dans l'onglet `(Via
La capture d'écran est suffisamment explicite je pense, non ?

2023-02-25 15:40 UTC, bariboo commented on modules/economie.md
> +Comme vous l'avez peut être remarqué, les sous-catégories (voir image) sont les mêmes que sur la commande <mark style="color:orange;">/config</mark>. Vous pouvez donc vous rendre dans l'onglet `(Via
Oky, je pourrais mettre cela en info hint, pour être sûr non ?

2023-02-25 15:44 UTC, bariboo commented on modules/economie.md
> +![Carte d'économie](../.gitbook/assets/economy/money.png)
De mon point de vue, je ne sais pas si ça fait une grosse différance t'en pense quoi ? Car les gens comprendront en voyant le screen.

2023-02-26 11:37 UTC, ErwanGit commented on modules/economie.md
> +Comme vous l'avez peut être remarqué, les sous-catégories (voir image) sont les mêmes que sur la commande <mark style="color:orange;">/config</mark>. Vous pouvez donc vous rendre dans l'onglet `(Via
Je n'ai pas compris

2023-02-26 20:25 UTC, ErwanGit requested changes

2023-02-26 20:25 UTC, ErwanGit commented on modules/economie.md
> +![Carte d'économie](../.gitbook/assets/economy/money.png)
Tu ne peux pas mettre la capture d'écran comme ça, il y a le nom du bot de développement
Il faudrait rogner l'image comme précédement

2023-02-28 14:08 UTC, IIbey requested changes
Après l'ajout des points manquants, pour moi cette PR est good.

2023-02-28 14:08 UTC, IIbey commented on modules/economie.md
> +Rendez-vous d'abord dans la catégorie "💰 Économie" de la commande <mark style="color:orange;">/config</mark> puis appuyez sur <mark style="color:blue;">"Configuration de la boutique"</mark>
```suggestion
Rendez-vous d'abord dans la catégorie "💰 Économie" de la commande <mark style="color:orange;">/config</mark> puis appuyez sur <mark style="color:blue;">"Configuration de la boutique"</mark>.

2023-02-28 14:08 UTC, IIbey commented on modules/economie.md
> +- <mark style="color:blue;">"Expérience"</mark> ➜ Vos membres pourront acheter de l'<mark style="color:blue;">[expérience](https://docs.draftbot.fr/modules/niveaux)</mark>
```suggestion
- <mark style="color:blue;">"Expérience"</mark> ➜ Vos membres pourront acheter de l'<mark style="color:blue;">[expérience](https://docs.draftbot.fr/modules/niveaux)</mark>.

2023-02-28 14:08 UTC, IIbey commented on modules/economie.md
> +Si vous souhaitez réinitialiser votre boutique, cliquez sur le bouton <mark style="color:blue;">"Réinitialiser"</mark>
```suggestion
Si vous souhaitez réinitialiser votre boutique, cliquez sur le bouton <mark style="color:blue;">"Réinitialiser"</mark>.

2023-02-28 14:08 UTC, IIbey commented on modules/economie.md
> +Si vous souhaitez modifier le type de la boutique, cliquez sur le bouton <mark style="color:blue;">"Type de la boutique"</mark>
```suggestion
Si vous souhaitez modifier le type de la boutique, cliquez sur le bouton <mark style="color:blue;">"Type de la boutique"</mark>.

2023-02-28 14:08 UTC, IIbey commented on modules/economie.md
> +Pour créer un article, cliquez sur le bouton "<mark style="color:orange;">Créer un article</mark>"
```suggestion
Pour créer un article, cliquez sur le bouton "<mark style="color:orange;">Créer un article</mark>".

2023-02-28 14:08 UTC, IIbey commented on modules/economie.md
> +Si vous souhaitez supprimer un article, cliquez sur le bouton <mark style="color:red;">"Supprimer"</mark>
```suggestion
Si vous souhaitez supprimer un article, cliquez sur le bouton <mark style="color:red;">"Supprimer"</mark>.

2023-02-28 14:58 UTC, DraftProducts approved these changes

2023-02-28 17:50 UTC, ErwanGit requested changes

2023-02-28 17:50 UTC, ErwanGit commented on modules/economie.md
> +Vous pouvez voir votre somme d'argent, ainsi que celle des autres membres en indiquant leur pseudo dans l'argument "Membre" avec <mark style="color:orange;">/argent \[**membre**]</mark>. Pour d'obten
```suggestion
Vous pouvez voir votre somme d'argent, ainsi que celle des autres membres en indiquant leur pseudo dans l'argument "Membre" avec <mark style="color:orange;">/argent \[**membre**]</mark>. Pour d'obtenir de l'argent, il faut que [le système d'économie](https://docs.draftbot.fr/modules/economie#configuration) soit activé sur le serveur.
```

2023-02-28 17:50 UTC, ErwanGit commented on modules/economie.md
> +Il vous faut d'abord <mark style="color:blue;">[__configurer__](https://docs.draftbot.fr/slash/module/economie#configuration)</mark> ce système.
```suggestion
Il vous faut d'abord <mark style="color:blue;">[__configurer__](https://docs.draftbot.fr/modules/economie#configuration)</mark> ce système.
```

2023-02-28 17:50 UTC, ErwanGit commented on modules/economie.md
> +Le marché noir est une variante de la boutique consistant à se supprimer au bout de 60 secondes d'inactivité, ni vu ni connu ! Plus d'informations <mark style="color:blue;">[__ici__](https://docs.dra
```suggestion
Le marché noir est une variante de la boutique consistant à se supprimer au bout de 60 secondes d'inactivité, ni vu ni connu ! Plus d'informations <mark style="color:blue;">[__ici__](https://docs.draftbot.fr/modules/economie#type-de-la-boutique-1)</mark>.
```

2023-02-28 17:50 UTC, ErwanGit commented on modules/economie.md
> +Vous avez la possibilité avec **DraftBot** de pouvoir animer la vie de votre serveur avec des objets d'inventaire. Une fois achetés dans la __<mark style="color:blue;">[boutique](https://docs.draftbo
```suggestion
Vous avez la possibilité avec **DraftBot** de pouvoir animer la vie de votre serveur avec des objets d'inventaire. Une fois achetés dans la __<mark style="color:blue;">[boutique](https://docs.draftbot.fr/modules/economie#boutique)</mark>__ ou gagnés, vous pouvez effectuer les commandes :
```

2023-02-28 17:50 UTC, ErwanGit commented on modules/economie.md
> +Une fois sur le panel de **DraftBot** (accessible depuis le lien ci-dessus), rendez-vous sur la page "Économie".
Je ne sais si c'est vraiment utile de mettre ça puisque c'est juste au dessus
```suggestion
Une fois sur le panel de **DraftBot**, rendez-vous sur la page "Économie".
```

2023-02-28 17:50 UTC, ErwanGit commented on modules/economie.md
> +Une fois sur le panel de **DraftBot** (accessible depuis le lien ci-dessus), rendez-vous en bas de la page "Économie".
Je ne sais si c'est vraiment utile de mettre ça puisque c'est juste au dessus
```suggestion
Une fois sur le panel de **DraftBot**, rendez-vous en bas de la page "Économie".
```

2023-02-28 22:40 UTC, DraftProducts commented on modules/economie.md
> +Vous pouvez voir votre somme d'argent, ainsi que celle des autres membres en indiquant leur pseudo dans l'argument "Membre" avec <mark style="color:orange;">/argent \[**membre**]</mark>. Pour d'obten
Pas besoin de mettre le NDD normalement

2023-03-02 14:45 UTC, Hugo-broc requested changes
Merci de ne pas mettre les boutons de couleur en couleur **avec les `""`. 
Les `""` ne font pas partie du bouton.

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +Vous pouvez voir votre somme d'argent, ainsi que celle des autres membres en indiquant leur pseudo dans l'argument "Membre" avec <mark style="color:orange;">/argent \[**membre**]</mark>. Pour d'obten
```suggestion
Vous pouvez voir votre somme d'argent, ainsi que celle des autres membres en indiquant leur pseudo dans l'argument "Membre" avec <mark style="color:orange;">/argent \[membre]</mark>. Pour d'obtenir de l'argent, il faut que <mark style="color:blue;">[le système d'économie](https://docs.draftbot.fr/modules/economie#configuration)</mark> soit activé sur le serveur.
```

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +Rendez-vous d'abord dans la catégorie "💰 Économie" de la commande <mark style="color:orange;">/config</mark> puis appuyez sur <mark style="color:blue;">"Configuration de la boutique"</mark>.
```suggestion
Rendez-vous d'abord dans la catégorie "💰 Économie" de la commande <mark style="color:orange;">/config</mark> puis appuyez sur "<mark style="color:blue;">Configuration de la boutique</mark>".
```

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +Après avoir cliqué sur le bouton <mark style="color:blue;">"Créer"</mark>, un menu va s'ouvrir :
```suggestion
Après avoir cliqué sur le bouton "<mark style="color:blue;">Créer</mark>", un menu va s'ouvrir :
```

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +- <mark style="color:blue;">"Rôle"</mark> ➜ Vos membres pourront acheter un rôle prédéfini.
```suggestion
- "<mark style="color:blue;">Rôle</mark>" ➜ Vos membres pourront acheter un rôle prédéfini.
```

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +- <mark style="color:blue;">"Rôle temporaire"</mark> ➜ Vos membres pourront acheter un rôle prédéfini qu'ils garderont durant une durée choisie.
```suggestion
- "<mark style="color:blue;">Rôle temporaire</mark>" ➜ Vos membres pourront acheter un rôle prédéfini qu'ils garderont durant une durée choisie.
```

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +- <mark style="color:blue;">"Expérience"</mark> ➜ Vos membres pourront acheter de l'<mark style="color:blue;">[expérience](https://docs.draftbot.fr/modules/niveaux)</mark>.
```suggestion
- "<mark style="color:blue;">Expérience</mark>" ➜ Vos membres pourront acheter de l'<mark style="color:blue;">[expérience](https://docs.draftbot.fr/modules/niveaux)</mark>.
```

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +- <mark style="color:blue;">"Personnaliser"</mark> ➜ Créer une récompense personnalisée (quelque chose que **DraftBot** ne peut pas offrir).
```suggestion
- "<mark style="color:blue;">Personnaliser</mark>" ➜ Créer une récompense personnalisée (quelque chose que **DraftBot** ne peut pas offrir).
```

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +Si vous vous rendez compte qu'une erreur s'est glissée dans un de vos articles, vous pouvez le modifier, en cliquant sur le bouton <mark style="color:blue;">"Modifier"</mark> :
```suggestion
Si vous vous rendez compte qu'une erreur s'est glissée dans un de vos articles, vous pouvez le modifier, en cliquant sur le bouton "<mark style="color:blue;">Modifier</mark>" :
```

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +Si vous souhaitez supprimer un article dans votre boutique, cliquez sur le bouton <mark style="color:blue;">"Supprimer"</mark> puis choisissez l'article à retirer.
```suggestion
Si vous souhaitez supprimer un article dans votre boutique, cliquez sur le bouton "<mark style="color:blue;">Supprimer</mark>" puis choisissez l'article à retirer.
```

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +Si vous souhaitez réinitialiser votre boutique, cliquez sur le bouton <mark style="color:blue;">"Réinitialiser"</mark>.
```suggestion
Si vous souhaitez réinitialiser votre boutique, cliquez sur le bouton "<mark style="color:blue;">Réinitialiser</mark>".
```

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +- <mark style="color:blue;">"Normal"</mark> ➜ Le message de la boutique est conservé.
```suggestion
- "<mark style="color:blue;">Normal</mark>" ➜ Le message de la boutique est conservé.
```

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +- <mark style="color:blue;">"Noir"</mark> ➜ Le message de la boutique est supprimé automatiquement après 60 secondes d'inactivité.
```suggestion
- "<mark style="color:blue;">Noir</mark>" ➜ Le message de la boutique est supprimé automatiquement après 60 secondes d'inactivité.
```

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +Une pop-up s'ouvrira dans laquelle vous pourrez configurer votre article.
Pop-up, comme tous les mots anglais que l'on dit en français sont au masculin (un hamburger, un chips (oui, on dit bien ça)...)
```suggestion
Un pop-up s'ouvrira dans lequel vous pourrez configurer votre article.
```

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +![Pop-up création d'un article](../.gitbook/assets/economy/dashboard_article_create_popup.png)
Peut-être prendre que la page du pop-up car ici cela fait une très grosse image avec un contour inutile et immense.

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +Pour créer un article, cliquez sur le bouton <mark style="color:orange;">"Créer un article"</mark>. Les options de configuration sont les mêmes que sur la commande <mark style="color:orange;">/config
```suggestion
Pour créer un article, cliquez sur le bouton "<mark style="color:orange;">Créer un article</mark>". Les options de configuration sont les mêmes que sur la commande <mark style="color:orange;">/config</mark>. Vous pouvez donc vous rendre dans l'onglet `(Via la commande /config)` pour les comparer.
```

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +Si vous souhaitez supprimer un article, cliquez sur le bouton <mark style="color:red;">"Supprimer"</mark>.
```suggestion
Si vous souhaitez supprimer un article, cliquez sur le bouton "<mark style="color:red;">Supprimer</mark>".
```

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +- <mark style="color:blue;">"Normal"</mark> ➜ Le message de la boutique est conservé.
```suggestion
- "<mark style="color:blue;">Normal</mark>" ➜ Le message de la boutique est conservé.
```

2023-03-02 14:45 UTC, Hugo-broc commented on modules/economie.md
> +- <mark style="color:blue;">"Noir"</mark> ➜ Le message de la boutique est supprimé automatiquement après 60 secondes d'inactivité.
```suggestion
- "<mark style="color:blue;">Noir</mark>" ➜ Le message de la boutique est supprimé automatiquement après 60 secondes d'inactivité.
```

2023-03-04 18:12 UTC, bariboo commented
Hello ! Je crois que on en a enfin fini, j'ai corrigé toute les erreurs !

2023-03-06 20:56 UTC, DraftProducts commented
Félicitations à toi @bariboo pour cette page de doc ! Je pense que peut se permettre de la merge 🎉

2023-03-06 20:56 UTC, merged