WIP - Messages récurrents
DraftBot/Documentation pull request #93
Opened 2024-03-06 19:10 UTC by kazotka

2024-03-06 21:31 UTC, DraftProducts commented on modules/messages-récurrents.md
> +Vous devez sélectionner le type d'intervalle pour l'envoie. *(<mark style="color:blue;">[Voir la référance ici](#intervalle-denvoi)</mark>)*
```suggestion
Vous devez sélectionner le type d'intervalle pour l'envoie. *(<mark style="color:blue;">[Voir la référance ici](repeat-messages.md#intervalle-denvoi)</mark>)*

```

2024-03-06 21:31 UTC, DraftProducts commented on SUMMARY.md
> +- [🔔 Messages récurents](modules/messages-r%C3%A9currents.md)
```suggestion
- [🔔 Messages récurrents](modules/repeat-messages.md)
```

2024-03-07 01:02 UTC, kazotka commented on modules/messages-récurrents.md
> +Vous devez sélectionner le type d'intervalle pour l'envoie. *(<mark style="color:blue;">[Voir la référance ici](#intervalle-denvoi)</mark>)*
C'est fait merci !

2024-03-10 22:19 UTC, kazotka commented
Il reste à corriger 2, 3 truc plus les fautes et j'ai fini !

2024-03-10 22:20 UTC, kazotka commented
@DraftProducts possible de retirer le contours des images svp !

2024-03-14 14:45 UTC, DraftProducts commented
Page mis a jour pour la nouvelle doc

2024-03-14 23:07 UTC, kazotka commented
Faute corriger, mais il en reste aux moins 7 car languages tools demande le premium pour les corriger

2024-03-14 23:23 UTC, DraftProducts requested changes
A part le fait que tu ne sais pas écrire le nom de DraftBot, tout est bon, les propositions premium sont des reformulations, on s'en fou.

2024-03-14 23:23 UTC, DraftProducts commented on 2.modules/23.repeat-messages.md
> +    Vous pouvez maintenant faire place à votre imagination pour créer votre message via le système création d'embed de Draftbot !
```suggestion
    Vous pouvez maintenant faire place à votre imagination pour créer votre message via le système création d'embed de DraftBot !

```

2024-03-15 02:23 UTC, kazotka commented on 2.modules/23.repeat-messages.md
> +    Vous pouvez maintenant faire place à votre imagination pour créer votre message via le système création d'embed de Draftbot !
roohh cv c'est juste une majuscule xD

2024-03-15 12:00 UTC, IIbey requested changes

2024-03-15 12:06 UTC, IIbey requested changes

2024-03-15 12:06 UTC, IIbey commented on 2.modules/23.repeat-messages.md
> +Permet que le message précédent soit supprimé lors du nouvel envoi.
```suggestion
Cette fonctionnalité permet de supprimer le message précédent lors d'un nouvel envoi.

2024-03-15 23:01 UTC, merged