Ajout page privaterooms
DraftBot/Documentation pull request #94
Opened 2024-03-19 21:33 UTC by kazotka

2024-03-20 01:50 UTC, kazotka commented
Draftman je suis prêt à merge ! Juste corriger les assets des boutons. De plus, je ne vois pas faute même avec language tools juste pour valider je mis Ibey en review

2024-03-21 03:15 UTC, DraftProducts requested changes
- Il manque selon moi un screen ou un gif de fonctionnement (gif en fonction du rendu).
- Il manque une partie concernant les salons permanants et leur importance (le warning suffit pas) (selon moi l'une des options les plus incomprises).
- La partie "Supprimer un hub de salons vocaux temporaires" peut peut être être déplacé en dernière section de la config comme tu l'as si bien fait pour le panel.
- "Utilisation du configurateur" peut selon moi prendre place en tant que deuxième section de la documentation, super importante (plus que la config).
- "Limite d'hubs" peut clairement prendre sa place en tant que warning lors de la partie qui traite de leur création.


Fix pour moi : 
- Virer les margin du dessus des titres quand ils sont les premiers éléments d'un tab.

2024-03-21 20:53 UTC, kazotka commented
- [ ] Il manque selon moi un screen ou un gif de fonctionnement (gif en fonction du rendu).

 -  [ ] Il manque une partie concernant les salons permanants et leur importance (le warning suffit pas) (selon moi l'une des options les plus incomprises).

 -  [ ] La partie "Supprimer un hub de salons vocaux temporaires" peut peut être être déplacé en dernière section de la config comme tu l'as si bien fait pour le panel.

 -  [ ] "Utilisation du configurateur" peut selon moi prendre place en tant que deuxième section de la documentation, super importante (plus que la config).

  - [ ] "Limite d'hubs" peut clairement prendre sa place en tant que warning lors de la partie qui traite de leur création.

 -  [ ]  Virer les margin du dessus des titres quand ils sont les premiers éléments d'un tab.

2024-03-23 00:37 UTC, kazotka commented
J'ai toujours l'erreur sur la preview

2024-03-24 00:08 UTC, DraftProducts commented
C'est corrigé !

2024-03-30 16:19 UTC, ErwanGit requested changes

2024-03-30 16:19 UTC, ErwanGit commented on 2.modules/24.privateroom.md
> +  Cet embed permet notamment d'utiliser toutes les permissions de modération, et ce même si le membre n'a pas activé l'A2F (puisque l'utilisateur passe par le bot et non pas par son compte).
```suggestion
  Cet embed permet notamment d'utiliser toutes les permissions de modération, et ce même si le membre n'a pas activé l'authentifcation à deux facteurs (puisque l'utilisateur passe par le bot et non pas par son compte).
```

2024-03-30 16:19 UTC, ErwanGit commented on 2.modules/24.privateroom.md
> +![Illustration des bouttons du configurateur](/.assets/privateroom/view_button.png)
```suggestion
![Illustration des boutons du configurateur](/.assets/privateroom/view_button.png)
```

2024-03-30 16:19 UTC, ErwanGit commented on 2.modules/24.privateroom.md
> +- `{custom-word}` pour attribuer un mot aléatoire parmi une liste personnalisable.
Il faudrait indiquer quelque part comment faire pour ajouter des mots personnalisés

2024-03-30 16:19 UTC, ErwanGit commented on 2.modules/24.privateroom.md
> +    > *Par défaut, elle est donc décochée et déconseillée pour les serveurs communautaires*
```suggestion
    > *Par défaut, elle est donc décochée et déconseillée pour les serveurs communautaires.*
```

2024-03-30 16:19 UTC, ErwanGit commented on .assets/privateroom/view_delete.png
Il faudrait remonter le souci d'affichage sur le panel dans cette situation 🤔

2024-03-30 21:35 UTC, kazotka commented on .assets/privateroom/view_delete.png
Je ne suis pas sure de comprendre je n'ai aucun souci d'affichage de mon côté

2024-03-30 21:39 UTC, kazotka commented on 2.modules/24.privateroom.md
> +- `{custom-word}` pour attribuer un mot aléatoire parmi une liste personnalisable.
la ligne juste au dessus (100) explique le processus du moins si se n'ai pas suffisant je peut modifier

2024-03-31 03:09 UTC, DraftProducts commented on .assets/privateroom/view_delete.png
- Il y a	 marqué "salons à supprimer" et il n'y a rien en dessous.
- Le footer avec le bouton confirmer touche pas le bas.

2024-04-02 18:26 UTC, ErwanGit commented on 2.modules/24.privateroom.md
> +- `{custom-word}` pour attribuer un mot aléatoire parmi une liste personnalisable.
Je pense que celas serait bien d'y ajouter une capture d'écran pour illustrer

2024-04-04 23:12 UTC, codelivins commented
slt poto
![un_image_de_garon_avec_des_cheve_bleu_dans_une_ (1)](https://github.com/DraftBot/Documentation/assets/166078594/42496d2a-0f91-46e4-8d73-d4dceedb244b)

2024-04-04 23:14 UTC, codelivins commented
moi je suis débutant et je souhait apprendre beaucoup de vous

2024-04-06 17:46 UTC, kazotka commented on .assets/privateroom/view_delete.png
j'avoue que je comprend pas vraiment pour le coup

2024-04-06 17:57 UTC, kazotka commented on 2.modules/24.privateroom.md
> +- `{custom-word}` pour attribuer un mot aléatoire parmi une liste personnalisable.
sa se serais ok pour toi ?
![Uploading preview rename.png…]()

2024-04-06 18:08 UTC, kazotka commented on .assets/privateroom/view_delete.png
ahh c'est bon !

2024-04-06 18:37 UTC, kazotka commented
Si jamais les images ont été mis a jour petit problème elles n’apparaissent pas

2024-04-09 15:03 UTC, DraftProducts commented on 2.modules/24.privateroom.md
> +- **Soundboard** : cette fonction permet d'activer/désactiver l'utilisation des soundboards pour tous les participants du salon vocal.
```suggestion
- **Soundboard** : Cette fonction permet d'activer/désactiver l'utilisation des soundboards pour tous les participants du salon vocal.
```

2024-04-09 15:03 UTC, DraftProducts commented on 2.modules/24.privateroom.md
> +  Notez que vous perdrez l'accès à l'embed de configuration du **salon vocal**.
```suggestion
  Vous perdrez l'accès à l'embed de configuration du **salon vocal**.
```

2024-04-09 15:04 UTC, DraftProducts commented on 2.modules/24.privateroom.md
> +- **Vidéo** : Tout comme la fonction précédente, elle permet d' activer/désactiver l'activation de la caméra ainsi que le partage d'écran de tous les participants du salon vocal.
```suggestion
- **Vidéo** : Tout comme la fonction précédente, elle permet d'autoriser/refuser la permission d'utiliser la caméra ou le partage d'écran de tous les participants du salon vocal.
```

2024-04-09 15:05 UTC, DraftProducts commented on 2.modules/24.privateroom.md
> +
Déjà dispo dans la première description, on peut delete.

2024-04-13 16:05 UTC, ErwanGit requested changes

2024-04-17 02:31 UTC, kazotka commented on 2.modules/24.privateroom.md
au secoure

2024-04-17 02:41 UTC, kazotka commented
problème régler si tu le voit encore refresh (cache)

2024-04-20 15:43 UTC, ErwanGit requested changes

2024-04-20 15:43 UTC, ErwanGit commented on 2.modules/24.privateroom.md
> +![Guide d'utilisation](/.assets/privateroom/view_guide.gif)
Le GIF n'est pas un guide mais plutôt une démonstration du système

2024-04-20 15:43 UTC, ErwanGit commented on 2.modules/24.privateroom.md
> +    > *Par défaut, elle est donc décochée et déconseillée pour les serveurs communautaires*
```suggestion
    > *Par défaut, elle est donc décochée et déconseillée pour les serveurs communautaires.*
```

2024-04-20 15:43 UTC, ErwanGit commented on 2.modules/24.privateroom.md
> +  Pour supprimer un hub, il vous suffit d'aller dans la partie **Salons vocaux privés** du [panel Draftbot](/dashboard/user/profil) et de **supprimer** le hub de votre choix.
```suggestion
  Pour supprimer un hub, il vous suffit d'aller dans la partie **Salons vocaux privés** du [panel de DraftBot](/dashboard/user/profil) et de **supprimer** le hub de votre choix.
```

2024-04-20 15:43 UTC, ErwanGit commented on 2.modules/24.privateroom.md
> +  - Créer un salon : Vous devez cliquer sur le bouton "**Créer**", indiquer un nom et **Draftbot** se chargera de créer le salon avec les permissions adéquates.
```suggestion
  - Créer un salon : Vous devez cliquer sur le bouton "**Créer**", indiquer un nom et **DraftBot** se chargera de créer le salon avec les permissions adéquates.
```

2024-04-25 13:19 UTC, ErwanGit requested changes

2024-05-01 01:17 UTC, kazotka commented on 2.modules/24.privateroom.md
> +    Certaines permissions plus classiques peuvent être contrôlées depuis l'embed de gestion du salon vocal. Veillez à désactiver les options que vous ne souhaitez pas laisser modifiables dans les per
je vais retirer car apres un check ya rien d'autre enfaite xD

2024-05-02 18:47 UTC, ErwanGit requested changes

2024-05-02 18:47 UTC, ErwanGit commented on 2.modules/24.privateroom.md
> +### Changer le nom par défaut des salons temporaires *(**Avantage premium ✨**)*
Je serai comme sur ta PR des messages récurrents de mettre le avantage premium dans une bulle plus bas, même si dans ce cas de figure, le mot premium n'est pas affiché sur le côté droit, question d'uniformisation

2024-05-02 18:47 UTC, ErwanGit commented on 2.modules/24.privateroom.md
> +  - Activer l'embed de réglages ➜ Embed de réglages activé
Ce paragraphe n'est pas hyper clair, il faudrait essayer de le reformuler plus simplement

2024-05-02 18:47 UTC, ErwanGit commented on 2.modules/24.privateroom.md
> +      ::
Ils ne sont pas dans le collapse 
<img width="839" alt="image" src="https://github.com/DraftBot/Documentation/assets/24718500/35ff1f20-9615-4d18-9fec-1f0ed018b737">

2024-05-02 18:47 UTC, ErwanGit commented on 2.modules/24.privateroom.md
> +      ::
Ils ne sont pas dans le collapse 
<img width="839" alt="image" src="https://github.com/DraftBot/Documentation/assets/24718500/900f9e86-5476-4798-8d36-70d57a73fdd3">

2024-05-02 18:47 UTC, ErwanGit commented on 2.modules/24.privateroom.md
> +## Changer le format des noms du salon *(**Avantage premium ✨**)*
Je serai comme sur ta PR des messages récurrents de mettre le avantage premium dans une bulle plus bas, même si dans ce cas de figure, le mot premium n'est pas affiché sur le côté droit, question d'uniformisation

2024-05-14 22:49 UTC, kazotka commented on 2.modules/24.privateroom.md
> +  - Activer l'embed de réglages ➜ Embed de réglages activé
je vois pas exactement de quoi tu parle si tu veux bien m'éclarer

2024-05-15 08:26 UTC, ErwanGit commented on 2.modules/24.privateroom.md
> +  - Activer l'embed de réglages ➜ Embed de réglages activé
Le changement du noms de boutons si activer ou non

2024-05-26 19:13 UTC, kazotka commented on 2.modules/24.privateroom.md
> +  - Activer l'embed de réglages ➜ Embed de réglages activé
Désolé j'ai totalement oublier se dernier fix
 ### Activer/Désactiver l'embed de réglages

  Pour activer ou désactiver l'embed de réglages, il vous suffira d'utiliser le bouton.

  - Cliquer sur le bouton **Embed de réglages activé** activera la fonction et le bouton deviendra **Activer l'embed de réglages** et inversement pour désactiver le système.

  En résumé :

  - Embed de réglages activé ➜ Activer l'embed de réglages
  - Activer l'embed de réglages ➜ Embed de réglages activé


C'est mieux selon toi ?

2024-05-26 19:36 UTC, ErwanGit commented on 2.modules/24.privateroom.md
> +  - Activer l'embed de réglages ➜ Embed de réglages activé
Je pense oui

2024-05-27 01:41 UTC, DraftProducts requested changes
Petit coup de language tool

2024-05-27 01:41 UTC, DraftProducts commented on 2.modules/24.privateroom.md
> +  Cet embed permet notamment d'utiliser toutes les permissions de modération, et ce même si le membre n'a pas activé l'authentifcation à deux facteurs (puisque l'utilisateur passe par le bot et non p
```suggestion
  Cet embed permet notamment d'utiliser toutes les permissions de modération, et ce, même si le membre n'a pas activé l'authentification à deux facteurs (puisque l'utilisateur passe par le bot et non pas par son compte).
```

2024-05-27 01:41 UTC, DraftProducts commented on 2.modules/24.privateroom.md
> +- **Liste Blanche** : Cette fonction permet d'ajouter des membres qui seront **autorisés à rejoindre** le salon peut importe le mode (Public, Fermé, Privé) et recevront toutes les permissions micro,
```suggestion
- **Liste Blanche** : Cette fonction permet d'ajouter des membres qui seront **autorisés à rejoindre** le salon peu importe le mode (Public, Fermé, Privé) et recevront toutes les permissions micro, vidéo & soundboards.
```

2024-05-27 01:41 UTC, DraftProducts commented on 2.modules/24.privateroom.md
> +  Vous pouvez définir la limite de membres autorisés à rejoindre un salon vocal en appuyant sur le bouton **Limite de membre**. Vous devrez ensuite indiquer une valeur entre 0 et 99 qui correspond au
```suggestion
  Vous pouvez définir la limite de membres autorisés à rejoindre un salon vocal en appuyant sur le bouton **Limite de membre**. Vous devrez ensuite indiquer une valeur entre 0 et 99 qui correspond au nombre de participants maximal. Indiquer "0" comme limite revient à la désactiver.
```

2024-05-27 01:41 UTC, DraftProducts commented on 2.modules/24.privateroom.md
> +  Pour personnaliser les boutons de réglages, vous devrez d'abord appuyer sur le bouton **Personnaliser les boutons de réglages** qui vous amènera sur un sélecteur. Cochez toutes les options que vous
```suggestion
  Pour personnaliser les boutons de réglages, vous devrez d'abord appuyer sur le bouton **Personnaliser les boutons de réglages** qui vous amènera sur un sélecteur. Cochez toutes les options que vous souhaitez rendre disponibles dans l'embed de configuration du salon.
```

2024-05-27 01:41 UTC, DraftProducts commented on 2.modules/24.privateroom.md
> +    Veuillez noter qu'il s'agit d'une option sensible car elle influe sur toutes les autres permissions du salon.
```suggestion
    Veuillez noter qu'il s'agit d'une option sensible, elle influe sur toutes les autres permissions du salon.
```

2024-05-27 01:41 UTC, DraftProducts commented on 2.modules/24.privateroom.md
> +## Changer le donnnoms du salon *(**Avantage premium ✨**)*
```suggestion
## Personnaliser le format du nom du salon *(**Avantage premium ✨**)*
```

2024-05-27 01:41 UTC, DraftProducts commented on 2.modules/24.privateroom.md
> +  Afin d'éviter des salons dit doublons, il est conseillé d'indiquer au moins une variable.
```suggestion
  Afin d'éviter des salons dits doublons, il est conseillé d'indiquer au moins une variable.
```

2024-05-27 01:42 UTC, DraftProducts approved these changes

2024-05-31 22:34 UTC, merged