Amélioration des messages récurents
DraftBot/Documentation pull request #95
Opened 2024-03-22 00:57 UTC by kazotka

2024-04-07 22:16 UTC, kazotka commented
J'ai fini l réécriture de la page et je suis prêt à recevoir vos retour

2024-04-13 15:54 UTC, ErwanGit requested changes

2024-04-13 15:54 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +    > ***Heure ciblée/Ciblé** : Envoi du message à un jour et une heure ciblée.*
Je ne suis pas convaincu des répétitions de "ciblée/ciblé" et "Répétition/Relatif", pourquoi ne pas mettre juste "Heure ciblée" et "Répétition" ?

2024-04-13 15:54 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
>      La première chose à faire sera de nommer votre message. Ce nom est uniquement utilisé à des fins pratiques et ne change absolument rien ! *(Maximum 30 caractères)*
Je ne suis pas convaincu par la dernière phrase
Le nom du message est quand même important pour le retrouver facilement sur le `/config`, panel ou dans les logs 

J'aurai dit quelque chose comme ça, si tu as des suggestions pour l'améliorer n'hésite pas
```suggestion
    La première chose à faire sera de nommer votre message. Ce nom, qui n'est pas affiché aux membres de votre serveur, permet de le distinguer dans la liste de vos messages récurrants.
```

2024-04-13 15:54 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +- Par la suite, vous avez le choix de sélectionner les jours où le message récurrent pourrait être envoyé avec des boutons.
Dans la capture d'écran, c'est un sélecteur qui est utilisé
![chrome_YSNzi0RjfR](https://github.com/DraftBot/Documentation/assets/24718500/35d7c3de-6226-4e09-87e6-e57d6f7d9695)

2024-04-13 15:54 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +Après cela vous pourez créer votre message via l'interface de DraftBot ci-dessous. Il est important de noter que certaine fonctionalité ne son uniquement accesible sur le **[panel de DraftBot](/dashb
Les embeds peuvent être faits aussi via la commande /embed puis en indiquant l'identifiant du message
De plus, j'ai l'impression qu'il y a un mélange panel/bot dans cette partie, qu'est ce que "l'interface de DraftBot ci-dessous" ?

2024-04-13 15:54 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +    *L'interface du panel peut paraitre déroutante, mais ne vous inquiétez pas.*
Alors, si cette phrase existe, cela veut dire qu'on a mal fait quelque chose côté dev
L'interface ne doit pas être "déroutante" pour un utilisateur qui arrive pour la première fois sur cette page et qui n'a pas lu la documentation, etc. 

(@ElBaguetto @DraftProducts)

2024-04-13 15:54 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +    ::collapse{ label="Paramêtre basique du message" }
```suggestion
    ::collapse{ label="Paramètres basiques du message" }

```

2024-04-13 15:54 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +      - La première chose à faire sera de nommer votre message. Ce nom est uniquement utilisé à des fins pratiques et ne change absolument rien ! *(Maximum 30 caractères)*
Même commentaire que côté bot

2024-04-13 15:54 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +    > ***Heure ciblée/Ciblé** : Envoi du message à un jour et une heure ciblée.*
Même commentaire que côté bot

2024-04-13 15:54 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +![Interval d'envoi](/.assets/repeat-messages/dashboard/view_interval_selector.png)
```suggestion
![Intervalle d'envoi](/.assets/repeat-messages/dashboard/view_interval_selector.png)

```

2024-04-13 15:54 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +### Historique
Ce n'est pas vraiment, un historique, mais une liste
Si on décide de supprimer un message récurrent, il disparaitra définitivement de cette liste

2024-04-13 15:54 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +::
Je pense qu'on peut directement faire une liste ou bien l'ajouter dans les deux parties
Un collapse est overkill dans cette situation je pense et ne sert qu'a caché ces options

2024-04-13 15:54 UTC, ErwanGit commented on .assets/repeat-messages/dashboard/view_historique.png
Il faudra changer le nom de l'image avec par exemple `view_list` je pense (voir commentaire côté panel à ce sujet)

2024-04-17 02:48 UTC, kazotka commented
Je m'occupe du reste quand j'ai le temps

2024-04-17 02:50 UTC, DraftProducts commented on 2.modules/23.repeat-messages.md
> +    *L'interface du panel peut paraitre déroutante, mais ne vous inquiétez pas.*
En effet

2024-04-25 01:17 UTC, kazotka commented on 2.modules/23.repeat-messages.md
> +    > ***Heure ciblée/Ciblé** : Envoi du message à un jour et une heure ciblée.*
D'accord pour l'heure ciblé, mais répétition/relatif c'est le nom différant selon le panel ou le /config

2024-04-25 13:15 UTC, ErwanGit requested changes

2024-04-25 13:15 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +    > ***Heure ciblée** : Envoi du message à un jour et une heure ciblée.*
J'ai vu ton message mais on est dans la partie `/config`, donc je propose : 
```suggestion
    > ***Relatif** : Envoi du message à une certaine récurrence.*
    
    > ***Ciblé** : Envoi du message à un jour et une heure ciblée.*

```

2024-04-25 13:15 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +- Par la suite, vous avez le choix de sélectionner les jours où le message récurrent pourrait être envoyé avec des boutons.
Commentaire non résolu
```suggestion
- Par la suite, vous avez le choix de sélectionner les jours où le message récurrent pourrait être envoyé dans les options du sélecteur.
```

2024-04-25 13:15 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +Après cela vous pourez créer votre message via cette commande ou avec la commande /embed. Il est important de noter que certaine fonctionalité ne son uniquement accesible sur le **[panel de DraftBot]
Il faudrait mentionner la commande /embed + quelles sont les "certaines fonctionnalités qui ne sont accessibles sur le panel" ? Parles-tu des options pour personnaliser le message ? Si oui, il faut le préciser, car ce n'est pas clair

2024-04-25 13:15 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +  *L'interface du panel peut paraitre déroutante, mais ne vous inquiétez pas.*
Autant retirer cette phrase

2024-04-25 13:15 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +      - La première chose à faire sera de nommer votre message. Ce nom est uniquement utilisé à des fins pratiques et ne change absolument rien ! *(Maximum 30 caractères)*
Comme ce que tu as mis côté bot
```suggestion
      - La première chose à faire sera de nommer votre message. Ce nom, qui n'est pas affiché aux membres de votre serveur, permet de le distinguer dans la liste de vos messages récurrants.

```

2024-04-25 13:15 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +    > ***Heure ciblée** : Envoi du message à un jour et une heure ciblée.*
Vu qu'on est sur le panel : 
```suggestion
    > ***Répétition** : Envoi du message à une certaine récurrence.*
    
    > ***Heure ciblée** : Envoi du message à un jour et une heure ciblée.*
```

2024-04-25 13:15 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +Sur le **[panel de DraftBot](/dashboard/user)**, vous pouvez accéder à un historique de vos messages récurrents déjà créés et les modifier, etc.
Ce n'est pas un historique, mais une liste des messages récurrents présents sur le serveur. Si on le supprime, il disparaît
(il me semble l'avoir déjà noté dans la review précedente 🤔)

2024-05-01 01:34 UTC, kazotka commented on 2.modules/23.repeat-messages.md
> +    > ***Heure ciblée** : Envoi du message à un jour et une heure ciblée.*
je comprend ! j'y avais pas penser sous cette angle

2024-05-01 01:35 UTC, kazotka commented on 2.modules/23.repeat-messages.md
> +- Par la suite, vous avez le choix de sélectionner les jours où le message récurrent pourrait être envoyé avec des boutons.
My bad

2024-05-01 01:38 UTC, kazotka commented on 2.modules/23.repeat-messages.md
> +Sur le **[panel de DraftBot](/dashboard/user)**, vous pouvez accéder à un historique de vos messages récurrents déjà créés et les modifier, etc.
en effet, mais je viens de me rendre compte que j'ai fait le travail a moitier en changant uniquement le titre

2024-05-02 18:40 UTC, ErwanGit requested changes
Je suis désolé pour toutes les nouveaux changements que je te fais à chaque nouvelle review au lieu de faire tout d'un seul coup 
Je vois des nouveaux trucs à chaque nouvelle review et je sais qu'à ta place, c'est pas forcément cool de se reprendre des requests changes alors que tu as fais toutes les modifications que je t'ai demandé 

-- 

Essaye aussi de relancer les autres reviewers pour avoir d'autres points de vues et que plus d'erreurs soient corrigés et qu'on merge ta PR rapidement sur le site de DraftBot

2024-05-02 18:40 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +
```suggestion
```

2024-05-02 18:40 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
>      - Entrez l'heure à laquelle vous souhaitez que le message soit envoyé.
```suggestion
Entrez l'heure à laquelle vous souhaitez que le message soit envoyé.
```

2024-05-02 18:40 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +- Par la suite, vous avez le choix de sélectionner les jours où le message récurrent pourrait être envoyé dans les options du sélecteur.
```suggestion
Par la suite, vous avez le choix de sélectionner les jours où le message récurrent pourrait être envoyé dans les options du sélecteur.
```

2024-05-02 18:40 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
>      - Vous êtes rendu à la création de votre message ! N'hésitez pas à utiliser le [Markdown](https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Und
```suggestion
Vous êtes rendu à la création de votre message ! N'hésitez pas à utiliser le [markdown](https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline){ target=_blank }.
```

2024-05-02 18:40 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
>      - Par la suite, vous devrez sélectionner le salon dans lequel sera envoyé le message.
```suggestion
Par la suite, vous devrez sélectionner le salon dans lequel sera envoyé le message.
```

2024-05-02 18:40 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +Après cela, vous pourrez créer votre message via cette commande ou avec la commande /embed. Il est important de noter que certaines fonctionnalités sont uniquement accessibles sur le **[panel de Draf
Il me semble que la mention fonctionne comme ceci
```suggestion
Après cela, vous pourrez créer votre message via cette commande ou avec la commande \/embed. Il est important de noter que certaines fonctionnalités sont uniquement accessibles sur le **[panel de DraftBot](/dashboard/user)** comme la possibilité d'ajouter un/des boutons ou encore les options de personnalisation des messages qui est plus intuitive et plus complète.
```

2024-05-02 18:40 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +Cette fonctionnalité permet de supprimer le message précédent lors d'un nouvel envoi. *( Avantage Premium ✨ )*
Il faudrait renvoyer sur la page premium quand on clique sur avantage premium
```suggestion
Cette fonctionnalité permet de supprimer le message précédent lors d'un nouvel envoi. *(Avantage Premium ✨ )*
```

2024-05-02 18:40 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +***Ou encore ...***
La phrase n'a pas de sens dans la documentation
```suggestion
```

2024-05-02 18:40 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +Sur le **[panel de DraftBot](/dashboard/user)**, vous pouvez accéder à une liste de vos messages récurrents déjà créés et les modifier, etc.
```suggestion
Sur le **[panel de DraftBot](/dashboard/user)**, vous pouvez accéder à une liste de vos messages récurrents déjà créés et les modifier ou les supprimer.
```

2024-05-02 18:40 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +- Par la suite, vous avez le choix de sélectionner les jours où le message récurrent pourrait être envoyé avec des boutons.
```suggestion
Par la suite, vous avez le choix de sélectionner les jours où le message récurrent pourrait être envoyé avec des boutons.
```

2024-05-02 18:40 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +  - Entrez l'heure à laquelle vous souhaitez que le message soit envoyé.
```suggestion
Entrez l'heure à laquelle vous souhaitez que le message soit envoyé.
```

2024-05-02 18:40 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +
```suggestion
```

2024-05-02 18:40 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +### Interval d'envoi
```suggestion
### Intervalle d'envoi
```

2024-05-02 18:40 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +      - La première chose à faire sera de nommer votre message. Ce nom, qui n'est pas affiché aux membres de votre serveur, permet de le distinguer dans la liste de vos messages récurrants.
```suggestion
La première chose à faire sera de nommer votre message. Ce nom, qui n'est pas affiché aux membres de votre serveur, permet de le distinguer dans la liste de vos messages récurrents.
```

2024-05-02 18:40 UTC, ErwanGit commented on 2.modules/23.repeat-messages.md
> +      - Par la suite, vous devrez sélectionner le salon dans lequel sera envoyé le message via un menu déroulant.
```suggestion
Par la suite, vous devrez sélectionner le salon dans lequel sera envoyé le message via un menu déroulant.
```

2024-05-14 21:45 UTC, kazotka commented
(deso de l'absence vacance a Boston)

J'ai ajouter Baribbo si tu veux faire des reviews n'hesite pas ! Sinon, je vais voir pour relancer dranftman et Ibey.

2024-05-19 09:27 UTC, closed without merging