🛠️ Starboard doc WIP
DraftBot/Documentation pull request #99
Opened 2024-06-03 21:54 UTC by kazotka

Je reprend la doc sur le Starboard

2024-06-03 23:36 UTC, kazotka commented
J'ai transférer complètement l'ancienne doc, prochaine état c'est de la revoir au complèt pour l'améliorer !

2024-06-04 02:29 UTC, DraftProducts commented
Nice 🔥

2024-06-14 00:42 UTC, kazotka commented
j'aimerais avoir vos reviews pour la première parti de la page la parti des options n'ai pas encore fini parcontre

2024-06-14 00:43 UTC, kazotka commented
@DraftProducts possible de me retirer les contours de : starboards-edit-2.png et starboards-delete-2.png

2024-06-25 14:23 UTC, ErwanGit requested changes

2024-06-25 14:23 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +      <:IconEmbedTransparent:1102254845219577907>
```suggestion
```

2024-06-25 14:23 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +      <:IconEmbedTransparent:1102254845219577907>
```suggestion
```

2024-06-25 14:23 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    - Cette option vous **permet de modifier l'émoji par défaut du Starboard *(Avantage [premium ✨](https://www.draftbot.fr/premium/) ) !***
```suggestion
    - Cette option vous **permet de modifier l'émoji par défaut du Starboard *(Avantage [premium ✨](https://www.draftbot.fr/premium/)) !***
```

2024-06-25 14:23 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +      Changer la couleur : on parle ici de changer la couleur de l'embed, donc il faut activer l'option pour avoir celle-ci. *(Avantage [**premium** ✨](https://www.draftbot.fr/premium/) )*
```suggestion
      Changer la couleur : on parle ici de changer la couleur de l'embed, donc il faut activer l'option pour avoir celle-ci. *(Avantage [**premium** ✨](https://www.draftbot.fr/premium/))*

```

2024-06-25 14:23 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +      Changer la couleur : on parle ici de changer la couleur de l'embed, donc il faut activer l'option pour avoir celle-ci. *(Avantage [**premium** ✨](https://www.draftbot.fr/premium/) )*
```suggestion
      Changer la couleur : on parle ici de changer la couleur de l'embed, donc il faut activer l'option pour avoir celle-ci. *(Avantage [**premium** ✨](https://www.draftbot.fr/premium/))*

```

2024-06-25 14:23 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    - Cette option vous **permet de modifier l'émoji par défaut du Starboard *(Avantage [premium ✨](https://www.draftbot.fr/premium/) ) !***
```suggestion
    - Cette option vous **permet de modifier l'émoji par défaut du Starboard *(Avantage [premium ✨](https://www.draftbot.fr/premium/)) !***

```

2024-06-25 22:09 UTC, kazotka commented on 2.modules/25.starboards.md
> +      <:IconEmbedTransparent:1102254845219577907>
C'est fait exprès dans le but d'être visuellement plus joli.

2024-06-25 22:09 UTC, kazotka commented on 2.modules/25.starboards.md
> +    - Cette option vous **permet de modifier l'émoji par défaut du Starboard *(Avantage [premium ✨](https://www.draftbot.fr/premium/) ) !***
C'est fait exprès dans le but d'être visuellement plus joli.

2024-06-26 01:42 UTC, kazotka commented on 2.modules/25.starboards.md
> +    - Cette option vous **permet de modifier l'émoji par défaut du Starboard *(Avantage [premium ✨](https://www.draftbot.fr/premium/) ) !***
Enfaite personnellement je trouve cela plus joli que la deuxième parenthèse ne soit pas collé a l'emoji

2024-06-26 01:43 UTC, kazotka commented on 2.modules/25.starboards.md
> +      <:IconEmbedTransparent:1102254845219577907>
c'est pour séparer l'img du texte, personellement je trouve cela plus beau

2024-06-26 09:45 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +      <:IconEmbedTransparent:1102254845219577907>
Il y a pas d'emojis custom sur la doc

2024-06-26 09:47 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +      <:IconEmbedTransparent:1102254845219577907>
Autant rajouter un saut de ligne, en plus c'est pas hyper beau![image](https://github.com/DraftBot/Documentation/assets/24718500/a0c6ff6c-c732-4bf4-bde9-54a100622fca)

2024-06-26 23:45 UTC, ls62 commented on 2.modules/25.starboards.md
> +
Pourquoi pas mettre une image du menu entier pour que l'utilisateur voie à quoi cela ressemble et de se repérer.

2024-06-26 23:48 UTC, ls62 commented on 2.modules/25.starboards.md
> +
Pareil pour le tab "via la commande /config" mettre une image du panel entier pour que l'utilisateur voie à quoi cela ressemble et de se repérer.

2024-06-26 23:54 UTC, ls62 commented on 2.modules/25.starboards.md
> +    #### Réaction (individuel) par salon
Reprendre le nom du panel "RÉACTIONS REQUISES PAR SALON"

2024-06-27 00:01 UTC, ls62 commented on 2.modules/25.starboards.md
> +      Les variables sont des morceaux de texte qui évoluent en fonction de la personne, du serveur, du salon ou encore du temps. Voici celles utilisables pour le système de Starboard :
Pourquoi pas détailler et mettre en avant ce texte pour que l'utilisateur voie qu'il a la possibilité de personnalisées sont message grâce à des variables.

2024-06-27 00:04 UTC, ls62 commented on 2.modules/25.starboards.md
> +## Exemple
Pourquoi pas remplacer par "Les différents formats" au lieu d'"exemple".

2024-06-27 00:10 UTC, ls62 commented on 2.modules/25.starboards.md
> +      Les variables sont des morceaux de texte qui évoluent en fonction de la personne, du serveur, du salon ou encore du temps. Voici celles utilisables pour le système de Starboard :
Pourquoi pas détailler et mettre en avant ce texte pour que l'utilisateur voie qu'il a la possibilité de personnalisées sont message grâce à des variables.

2024-06-27 00:13 UTC, ls62 commented on 2.modules/25.starboards.md
> +### Avec Embed
Changer par "Message via un Embed"

2024-06-27 00:21 UTC, ls62 commented on 2.modules/25.starboards.md
> +### Sans Embed
Changer par "Message sans Embed" ou une alternative.

2024-06-27 00:33 UTC, ls62 commented
Hello @kazotka !
J'ai check ta documentation et j'ai rapporté des suggestions sur la forme des phrases et le rajout d'images. 

N'hésite pas à mettre des images dans la partie [Options disponibles](https://preview.draftbot.fr/docs/pr-99/modules/starboards#options-disponibles) pour que les utilisateurs voient à quoi cela ressemble et arrivent à s'orienter grâce à ça. ✨

2024-07-01 02:40 UTC, kazotka commented
Pour toutes les personnes qui souhaitent faire des reviews, sachez qu'il y a un problème avec les assets en ce moment. Ce problème **ne provient pas de moi**, donc merci d'éviter les reviews à ce sujet, les devs travaillent sur ce problème.

2024-07-01 13:41 UTC, ErwanGit requested changes

2024-07-01 13:41 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    Pour configurer le système via le [panel](https://www.draftbot.fr/dashboard/), il vous suffit de vous diriger dans l'onglet ''Communautaire''. Ensuite, descendez dans la liste des systèmes et vou
```suggestion
    Pour configurer le système via le [panel](https://www.draftbot.fr/dashboard/), il vous suffit de vous diriger dans l'onglet ''Communautaire''. Ensuite, descendez dans la liste des systèmes et vous trouverez le système de starboards.
```

2024-07-01 13:41 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    La configuration d'un "Starboard" depuis la commande \</config> se trouve dans la catégorie Starboards. Après avoir cliqué sur le bouton "Créer", laissez-vous guider par les questions afin de con
```suggestion
    La configuration d'un starboard depuis la commande \</config> se trouve dans la catégorie Starboards. Après avoir cliqué sur le bouton "Créer", laissez-vous guider par les questions afin de configurer le starboard à l'image de votre serveur.
```

2024-07-01 13:41 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    ![La configuration via /config](/.assets/starboards/config_example.png)
```suggestion
    ![La configuration via la commande /config](/.assets/starboards/config_example.png)
```

2024-07-01 13:41 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    Pour créer un Starboard, descendez dans la partie "Starboards" et cliquez sur "Créer un hub". Par la suite, DraftBot vous proposera une sorte de menu de configuration pour configurer votre premie
```suggestion
    Pour créer un starboard, descendez dans la partie "Starboards" et cliquez sur "Créer un hub". Par la suite, DraftBot vous proposera une sorte de menu de configuration pour configurer votre premier Starboard.
```

2024-07-01 13:41 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +      Pour créer jusqu'à 5 Starboards et choisir l'émoji associé aux réactions, le [premium ✨](https://www.draftbot.fr/premium) est nécessaire.
```suggestion
      Pour créer jusqu'à 5 starboards et choisir l'émoji associé aux réactions, le [premium ✨](https://www.draftbot.fr/premium) est nécessaire.
```

2024-07-01 13:41 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    Vous avez la possibilité de définir un nombre minimum de réactions, compris entre 1 et 25, avant qu'un message n'apparaisse dans le salon dédié à ce Starboard.
```suggestion
    Vous avez la possibilité de définir un nombre minimum de réactions, compris entre 1 et 25, avant qu'un message n'apparaisse dans le salon dédié à ce starboard.
```

2024-07-01 13:41 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    Pour supprimer un Starboard, cliquez sur le bouton "Supprimer".
```suggestion
    Pour supprimer un starboard, cliquez sur le bouton "Supprimer".
```

2024-07-01 13:41 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    - Grâce à cette option, vous pouvez **définir uniquement les messages d'un groupe d'utilisateur *(via des rôles)* pouvant apparaitre dans le Starboard** et inversement.
```suggestion
    - Grâce à cette option, vous pouvez **définir uniquement les messages d'un groupe d'utilisateur *(via des rôles)* pouvant apparaitre dans le starboard** et inversement.

```

2024-07-01 13:41 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    - Vous pouvez définir, via cette option, **un ou des rôles, limitant ainsi la possibilité de voter pour qu'un message se retrouve dans le Starboard** et inversement.
```suggestion
    - Vous pouvez définir, via cette option, **un ou des rôles, limitant ainsi la possibilité de voter pour qu'un message se retrouve dans le starboard** et inversement.

```

2024-07-01 13:41 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    Les variables ci-dessous peuvent être utilisée dans le message envoyé dans le Starboard. Voici celles utilisables pour le système de Starboard :
```suggestion
    Les variables ci-dessous peuvent être utilisée dans le message envoyé dans le Starboard. Voici celles utilisables pour le système de starboard :
```

2024-07-01 13:41 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    - Cette option vous **permet de modifier l'émoji par défaut du Starboard *(Avantage [premium ✨](https://www.draftbot.fr/premium/)) !***
```suggestion
    - Cette option vous **permet de modifier l'émoji par défaut du starboard *(Avantage [premium ✨](https://www.draftbot.fr/premium/)) !***

```

2024-07-01 13:41 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +      Le nombre doit être compris entre 1 et 25, avant qu'un message n'apparaisse dans le salon dédié à ce Starboard.
```suggestion
      Le nombre doit être compris entre 1 et 25, avant qu'un message n'apparaisse dans le salon dédié à ce starboard.
```

2024-07-01 13:41 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    - Grâce à cette option, vous pouvez **définir uniquement les messages d'un groupe d'utilisateur *(via des rôles)* pouvant apparaitre dans le Starboard** et inversement.
```suggestion
    - Grâce à cette option, vous pouvez **définir uniquement les messages d'un groupe d'utilisateur *(via des rôles)* pouvant apparaitre dans le starboard** et inversement.
```

2024-07-01 13:41 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    - Vous pouvez définir, via cette option, **un ou des rôles, limitant ainsi la possibilité de voter pour qu'un message se retrouve dans le Starboard** et inversement.
```suggestion
    - Vous pouvez définir, via cette option, **un ou des rôles, limitant ainsi la possibilité de voter pour qu'un message se retrouve dans le starboard** et inversement.
```

2024-07-01 13:41 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    #### Rôles autorisés / interdits  à réagir
```suggestion
    #### Rôles autorisés/interdits  à réagir
```

2024-07-01 13:41 UTC, ErwanGit commented on .assets/starboards/example_embed.png
Il faudrait refaire l'image, je pense avec "un incroyable starboard ! ⭐"

2024-07-01 18:35 UTC, ErwanGit requested changes

2024-07-01 18:35 UTC, ErwanGit commented on .assets/starboards/example_embed.png
Modifier la description de l'embed pour `... un incroyable starboard ! ⭐`

2024-07-01 18:35 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +Le système de "starboard" met en avant les messages qui reçoivent un certain nombre de réactions `⭐`, qui seront alors affichés par DraftBot dans un salon dédié, choisi ou créé lors de la configurati
```suggestion
Le système de starboard met en avant les messages qui reçoivent un certain nombre de réactions `⭐`, qui seront alors affichés par DraftBot dans un salon dédié, choisi ou créé lors de la configuration.
```

2024-07-01 18:35 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    La configuration d'un "starboard" depuis la commande \</config> se trouve dans la catégorie starboards. Après avoir cliqué sur le bouton "Créer", laissez-vous guider par les questions afin de con
```suggestion
    La configuration d'un starboard depuis la commande \</config> se trouve dans la catégorie starboards. Après avoir cliqué sur le bouton "Créer", laissez-vous guider par les questions afin de configurer le starboard à l'image de votre serveur.
```

2024-07-01 18:35 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    Pour créer un starboard, descendez dans la partie "starboards" et cliquez sur "Créer un hub". Par la suite, DraftBot vous proposera une sorte de menu de configuration pour configurer votre premie
```suggestion
    Pour créer un starboard, descendez dans la partie dédié aux starboards et cliquez sur "Créer un hub". Par la suite, DraftBot vous proposera une sorte de menu de configuration pour configurer votre premier starboard.
```

2024-07-01 18:35 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    Pour modifier un starboard, il vous suffit de cliquer sur "Modifier".  Vous pouvez choisir si la représentation du message dans le salon est dans un embed ou pas, mais vous pouvez également chois
```suggestion
    Pour modifier un starboard, il vous suffit de cliquer sur "Modifier". Vous pouvez choisir si la représentation du message dans le salon est dans un embed ou pas, mais vous pouvez également choisir dans quel salon vous souhaitez qu'il s'y trouve.

```

2024-07-06 12:30 UTC, ErwanGit commented on .assets/starboards/example_embed.png
Avec un U majuscule
⇾ DraftBot possède un incroybale starboard ! ⭐

2024-07-06 12:32 UTC, ErwanGit commented on 2.modules/25.starboards.md
> +    ::
Il y a un soucis ici
![chrome_Pg5Ezi8VJI](https://github.com/DraftBot/Documentation/assets/24718500/c91df54c-5a41-42b9-83f0-31d0978041d2)

2024-07-11 19:19 UTC, ErwanGit approved these changes

2024-08-05 17:09 UTC, DraftProducts approved these changes

2024-08-05 17:09 UTC, merged